<?php

declare(strict_types=1);
if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

function v50_has_hypothesis(string $classId,string $studentKey,int $lessonNo): bool
{
    foreach(v50_student_events($classId,$studentKey,$lessonNo) as $row)if((string)($row['kind']??'')==='hypothesis')return true;return false;
}
function v50_last_event_of_kind(string $classId,string $studentKey,int $lessonNo,string $kind): ?array
{
    $last=null;foreach(v50_student_events($classId,$studentKey,$lessonNo) as $row)if((string)($row['kind']??'')===$kind)$last=$row;return is_array($last)?$last:null;
}
function v50_dim_label(string $dim): string
{
    return match($dim){'principle'=>tr('Znám princip'),'recognition'=>tr('Poznám problém'),'diagnosis'=>tr('Umím diagnostikovat'),'repair'=>tr('Umím opravit'),'explain'=>tr('Umím vysvětlit'),'transfer'=>tr('Umím použít jinde'),default=>$dim};
}
function v50_topology_svg(array $spec): void
{
    $top=(array)($spec['topology']??[]);$nodes=(array)($top['nodes']??[]);$edges=(array)($top['edges']??[]);$path=(array)($top['packet_path']??[]);
    ?><div class="v50-topology" data-v50-topology data-packet-path="<?=e(implode(',',$path))?>">
      <div class="v50-layer-switch" role="group" aria-label="<?=e(tr('Vrstva diagramu'))?>"><button type="button" data-layer="all" class="active"><?=e(tr('Vše'))?></button><button type="button" data-layer="L2">L2</button><button type="button" data-layer="L3">L3</button><button type="button" data-layer="L4">L4</button><button type="button" data-layer="L7">L7</button><button type="button" data-layer="OS">OS</button></div>
      <svg viewBox="0 0 100 70" role="img" aria-label="<?=e(tr('Interaktivní topologie labu'))?>">
        <defs><marker id="v50-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z"/></marker><filter id="v50-glow"><feGaussianBlur stdDeviation="1.2" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
        <?php foreach($edges as $i=>$edge): $a=null;$b=null;foreach($nodes as $n){if(($n['id']??'')===($edge['from']??''))$a=$n;if(($n['id']??'')===($edge['to']??''))$b=$n;}if(!$a||!$b)continue; ?><g class="v50-edge" data-layer="<?=e((string)($edge['layer']??''))?>"><line x1="<?=e((string)$a['x'])?>" y1="<?=e((string)$a['y'])?>" x2="<?=e((string)$b['x'])?>" y2="<?=e((string)$b['y'])?>" marker-end="url(#v50-arrow)"/><text x="<?=e((string)(($a['x']+$b['x'])/2))?>" y="<?=e((string)(($a['y']+$b['y'])/2-2))?>"><?=e((string)($edge['label']??''))?></text></g><?php endforeach; ?>
        <?php foreach($nodes as $node): ?><g class="v50-node" tabindex="0" role="button" data-node="<?=e((string)$node['id'])?>" data-layer="<?=e((string)$node['layer'])?>" data-label="<?=e((string)$node['label'])?>" data-meta="<?=e((string)$node['meta'])?>" transform="translate(<?=e((string)$node['x'])?> <?=e((string)$node['y'])?>)"><circle r="6"/><text y=".8" text-anchor="middle" class="v50-node-mark"><?=e(strtoupper(substr((string)$node['kind'],0,1)))?></text><text y="10" text-anchor="middle" class="v50-node-label"><?=e((string)$node['label'])?></text></g><?php endforeach; ?>
        <circle class="v50-packet" r="1.8" cx="8" cy="50" aria-hidden="true"/>
      </svg>
      <div class="v50-topology-tools"><button type="button" class="btn secondary small" data-packet-play><?=e(tr('▶ Přehrát packet path'))?></button><div class="v50-inspector" data-v50-inspector><strong><?=e(tr('Vyber uzel'))?></strong><span><?=e(tr('Kliknutím zjistíš roli a adresu prvku.'))?></span></div></div>
    </div><?php
}

function v50_render_student_hands_on_page(string $classId,array $lesson,array $module,string $flash=''): void
{
    $studentKey=adaptive_student_key($classId);if($studentKey===''){redirect_to('?view=dashboard');}
    $spec=v50_lab_spec($classId,$lesson,$studentKey);$lessonNo=(int)$spec['lesson_number'];$events=v50_student_events($classId,$studentKey,$lessonNo);$state=v50_latest_state($classId,$studentKey,$spec);$hasHyp=v50_has_hypothesis($classId,$studentKey,$lessonNo);$passport=v50_student_passport($classId,$studentKey);$stop=v50_stop_rule($classId,$studentKey,$lessonNo);$lastCmd=v50_last_event_of_kind($classId,$studentKey,$lessonNo,'command');$lastValidation=v50_last_event_of_kind($classId,$studentKey,$lessonNo,'validation');
    render_header(tr('Hands-on Lab · {title}',['title'=>(string)$spec['lesson_title']]),$module,true);
    ?><section class="v50-shell">
      <header class="v50-hero"><div><div class="eyebrow">v50 · Hands-on Learning Runtime</div><h1><?=edu_cs((string)$spec['lesson_title'])?></h1><p><?=edu_cs((string)$spec['mission'])?></p><div class="v50-chip-row"><span><?=edu_cs((string)$spec['family_label'])?></span><span><?=edu_cs((string)$spec['layer'])?></span><span><?=e(v50_runtime_mode()==='oci'?tr('Real OCI Linux'):tr('Stateful simulator'))?></span><?php if(!empty($spec['boss_fight'])):?><strong>Boss Fight</strong><?php endif;?></div></div><div class="v50-hero-actions"><a class="btn primary" href="<?=e(v69_task_url('lab',['lesson'=>(string)$lessonNo],module_url('hands_on',['lesson'=>$lessonNo])))?>">One Task Mode →</a><a class="btn secondary" href="<?=e(module_url('visual_lab',['lesson'=>$lessonNo]))?>">Visual Lab</a><a class="btn secondary" href="?view=skill_passport">Skill Passport</a></div></header>
      <?php if($flash!==''):?><div class="notice"><?=e($flash)?></div><?php endif;?>
      <?php if($stop):?><section class="v50-stop-card"><div><span><?=e(tr('✓ Dostatek kvalitní evidence'))?></span><h2><?=e(tr('Pro dnešek stačí.'))?></h2><p><?=e(tr('Diagnostiku, opravu, vysvětlení i transfer už máš doložené. Další opakování stejného typu by teď mělo menší přínos.'))?></p></div><a class="btn primary" href="?view=growth"><?=e(tr('Chci se rozvíjet dál'))?></a></section><?php endif;?>
      <div class="v50-main-grid">
        <section class="v50-card v50-system"><div class="v50-section-head"><div><span><?=e(tr('01 · Vidím systém'))?></span><h2><?=e(tr('Interaktivní model'))?></h2></div><small><?=e(tr('Přepínej vrstvy L2–L7 / OS'))?></small></div><?php v50_topology_svg($spec); ?><div class="v50-problem"><strong><?=e(tr('Symptom'))?></strong><p><?=edu_cs((string)$spec['problem'])?></p><small><?=e(tr('Parametrická varianta: VLAN {vlan} · {ip}/{prefix} · port {port}',['vlan'=>(string)$spec['params']['vlan'],'ip'=>(string)$spec['params']['client_ip'],'prefix'=>(string)$spec['params']['prefix'],'port'=>(string)$spec['params']['port']]))?></small></div></section>
        <aside class="v50-card v50-passport-mini"><div class="v50-section-head"><div><span>Skill Passport</span><h2><?=e(tr('Co už umíš prokázat'))?></h2></div></div><?php foreach($passport as $dim=>$pct):?><div class="v50-dim"><div><span><?=e(v50_dim_label($dim))?></span><strong><?=(int)$pct?>%</strong></div><i><b style="width:<?=(int)$pct?>%"></b></i></div><?php endforeach;?><a href="?view=skill_passport"><?=e(tr('Otevřít celý Passport →'))?></a></aside>
      </div>

      <section class="v50-card"><div class="v50-section-head"><div><span><?=e(tr('02 · Předpověz'))?></span><h2><?=e(tr('Hypotéza před terminálem'))?></h2></div><small><?=e(tr('Terminál se odemyká až po commitnutí modelu.'))?></small></div><?php if(!$hasHyp):?><form method="post" class="v50-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="v50_hypothesis"><input type="hidden" name="lesson_number" value="<?=$lessonNo?>"><label><?=edu_cs((string)$spec['hypothesis_prompt'])?><textarea name="hypothesis" rows="3" required minlength="18" maxlength="1400" placeholder="<?=e(tr('Myslím, že… Vyvrátil by to výsledek…'))?>"></textarea></label><button class="btn primary"><?=e(tr('Commitnout hypotézu a odemknout lab'))?></button></form><?php else:?><div class="v50-complete-line"><span>✓</span><div><strong><?=e(tr('Hypotéza je commitnutá'))?></strong><p><?=e(tr('Teď hledej důkaz, který ji může potvrdit nebo vyvrátit.'))?></p></div></div><?php endif;?></section>

      <section class="v50-card <?=!$hasHyp?'v50-locked':''?>"><div class="v50-section-head"><div><span><?=e(tr('03 · Měř'))?></span><h2><?=e(tr('Terminál + evidence'))?></h2></div><small><?=e(v50_runtime_mode()==='oci'?tr('Ephemeral rootless OCI sandbox'):tr('Bezpečný stateful simulator'))?></small></div>
        <?php if(!$hasHyp):?><div class="v50-lock"><strong><?=e(tr('Nejdřív hypotéza.'))?></strong><span><?=e(tr('Bez předpovědi se z terminálu snadno stane náhodné zkoušení příkazů.'))?></span></div><?php else:?><div class="v50-terminal" data-v50-terminal><div class="v50-terminal-bar"><i></i><i></i><i></i><span>student@educanet-lab:~</span></div><pre data-terminal-output><?=e((string)($lastCmd['output']??tr('Terminál je připraven. Zvol nejmenší test, který něco rozliší.')))?></pre><form method="post" class="v50-command-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="v50_command"><input type="hidden" name="lesson_number" value="<?=$lessonNo?>"><label><span>$</span><input name="command" required autocomplete="off" spellcheck="false" list="v50-command-list" placeholder="<?=e(tr('napiš bezpečný diagnostický příkaz'))?>"></label><datalist id="v50-command-list"><?php foreach($spec['allowed_commands'] as $cmd):?><option value="<?=e((string)$cmd)?>"><?php endforeach;?></datalist><button class="btn primary"><?=e(tr('Spustit'))?></button></form></div><div class="v50-command-palette"><span><?=e(tr('Možné nástroje pro tento sandbox'))?></span><?php foreach(array_slice((array)$spec['allowed_commands'],0,8) as $cmd):?><button type="button" data-command-fill="<?=e((string)$cmd)?>"><code><?=e((string)$cmd)?></code></button><?php endforeach;?></div><?php endif;?>
      </section>

      <section class="v50-two-col">
        <article class="v50-card"><div class="v50-section-head"><div><span><?=e(tr('04 · Least help first'))?></span><h2><?=e(tr('Nápověda bez prozrazení'))?></h2></div></div><div class="v50-hints"><?php foreach($spec['hints'] as $hint):?><details><summary><b><?=e(tr('Úroveň {level}',['level'=>(int)$hint['level']]))?></b> <?=edu_cs((string)$hint['label'])?></summary><p><?=edu_cs((string)$hint['text'])?></p><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="v50_hint"><input type="hidden" name="lesson_number" value="<?=$lessonNo?>"><input type="hidden" name="hint_level" value="<?=(int)$hint['level']?>"><button class="v50-text-button"><?=e(tr('Zaznamenat použití této nápovědy'))?></button></form></details><?php endforeach;?></div></article>
        <article class="v50-card"><div class="v50-section-head"><div><span><?=e(tr('05 · Ověř stav'))?></span><h2><?=e(tr('Ne „správný příkaz“, ale funkční systém'))?></h2></div></div><p><?=edu_cs((string)$spec['proof'])?></p><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="v50_validate"><input type="hidden" name="lesson_number" value="<?=$lessonNo?>"><button class="btn primary"><?=e(tr('Ověřit výsledný stav'))?></button></form><?php if($lastValidation):?><div class="v50-validation <?=!empty($lastValidation['correct'])?'ok':'no'?>"><?=e(!empty($lastValidation['correct'])?tr('✓ Stav splňuje checkpoint.'):tr('Ještě ne. Získej další důkaz nebo oprav skutečnou příčinu.'))?></div><?php endif;?></article>
      </section>

      <section class="v50-two-col"><article class="v50-card"><div class="v50-section-head"><div><span><?=e(tr('06 · Vysvětli'))?></span><h2><?=e(tr('Root cause vlastními slovy'))?></h2></div></div><form method="post" class="v50-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="v50_explain"><input type="hidden" name="lesson_number" value="<?=$lessonNo?>"><textarea name="explanation" rows="4" minlength="28" required placeholder="<?=e(tr('Příčina byla… Důkazem je… Oprava funguje, protože…'))?>"></textarea><button class="btn secondary"><?=e(tr('Uložit vysvětlení'))?></button></form></article><article class="v50-card"><div class="v50-section-head"><div><span><?=e(tr('07 · Přenes'))?></span><h2><?=e(tr('Nový kontext'))?></h2></div></div><p><?=edu_cs((string)$spec['transfer'])?></p><form method="post" class="v50-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="v50_transfer"><input type="hidden" name="lesson_number" value="<?=$lessonNo?>"><textarea name="transfer" rows="4" minlength="28" required placeholder="<?=e(tr('Stejný princip by… Znovu bych ale ověřil…'))?>"></textarea><button class="btn secondary"><?=e(tr('Uložit transfer'))?></button></form></article></section>
      <section class="v50-card v50-peer-cta"><div><span><?=e(tr('Peer debugging'))?></span><h2><?=e(tr('Nech si oponovat hypotézu, ne opsat řešení.'))?></h2><p><?=e(tr('Driver, Observer a Explainer sdílejí jen hypotézu, důkaz a další krok.'))?></p></div><a class="btn secondary" href="?view=peer_lab"><?=e(tr('Otevřít peer room'))?></a></section>
    </section><?php render_footer();
}

function v50_render_skill_passport(string $classId,array $module,string $flash=''): void
{
    $studentKey=adaptive_student_key($classId);$passport=v50_student_passport($classId,$studentKey);$capstones=v50_growth_capstones_for_student($classId,$studentKey);render_header(tr('Skill Passport'),$module);
    ?><section class="v50-shell"><header class="v50-hero"><div><div class="eyebrow">Skill Passport</div><h1><?=e(tr('Důkazy, které umíš přenést do praxe'))?></h1><p><?=e(tr('Oddělujeme znalost principu od diagnostiky, opravy, vysvětlení a transferu. Není to známka ani XP.'))?></p></div><a class="btn secondary" href="?view=growth"><?=e(tr('Rozvojové cesty'))?></a></header><?php if($flash!==''):?><div class="notice"><?=e($flash)?></div><?php endif;?><section class="v50-passport-grid"><?php foreach($passport as $dim=>$pct):?><article><span><?=e(v50_dim_label($dim))?></span><strong><?=(int)$pct?>%</strong><div class="v50-ring" style="--p:<?=(int)$pct?>"><i></i></div><p><?=e(match($dim){'principle'=>tr('Umíš formulovat model před experimentem.'),'recognition'=>tr('Umíš číst signály a výstupy.'),'diagnosis'=>tr('Umíš zúžit příčinu pomocí evidence.'),'repair'=>tr('Umíš dostat systém do cílového stavu.'),'explain'=>tr('Umíš obhájit příčinu i důkaz.'),'transfer'=>tr('Umíš použít princip v jiné situaci.'),default=>''})?></p></article><?php endforeach;?></section><section class="v50-card"><div class="v50-section-head"><div><span><?=e(tr('Portfolio evidence'))?></span><h2><?=e(tr('Capstone projekty'))?></h2></div></div><?php if(!$capstones):?><p><?=e(tr('Zatím bez capstone projektu. Dobrovolné cesty je odemknou po skutečném progressu.'))?></p><?php else:?><div class="v50-capstones"><?php foreach($capstones as $c):?><article><span><?=edu_cs((string)(v50_growth_catalog()[(string)$c['path_id']]['title']??$c['path_id']))?></span><h3><?=edu_cs((string)$c['title'])?></h3><p><?=edu_cs((string)$c['reflection'])?></p><?php if(safe_url((string)($c['url']??''))!==''):?><a target="_blank" rel="noopener noreferrer" href="<?=e(safe_url((string)$c['url']))?>"><?=e(tr('Otevřít projekt ↗'))?></a><?php endif;?></article><?php endforeach;?></div><?php endif;?></section></section><?php render_footer();
}

function v50_render_peer_lab(string $classId,array $module,string $flash=''): void
{
    $studentKey=adaptive_student_key($classId);$code=strtoupper((string)($_GET['room']??''));$room=$code!==''?v50_peer_room($classId,$code):null;render_header(tr('Peer debugging'),$module);
    ?><section class="v50-shell"><header class="v50-hero"><div><div class="eyebrow">Peer debugging</div><h1><?=e(tr('Tři role, žádné „udělám to za tebe“'))?></h1><p><?=e(tr('Driver provádí kroky, Observer hledá chybějící důkaz, Explainer musí obhájit kauzalitu.'))?></p></div></header><?php if($flash!==''):?><div class="notice"><?=e($flash)?></div><?php endif;?><section class="v50-card"><form method="post" class="v50-inline-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="v50_peer_join"><label><?=e(tr('Kód místnosti'))?><input name="room_code" value="<?=e($code)?>" minlength="4" maxlength="10" required placeholder="NET42"></label><button class="btn primary"><?=e(tr('Vstoupit / vytvořit'))?></button></form></section><?php if($room):?><section class="v50-peer-grid"><article class="v50-card"><div class="v50-section-head"><div><span><?=e(tr('Room {code}',['code'=>$code]))?></span><h2><?=e(tr('Role'))?></h2></div></div><?php foreach((array)$room['members'] as $sk=>$m):?><div class="v50-peer-member"><b><?=e((string)$m['role'])?></b><span><?=e(hash_equals((string)$sk,$studentKey)?tr('Ty'):tr('Spolužák {hash}',['hash'=>substr(hash('sha256',(string)$sk),0,4)]))?></span></div><?php endforeach;?></article><article class="v50-card"><div class="v50-section-head"><div><span><?=e(tr('Strukturovaná spolupráce'))?></span><h2><?=e(tr('Přidej jeden kvalitní krok'))?></h2></div></div><form method="post" class="v50-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="v50_peer_note"><input type="hidden" name="room_code" value="<?=e($code)?>"><select name="note_type"><option value="hypothesis"><?=e(tr('Hypotéza'))?></option><option value="evidence"><?=e(tr('Evidence'))?></option><option value="next_step"><?=e(tr('Další krok'))?></option></select><textarea name="note" required minlength="8" rows="3"></textarea><button class="btn secondary"><?=e(tr('Přidat'))?></button></form></article></section><section class="v50-card"><div class="v50-peer-notes"><?php foreach(array_reverse((array)$room['notes']) as $note):?><article><b><?=e((string)$note['type'])?></b><p><?=edu_cs((string)$note['text'])?></p><small><?=e((string)$note['created_at'])?></small></article><?php endforeach;?></div></section><?php endif;?></section><?php render_footer();
}

function v50_render_teacher_heatmap(string $classId): void
{
    $heat=v50_teacher_heatmap($classId);?><section class="teacher-ops-section v50-teacher-heat"><div class="teacher-section-head"><div><div class="eyebrow">v50 · Hands-on Intelligence</div><h2>Jak třída přemýšlí v praxi</h2><p>Agregace odděluje rozpoznání problému, diagnostiku, opravu, vysvětlení a transfer. Počet příkazů se nehodnotí.</p></div><span><?=count((array)$heat['students'])?> studentů</span></div><div class="v50-teacher-dims"><?php foreach((array)$heat['average'] as $dim=>$pct):?><article><span><?=e(v50_dim_label((string)$dim))?></span><strong><?=(int)$pct?>%</strong><i><b style="width:<?=(int)$pct?>%"></b></i></article><?php endforeach;?></div></section><?php
}

function v50_render_teacher_lesson_card(string $classId,int $lessonNo): void
{
    if(!in_array($classId,['class_3a','class_4a'],true))return;
    $lesson=v42_find_lesson($classId,max(1,min(28,$lessonNo)));if(!$lesson)return;
    $spec=v50_lab_spec($classId,$lesson,'teacher-preview');
    ?><section class="teacher-panel v50-teacher-mission"><div class="teacher-panel-head"><div><span>v50 · Hands-on mise</span><h2><?=e((string)$spec['lesson_title'])?></h2><p><?=e((string)$spec['mission'])?></p></div><?php if(!empty($spec['boss_fight'])):?><b class="v50-boss-pill">Boss Fight</b><?php endif;?></div><div class="v50-teacher-mission-grid"><article><span>Hypotéza</span><p><?=e((string)$spec['hypothesis_prompt'])?></p></article><article><span>Minimální důkaz</span><p><?=e((string)$spec['proof'])?></p></article><article><span>Transfer</span><p><?=e((string)$spec['transfer'])?></p></article></div><div class="v50-chip-row"><span><?=e((string)$spec['family_label'])?></span><span><?=e((string)$spec['layer'])?></span><span><?=count((array)$spec['allowed_commands'])?> bezpečných nástrojů</span></div></section><?php
}
