<?php

declare(strict_types=1);
if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

function v50_growth_domain_label(string $domain): string { return match($domain){'design'=>tr('Design'),'development'=>tr('Web development'),'backend'=>tr('Backend'),'infrastructure'=>tr('Infrastructure'),'security'=>tr('Security'),default=>$domain}; }
function v50_growth_path_order(): array { return ['webdesign','frontend-foundations','modern-frontend','ux-engineering','php-foundations','modern-php','laravel-backend','fullstack-product','network-engineering','linux-automation','containers-devops','cloud-sre','blue-team']; }

function v50_render_growth_overview(string $classId,array $module,string $flash=''): void
{
    $studentKey=adaptive_student_key($classId);$catalog=v50_growth_catalog();$controls=v50_growth_controls_for_student($classId,$studentKey);
    $goalNow=function_exists('v504_goal_selected')?v504_goal_selected($classId,$studentKey):null;$goalPath=is_array($goalNow)?(string)($goalNow['path']??''):'';
    $rows=[];$focus=null;
    foreach(v50_growth_path_order() as $id){$path=$catalog[$id]??null;if(!is_array($path)||!in_array($classId,(array)$path['classes'],true))continue;$state=v50_growth_state($classId,$studentKey,$id);$control=$controls[$id]??null;$pct=(int)round((float)$state['progress']*100);$row=['id'=>$id,'path'=>$path,'state'=>$state,'control'=>$control,'pct'=>$pct];$rows[]=$row;if($goalPath===$id&&!empty($state['unlocked']))$focus=$row;}
    if(!$focus){foreach($rows as $row){if(!empty($row['state']['unlocked'])&&(int)$row['pct']<100){$focus=$row;break;}}}
    if(!$focus){foreach($rows as $row){if(!empty($row['state']['unlocked'])){$focus=$row;break;}}}
    render_header(tr('Dobrovolný rozvoj'),$module);
    ?><section class="v50-shell v506-growth-shell"><header class="v50-hero"><div><div class="eyebrow"><?=e(tr('Dobrovolný rozvoj'))?></div><h1><?=e(tr('Rozvíjej se jedním směrem.'))?></h1><p><?=e(tr('Povinná výuka má vždy přednost. Tady stačí pokračovat v jedné cestě; ostatní směry jsou schované v mapě.'))?></p></div></header><?php if($flash!==''):?><div class="notice"><?=e($flash)?></div><?php endif;?>
    <?php if(is_array($focus)): $fp=$focus['path'];$fs=$focus['state']; ?><article class="v506-growth-focus goal-recommended"><div><span><?= $goalPath===(string)$focus['id']?e(tr('TVŮJ ZVOLENÝ SMĚR')):e(tr('DOPORUČENÝ DALŠÍ SMĚR')) ?></span><h2><?=edu_cs((string)$fp['title'])?></h2><p><?=isset($fp['summary'])||isset($fp['description'])?edu_cs((string)($fp['summary']??$fp['description'])):e(tr('Pokračuj nejbližším odemčeným modulem.'))?></p><small><?=count((array)$fs['completed'])?> / <?=count((array)$fp['modules'])?> <?=e(tr('modulů hotovo'))?> · <?= (int)$focus['pct'] ?> %</small></div><a class="btn primary" href="<?=e(v505_task_url('growth',['path'=>(string)$focus['id']], '?view=growth'))?>"><?=e(tr('Pokračovat →'))?></a></article><?php else:?><section class="v50-card"><h2><?=e(tr('Nejdřív dokonči nejbližší povinný krok.'))?></h2><p><?=e(tr('Jakmile se odemkne rozvojová cesta, objeví se tady jako jediný doporučený směr.'))?></p><a class="btn primary" href="?view=dashboard"><?=e(tr('Pokračovat ve výuce →'))?></a></section><?php endif;?>
    <details class="v506-progressive v506-map-details"><summary><span><strong><?=e(tr('Všechny rozvojové cesty'))?></strong><small><?=e(tr('Mapa je jen pro přehled nebo změnu směru.'))?></small></span><b><?=e(tr('Zobrazit mapu'))?></b></summary><section class="v50-growth-map"><?php foreach($rows as $row):$id=(string)$row['id'];$path=(array)$row['path'];$state=(array)$row['state'];$control=$row['control'];$pct=(int)$row['pct'];?><article class="v50-growth-node <?=!empty($state['unlocked'])?'open':'locked'?> <?=is_array($control)?'teacher-marked':''?> <?=$goalPath===$id?'goal-recommended':''?>"><div class="v50-growth-node-top"><span><?=e(v50_growth_domain_label((string)$path['domain']))?></span><?php if(is_array($control)):?><b><?=e(match((string)$control['mode']){'pin'=>tr('Připnuto učitelem'),'hide'=>tr('Dočasně skryto'),'recommend'=>tr('Doporučeno'),default=>tr('Učitel')})?></b><?php endif;?></div><h2><?=edu_cs((string)$path['title'])?></h2><div class="v50-progress"><i><b style="width:<?=$pct?>%"></b></i><strong><?=$pct?>%</strong></div><?php if(!empty($state['unlocked'])):?><p><?=count((array)$state['completed'])?> / <?=count((array)$path['modules'])?> <?=e(tr('modulů · bez deadline'))?></p><a class="btn secondary small" href="<?=e(v505_task_url('growth',['path'=>$id], '?view=growth'))?>"><?=e(tr('Pokračovat →'))?></a><?php else:?><p><?=e(implode(' ',(array)$state['reasons']))?></p><a class="v50-preview-link" href="<?=e(module_url('growth_path',['path'=>$id]))?>"><?=e(tr('Náhled roadmapy'))?></a><?php endif;?></article><?php endforeach;?></section></details></section><?php render_footer();
}

function v50_render_php_card(array $card): void
{
    ?><section class="v50-php-lab" data-php-lab<?=edu_content_lang_attr()?>><div class="v50-php-mental"><span><?=e(tr('Mentální model'))?></span><p><?=e((string)$card['model'])?></p><div class="v50-flow"><?php foreach((array)$card['flow'] as $i=>$step):?><div><b><?=sprintf('%02d',$i+1)?></b><span><?=e((string)$step)?></span></div><?php endforeach;?></div></div><div class="v50-code-trace"><div class="v50-code"><div class="v50-codebar"><span>PHP 8.5 · <?=e(tr('bezpečná ukázka'))?></span><button type="button" data-trace-next><?=e(tr('Další krok →'))?></button></div><pre><code><?=e((string)$card['code'])?></code></pre></div><ol class="v50-trace"><?php foreach((array)$card['trace'] as $i=>$t):?><li data-trace-step="<?=$i?>"><b><?=$i+1?></b><span><?=e((string)$t)?></span></li><?php endforeach;?></ol></div><div class="v50-php-bottom"><article><span><?=e(tr('Typická chyba'))?></span><p><?=e((string)$card['mistake'])?></p></article><article><span>Security</span><p><?=e((string)$card['security'])?></p></article><article><span><?=e(tr('Mikro-check'))?></span><p><?=e((string)$card['check'])?></p></article></div></section><?php
}

function v50_render_growth_path(string $classId,array $module,string $pathId,string $flash=''): void
{
    $studentKey=adaptive_student_key($classId);$state=v50_growth_state($classId,$studentKey,$pathId);if(empty($state['exists'])){$_SESSION['flash']=tr('Rozvojová cesta nebyla nalezena.');redirect_to('?view=growth');}$path=(array)$state['path'];$cards=v50_php_learning_cards();render_header((string)$path['title'],$module,true);$pct=(int)round((float)$state['progress']*100);$firstPending='';foreach((array)$path['modules'] as $gm){if(!is_array($gm))continue;$gs=(string)($gm['slug']??'');if($gs!==''&&!isset($state['completed'][$gs])){$firstPending=$gs;break;}}
    ?><section class="v50-shell"><header class="v50-hero"><div><div class="eyebrow"><?=e(tr('Dobrovolná cesta'))?> · <?=e(v50_growth_domain_label((string)$path['domain']))?></div><h1><?=edu_cs((string)$path['title'])?></h1><p><?=e(tr('Pochop → Vyzkoušej → Postav → Reflektuj. Není to povinná část školní hodiny.'))?></p><div class="v50-chip-row"><span><?=$pct?> <?=e(tr('% cesty'))?></span><span><?=count((array)$path['modules'])?> <?=e(tr('modulů'))?></span><span><?=e(tr('Capstone od 50 %'))?></span></div></div><a class="btn secondary" href="?view=growth"><?=e(tr('← Mapa rozvoje'))?></a></header><?php if($flash!==''):?><div class="notice"><?=e($flash)?></div><?php endif;?><?php if(empty($state['unlocked'])):?><section class="v50-card v50-path-locked"><span>Roadmap preview</span><h2><?=e(tr('Cesta ještě není odemčená'))?></h2><p><?=e(implode(' ',(array)$state['reasons']))?></p><p><?=e(tr('Můžeš si prohlédnout, co tě čeká, ale dokončení modulů zůstává zamčené, dokud opravdu neumíš prerequisites.'))?></p></section><?php elseif($firstPending!==''):?><section class="v50-card"><div class="eyebrow"><?=e(tr('Nejbližší krok'))?></div><h2><?=e(tr('Pracuj jen na jednom modulu.'))?></h2><p><?=e(tr('One Task Mode schová zbytek roadmapy a po dokončení tě vrátí sem nebo rovnou posune dál.'))?></p><a class="btn primary" href="<?=e(v505_task_url('growth',['path'=>$pathId],module_url('growth_path',['path'=>$pathId])))?>"><?=e(tr('Pokračovat v One Task →'))?></a></section><?php endif;?>
    <details class="v506-progressive v506-map-details"><summary><span><strong><?=e(tr('Celá roadmapa'))?></strong><small><?=e(tr('Aktuální modul řeš v One Task. Roadmapa je jen pro přehled.'))?></small></span><b><?=e(tr('Zobrazit'))?></b></summary><section class="v50-module-list"><?php foreach((array)$path['modules'] as $i=>$m):$slug=(string)$m['slug'];$done=isset($state['completed'][$slug]);?><article id="<?=e($slug===$firstPending?'goal-current-module':'growth-module-'.$slug)?>" class="v50-card v50-module <?= $done?'done':'' ?>"><div class="v50-module-head"><div><span><?=e(tr('Modul'))?> <?=$i+1?> · <?=(int)$m['minutes']?> <?=e(tr('min'))?></span><h2><?=edu_cs((string)$m['title'])?></h2><p><?=edu_cs((string)$m['goal'])?></p></div><b><?=$done?e(tr('✓ hotovo')):e(tr('dobrovolné'))?></b></div><?php if(isset($cards[$slug])): v50_render_php_card($cards[$slug]); else: ?><div class="v50-growth-cycle"<?=edu_content_lang_attr()?>><article><span>01 · <?=e(tr('Pochop'))?></span><p><?=e((string)$m['goal'])?></p></article><article><span>02 · <?=e(tr('Vyzkoušej'))?></span><p><?=e((string)$m['practice'])?></p></article><article><span>03 · <?=e(tr('Postav'))?></span><p><?=e((string)$m['build'])?></p></article><article><span>04 · <?=e(tr('Reflektuj'))?></span><p><?=e((string)$m['reflect'])?></p></article></div><?php endif;?><?php if(!empty($state['unlocked'])&&!$done):?><form method="post" class="v50-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="v50_growth_complete"><input type="hidden" name="path_id" value="<?=e($pathId)?>"><input type="hidden" name="module_slug" value="<?=e($slug)?>"><textarea name="reflection" rows="2" maxlength="1200" placeholder="<?=e(tr('Co bylo rozhodující? Co bys příště udělal/a jinak?'))?>"></textarea><button class="btn secondary"><?=e(tr('Označit modul jako dokončený'))?></button></form><?php endif;?></article><?php endforeach;?></section></details>
    <section id="goal-capstone" class="v50-card v50-capstone"><div><span>Capstone</span><h2><?=edu_cs((string)$path['capstone'])?></h2><p><?=e(tr('Capstone patří do Skill Passportu jako portfolio evidence. Nemění známku ani Mastery.'))?></p></div><?php if(!empty($state['capstone_ready'])):?><form method="post" class="v50-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="v50_growth_capstone"><input type="hidden" name="path_id" value="<?=e($pathId)?>"><input name="title" required maxlength="180" placeholder="<?=e(tr('Název projektu'))?>"><input name="url" type="url" placeholder="https://… (<?=e(tr('volitelné'))?>)"><textarea name="reflection" required minlength="30" rows="4" placeholder="<?=e(tr('Co jsi vytvořil/a, co jsi musel/a vyřešit a jaký důkaz ukazuje, že projekt funguje?'))?>"></textarea><button class="btn primary"><?=e(tr('Přidat do Skill Passportu'))?></button></form><?php else:?><div class="v50-lock"><strong><?=e(tr('Odemkne se při 50 % cesty.'))?></strong><span><?=e(tr('Nejde přeskočit rovnou k certifikátu/projektu bez práce s moduly.'))?></span></div><?php endif;?></section></section><?php render_footer();
}

function v50_render_teacher_growth(string $classId): void
{
    $students=project_students_for_class($classId);$catalog=v50_growth_catalog();?><section class="teacher-ops-section"><div class="teacher-section-head"><div><div class="eyebrow">Dobrovolný rozvoj</div><h1>Growth Paths</h1><p>Učitel může cestu doporučit, připnout nebo skrýt. Nemůže ji změnit na povinnou.</p></div></div><div class="v50-teacher-growth-list"><?php foreach($students as $student):if(!is_array($student))continue;$label=(string)($student['label']??'');if($label==='')continue;$sk=project_student_key($classId,$label);?><article><div><strong><?=e($label)?></strong><span><?=e($classId)?></span></div><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="v50_teacher_growth_control"><input type="hidden" name="class_id" value="<?=e($classId)?>"><input type="hidden" name="student_key" value="<?=e($sk)?>"><select name="path_id"><?php foreach($catalog as $id=>$path):if(!in_array($classId,(array)$path['classes'],true))continue;?><option value="<?=e((string)$id)?>"><?=e((string)$path['title'])?></option><?php endforeach;?></select><select name="control_mode"><option value="recommend">Doporučit</option><option value="pin">Připnout</option><option value="hide">Skrýt</option><option value="clear">Vyčistit</option></select><input name="note" maxlength="600" placeholder="Krátká poznámka"><button class="btn secondary small">Uložit</button></form></article><?php endforeach;?></div></section><?php
}
