<?php

declare(strict_types=1);

return [
 'class_1a' => [
  'color-harmony'=>['title'=>'Barevná harmonie a role palety','summary'=>'Paleta není sbírka oblíbených barev. Každá barva má roli: pozadí, text, akcent nebo stav.','body'=>['Začni neutrální nebo klidnou základní barvou a jedním akcentem. Teprve potom přidávej další odstíny.','Harmonie neznamená, že barvy musí být podobné. Důležité je, aby spolu fungovaly a zachovaly čitelnost.','Pro jednoduchý školní plakát často stačí background + text + accent + případně sekundární neutrální tón.'],'example'=>'#0F172A background · #F8FAFC text · #22C55E accent. Akcent použij na CTA a jeden klíčový detail, ne na všechno.'],
  'iconography'=>['title'=>'Ikonografie: jedna vizuální řeč','summary'=>'Ikony pomáhají rychle číst informace, pokud sdílejí stejný styl a nejsou jen dekorací.','body'=>['Nekombinuj bez důvodu outline, 3D, emoji a ilustrativní ikony v jednom systému.','Sleduj tloušťku tahu, zaoblení, detailnost a optickou velikost.','Ikona má zkrátit cestu k významu. Když je nejasná, textový label je lepší než hádanka.'],'example'=>'Datum, místo a registrace: tři jednoduché outline ikony stejné sady, stejné velikosti a stejného stroke.'],
  'image-composition'=>['title'=>'Obrazová kompozice a focal point','summary'=>'Obraz musí mít hlavní bod a zároveň nechat prostor ostatním informacím.','body'=>['Focal point je místo, ke kterému má oko přijít jako první. Často jde o obličej, produkt nebo hlavní akci.','Crop může změnit příběh fotografie. Vyzkoušej více variant a sleduj, zda zůstává důležitý obsah i prostor pro text.','Při práci s textem nad fotografií kontroluj lokální kontrast, ne jen průměrnou barvu obrázku.'],'example'=>'Portrét vpravo, pohled směrem do volného prostoru vlevo: ideální místo pro headline.'],
  'template-critique'=>['title'=>'Jak kritizovat šablonu bez „líbí/nelíbí“','summary'=>'Kritika designu má pojmenovat problém, jeho dopad a návrh opravy.','body'=>['Začni cílem: co má návrh sdělit a komu. Potom teprve posuzuj hierarchii, čitelnost a konzistenci.','Rozlišuj symptom a příčinu. „Je to přeplněné“ je symptom; příčinou může být příliš mnoho stejně výrazných prvků.','Každá kritika by měla skončit konkrétním návrhem změny a důvodem.'],'example'=>'Problém: datum je stejně výrazné jako headline. Dopad: oko neví, co číst první. Oprava: zmenšit datum a přesunout ho do info skupiny.'],
 ],
 'class_2a' => [
  'ui-spacing-system'=>['title'=>'Spacing tokeny pro UI','summary'=>'Místo náhodných mezer používej malou sadu hodnot, které vytvářejí rytmus a urychlují rozhodování.','body'=>['Typický systém může používat 4 / 8 / 12 / 16 / 24 / 32 px. Nemusíš použít všechny.','Menší mezery drží prvky ve skupině, větší mezery oddělují sekce.','Token neznamená, že každá mezera musí být stejná; znamená, že volíš z řízené sady.'],'example'=>'Button padding 12×16, card gap 16, section gap 32.'],
  'component-consistency'=>['title'=>'Komponenty a konzistence','summary'=>'Komponenta je opakovatelné pravidlo pro stejný typ prvku, ne jen zkopírovaný obdélník.','body'=>['Definuj strukturu, padding, textové role, radius a stavy.','Když stejná role vypadá pokaždé jinak, uživatel musí znovu přemýšlet.','Varianty komponenty jsou v pořádku, pokud mají jasný význam: primary/secondary, default/disabled apod.'],'example'=>'Primary button: stejné paddingy, radius a typografie; mění se label a případně stav.'],
  'microinteraction-storyboard'=>['title'=>'Mikrointerakce: pohyb jako feedback','summary'=>'Krátká animace má vysvětlit změnu stavu, potvrdit akci nebo udržet orientaci.','body'=>['Definuj trigger, přechod a výsledný stav.','Animace bez funkce může zpomalovat a odvádět pozornost.','Storyboard je levnější než ladit efekty až v animačním programu.'],'example'=>'Klik na Save → button loading 400 ms → check + „Uloženo“.'],
  'portfolio-case-study'=>['title'=>'Portfolio case study: ukaž rozhodování','summary'=>'Silná case study vysvětluje problém, proces a výsledek, ne jen galerii hotových obrázků.','body'=>['Struktura: problém → omezení → klíčová rozhodnutí → výsledky → co bych zlepšil.','Vyber jen ty mezikroky, které něco dokazují.','Piš stručně a konkrétně; designérská terminologie má podporovat důvod, ne zakrývat prázdné fráze.'],'example'=>'Before/after hierarchie + krátké vysvětlení, proč se změnil grid a CTA.'],
 ],
 'class_3a' => [
  'ipv6-basics'=>['title'=>'IPv6 základy: adresa, prefix, link-local','summary'=>'IPv6 je 128bitová adresace. Pro začátek stačí umět číst zápis, /64 a rozdíl mezi global a link-local adresou.','body'=>['Nuly lze zkrátit, ale dvojtečku :: můžeš v jedné adrese použít pouze jednou.','/64 je běžná velikost LAN prefixu. Prvních 64 bitů identifikuje síť, zbytek interface část.','fe80::/10 jsou link-local adresy používané na lokálním segmentu.'],'example'=>'2001:db8:10:20::42/64 a 2001:db8:10:20::99/64 sdílejí stejný /64 prefix.'],
  'dns-record-types'=>['title'=>'DNS A, AAAA a CNAME','summary'=>'DNS záznamy mají různé role. A mapuje jméno na IPv4, AAAA na IPv6 a CNAME vytváří alias na jiné jméno.','body'=>['A a AAAA mohou existovat současně pro dual-stack službu.','CNAME neobsahuje IP; ukazuje na další DNS jméno, které se musí dále vyřešit.','Při troubleshootingu ověř typ záznamu, TTL i výslednou hodnotu.'],'example'=>'www.school.cz CNAME web.school.cz; web.school.cz A 203.0.113.50; web.school.cz AAAA 2001:db8::50.'],
  'monitoring-basics'=>['title'=>'Monitoring služby: měř to, co uživatel potřebuje','summary'=>'Ping serveru nestačí. Monitoring má co nejlépe napodobit reálnou uživatelskou cestu.','body'=>['L1: host reachability, L2: port, L3: protokol/aplikace, L4: business/user flow.','Alert musí mít timeout, interval a práh, aby nereagoval na každý jednorázový výkyv.','Po incidentu ověř, zda monitoring uměl problém odhalit dřív než uživatel.'],'example'=>'Web: TCP/443 + HTTPS GET /health + očekávaný status 200 + latency.'],
  'dhcp-reservations'=>['title'=>'DHCP reservation vs. ruční static IP','summary'=>'Reservation dává známému zařízení stabilní adresu přes DHCP a drží centrální přehled.','body'=>['Reservation obvykle páruje identifikátor klienta/MAC s konkrétní IP.','Výhodou je centrální správa gateway, DNS a dalších options.','Ruční static IP může být správně u infrastruktury, ale musí být koordinovaná s adresním plánem.'],'example'=>'Tiskárna MAC AA:BB:CC:DD:EE:01 → reservation 192.168.10.50.'],
 ],
 'class_4a' => [
  'http-observability'=>['title'=>'HTTP observability: status, headers, latency','summary'=>'Jedna HTTP odpověď obsahuje více důkazů než jen body stránky. Status a headers často rychle ukážou, která vrstva reaguje.','body'=>['2xx znamená úspěch, 3xx přesměrování, 4xx problém požadavku/autorizace a 5xx serverovou chybu.','Headers jako Location, Retry-After, Server, Cache-Control nebo trace ID mohou zásadně zrychlit diagnostiku.','Měř status i latency v čase. Jednorázový 200 neříká nic o stabilitě.'],'example'=>'HTTP 503 + Retry-After: 30 znamená, že server/proxy odpovídá, ale služba je dočasně nedostupná.'],
  'load-balancing'=>['title'=>'Load balancing a health checks','summary'=>'Load balancer rozděluje provoz mezi backendy a musí umět nezdravé instance automaticky vyřadit.','body'=>['Round-robin je jednoduchý model; weighted routing dovoluje posílat různý podíl provozu.','Health check musí ověřovat smysluplný stav aplikace, ne jen otevřený port.','Sticky sessions, state a cache mohou změnit očekávané chování a je potřeba o nich vědět.'],'example'=>'web01 50 %, web02 50 %. web02 /health = 500 → vyřadit, dokud se nevrátí do healthy stavu.'],
  'canary-release'=>['title'=>'Canary release a decision gate','summary'=>'Canary nasadí novou verzi malé části uživatelů a dovolí rozhodnout podle měření před plošným rolloutem.','body'=>['Předem definuj baseline, stop podmínky a rollback.','Porovnávej error rate, latency a uživatelský/business signál mezi v1 a v2.','Canary není jen procento provozu; je to řízený experiment s rozhodovacím bodem.'],'example'=>'10 % na v2; pokud error rate >2× baseline po 5 min, automaticky stop + rollback.'],
  'backup-restore'=>['title'=>'Backup nestačí: musíš umět restore','summary'=>'Záloha je hodnotná až tehdy, když je ověřená, dostupná a umíš z ní bezpečně obnovit službu nebo data.','body'=>['Rozliš RPO (kolik dat můžeš ztratit) a RTO (jak dlouho může trvat obnova).','Restore drill prováděj do bezpečného cíle a validuj integritu i funkční stav.','Runbook musí obsahovat zdroj backupu, ownera, pořadí kroků a validační test.'],'example'=>'Denní backup DB + 15min WAL archivy: RPO může být výrazně menší než 24 hodin.'],
 ],
];
