<?php

declare(strict_types=1);

return [
 'class_1a'=>[
  'editorial-typography-i'=>['time'=>'12–16 min','level'=>'Základ+','visual'=>['type'=>'layers','items'=>[['Display','48 px','dominanta'],['Heading','30 px','sekce'],['Body','18 px','čtení'],['Meta','14 px','detail']]],'mental'=>'Typografie je systém rolí, ne sbírka náhodných velikostí.','steps'=>['Pojmenuj textové role.','Sestav malou škálu velikostí.','Nastav line-height.','Ověř délku řádku.','Porovnej návrh v malém náhledu.'],'mistakes'=>['Příliš mnoho velikostí.','Dlouhý řádek bez prostoru.','Stejná váha všech rolí.'],'check'=>['q'=>'Co nejlépe drží delší text čitelný?','options'=>['Jasné role, rozumná délka řádku a konzistentní line-height.','Co nejvíc fontů.','Stejná velikost všech textů.'],'correct'=>0,'why'=>'Čitelnost je kombinace hierarchie a rytmu.']],
  'layout-rhythm-i'=>['time'=>'11–15 min','level'=>'Základ+','visual'=>['type'=>'grid','cols'=>6,'label'=>'Rytmus 8 / 16 / 24 / 40'],'mental'=>'Whitespace a opakovaný spacing vytvářejí strukturu stejně jako samotný grid.','steps'=>['Vyber spacing základ.','Seskup související prvky.','Odděl sekce větší mezerou.','Zarovnej hrany.','Ověř rytmus bez dekorací.'],'mistakes'=>['Každá mezera jiná.','Vyplnit každé prázdné místo.','Nesouvisející prvky příliš blízko.'],'check'=>['q'=>'Kdy použít větší mezeru?','options'=>['Mezi odlišnými skupinami nebo sekcemi.','Mezi každými dvěma písmeny.','Náhodně pro dynamiku.'],'correct'=>0,'why'=>'Velikost mezery komunikuje vztah mezi prvky.']],
  'visual-story-i'=>['time'=>'12–16 min','level'=>'Základ+','visual'=>['type'=>'sequence','items'=>[['01','Focal point'],['02','Kontext'],['03','Detail'],['04','CTA']]],'mental'=>'I statický návrh má časovou osu: divák něco uvidí první a něco až potom.','steps'=>['Urči první pohled.','Nasměruj druhý krok.','Odstraň konkurující dominantu.','Ověř 3s test.','Zkontroluj CTA.'],'mistakes'=>['Tři dominanty současně.','Fotografie vede pohled mimo obsah.','CTA nemá vizuální návaznost.'],'check'=>['q'=>'Co je dobrý focal point?','options'=>['Jasný první bod, který zahájí zamýšlenou sekvenci čtení.','Nejbarevnější prvek bez ohledu na obsah.','Každý prvek stejně výrazný.'],'correct'=>0,'why'=>'Focal point má zahájit příběh, ne jen poutat pozornost.']],
  'production-preflight-i'=>['time'=>'10–14 min','level'=>'Praktické','visual'=>['type'=>'export','formats'=>['master','web','print'],'label'=>'Preflight workflow'],'mental'=>'Kvalitní návrh končí až tehdy, když je správně pojmenovaný, zkontrolovaný a exportovaný.','steps'=>['Odděl master od exportů.','Použij verzování.','Ověř rozměry a obsah.','Zvol preset podle cíle.','Otevři export a zkontroluj ho.'],'mistakes'=>['final_final2.png.','Export bez kontroly.','Přepsat master exportem.'],'check'=>['q'=>'Co patří do preflightu?','options'=>['Rozměr, obsah, crop, kontrast, název a správný export.','Pouze kontrola názvu souboru.','Jen přidání dalšího efektu.'],'correct'=>0,'why'=>'Preflight je poslední kontrola funkčnosti před předáním.']],
 ],
 'class_2a'=>[
  'responsive-type-ii'=>['time'=>'13–17 min','level'=>'Střední','visual'=>['type'=>'compare','left'=>['Desktop','64 / 22 / 18'], 'right'=>['Mobile','40 / 20 / 17']],'mental'=>'Role zůstávají stejné, ale jejich velikost a zalomení se přizpůsobují dostupnému prostoru.','steps'=>['Definuj min/max pro role.','Otestuj desktop.','Zúž viewport.','Oprav wrap a line-height.','Ověř hierarchii na mobilu.'],'mistakes'=>['Proporcionálně zmenšit úplně vše.','Body text pod čitelné minimum.','Ignorovat zalomení headline.'],'check'=>['q'=>'Co se má při změně viewportu zachovat?','options'=>['Role a priorita textu, ne nutně stejná velikost nebo počet řádků.','Přesná pixelová velikost.','Stejný počet znaků na řádku.'],'correct'=>0,'why'=>'Responsivní typografie chrání hierarchii a čitelnost.']],
  'design-tokens-ii'=>['time'=>'13–18 min','level'=>'Střední+','visual'=>['type'=>'layers','items'=>[['Primitive','blue-600 / 16'],['Semantic','action-primary / space-m'],['Component','Button / Card'],['Product','Screen']]],'mental'=>'Token vytváří vrstvu mezi hodnotou a konkrétním použitím.','steps'=>['Odděl primitive a semantic tokeny.','Pojmenuj token podle účelu.','Napoj komponentu.','Vytvoř varianty.','Změň token a sleduj dopad.'],'mistakes'=>['Token nazvaný podle náhodné hodnoty.','Lokální override na každé komponentě.','Duplikovat komponentu pro každý stav.'],'check'=>['q'=>'Proč je semantic token užitečný?','options'=>['Popisuje účel a umožní měnit hodnotu bez přepisování všech komponent.','Zvyšuje počet barev.','Nahrazuje potřebu komponent.'],'correct'=>0,'why'=>'Sémantická vrstva odděluje designové rozhodnutí od konkrétní hodnoty.']],
  'interaction-patterns-ii'=>['time'=>'12–17 min','level'=>'Střední+','visual'=>['type'=>'sequence','items'=>[['Default','ready'],['Loading','čekám'],['Success','potvrzení'],['Error','náprava']]],'mental'=>'Interakce je stavový model. Motion pouze pomáhá vysvětlit přechod mezi stavy.','steps'=>['Sepiš všechny stavy.','Definuj trigger.','Přidej feedback.','Ověř reduced motion.','Zkontroluj stav bez barvy.'],'mistakes'=>['Hover jako jediný stav.','Nekonečná dekorativní animace.','Error jen červenou.'],'check'=>['q'=>'Kdy je motion užitečný?','options'=>['Když vysvětluje změnu stavu nebo potvrzuje akci.','Když je co nejdelší.','Když nahrazuje text chyby.'],'correct'=>0,'why'=>'Motion má zlepšit porozumění a feedback.']],
  'design-critique-ii'=>['time'=>'12–16 min','level'=>'Pokročilé','visual'=>['type'=>'compare','left'=>['Slabá kritika','„nelíbí se mi“'], 'right'=>['Silná kritika','cíl → evidence → rozhodnutí']],'mental'=>'Profesionální kritika hodnotí návrh vůči cíli a důkazům, ne osobnímu vkusu.','steps'=>['Pojmenuj cíl.','Popiš pozorovaný problém.','Přidej evidence.','Navrhni konkrétní změnu.','Dokumentuj handoff.'],'mistakes'=>['Komentovat bez cíle.','Používat jen preference.','Handoff = screenshot.'],'check'=>['q'=>'Co je nejsilnější design argument?','options'=>['Rozhodnutí navázané na cíl a ověřitelnou evidenci.','„Mně se to líbí víc“.','Co nejvíce efektů.'],'correct'=>0,'why'=>'Argumentace musí být přenositelná a testovatelná.']],
 ],
 'class_3a'=>[
  'subnetting-vlsm'=>['time'=>'14–19 min','level'=>'Střední','visual'=>['type'=>'subnet','network'=>'192.168.10.0/24','segments'=>['90 hostů','40 hostů','20 hostů','10 hostů']],'mental'=>'VLSM řeš od největšího segmentu a po každém přidělení posuň další volnou hranici.','steps'=>['Seřaď segmenty podle velikosti.','Vyber prefix pro největší.','Zapiš network/broadcast.','Pokračuj další volnou adresou.','Ověř překryv a rezervu.'],'mistakes'=>['Začít nejmenším subnetem.','Zapomenout hranici bloku.','Překrývající se rozsahy.'],'check'=>['q'=>'Jaký je bezpečný postup VLSM?','options'=>['Přidělovat od největšího požadavku a hlídat hranice každého bloku.','Přidělovat náhodně.','Všem dát /24.'],'correct'=>0,'why'=>'Tím minimalizuješ fragmentaci a chyby.']],
  'network-security-basics'=>['time'=>'13–18 min','level'=>'Střední','visual'=>['type'=>'ports','items'=>[['USERS → WEB','443','allow'],['USERS → SERVERS','ANY','deny'],['MGMT → SERVERS','22','allow']]],'mental'=>'Bezpečný návrh definuje nejen co fungovat má, ale i co fungovat nesmí.','steps'=>['Definuj zóny.','Sepiš potřebné služby.','Vytvoř konkrétní allow.','Přidej deny.','Otestuj pozitivní i negativní cestu.'],'mistakes'=>['ANY→ANY allow.','Pravidlo bez source scope.','Po změně testovat jen povolený scénář.'],'check'=>['q'=>'Co nejlépe odpovídá least privilege?','options'=>['Povolit přesně nutný tok a ostatní nechat blokované.','Povolit vše interně.','Použít jen jeden společný VLAN.'],'correct'=>0,'why'=>'Minimální scope snižuje dopad chyby i útoku.']],
  'dns-dhcp-operations'=>['time'=>'12–17 min','level'=>'Střední','visual'=>['type'=>'sequence','items'=>[['TTL','cache'],['DNS change','nová IP'],['Lease','DHCP čas'],['Renew','nová konfigurace']]],'mental'=>'Změna konfigurace a změna pozorovaná klientem nejsou vždy ve stejný okamžik.','steps'=>['Zjisti TTL/lease.','Naplánuj změnu.','Sleduj starý i nový stav.','Vynucuj renew jen když je potřeba.','Po stabilizaci vrať normální hodnoty.'],'mistakes'=>['Čekat okamžitou propagaci.','Ignorovat cache.','Snížit TTL až po změně.'],'check'=>['q'=>'Proč klient stále vidí starou DNS adresu?','options'=>['Může mít validní cache do vypršení TTL.','DNS vždy používá DHCP port.','TCP automaticky drží starý A record celý den.'],'correct'=>0,'why'=>'TTL určuje dobu platnosti cacheované odpovědi.']],
  'service-debug-chain'=>['time'=>'14–19 min','level'=>'Praktické+','visual'=>['type'=>'layers','items'=>[['DNS','jméno → IP'],['TCP','port reachable'],['TLS','handshake + cert'],['HTTP','status + app']]],'mental'=>'Najdi první vrstvu, která nedává očekávaný důkaz. Tam začíná tvoje další hypotéza.','steps'=>['Ověř DNS.','Ověř TCP port.','Ověř TLS.','Ověř HTTP.','Po opravě zopakuj chain.'],'mistakes'=>['Začít restartem všeho.','Zaměnit ping za test služby.','Ignorovat negativní kontrolu.'],'check'=>['q'=>'DNS i TCP/443 fungují, TLS handshake selže. Kde hledat dál?','options'=>['Certifikát, TLS konfigurace nebo proxy terminace.','DHCP pool klienta.','ARP tabulka tiskárny.'],'correct'=>0,'why'=>'Evidence lokalizuje problém do vrstvy TLS.']],
 ],
 'class_4a'=>[
  'infrastructure-as-code'=>['time'=>'14–20 min','level'=>'Pokročilé','visual'=>['type'=>'flow','items'=>[['Code','desired state'],['Plan','diff'],['Review','scope'],['Apply','change'],['Validate','evidence']]],'mental'=>'Bezpečná automatizace odděluje popis změny, kontrolu dopadu a samotné provedení.','steps'=>['Popiš desired state.','Vytvoř plan/diff.','Zkontroluj scope.','Aplikuj změnu.','Validuj výsledek.'],'mistakes'=>['Apply bez planu.','Velký nečitelný change set.','Ruční změna mimo zdroj pravdy.'],'check'=>['q'=>'Proč je plan důležitý?','options'=>['Ukáže očekávaný diff před změnou prostředí.','Automaticky opraví všechny incidenty.','Nahrazuje monitoring.'],'correct'=>0,'why'=>'Plan dává prostor zkontrolovat scope a riziko.']],
  'config-drift'=>['time'=>'12–18 min','level'=>'Pokročilé','visual'=>['type'=>'compare','left'=>['Desired','repo: 443'], 'right'=>['Actual','runtime: 8443']],'mental'=>'Drift je rozdíl mezi zdrojem pravdy a skutečným prostředím. Nejdřív vysvětli proč vznikl, potom ho naprav.','steps'=>['Detekuj diff.','Zjisti původ změny.','Vyber zdroj pravdy.','Sjednoť stav.','Zabraň opakování.'],'mistakes'=>['Přepsat drift bez analýzy.','Ignorovat ruční hotfix.','Nezapsat finální stav do repozitáře.'],'check'=>['q'=>'Co je configuration drift?','options'=>['Rozdíl mezi deklarovaným a skutečným stavem prostředí.','Běžné kolísání latency.','DNS TTL.'],'correct'=>0,'why'=>'Drift znamená, že realita už neodpovídá požadované konfiguraci.']],
  'performance-engineering'=>['time'=>'14–20 min','level'=>'Pokročilé','visual'=>['type'=>'layers','items'=>[['Latency','p50 / p95 / p99'],['Throughput','RPS'],['Errors','rate'],['Saturation','CPU / queue / I/O']]],'mental'=>'Výkon je víc rozměrů současně. Hledej korelaci mezi uživatelským symptomem a saturací konkrétního zdroje.','steps'=>['Změř baseline.','Sleduj percentily.','Najdi saturaci.','Změň jednu věc.','Znovu změř.'],'mistakes'=>['Pouze průměr latency.','Optimalizace bez baseline.','Přidat CPU bez důkazu bottlenecku.'],'check'=>['q'=>'Proč sledovat p95?','options'=>['Odhalí špatnou zkušenost pomalejší části požadavků, kterou průměr může skrýt.','Je vždy menší než p50.','Nahrazuje error rate.'],'correct'=>0,'why'=>'Percentily ukazují distribuci, ne jen průměr.']],
  'capacity-planning'=>['time'=>'13–19 min','level'=>'Pokročilé','visual'=>['type'=>'flow','items'=>[['Load','realistický mix'],['Measure','latency/errors'],['Headroom','rezerva'],['Decision','scale/optimize'],['Retest','ověření']]],'mental'=>'Kapacitu plánuj podle cílového zatížení a rezervy, ne podle absolutního maxima laboratorního testu.','steps'=>['Definuj workload.','Najdi bod degradace.','Urči headroom.','Vyber scale/optimize strategii.','Retestuj při cílové zátěži.'],'mistakes'=>['Load test s nereálným trafficem.','Kapacita = maximum bez rezervy.','Ignorovat failover scénář.'],'check'=>['q'=>'Co je headroom?','options'=>['Rezerva kapacity pro špičky, růst a výpadek části systému.','Unused DNS cache.','Rozdíl mezi HTTP 200 a 404.'],'correct'=>0,'why'=>'Produkce potřebuje rezervu, ne provoz přesně na limitu.']],
 ],
];
