<?php

declare(strict_types=1);

return [
 'class_1a'=>[
  'color-harmony'=>['time'=>'9–12 min','level'=>'Základ','visual'=>['type'=>'sequence','items'=>[['Background','největší plocha'],['Text','čitelnost'],['Accent','pozornost'],['State','význam']]],'mental'=>'Barva funguje nejlépe, když má jasnou roli a neopakuje se bez důvodu.','steps'=>['Vyber neutrální nebo klidný background.','Nastav čitelný text.','Přidej jeden accent.','Zkontroluj grayscale.','Ověř CTA.'],'mistakes'=>['Pět akcentních barev.','Paleta bez textového kontrastu.','Použít accent na všechno.'],'check'=>['q'=>'Která paleta má nejjasnější strukturu?','options'=>['Background + text + jeden accent.','Šest stejně silných barev.','Každý blok jinou barvou.'],'correct'=>0,'why'=>'Role barev snižují vizuální šum.']],
  'iconography'=>['time'=>'8–11 min','level'=>'Základ','visual'=>['type'=>'flow','items'=>[['Meaning','datum'],['Icon family','outline'],['Size','24 px'],['Label','12. 10.']]],'mental'=>'Ikona je součást informačního systému. Musí být stylově i významově čitelná.','steps'=>['Vyber jednu rodinu ikon.','Sjednoť optickou velikost.','Použij konzistentní barvu/stroke.','Přidej label u nejasné ikony.','Ověř v thumbnailu.'],'mistakes'=>['Emoji + 3D + outline dohromady.','Různé tloušťky.','Ikona místo důležitého textu bez labelu.'],'check'=>['q'=>'Co nejvíc vytváří konzistenci ikon?','options'=>['Společná kresba a optická velikost.','Náhodné efekty.','Každá jiná perspektiva.'],'correct'=>0,'why'=>'Opakovatelné vizuální vlastnosti tvoří systém.']],
  'image-composition'=>['time'=>'9–13 min','level'=>'Základ','visual'=>['type'=>'flow','items'=>[['Photo','focal point'],['Crop','priorita'],['Quiet area','text'],['Contrast','čitelnost']]],'mental'=>'Crop je rozhodnutí o hierarchii obrazu, ne jen technické oříznutí.','steps'=>['Najdi focal point.','Vyzkoušej portrait/square crop.','Vytvoř klidovou zónu pro text.','Ověř lokální kontrast.','Porovnej thumbnail.'],'mistakes'=>['Uříznout důležitou část.','Text přes nejdetailnější místo.','Stejný crop pro všechny formáty.'],'check'=>['q'=>'Co je dobrý crop pro plakát s textem?','options'=>['Zachová focal point a vytvoří prostor pro text.','Vždy vycentruje všechno.','Použije nejvíc detailů.'],'correct'=>0,'why'=>'Crop podporuje hlavní sdělení a čitelnost.']],
  'template-critique'=>['time'=>'10–14 min','level'=>'Praktické','visual'=>['type'=>'sequence','items'=>[['Cíl','co má divák pochopit'],['Symptom','co nefunguje'],['Příčina','proč'],['Oprava','konkrétní změna'],['Test','thumbnail/contrast']]],'mental'=>'Kritika je diagnóza: problém → dopad → oprava → ověření.','steps'=>['Napiš cíl.','Najdi tři symptomy.','Urči příčinu.','Navrhni konkrétní změnu.','Ověř before/after.'],'mistakes'=>['„Nelíbí se mi to“.','Měnit styl bez znalosti cíle.','Přidat další dekorace.'],'check'=>['q'=>'Která kritika je použitelná?','options'=>['Datum soupeří s titulkem; zmenším ho a seskupím s místem.','Je to divné.','Přidáme neon.'],'correct'=>0,'why'=>'Popisuje konkrétní problém, důsledek i opravu.']],
 ],
 'class_2a'=>[
  'ui-spacing-system'=>['time'=>'9–12 min','level'=>'Střední','visual'=>['type'=>'sequence','items'=>[['4','micro'],['8','inside'],['16','group'],['24','section'],['32','major']]],'mental'=>'Tokeny zmenšují počet náhodných rozhodnutí a vytvářejí rytmus.','steps'=>['Vyber základní krok.','Definuj 4–6 hodnot.','Přiřaď role.','Použij systém na cards.','Audituj výjimky.'],'mistakes'=>['13, 17, 23, 29 px bez důvodu.','Stejná mezera uvnitř i mezi sekcemi.','Tokeny bez názvu/role.'],'check'=>['q'=>'Proč používat spacing tokeny?','options'=>['Kvůli konzistenci a rychlejším rozhodnutím.','Aby všechny mezery byly stejné.','Aby UI mělo více čísel.'],'correct'=>0,'why'=>'Tokeny jsou omezená sada smysluplných hodnot.']],
  'component-consistency'=>['time'=>'10–14 min','level'=>'Střední','visual'=>['type'=>'flow','items'=>[['Component','Button'],['Variant','Primary'],['State','Hover'],['Token','padding/radius/type']]],'mental'=>'Komponenta drží stejné významové role ve stejném vizuálním pravidle.','steps'=>['Definuj anatomy.','Nastav tokeny.','Vytvoř varianty.','Vytvoř states.','Použij v reálném layoutu.'],'mistakes'=>['Každý button jiný radius.','Disabled bez kontrastního rozlišení.','Varianty bez významu.'],'check'=>['q'=>'Co je správná varianta komponenty?','options'=>['Primary/secondary podle významu.','Náhodný gradient pro každou instanci.','Jiná výška každého tlačítka.'],'correct'=>0,'why'=>'Varianty mají odpovídat funkčním rolím.']],
  'microinteraction-storyboard'=>['time'=>'9–13 min','level'=>'Střední','visual'=>['type'=>'sequence','items'=>[['Trigger','click'],['Transition','loading'],['Feedback','success'],['Rest','stable state']]],'mental'=>'Mikrointerakce komunikuje změnu stavu v čase.','steps'=>['Definuj trigger.','Urči očekávání uživatele.','Navrhni přechod.','Navrhni feedback.','Ověř fallback bez animace.'],'mistakes'=>['Animace bez funkce.','Příliš dlouhý delay.','Stav pochopitelný jen přes pohyb.'],'check'=>['q'=>'Co je dobrá mikrointerakce?','options'=>['Krátký feedback na konkrétní akci.','Náhodné poskakování prvků.','Pětisekundový přechod při každém hoveru.'],'correct'=>0,'why'=>'Pohyb má pomáhat orientaci a potvrdit stav.']],
  'portfolio-case-study'=>['time'=>'10–15 min','level'=>'Střední','visual'=>['type'=>'sequence','items'=>[['Problem','brief'],['Process','wireframe'],['Decision','why'],['Result','final'],['Reflection','next']]],'mental'=>'Case study ukazuje schopnost rozhodovat, ne jen schopnost exportovat obrázek.','steps'=>['Zkrať problém na 2 věty.','Vyber 2 důležitá rozhodnutí.','Ukaž relevantní proces.','Ukaž výsledek.','Přidej reflexi.'],'mistakes'=>['Galerie bez kontextu.','Deset screenshotů editoru.','Text plný prázdných superlativů.'],'check'=>['q'=>'Co je jádro case study?','options'=>['Problém, rozhodnutí a výsledek.','Seznam použitých kláves.','Pouze finální mockup.'],'correct'=>0,'why'=>'Portfolio dokazuje způsob řešení problému.']],
 ],
 'class_3a'=>[
  'ipv6-basics'=>['time'=>'11–15 min','level'=>'Základ+','visual'=>['type'=>'layers','items'=>[['Global','2001:db8::/32','routovatelná'],['LAN','/64','prefix'],['Host','::42','interface'],['Link-local','fe80::/10','lokální']]],'mental'=>'IPv6 čti jako prefix sítě + interface část. Neuč se celou adresu nazpaměť.','steps'=>['Najdi prefix.','Zkrať nuly.','Rozliš global/link-local.','Porovnej dvě /64 adresy.','Ověř ip -6 addr.'],'mistakes'=>['Dvakrát použít ::.','Zaměnit /64 za počet hostů jako u IPv4.','Ignorovat link-local gateway.'],'check'=>['q'=>'Co typicky znamená /64 v LAN?','options'=>['Prvních 64 bitů je prefix sítě.','64 hostů.','TCP port 64.'],'correct'=>0,'why'=>'Prefix length udává počet bitů síťové části.']],
  'dns-record-types'=>['time'=>'10–14 min','level'=>'Základ+','visual'=>['type'=>'flow','items'=>[['www','CNAME'],['web.school.cz','A + AAAA'],['IPv4','203.0.113.50'],['IPv6','2001:db8::50']]],'mental'=>'Typ záznamu říká, jaký vztah DNS popisuje.','steps'=>['Urči A.','Urči AAAA.','Urči CNAME.','Ověř dig/nslookup.','Porovnej TTL.'],'mistakes'=>['CNAME s IP hodnotou.','AAAA pro IPv4.','Ignorovat chybný AAAA v dual-stack.'],'check'=>['q'=>'Který záznam mapuje jméno na IPv6?','options'=>['AAAA','A','CNAME'],'correct'=>0,'why'=>'AAAA je adresní záznam pro IPv6.']],
  'monitoring-basics'=>['time'=>'11–15 min','level'=>'Praktické','visual'=>['type'=>'layers','items'=>[['Ping','host'],['TCP','port'],['HTTP','protokol'],['User flow','funkce']]],'mental'=>'Čím výš monitoruješ, tím lépe měříš skutečnou zkušenost uživatele.','steps'=>['Vyber cíl.','Zvol check.','Nastav interval/timeout.','Nastav threshold.','Ověř alert.'],'mistakes'=>['Ping jako jediný web monitoring.','Alert po jednom packet loss.','Bez success criteria.'],'check'=>['q'=>'Co nejlépe ověří web z pohledu uživatele?','options'=>['HTTPS request s očekávaným statusem/obsahem.','Pouze ping.','ARP cache.'],'correct'=>0,'why'=>'Aplikační check ověřuje skutečnou službu.']],
  'dhcp-reservations'=>['time'=>'9–13 min','level'=>'Praktické','visual'=>['type'=>'flow','items'=>[['MAC','AA:BB...'],['DHCP','reservation'],['IP','192.168.10.50'],['Options','GW + DNS']]],'mental'=>'Reservation kombinuje stabilní adresu s centrální DHCP správou.','steps'=>['Najdi MAC/ID.','Vyber IP podle plánu.','Zapiš reservation.','Renew klienta.','Ověř lease.'],'mistakes'=>['IP koliduje s jiným static zařízením.','Špatná MAC.','Klient neobnoví lease.'],'check'=>['q'=>'Jaká je výhoda reservation?','options'=>['Stabilní IP a centrální správa DHCP options.','Nemusí existovat DHCP server.','Automaticky vypne firewall.'],'correct'=>0,'why'=>'Adresa zůstává řízená serverem, ale může být stabilní pro konkrétní zařízení.']],
 ],
 'class_4a'=>[
  'http-observability'=>['time'=>'11–15 min','level'=>'Pokročilé','visual'=>['type'=>'sequence','items'=>[['Request','GET /'],['Status','503'],['Headers','Retry-After'],['Trace','x-request-id'],['Latency','820 ms']]],'mental'=>'HTTP odpověď je diagnostický balíček: status + headers + čas + body.','steps'=>['Získej curl -I/-v.','Přečti status.','Přečti důležité headers.','Porovnej latency.','Spoj trace ID s logy.'],'mistakes'=>['Ignorovat headers.','200 = vše vždy zdravé.','Měřit bez času.'],'check'=>['q'=>'HTTP 503 dokazuje co?','options'=>['Nějaká HTTP vrstva odpověděla, ale služba je nedostupná.','DNS určitě selhal.','TCP port je zavřený.'],'correct'=>0,'why'=>'Status 503 je HTTP odpověď, takže cesta do HTTP vrstvy proběhla.']],
  'load-balancing'=>['time'=>'11–15 min','level'=>'Pokročilé','visual'=>['type'=>'flow','items'=>[['Client','requests'],['LB','policy + health'],['web01','healthy'],['web02','unhealthy']]],'mental'=>'LB rozhoduje kam poslat request; health check rozhoduje, kdo smí dostávat běžný provoz.','steps'=>['Definuj pool.','Nastav policy.','Nastav health check.','Simuluj failure.','Ověř recovery.'],'mistakes'=>['TCP open = app healthy.','Žádný fail threshold.','Unhealthy backend stále v rotaci.'],'check'=>['q'=>'Co má LB udělat s backendem, který stabilně selhává health check?','options'=>['Dočasně ho vyřadit z běžného provozu.','Poslat mu více requestů.','Změnit klientům DNS.'],'correct'=>0,'why'=>'Health check chrání uživatele před známým nezdravým backendem.']],
  'canary-release'=>['time'=>'12–16 min','level'=>'Pokročilé','visual'=>['type'=>'flow','items'=>[['Baseline','v1'],['10 %','v2'],['Compare','error + latency'],['Gate','promote/rollback']]],'mental'=>'Canary je experiment s omezeným dopadem a předem definovaným rozhodovacím pravidlem.','steps'=>['Zapiš baseline.','Definuj 10 %.','Definuj metrics.','Definuj stop podmínku.','Rozhodni promote/rollback.'],'mistakes'=>['Bez baseline.','Rozšířit problém na 100 %.','Rozhodovat pocitem.'],'check'=>['q'=>'Kdy canary rollbackovat?','options'=>['Když překročí předem definovanou stop podmínku.','Až když si stěžuje celá škola.','Nikdy.'],'correct'=>0,'why'=>'Decision gate musí být objektivní a připravený před deployem.']],
  'backup-restore'=>['time'=>'12–16 min','level'=>'Pokročilé','visual'=>['type'=>'sequence','items'=>[['Backup','snapshot/WAL'],['Verify','integrity'],['Restore','test target'],['Validate','data + app'],['RPO/RTO','fit']]],'mental'=>'Backup bez testovaného restore postupu je jen naděje.','steps'=>['Vyber recovery point.','Ověř backup.','Obnov do bezpečného cíle.','Validuj data i funkci.','Zapiš skutečný čas a gap.'],'mistakes'=>['Restore poprvé v produkčním incidentu.','Neověřený backup.','Ignorovat RPO/RTO.'],'check'=>['q'=>'Co je RPO?','options'=>['Maximální tolerovaná ztráta dat v čase.','Maximální CPU.','Port pro restore.'],'correct'=>0,'why'=>'RPO určuje, jak stará data ještě mohou být přijatelná po obnově.']],
 ],
];
