<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · Linux Lab – příručka (CNT-02), část B: příkazy v57 od m do z.
 * Čistá data ('tldr' + 'see_also' přes 'extend'); chybějící příkazy registru dostávají plnou položku.
 */

lab58_register_manual(['commands' => [
    'man' => ['extend' => true, 'tldr' => [['man ls', 'příručka k příkazu'], ['man -k obráz', 'hledá příkazy podle popisu']], 'see_also' => ['help', 'whereis', 'type']],
    'md5sum' => ['extend' => true, 'tldr' => [['md5sum vitej.txt', 'otisk souboru'], ['md5sum data/* > otisky.txt', 'uloží otisky pro pozdější kontrolu']], 'see_also' => ['sha256sum', 'sha1sum', 'diff']],
    'mise' => ['extend' => true, 'tldr' => [['mise', 'znovu ukáže zadání úlohy']], 'see_also' => ['hint', 'check', 'submit']],
    'mkdir' => ['extend' => true, 'tldr' => [['mkdir fotky', 'nová složka'], ['mkdir -p web/obrazky/nahledy', 'celá cesta najednou'], ['mkdir -v fotky texty', 'víc složek najednou a vypíše co vytvořil']], 'see_also' => ['rmdir', 'mv', 'tree']],
    'more' => ['extend' => true, 'tldr' => [['more data/access.log', 'stránkovaný výpis']], 'see_also' => ['less', 'cat']],
    'mv' => ['extend' => true, 'tldr' => [['mv vitej.txt uvod.txt', 'přejmenuje soubor'], ['mv data/*.txt /tmp/', 'přesune víc souborů do složky'], ['mv -v poznamky.txt projekty/', 'přesune a vypíše co udělal']], 'see_also' => ['cp', 'rename', 'rm']],
    'nano' => ['extend' => true, 'tldr' => [['nano poznamky.txt', 'otevře soubor v editoru (Ctrl+O uloží, Ctrl+X konec)']], 'see_also' => ['cat', 'touch']],
    'nc' => ['extend' => true, 'tldr' => [['nc -zv intranet.skola.test 80', 'je port otevřený?'], ['nc -zv -w 2 10.0.0.1 53', 'totéž s časovým limitem 2 s']], 'see_also' => ['ss', 'curl', 'ping']],
    'netstat' => ['extend' => true, 'tldr' => [['sudo apt install net-tools', 'doinstaluje netstat'], ['netstat -tuln', 'naslouchající porty (nově ss -tuln)']], 'see_also' => ['ss', 'ip']],
    'nginx' => ['extend' => true, 'tldr' => [['sudo nginx -t', 'zkontroluje konfiguraci'], ['nginx -v', 'verze serveru']], 'see_also' => ['systemctl', 'journalctl', 'curl']],
    'nl' => ['extend' => true, 'tldr' => [['nl poznamky.txt', 'očísluje neprázdné řádky']], 'see_also' => ['cat', 'wc']],
    'nslookup' => ['extend' => true, 'tldr' => [['nslookup example.com', 'přeloží jméno na adresu'], ['nslookup example.com 8.8.8.8', 'zeptá se konkrétního serveru']], 'see_also' => ['dig', 'host']],
    'ping' => ['extend' => true, 'tldr' => [['ping -c 3 10.0.0.1', 'tři pokusy na bránu'], ['ping -c 2 example.com', 'dostupnost serveru na internetu']], 'see_also' => ['traceroute', 'ip', 'dig']],
    'pkill' => ['extend' => true, 'tldr' => [['sudo pkill nginx', 'ukončí procesy podle jména']], 'see_also' => ['kill', 'pgrep', 'ps']],
    'ps' => ['extend' => true, 'tldr' => [['ps aux', 'všechny procesy'], ['ps aux --sort=-%cpu | head -5', 'nejvíc vytěžující procesy'], ['ps -u student', 'procesy jednoho uživatele']], 'see_also' => ['top', 'pgrep', 'kill']],
    'pwd' => ['extend' => true, 'tldr' => [['pwd', 'kde právě jsem']], 'see_also' => ['cd', 'realpath']],
    'reset' => ['extend' => true, 'tldr' => [['reset', 'vrátí úlohu do původního stavu']], 'see_also' => ['mise', 'check']],
    'rev' => ['extend' => true, 'tldr' => [['echo ahoj | rev', 'obrátí text: joha']], 'see_also' => ['tr', 'sort']],
    'rm' => ['extend' => true, 'tldr' => [['rm kopie.txt', 'smaže soubor'], ['rm -r stara_slozka', 'smaže složku i s obsahem'], ['rm -i *.tmp', 'před každým smazáním se zeptá']], 'see_also' => ['rmdir', 'mv', 'find']],
    'rmdir' => ['extend' => true, 'tldr' => [['rmdir prazdna', 'smaže prázdnou složku']], 'see_also' => ['rm', 'mkdir']],
    'sed' => ['extend' => true, 'tldr' => [['sed "s/Linux/GNU\/Linux/" poznamky.txt', 'nahradí text (výpis)'], ['sed -n "2,4p" poznamky.txt', 'vypíše jen řádky 2–4'], ['sed -i "/TODO/d" poznamky.txt', 'smaže řádky s TODO přímo v souboru']], 'see_also' => ['grep', 'awk', 'tr']],
    'sha256sum' => ['extend' => true, 'tldr' => [['sha256sum vitej.txt', 'otisk SHA-256'], ['sha256sum data/* > otisky.txt', 'otisky všech souborů do souboru']], 'see_also' => ['md5sum', 'sha1sum']],
    'sort' => ['extend' => true, 'tldr' => [['sort data/slova.txt', 'abecedně'], ['sort -n data/cisla.txt', 'číselně'], ['sort -t, -k4 -n data/zaci.csv', 'CSV podle 4. sloupce']], 'see_also' => ['uniq', 'shuf', 'comm']],
    'ss' => ['extend' => true, 'tldr' => [['ss -tuln', 'naslouchající porty TCP/UDP'], ['ss -tlnp', 'i s programem, který port drží']], 'see_also' => ['nc', 'netstat', 'systemctl']],
    'stat' => ['extend' => true, 'tldr' => [['stat vitej.txt', 'podrobnosti o souboru'], ["stat -c '%s %n' data/*", 'jen velikost a jméno']], 'see_also' => ['ls', 'file', 'du']],
    'strings' => ['extend' => true, 'tldr' => [['strings obrazky/logo.png', 'čitelné kousky textu v binárním souboru']], 'see_also' => ['xxd', 'file', 'exiftool']],
    'submit' => ['extend' => true, 'tldr' => [['submit EDU-ABCD-1234', 'odevzdá nalezený kód']], 'see_also' => ['mise', 'answer']],
    'sudo' => ['extend' => true, 'tldr' => [['sudo -l', 'co smím jako správce'], ['sudo systemctl restart nginx', 'jeden příkaz s právy správce']], 'see_also' => ['su', 'id', 'groups']],
    'systemctl' => ['extend' => true, 'tldr' => [['systemctl status nginx', 'stav služby'], ['sudo systemctl restart nginx', 'restart služby'], ['systemctl list-units --type=service', 'přehled služeb']], 'see_also' => ['journalctl', 'service', 'ps']],
    'tail' => ['extend' => true, 'tldr' => [['tail -n 5 data/access.log', 'posledních 5 řádků'], ['tail -n +2 data/zaci.csv', 'vše od 2. řádku (bez hlavičky)']], 'see_also' => ['head', 'less', 'journalctl']],
    'tee' => ['extend' => true, 'tldr' => [['ls | tee seznam.txt', 'vypíše a zároveň uloží'], ['echo 127.0.0.1 test | sudo tee -a /etc/hosts', 'připíše do souboru správce']], 'see_also' => ['cat', 'echo']],
    'top' => ['extend' => true, 'tldr' => [['top', 'živý přehled procesů (q = konec)']], 'see_also' => ['ps', 'free', 'uptime']],
    'touch' => ['extend' => true, 'tldr' => [['touch novy.txt', 'vytvoří prázdný soubor'], ['touch vitej.txt', 'aktualizuje čas změny']], 'see_also' => ['mkdir', 'stat', 'nano']],
    'tr' => ['extend' => true, 'tldr' => [["echo ahoj | tr a-z A-Z", 'na velká písmena'], ["tr -d ',' < data/zaci.csv", 'smaže čárky'], ["echo 'a  b' | tr -s ' '", 'sloučí opakované mezery']], 'see_also' => ['sed', 'cut', 'rename']],
    'tracepath' => ['extend' => true, 'tldr' => [['tracepath example.com', 'cesta k serveru bez práv správce']], 'see_also' => ['traceroute', 'ping']],
    'traceroute' => ['extend' => true, 'tldr' => [['traceroute example.com', 'přes které routery vede cesta'], ['traceroute -n 8.8.8.8', 'jen adresy, bez jmen']], 'see_also' => ['tracepath', 'ping', 'ip']],
    'tree' => ['extend' => true, 'tldr' => [['tree projekty', 'strom složky'], ['tree -L 1 /', 'jen první úroveň']], 'see_also' => ['ls', 'find', 'du']],
    'truncate' => ['extend' => true, 'tldr' => [['truncate -s 0 data/access.log', 'vyprázdní soubor'], ['truncate -s 1K test.bin', 'vytvoří soubor dané velikosti']], 'see_also' => ['stat', 'du', 'split']],
    'uname' => ['extend' => true, 'tldr' => [['uname -a', 'vše o jádru a systému'], ['uname -r', 'jen verze jádra']], 'see_also' => ['hostname', 'lscpu', 'uptime']],
    'uniq' => ['extend' => true, 'tldr' => [['sort data/slova.txt | uniq -c', 'kolikrát se každé slovo opakuje'], ['sort data/slova.txt | uniq -d', 'jen opakovaná slova']], 'see_also' => ['sort', 'comm', 'wc']],
    'uptime' => ['extend' => true, 'tldr' => [['uptime', 'jak dlouho počítač běží a zátěž']], 'see_also' => ['top', 'free', 'date']],
    'wc' => ['extend' => true, 'tldr' => [['wc -l poznamky.txt', 'počet řádků'], ['ls | wc -l', 'počet položek ve složce']], 'see_also' => ['grep', 'nl', 'sort']],
    'wget' => ['extend' => true, 'tldr' => [['wget -q -O - http://intranet.skola.test', 'vypíše stránku'], ['wget -O stranka.html http://intranet.skola.test', 'uloží stránku do souboru']], 'see_also' => ['curl', 'ping']],
    'which' => ['extend' => true, 'tldr' => [['which ls', 'kde leží program'], ['which convert identify', 'víc programů najednou']], 'see_also' => ['type', 'whereis', 'man']],
    'whoami' => ['extend' => true, 'tldr' => [['whoami', 'pod kým pracuju']], 'see_also' => ['id', 'groups', 'hostname']],
    'xxd' => ['extend' => true, 'tldr' => [['xxd obrazky/logo.png | head -3', 'první bajty v šestnáctkové soustavě'], ['echo 414243 | xxd -r -p', 'převede hex zpět na text: ABC']], 'see_also' => ['base64', 'strings', 'file']],
    'mount' => ['extend' => true, 'examples' => [['mount -t ext4', 'jen připojené oddíly ext4']], 'tldr' => [['mount', 'vypíše všechny připojené svazky'], ['mount | grep sda', 'jen svazky z disku sda']], 'see_also' => ['lsblk', 'df']],
]]);

// Příkazy z registru, které příručka v57 neměla (m–z).
lab58_register_manual(['commands' => [
    'printenv' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'zaklady', 'level' => 2,
        'summary' => 'Vypíše hodnotu proměnné prostředí (nebo všechny).',
        'synopsis' => 'printenv [PROMĚNNÁ]',
        'about' => 'S názvem proměnné vypíše jen její hodnotu (bez $), bez argumentu celé prostředí jako env. Pokud proměnná neexistuje, skončí kódem 1.',
        'examples' => [['printenv HOME', 'cesta k domovské složce'], ['printenv PATH', 'kde shell hledá programy']],
        'related' => ['env', 'export'], 'see_also' => ['echo', 'unset'],
    ],
    'printf' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'zaklady', 'level' => 2,
        'summary' => 'Vypíše text podle formátu (přesněji než echo).',
        'synopsis' => 'printf FORMÁT [argumenty…]',
        'about' => 'Formát obsahuje značky %s (text), %d (celé číslo), %5.2f (desetinné číslo) a escape sekvence \n a \t. Na rozdíl od echo nepřidává nový řádek na konec sám.',
        'examples' => [["printf '%s má %d bodů\\n' Eva 42", 'dosadí hodnoty do šablony'], ["printf '%05d\\n' 42", 'doplní nuly zleva: 00042']],
        'related' => ['echo', 'seq'], 'see_also' => ['column'],
    ],
    'service' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'sluzby', 'level' => 2,
        'summary' => 'Starší způsob ovládání služeb (volá systemctl).',
        'synopsis' => 'service SLUŽBA status|start|stop|restart',
        'about' => 'Pořadí je obrácené než u systemctl: nejdřív jméno služby, pak akce. Na současných systémech se místo toho používá systemctl.',
        'examples' => [['service nginx status', 'stav služby'], ['sudo service nginx restart', 'restart služby']],
        'related' => ['systemctl', 'journalctl'], 'see_also' => ['sudo'],
    ],
    'sh' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'zaklady', 'level' => 2,
        'summary' => 'Základní shell POSIX – spustí skript nebo příkaz.',
        'synopsis' => 'sh [skript] | sh -c "příkaz"',
        'about' => 'V Debianu je sh odlehčený shell dash; umí méně než bash, zato je rychlý. V laboratoři se chová jako bash.',
        'examples' => [['sh projekty/skripty/pozdrav.sh', 'spustí skript'], ["sh -c 'echo ahoj'", 'jeden příkaz']],
        'related' => ['bash', 'source'], 'see_also' => ['chmod'],
    ],
    'sha1sum' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'data', 'level' => 2,
        'summary' => 'Spočítá otisk SHA-1 souboru.',
        'synopsis' => 'sha1sum soubor…',
        'about' => 'SHA-1 se dnes už nepovažuje za bezpečný (umí se najít kolize), ale na kontrolu, jestli se soubor nezměnil, stačí. Bezpečnější je sha256sum.',
        'examples' => [['sha1sum vitej.txt', 'otisk souboru']],
        'related' => ['sha256sum', 'md5sum'], 'see_also' => ['diff'],
    ],
    'sleep' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'procesy', 'level' => 1,
        'summary' => 'Počká zadaný čas (s, m, h, d).',
        'synopsis' => 'sleep ČAS[s|m|h|d]',
        'about' => 'Hodí se ve skriptech mezi dvěma kroky. V simulaci se nečeká doopravdy – příkaz skončí hned.',
        'examples' => [['sleep 2', 'počká 2 sekundy'], ['sleep 1m', 'počká minutu']],
        'tldr' => [['time sleep 2', 'ukáže, že sleep opravdu „trval“ 2 s']],
        'related' => ['watch', 'time'], 'see_also' => ['date'],
    ],
    'source' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'zaklady', 'level' => 2,
        'summary' => 'Provede příkazy ze souboru v aktuálním shellu (také tečka .).',
        'synopsis' => 'source soubor | . soubor',
        'about' => 'Na rozdíl od bash skript.sh se změny (proměnné, aliasy, cd) projeví v tvém terminálu. Typicky source ~/.bashrc po úpravě konfigurace.',
        'examples' => [['source ~/.bashrc', 'načte znovu konfiguraci shellu']],
        'related' => ['bash', 'alias'], 'see_also' => ['export'],
    ],
    'test' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'zaklady', 'level' => 2,
        'summary' => 'Vyhodnotí podmínku (soubor existuje, čísla se rovnají…) a vrátí 0 nebo 1.',
        'synopsis' => 'test PODMÍNKA | [ PODMÍNKA ]',
        'about' => 'Nic nevypisuje, jen nastaví návratový kód: 0 = pravda, 1 = nepravda. -f soubor (existuje soubor), -d složka, -z text (prázdný), a -eq b (čísla se rovnají). Zápis [ … ] je totéž – mezery kolem závorek jsou povinné.',
        'options' => [['-f SOUBOR', 'existuje běžný soubor'], ['-d SLOŽKA', 'existuje složka'], ['-z TEXT', 'text je prázdný'], ['A -eq B', 'čísla se rovnají (-lt menší, -gt větší)']],
        'examples' => [['test -f vitej.txt && echo existuje', 'podmínka se souborem'], ['[ 3 -gt 2 ] && echo ano', 'porovnání čísel']],
        'related' => ['true', 'false'], 'see_also' => ['expr'],
    ],
    'true' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'zaklady', 'level' => 2,
        'summary' => 'Nedělá nic a skončí úspěchem (návratový kód 0).',
        'synopsis' => 'true',
        'about' => 'Protějšek příkazu false; hodí se při zkoušení && a || nebo jako „prázdný“ příkaz.',
        'examples' => [['true && echo povedlo se', 'po úspěchu se provede příkaz za &&']],
        'related' => ['false', 'test'], 'see_also' => ['echo'],
    ],
    'type' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'zaklady', 'level' => 2,
        'summary' => 'Řekne, co se spustí pod daným jménem: alias, vestavěný příkaz, nebo program.',
        'synopsis' => 'type JMÉNO…',
        'about' => 'Užitečné, když příkaz nedělá to, co čekáš – třeba je to alias. Pro programy vypíše cestu jako which.',
        'examples' => [['type ls', 'program, nebo alias?'], ['type cd ll', 'vestavěný příkaz a alias']],
        'related' => ['which', 'alias'], 'see_also' => ['whereis'],
    ],
    'unalias' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'zaklady', 'level' => 2,
        'summary' => 'Zruší alias.',
        'synopsis' => 'unalias JMÉNO | unalias -a',
        'about' => 'Odstraní zkratku vytvořenou příkazem alias. Volba -a zruší všechny aliasy v aktuálním terminálu.',
        'examples' => [['unalias ll', 'zruší alias ll']],
        'related' => ['alias', 'type'], 'see_also' => ['history'],
    ],
    'unset' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'zaklady', 'level' => 2,
        'summary' => 'Smaže proměnnou prostředí.',
        'synopsis' => 'unset PROMĚNNÁ',
        'about' => 'Po unset proměnná přestane existovat ($JMENO bude prázdné). Nemaže soubory ani aliasy – jen proměnné shellu.',
        'examples' => [['unset JMENO', 'smaže proměnnou JMENO'], ['export JMENO=Eva; unset JMENO; echo "[$JMENO]"', 'vypíše prázdné []']],
        'related' => ['export', 'env'], 'see_also' => ['printenv'],
    ],
    'xargs' => [
        'extend' => true, 'in_lab' => true, 'cat' => 'text', 'level' => 3,
        'summary' => 'Vezme položky ze vstupu a předá je jako argumenty dalšímu příkazu.',
        'synopsis' => 'příkaz | xargs [-n N] PŘÍKAZ',
        'about' => 'Spojí výstup jednoho příkazu s příkazem, který čte argumenty, ne vstup. Klasika: find … | xargs wc -l. Volba -n N předává po N položkách.',
        'options' => [['-n N', 'nejvýš N argumentů na jedno spuštění']],
        'examples' => [['ls data | xargs echo', 'všechna jména na jeden řádek'], ["find data -name '*.txt' | xargs wc -l", 'řádky všech .txt souborů']],
        'tldr' => [['seq 6 | xargs -n 2', 'po dvou na řádek']],
        'related' => ['find', 'echo'], 'see_also' => ['paste'],
    ],
]]);

// Rychlé tahy k položkám výše, které je zatím neměly.
lab58_register_manual([
    'printenv' => ['extend' => true, 'tldr' => [['printenv HOME', 'hodnota jedné proměnné'], ['printenv | sort', 'všechny proměnné podle abecedy']]],
    'printf' => ['extend' => true, 'tldr' => [['printf \'%s\n\' jablko hruska', 'každý argument na vlastní řádek'], ['printf \'Jméno: %s\n\' Ema', 'dosadí text do šablony']]],
    'service' => ['extend' => true, 'tldr' => [['service ssh status', 'stav služby (starší zápis místo systemctl)']]],
    'sh' => ['extend' => true, 'tldr' => [['sh -c "echo ahoj"', 'spustí jeden příkaz v novém shellu']]],
    'sha1sum' => ['extend' => true, 'tldr' => [['sha1sum vitej.txt', 'otisk SHA-1 souboru'], ['sha1sum *.txt > otisky.sha1', 'uloží otisky pro pozdější kontrolu']]],
    'source' => ['extend' => true, 'tldr' => [['echo X=5 > nast.sh && source nast.sh && echo $X', 'načte proměnné ze souboru do aktuálního shellu']]],
    'test' => ['extend' => true, 'tldr' => [['test -f vitej.txt && echo soubor', 'je to soubor?'], ['[ -d data ] && echo složka', 'totéž s hranatými závorkami']]],
    'true' => ['extend' => true, 'tldr' => [['true && echo vždy', 'true vždy uspěje (kód 0)']]],
    'type' => ['extend' => true, 'tldr' => [['type ls', 'alias, vestavěný příkaz, nebo program?'], ['type cd', 'cd je vestavěný příkaz shellu']]],
    'unalias' => ['extend' => true, 'tldr' => [['alias ll="ls -l" && unalias ll', 'zruší alias ll']]],
    'unset' => ['extend' => true, 'tldr' => [['X=5; unset X; echo "[$X]"', 'proměnná je pryč: []']]],
]);
