<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · Linux Lab – příručka (CNT-02), část C: nové příkazy v58 (grafika, drobné nástroje,
 * výpočty). Čistá data; příklady běží v pískovišti (obrázek obrazky/logo.png, data/*).
 */

lab58_register_manual([
    'categories' => [
        'grafika' => ['label' => 'Obrázky a grafika', 'icon' => '🖼', 'lead' => 'Rozměry, převody formátů, náhledy a metadata fotek – bez grafického editoru.'],
        'vypocty' => ['label' => 'Výpočty a čísla', 'icon' => '🧮', 'lead' => 'Kalkulačka, řady čísel, prvočísla a náhodné pořadí.'],
    ],
    'commands' => [
        'identify' => [
            'cat' => 'grafika', 'level' => 1,
            'summary' => 'Zjistí formát, rozměry, barvy a velikost obrázku (ImageMagick).',
            'synopsis' => 'identify [-verbose] [-format "…"] obrázek…',
            'about' => 'Na jednom řádku vypíše jméno, formát (JPEG, PNG…), rozměry v pixelech, barevnou hloubku, barevný prostor a velikost souboru. S -verbose ukáže vše včetně DPI, kvality a metadat EXIF, s -format jen to, co chceš (%w šířka, %h výška, %m formát, %b velikost, %Q kvalita).',
            'options' => [['-verbose', 'podrobný výpis všech vlastností'], ['-format "%w x %h\n"', 'vlastní tvar výpisu'], ['%[EXIF:Model]', 'hodnota značky EXIF ve -format']],
            'examples' => [['identify obrazky/logo.png', 'formát, rozměry a velikost'], ["identify -format '%f: %wx%h\\n' obrazky/*.png", 'jen jméno a rozměry každého obrázku']],
            'tldr' => [['identify -verbose obrazky/logo.png | head -12', 'začátek podrobného výpisu'], ["identify -format '%m %b\\n' obrazky/logo.png", 'formát a velikost souboru']],
            'related' => ['convert', 'file', 'exiftool'], 'see_also' => ['mogrify', 'magick'],
            'tip' => 'Rozměry obrázku najdeš i příkazem file, ale identify umí všechny formáty a -format.',
        ],
        'convert' => [
            'cat' => 'grafika', 'level' => 2,
            'summary' => 'Převede nebo upraví obrázek a uloží ho jako nový soubor (ImageMagick 6).',
            'synopsis' => 'convert vstup [volby] výstup',
            'about' => 'Formát výstupu určí přípona: .jpg, .png, .webp, .gif, .ico… Volby se provádějí v pořadí, v jakém je napíšeš. Originál zůstane beze změny. -resize mění velikost (50%, 800x600 – zachová poměr stran, 800x600! – přesně), -quality nastaví kompresi JPEG/WebP (1–100), -strip odstraní metadata.',
            'options' => [['-resize 50%', 'zmenší na polovinu'], ['-resize 800x', 'šířka 800 px, výška podle poměru stran'], ['-quality 80', 'kvalita JPEG/WebP'], ['-strip', 'smaže metadata (EXIF, GPS, komentáře)'], ['-crop 300x200+10+20', 'výřez šířka×výška od bodu x,y'], ['-rotate 90', 'otočí o 90°'], ['-thumbnail 200x200', 'náhled (zmenší a smaže metadata)']],
            'examples' => [['convert obrazky/logo.png logo.jpg', 'převod PNG na JPEG'], ['convert obrazky/logo.png -resize 50% maly.png', 'zmenšení na polovinu'], ['convert obrazky/logo.png -quality 80 logo.webp', 'moderní formát WebP']],
            'tldr' => [['convert -size 800x600 xc:white pozadi.png', 'nový bílý obrázek'], ['convert obrazky/logo.png -resize 32x32 favicon.ico', 'ikona webu'], ['convert obrazky/logo.png -crop 32x32+0+0 vyrez.png', 'výřez levého horního rohu']],
            'related' => ['mogrify', 'identify', 'magick'], 'see_also' => ['exiftool', 'file'],
            'warn' => 'Pozor na pořadí: convert vstup výstup. Když prohodíš jména, přepíšeš si originál.',
        ],
        'magick' => [
            'cat' => 'grafika', 'level' => 2,
            'summary' => 'Nová podoba ImageMagicku 7: magick vstup [volby] výstup.',
            'synopsis' => 'magick vstup [volby] výstup | magick identify|mogrify …',
            'about' => 'V ImageMagicku 7 se všechny nástroje spouští přes magick (convert je jen starší jméno). Volby jsou stejné: -resize, -quality, -strip… magick identify a magick mogrify odpovídají samostatným příkazům.',
            'examples' => [['magick obrazky/logo.png -resize 50% maly.webp', 'zmenší a uloží jako WebP'], ['magick identify obrazky/logo.png', 'informace o obrázku']],
            'tldr' => [['magick obrazky/logo.png -strip cisty.png', 'kopie bez metadat']],
            'related' => ['convert', 'identify', 'mogrify'], 'see_also' => ['exiftool'],
        ],
        'mogrify' => [
            'cat' => 'grafika', 'level' => 2,
            'summary' => 'Hromadně upraví obrázky – přepíše originály, nebo uloží jinam/jiný formát.',
            'synopsis' => 'mogrify [-path SLOŽKA] [-format PŘÍPONA] [volby] obrázek…',
            'about' => 'Stejné volby jako convert, ale pro mnoho souborů najednou (typicky *.jpg). Bez -path a -format PŘEPÍŠE originály! S -path uloží výsledky do jiné (existující) složky, s -format vytvoří nové soubory s jinou příponou a originály nechá.',
            'options' => [['-path SLOŽKA', 'výsledky ulož do složky (musí existovat)'], ['-format webp', 'převede na jiný formát, originál zůstane'], ['-resize 50%', 'změna velikosti'], ['-quality 80', 'kvalita JPEG/WebP'], ['-strip', 'odstraní metadata']],
            'examples' => [['mogrify -format webp obrazky/*.png', 'vedle každého PNG vytvoří WebP'], ['mkdir -p nahledy && mogrify -path nahledy -resize 50% obrazky/*.png', 'náhledy do jiné složky']],
            'tldr' => [['mogrify -strip obrazky/*.png', 'smaže metadata všem obrázkům']],
            'related' => ['convert', 'identify', 'magick'], 'see_also' => ['find', 'exiftool'],
            'warn' => 'mogrify bez -path/-format mění originály – nejdřív si udělej zálohu (cp -r).',
        ],
        'exiftool' => [
            'cat' => 'grafika', 'level' => 2,
            'summary' => 'Čte a mění metadata souborů: fotoaparát, datum, autor, GPS poloha…',
            'synopsis' => 'exiftool [-ZNAČKA] [-ZNAČKA=hodnota] [-gps:all=] soubor|složka…',
            'about' => 'Fotky z mobilu v sobě nesou EXIF: model telefonu, čas pořízení i přesnou GPS polohu. exiftool je vypíše (exiftool foto.jpg), vybere (-GPSLatitude, -gps:all) nebo smaže (-gps:all= jen polohu, -all= vše). Při zápisu nechá zálohu soubor.jpg_original – i v ní jsou stará data. -overwrite_original zálohu nevytvoří.',
            'options' => [['-gps:all', 'jen značky GPS'], ['-gps:all=', 'smaže polohu GPS'], ['-all=', 'smaže všechna metadata'], ['-Artist="Jméno"', 'zapíše autora'], ['-overwrite_original', 'nevytváří zálohu _original'], ['-s', 'krátká jména značek'], ['-n', 'čísla místo textu (GPS ve stupních)'], ['-r', 'i podsložky']],
            'examples' => [['exiftool obrazky/logo.png', 'všechna metadata'], ['exiftool -ImageWidth -ImageHeight obrazky/logo.png', 'jen vybrané značky']],
            'tldr' => [['exiftool -gps:all= obrazky/logo.png', 'smaže GPS polohu (vytvoří zálohu _original)'], ['exiftool -Artist="Foto kroužek" -overwrite_original obrazky/logo.png', 'zapíše autora bez zálohy']],
            'related' => ['identify', 'convert'], 'see_also' => ['strings', 'rm'],
            'tip' => 'Před zveřejněním fotek zkontroluj GPS: exiftool -gps:all fotky/. Poloha prozradí třeba, kde bydlíš.',
        ],
        'rename' => [
            'cat' => 'soubory', 'level' => 2,
            'summary' => 'Hromadně přejmenuje soubory podle výrazu v Perlu (s/staré/nové/).',
            'synopsis' => "rename [-n] [-v] [-f] 's/VZOR/NÁHRADA/[g]' soubory…",
            'about' => 'Na každé jméno použije výraz: s/VZOR/NÁHRADA/ nahradí první výskyt (s /g všechny), y/a-z/A-Z/ mění písmena. Ve vzoru fungují regulární výrazy, v náhradě $1 vloží, co zachytila závorka. Volba -n jen ukáže, co by se stalo – vždy ji zkus nejdřív.',
            'options' => [['-n', 'nic nepřejmenuje, jen vypíše plán'], ['-v', 'vypíše, co přejmenoval'], ['-f', 'přepíše existující soubory']],
            'examples' => [["rename -n 's/\\.txt\$/.md/' *.txt", 'ukáže plán: .txt na .md'], ["rename -v 's/ /_/g' *", 'mezery ve jménech na podtržítka']],
            'tldr' => [["rename 'y/A-Z/a-z/' *", 'jména malými písmeny'], ["rename -n 's/^(\\w+)\\.txt\$/poznamka-\$1.txt/' *.txt", 'předpona se zachovaným jménem']],
            'related' => ['mv', 'find'], 'see_also' => ['sed', 'ls'],
            'tip' => 'Výraz dej do apostrofů, jinak shell pozmění $ a hvězdičky.',
        ],
        'basename' => [
            'cat' => 'soubory', 'level' => 2,
            'summary' => 'Z cesty nechá jen jméno souboru (případně bez přípony).',
            'synopsis' => 'basename CESTA [PŘÍPONA] | basename -a CESTA…',
            'about' => 'Z /home/student/data/zaci.csv udělá zaci.csv, s příponou .csv jen zaci. Nečte disk – pracuje jen s textem cesty. Hodí se ve skriptech při přejmenování.',
            'options' => [['-a', 'víc cest najednou'], ['-s PŘÍPONA', 'odstraní příponu (i u víc cest)']],
            'examples' => [['basename /home/student/data/zaci.csv', 'zaci.csv'], ['basename data/zaci.csv .csv', 'zaci']],
            'tldr' => [['basename -a data/zaci.csv obrazky/logo.png', 'jména z víc cest']],
            'related' => ['dirname', 'realpath'], 'see_also' => ['rename'],
        ],
        'dirname' => [
            'cat' => 'soubory', 'level' => 2,
            'summary' => 'Z cesty nechá jen složku (vše před posledním lomítkem).',
            'synopsis' => 'dirname CESTA…',
            'about' => 'Z /home/student/data/zaci.csv udělá /home/student/data. Jméno bez lomítka vrátí tečku (aktuální složka). Pracuje jen s textem, disk nečte.',
            'examples' => [['dirname /home/student/data/zaci.csv', '/home/student/data'], ['dirname zaci.csv', '.']],
            'related' => ['basename', 'realpath'], 'see_also' => ['cd'],
        ],
        'realpath' => [
            'cat' => 'soubory', 'level' => 2,
            'summary' => 'Vypíše úplnou (absolutní) cestu k souboru.',
            'synopsis' => 'realpath [-e] [--relative-to=SLOŽKA] cesta…',
            'about' => 'Z relativní cesty (data/../data/zaci.csv) udělá čistou absolutní cestu. Bez voleb musí existovat vše kromě posledního jména, s -e musí existovat celá cesta.',
            'options' => [['-e', 'celá cesta musí existovat'], ['-m', 'nic nemusí existovat'], ['--relative-to=SLOŽKA', 'cesta relativně k jiné složce']],
            'examples' => [['realpath data/zaci.csv', 'absolutní cesta'], ['realpath --relative-to=data obrazky/logo.png', 'relativní cesta: ../obrazky/logo.png']],
            'related' => ['readlink', 'pwd', 'basename'], 'see_also' => ['find'],
        ],
        'readlink' => [
            'cat' => 'soubory', 'level' => 3,
            'summary' => 'Ukáže, kam vede symbolický odkaz; s -f vypíše úplnou cestu.',
            'synopsis' => 'readlink [-f|-e|-m] cesta…',
            'about' => 'Bez voleb vypíše cíl symbolického odkazu (v laboratoři odkazy nejsou, takže skončí kódem 1). S -f funguje jako realpath – vypíše kanonickou absolutní cestu.',
            'options' => [['-f', 'kanonická cesta (vše kromě posledního jména musí existovat)'], ['-e', 'celá cesta musí existovat'], ['-n', 'bez nového řádku na konci']],
            'examples' => [['readlink -f data/./zaci.csv', 'úplná cesta']],
            'related' => ['realpath', 'ls'], 'see_also' => ['ln'],
        ],
        'seq' => [
            'cat' => 'vypocty', 'level' => 1,
            'summary' => 'Vypíše řadu čísel (od, krok, do).',
            'synopsis' => 'seq [-w] [-s ODDĚL] [-f FORMÁT] [OD [KROK]] DO',
            'about' => 'seq 5 vypíše 1 až 5, seq 2 2 10 sudá čísla, seq 0 0.5 2 i desetinná. -w doplní nuly na stejnou šířku, -s nastaví oddělovač, -f formát jako printf (img%03g.jpg). Hodí se do rour a ke generování jmen.',
            'options' => [['-w', 'stejná šířka (doplní nuly)'], ['-s ODDĚL', 'oddělovač místo nového řádku'], ['-f FORMÁT', 'formát čísla, např. %03g']],
            'examples' => [['seq 5', 'čísla 1 až 5'], ['seq -s, 2 2 10', '2,4,6,8,10']],
            'tldr' => [["seq -f 'foto-%02g.jpg' 3", 'jména foto-01.jpg …'], ['seq 10 | paste -sd+ | bc', 'součet 1 až 10']],
            'related' => ['shuf', 'printf'], 'see_also' => ['xargs', 'bc'],
        ],
        'shuf' => [
            'cat' => 'vypocty', 'level' => 2,
            'summary' => 'Náhodně zamíchá řádky nebo vybere náhodné položky.',
            'synopsis' => 'shuf [-n N] [soubor] | shuf -e položky… | shuf -i OD-DO',
            'about' => 'Zamíchá řádky souboru nebo položky za -e; -i 1-10 zamíchá čísla, -n vybere jen N kusů. V laboratoři je náhoda odvozená ze semínka úlohy, takže je výsledek opakovatelný.',
            'options' => [['-n N', 'vypiš jen N položek'], ['-e', 'míchej argumenty'], ['-i OD-DO', 'míchej čísla z rozsahu'], ['-r', 's opakováním (s -n)']],
            'examples' => [['shuf -n 3 data/slova.txt', 'tři náhodná slova'], ['shuf -i 1-6 -n 1', 'hod kostkou']],
            'tldr' => [['shuf -e Adam Bára Cyril', 'náhodné pořadí jmen']],
            'related' => ['sort', 'seq'], 'see_also' => ['head'],
        ],
        'paste' => [
            'cat' => 'text', 'level' => 2,
            'summary' => 'Spojí soubory vedle sebe po řádcích (sloupce).',
            'synopsis' => 'paste [-d ODDĚL] [-s] soubor…',
            'about' => 'Řádek 1 prvního souboru spojí s řádkem 1 druhého atd., oddělovačem je tabulátor (-d změní). S -s spojí všechny řádky jednoho souboru do jednoho řádku. Pomlčka - znamená vstup z roury.',
            'options' => [['-d ODDĚL', 'oddělovač (např. -d,)'], ['-s', 'všechny řádky do jednoho']],
            'examples' => [['paste -d, data/cisla.txt data/slova.txt', 'dva soubory jako CSV'], ['seq 6 | paste - - -', 'po třech do řádku']],
            'tldr' => [['paste -sd+ data/cisla.txt | bc', 'sečte čísla ze souboru']],
            'related' => ['cut', 'join', 'column'], 'see_also' => ['xargs'],
        ],
        'column' => [
            'cat' => 'text', 'level' => 2,
            'summary' => 'Zarovná text do sloupců nebo tabulky.',
            'synopsis' => 'column [-t] [-s ODDĚL] [-o ODDĚL] [soubor]',
            'about' => 'S -t udělá z řádků přehlednou tabulku se zarovnanými sloupci (podle mezer, nebo podle znaků z -s). Bez -t rozloží krátké položky do více sloupců jako ls.',
            'options' => [['-t', 'tabulka'], ['-s ODDĚL', 'vstupní oddělovač, např. -s,'], ['-o ODDĚL', 'výstupní oddělovač (výchozí dvě mezery)']],
            'examples' => [['column -t -s, data/zaci.csv', 'CSV jako čitelná tabulka'], ['ls /etc | column', 'dlouhý seznam do sloupců']],
            'related' => ['paste', 'cut', 'awk'], 'see_also' => ['printf'],
        ],
        'fold' => [
            'cat' => 'text', 'level' => 2,
            'summary' => 'Zalomí dlouhé řádky na zadanou šířku.',
            'synopsis' => 'fold [-w ŠÍŘKA] [-s] [soubor]',
            'about' => 'Rozdělí řádky delší než ŠÍŘKA (výchozí 80). S -s láme za mezerou, takže nerozdělí slova. V laboratoři počítá znaky, takže česká písmena se nerozlomí.',
            'options' => [['-w ŠÍŘKA', 'šířka řádku'], ['-s', 'láme jen za mezerou']],
            'examples' => [['fold -w 30 vitej.txt', 'řádky nejvýš 30 znaků'], ['fold -sw 20 poznamky.txt', 'bez rozdělení slov']],
            'related' => ['cut', 'column'], 'see_also' => ['wc'],
        ],
        'comm' => [
            'cat' => 'text', 'level' => 3,
            'summary' => 'Porovná dva seřazené soubory: co je jen v prvním, jen ve druhém a v obou.',
            'synopsis' => 'comm [-1] [-2] [-3] soubor1 soubor2',
            'about' => 'Vypíše tři sloupce: řádky jen v souboru 1, jen v souboru 2 (odsazené tabulátorem) a společné (dvěma tabulátory). -1, -2, -3 sloupec skryjí – comm -12 a b vypíše jen společné řádky. Oba soubory musí být seřazené (sort).',
            'options' => [['-1', 'skryj řádky jen z prvního'], ['-2', 'skryj řádky jen z druhého'], ['-3', 'skryj společné']],
            'examples' => [['seq 5 > a.txt && seq 3 7 > b.txt && comm a.txt b.txt', 'tři sloupce'], ['seq 5 > a.txt && seq 3 7 > b.txt && comm -12 a.txt b.txt', 'jen společné: 3 4 5']],
            'related' => ['diff', 'sort', 'join'], 'see_also' => ['uniq'],
        ],
        'join' => [
            'cat' => 'text', 'level' => 3,
            'summary' => 'Spojí řádky dvou seřazených souborů podle společného pole (jako tabulky v databázi).',
            'synopsis' => 'join [-t ODDĚL] [-1 POLE] [-2 POLE] [-a 1|2] [-v 1|2] soubor1 soubor2',
            'about' => 'Najde řádky se stejnou hodnotou klíče (výchozí 1. pole) a vypíše klíč, zbytek řádku z prvního a zbytek z druhého souboru. -a 1 přidá i nespárované řádky prvního souboru, -v 1 vypíše jen je. Soubory musí být seřazené podle klíče.',
            'options' => [['-t ODDĚL', 'oddělovač polí'], ['-1 N / -2 N', 'klíč je N-té pole'], ['-a 1', 'i nespárované řádky souboru 1'], ['-v 1', 'jen nespárované řádky souboru 1']],
            'examples' => [["printf '1 Adam\\n2 Bára\\n' > a.txt && printf '1 3.A\\n2 4.A\\n' > b.txt && join a.txt b.txt", 'spojí jméno a třídu podle čísla']],
            'related' => ['paste', 'comm', 'sort'], 'see_also' => ['awk'],
        ],
        'split' => [
            'cat' => 'soubory', 'level' => 2,
            'summary' => 'Rozdělí soubor na menší kusy (podle řádků, velikosti nebo počtu).',
            'synopsis' => 'split [-l ŘÁDKY | -b VELIKOST | -n POČET] [-d] soubor [PŘEDPONA]',
            'about' => 'Vytvoří soubory PŘEDPONAaa, PŘEDPONAab, … (s -d číselné 00, 01). Výchozí je 1000 řádků na kus. Zpátky je spojíš cat PŘEDPONA* > celek.',
            'options' => [['-l N', 'N řádků na kus'], ['-b 1M', 'kusy dané velikosti (K, M, G)'], ['-n 3', 'přesně 3 kusy'], ['-d', 'číselné přípony']],
            'examples' => [['split -l 10 data/access.log kus_', 'po 10 řádcích'], ['split -n 2 -d data/zaci.csv cast', 'na dvě poloviny']],
            'tldr' => [['split -l 10 data/access.log kus_ && cat kus_* > zpet.log', 'rozdělit a znovu spojit']],
            'related' => ['cat', 'head', 'wc'], 'see_also' => ['du'],
        ],
        'yes' => [
            'cat' => 'text', 'level' => 1,
            'summary' => 'Opakovaně vypisuje y (nebo zadaný text), dokud ho nezastavíš.',
            'synopsis' => 'yes [TEXT]',
            'about' => 'Posílá se rourou do příkazů, které se na něco ptají (yes | příkaz odpoví všude y). Samotný by psal donekonečna – v laboratoři skončí po pár tisících řádcích.',
            'examples' => [['yes | head -3', 'tři řádky y'], ['yes ahoj | head -2', 'opakuje zadaný text']],
            'related' => ['head', 'seq'], 'see_also' => ['xargs'],
        ],
        'whereis' => [
            'cat' => 'zaklady', 'level' => 2,
            'summary' => 'Najde program, jeho manuálovou stránku a konfiguraci.',
            'synopsis' => 'whereis [-b|-m] příkaz…',
            'about' => 'Na rozdíl od which prohledá pevně dané systémové složky a ukáže i manuál a složku v /etc (např. whereis nginx).',
            'options' => [['-b', 'jen programy'], ['-m', 'jen manuálové stránky']],
            'examples' => [['whereis ls', 'program a manuál'], ['whereis nginx', 'i konfigurace v /etc']],
            'related' => ['which', 'type'], 'see_also' => ['man', 'find'],
        ],
        'pgrep' => [
            'cat' => 'procesy', 'level' => 2,
            'summary' => 'Najde čísla procesů (PID) podle jména.',
            'synopsis' => 'pgrep [-l] [-a] [-u UŽIVATEL] [-c] VZOR',
            'about' => 'Rychlejší než ps aux | grep: vypíše jen PID procesů, jejichž jméno odpovídá vzoru. -l přidá jméno, -a celý příkaz, -c jen počet. Když nic nenajde, skončí kódem 1.',
            'options' => [['-l', 'i jméno procesu'], ['-a', 'i celý příkazový řádek'], ['-u UŽIVATEL', 'jen procesy uživatele'], ['-c', 'jen počet'], ['-f', 'hledá v celém příkazovém řádku']],
            'examples' => [['pgrep -l nginx', 'PID a jméno procesů nginx'], ['pgrep -c ssh', 'kolik jich je']],
            'tldr' => [['pgrep -a cron', 'i s celým příkazem']],
            'related' => ['ps', 'pkill', 'kill'], 'see_also' => ['top'],
        ],
        'lscpu' => [
            'cat' => 'zaklady', 'level' => 2,
            'summary' => 'Vypíše informace o procesoru: model, počet jader, cache, virtualizaci.',
            'synopsis' => 'lscpu [-e]',
            'about' => 'Přehledně shrne /proc/cpuinfo: architekturu, počet CPU, model, velikosti cache a to, jestli systém běží ve virtuálním stroji (Hypervisor vendor).',
            'options' => [['-e', 'tabulka po jednotlivých CPU']],
            'examples' => [['lscpu', 'přehled procesoru'], ['lscpu | grep "Model name"', 'jen model']],
            'related' => ['free', 'uname'], 'see_also' => ['lsblk', 'cat'],
        ],
        'watch' => [
            'cat' => 'procesy', 'level' => 2,
            'summary' => 'Spouští příkaz opakovaně a ukazuje jeho aktuální výstup.',
            'synopsis' => 'watch [-n SEKUNDY] [-t] příkaz',
            'about' => 'Každé 2 s (nebo -n N) spustí příkaz a překreslí obrazovku – třeba sledování místa na disku nebo běžících procesů. Končí se Ctrl+C. V laboratoři proběhne jen jednou.',
            'options' => [['-n N', 'interval v sekundách'], ['-t', 'bez záhlaví']],
            'examples' => [['watch -n 5 df -h', 'místo na disku každých 5 s'], ["watch 'ps aux | head -5'", 'příkaz s rourou dej do apostrofů']],
            'related' => ['top', 'sleep'], 'see_also' => ['ps', 'df'],
        ],
        'time' => [
            'cat' => 'procesy', 'level' => 2,
            'summary' => 'Změří, jak dlouho příkaz běžel (real, user, sys).',
            'synopsis' => 'time [-p] příkaz',
            'about' => 'Po skončení příkazu vypíše na chybový výstup tři časy: real (skutečně uplynulý), user (výpočet programu) a sys (práce jádra). V laboratoři jsou časy odhadnuté podle objemu práce.',
            'options' => [['-p', 'formát POSIX (sekundy)']],
            'examples' => [['time ls -R', 'jak dlouho trvá výpis'], ['time sleep 2', 'real bude asi 2 s']],
            'related' => ['sleep', 'date'], 'see_also' => ['top'],
        ],
        'expr' => [
            'cat' => 'vypocty', 'level' => 2,
            'summary' => 'Vyhodnotí jednoduchý výraz: celočíselné počty, porovnání, práce s textem.',
            'synopsis' => 'expr ČÍSLO OPERÁTOR ČÍSLO | expr length TEXT | expr TEXT : VZOR',
            'about' => 'Každé číslo a operátor musí být samostatný argument (mezery!). Umí + - * / % (jen celá čísla), porovnání = != < > a textové funkce length, substr, index. Hvězdičku chraň před shellem: expr 3 \\* 4. Na desetinná čísla použij bc.',
            'examples' => [['expr 7 + 5', '12'], ['expr 17 / 5', '3 (celočíselně)'], ['expr length ahoj', '4']],
            'tldr' => [["expr 3 '*' 4", 'násobení s ochranou hvězdičky'], ['expr substr terminal 1 4', 'term']],
            'related' => ['bc', 'test'], 'see_also' => ['factor', 'seq'],
            'tip' => 'V bashi se místo expr častěji píše $((7 + 5)).',
        ],
        'factor' => [
            'cat' => 'vypocty', 'level' => 1,
            'summary' => 'Rozloží číslo na prvočísla.',
            'synopsis' => 'factor ČÍSLO…',
            'about' => 'Vypíše číslo a jeho prvočinitele vzestupně, např. 84: 2 2 3 7. Prvočíslo má jen sebe sama. Zvládne celá čísla do 9 223 372 036 854 775 807.',
            'examples' => [['factor 84', '84: 2 2 3 7'], ['factor 97 360', 'víc čísel najednou']],
            'related' => ['expr', 'bc'], 'see_also' => ['seq'],
        ],
        'bc' => [
            'cat' => 'vypocty', 'level' => 2,
            'summary' => 'Kalkulačka s libovolnou přesností (čte výrazy z roury nebo ze souboru).',
            'synopsis' => "echo 'výraz' | bc [-l]",
            'about' => 'Počítá + - * / % ^ se závorkami, proměnnými a funkcí sqrt(). Počet desetinných míst určuje scale (výchozí 0 = celočíselné dělení); bc -l nastaví scale=20 a přidá s(), c(), a(), l(), e(). obase=2 vypisuje ve dvojkové soustavě, ibase=16 čte šestnáctkovou.',
            'options' => [['-l', 'matematická knihovna, scale=20'], ['scale=N', 'počet desetinných míst'], ['obase=2', 'výstup ve dvojkové soustavě'], ['ibase=16', 'vstup v šestnáctkové soustavě']],
            'examples' => [["echo 'scale=2; 10/3' | bc", '3.33'], ["echo '2^64' | bc", 'velká čísla přesně'], ["echo 'obase=2; 200' | bc", '11001000 (dvojkově)']],
            'tldr' => [["echo 'sqrt(2)' | bc -l", 'odmocnina na 20 míst'], ["echo 'ibase=16; FF' | bc", '255']],
            'related' => ['expr', 'factor'], 'see_also' => ['seq', 'paste'],
            'tip' => 'Pozor na pořadí: po ibase=16 se i obase=10 čte šestnáctkově. Nastav nejdřív obase, pak ibase.',
        ],
    ],
]);

// Rychlé tahy (tldr) k drobným nástrojům – doplněk položek výše.
lab58_register_manual([
    'dirname' => ['extend' => true, 'tldr' => [['dirname ~/data/zaci.csv', 'složka, ve které soubor leží']]],
    'realpath' => ['extend' => true, 'tldr' => [['realpath .', 'plná cesta k aktuální složce'], ['realpath -e chybi.txt', 'chyba, pokud cesta neexistuje']]],
    'readlink' => ['extend' => true, 'tldr' => [['readlink -f ~/data', 'kanonická cesta ke složce']]],
    'column' => ['extend' => true, 'tldr' => [['column -t -s, data/zaci.csv', 'zarovná CSV do tabulky']]],
    'fold' => ['extend' => true, 'tldr' => [['fold -s -w 40 poznamky.txt', 'zalomí po slovech na 40 znaků']]],
    'comm' => ['extend' => true, 'tldr' => [['seq 4 > a.txt && seq 2 6 > b.txt && comm -23 a.txt b.txt', 'řádky jen v prvním souboru']]],
    'join' => ['extend' => true, 'tldr' => [["printf '1 Ema\\n' > a.txt && printf '1 1.A\\n' > b.txt && join a.txt b.txt", 'spojí řádky se stejným klíčem']]],
    'yes' => ['extend' => true, 'tldr' => [['yes n | head -2', 'automatická odpověď „n“']]],
    'whereis' => ['extend' => true, 'tldr' => [['whereis -b bash', 'jen cesta k programu']]],
    'lscpu' => ['extend' => true, 'tldr' => [['lscpu | grep "^CPU(s)"', 'počet procesorů']]],
    'watch' => ['extend' => true, 'tldr' => [['watch -n 2 uptime', 'zátěž stroje každé 2 s']]],
    'time' => ['extend' => true, 'tldr' => [['time sort data/zaci.csv', 'změří, jak dlouho příkaz trval']]],
    'factor' => ['extend' => true, 'tldr' => [['factor 360', 'rozklad na prvočísla: 2 2 2 3 3 5']]],
]);
