<?php

declare(strict_types=1);

return [
    'class_3a' => [
        'name' => '3.A',
        'subject' => 'Seminář OS a sítě',
        'course_type' => 'networks',
        'code' => '75GXC9',
        'accent' => 'network',
        'intro' => 'Procvičení základů sítí podle vstupní diagnostiky. Nejde o známku – cílem je zjistit, co už drží a co je potřeba dovysvětlit.',
        'lesson_note' => 'Doporučené pořadí: test 20–25 min → výsledky a vysvětlení → knowledgebase + krátké scénáře 15–20 min.',
        'diagnostic' => [
            'responses' => 10,
            'average' => '7,1 / 10',
            'focus' => ['HTTPS', 'privátní IP rozsahy', 'SSH/SFTP', 'ping / ICMP', 'DHCP'],
        ],
        'questions' => [
            [
                'id' => 'dns_role',
                'question' => 'Co je hlavní úlohou DNS?',
                'options' => [
                    'a' => 'Přidělovat klientům IP adresy automaticky',
                    'b' => 'Překládat doménová jména na IP adresy a naopak podle typu záznamu',
                    'c' => 'Šifrovat provoz mezi počítači',
                    'd' => 'Blokovat nebezpečné porty',
                ],
                'correct' => 'b',
                'explanation' => 'DNS je adresář internetu a sítí: jméno jako server.example.cz převádí na IP adresu. Automatické přidělení IP řeší DHCP.',
                'kb' => 'dns',
            ],
            [
                'id' => 'dhcp_role',
                'question' => 'Nový notebook se připojí do školní LAN a automaticky dostane IP adresu, masku, bránu a DNS. Která služba to typicky zajistila?',
                'options' => [
                    'a' => 'DHCP',
                    'b' => 'DNS',
                    'c' => 'SSH',
                    'd' => 'HTTPS',
                ],
                'correct' => 'a',
                'explanation' => 'DHCP klientům automaticky předává síťovou konfiguraci. DNS naopak řeší překlad jmen.',
                'kb' => 'dhcp',
            ],
            [
                'id' => 'private_ip',
                'question' => 'Která z adres je privátní IPv4 adresa?',
                'options' => [
                    'a' => '8.8.8.8',
                    'b' => '172.40.10.5',
                    'c' => '192.168.10.25',
                    'd' => '1.1.1.1',
                ],
                'correct' => 'c',
                'explanation' => 'Privátní rozsahy jsou 10.0.0.0/8, 172.16.0.0/12 a 192.168.0.0/16. Adresa 192.168.10.25 do nich patří.',
                'kb' => 'ip-addressing',
            ],
            [
                'id' => 'ssh_port',
                'question' => 'Jaký výchozí TCP port používá SSH?',
                'options' => [
                    'a' => '21',
                    'b' => '22',
                    'c' => '53',
                    'd' => '443',
                ],
                'correct' => 'b',
                'explanation' => 'SSH standardně používá TCP/22. Port lze změnit, ale 22 je výchozí a nejčastější.',
                'kb' => 'ports',
            ],
            [
                'id' => 'sftp',
                'question' => 'Které tvrzení o SFTP je správně?',
                'options' => [
                    'a' => 'Je to totéž jako klasické FTP, jen na portu 443',
                    'b' => 'Přenáší soubory přes SSH a typicky používá port 22',
                    'c' => 'Funguje pouze v prohlížeči',
                    'd' => 'Používá DNS místo TCP',
                ],
                'correct' => 'b',
                'explanation' => 'SFTP znamená SSH File Transfer Protocol. Běží nad SSH, takže typicky využívá stejné připojení a port 22.',
                'kb' => 'ssh-sftp',
            ],
            [
                'id' => 'https',
                'question' => 'Co nejlépe popisuje HTTPS?',
                'options' => [
                    'a' => 'HTTP provoz chráněný TLS, typicky na TCP/443',
                    'b' => 'Protokol pro vzdálený shell na TCP/22',
                    'c' => 'Službu pro přidělování IP adres',
                    'd' => 'Protokol pro testování dostupnosti pomocí ICMP',
                ],
                'correct' => 'a',
                'explanation' => 'HTTPS je HTTP přenášené přes TLS. TLS zajišťuje šifrování, integritu a ověření protistrany pomocí certifikátu.',
                'kb' => 'https',
            ],
            [
                'id' => 'ping',
                'question' => 'Co typicky ověřuje příkaz ping?',
                'options' => [
                    'a' => 'Zda cílový systém odpovídá na ICMP Echo a jaká je přibližná odezva',
                    'b' => 'Zda na serveru běží HTTPS certifikát',
                    'c' => 'Jaké soubory jsou na serveru',
                    'd' => 'Kdo je přihlášený přes SSH',
                ],
                'correct' => 'a',
                'explanation' => 'Ping používá ICMP Echo Request/Reply. Neověřuje automaticky konkrétní aplikační službu ani otevřený TCP port.',
                'kb' => 'icmp',
            ],
            [
                'id' => 'gateway',
                'question' => 'K čemu slouží výchozí brána (default gateway)?',
                'options' => [
                    'a' => 'K překladu domén na IP adresy',
                    'b' => 'K odesílání provozu do jiných sítí, když cíl není v lokálním subnetu',
                    'c' => 'K ukládání souborů uživatele',
                    'd' => 'K přidělení MAC adresy',
                ],
                'correct' => 'b',
                'explanation' => 'Pokud cílová IP neleží v lokální síti, host odešle paket na výchozí bránu, která ho směruje dál.',
                'kb' => 'routing',
            ],
            [
                'id' => 'dns_symptom',
                'question' => 'Počítač otevře web zadáním IP adresy serveru, ale ne pomocí domény. Co je nejpravděpodobnější problém?',
                'options' => [
                    'a' => 'DNS nebo jeho konfigurace',
                    'b' => 'Rozbitý monitor',
                    'c' => 'Nefunkční DHCP vždy bez výjimky',
                    'd' => 'Nesprávný port SSH',
                ],
                'correct' => 'a',
                'explanation' => 'Když spojení na IP funguje, ale jméno ne, je přirozené ověřit DNS: nastavený resolver, překlad jména a dostupnost DNS serveru.',
                'kb' => 'troubleshooting',
            ],
            [
                'id' => 'firewall',
                'question' => 'Server odpovídá na ping, ale web na portu 443 se z klienta neotevře. Co je rozumné ověřit mezi prvními kroky?',
                'options' => [
                    'a' => 'Zda webová služba naslouchá na 443 a zda port neblokuje firewall',
                    'b' => 'Jen barvu síťového kabelu',
                    'c' => 'Změnu názvu počítače',
                    'd' => 'Přeinstalaci operačního systému bez diagnostiky',
                ],
                'correct' => 'a',
                'explanation' => 'Ping potvrzuje jen část konektivity. Pro HTTPS je potřeba ověřit, že služba běží, naslouchá na správném rozhraní/portu a firewall spojení dovolí.',
                'kb' => 'troubleshooting',
            ],
            [
                'id' => 'cidr24',
                'question' => 'Co znamená zápis 192.168.20.15/24?',
                'options' => [
                    'a' => 'Prvních 24 bitů určuje síťovou část adresy',
                    'b' => 'Server používá port 24',
                    'c' => 'Adresa je platná jen 24 minut',
                    'd' => 'Síť obsahuje přesně 24 zařízení',
                ],
                'correct' => 'a',
                'explanation' => 'CIDR prefix /24 říká, že prvních 24 bitů je síťová část. Odpovídá masce 255.255.255.0.',
                'kb' => 'ip-addressing',
            ],
            [
                'id' => 'troubleshoot_order',
                'question' => 'Které pořadí je při řešení „nejde internet“ nejrozumnější?',
                'options' => [
                    'a' => 'Hned přeinstalovat systém → vyměnit router → zkusit ping',
                    'b' => 'Ověřit lokální konfiguraci → bránu → konektivitu na IP → DNS → konkrétní službu',
                    'c' => 'Změnit heslo → vypnout antivirus → konec',
                    'd' => 'Nejdřív měnit DNS záznamy veřejné domény bez měření',
                ],
                'correct' => 'b',
                'explanation' => 'Troubleshooting je nejrychlejší, když postupuje od základů nahoru: lokální konfigurace, cesta sítí, DNS a teprve potom konkrétní aplikace.',
                'kb' => 'troubleshooting',
            ],
            [
                'id' => 'https_dns',
                'question' => 'Uživatel zadá https://portal.example.cz. Co se typicky stane dříve, než začne HTTP komunikace?',
                'options' => [
                    'a' => 'Překlad DNS jména a navázání síťového/TCP spojení; následně TLS handshake',
                    'b' => 'Nejdřív se vždy připojí přes FTP',
                    'c' => 'DHCP přidělí serveru novou IP při každém požadavku',
                    'd' => 'SSH vytvoří certifikát',
                ],
                'correct' => 'a',
                'explanation' => 'Prohlížeč nejprve potřebuje zjistit IP cíle, spojit se s ním a pro HTTPS proběhne TLS handshake. Až potom se přenáší HTTP požadavek.',
                'kb' => 'https',
            ],
            [
                'id' => 'same_subnet',
                'question' => 'Host 192.168.1.20/24 komunikuje s 192.168.1.80/24. Potřebuje pro samotné doručení v této síti výchozí bránu?',
                'options' => [
                    'a' => 'Ano, vždy',
                    'b' => 'Ne, oba hosté jsou ve stejném subnetu a mohou komunikovat přímo přes lokální síť',
                    'c' => 'Jen pokud používají HTTPS',
                    'd' => 'Jen pokud mají Windows',
                ],
                'correct' => 'b',
                'explanation' => 'Ve stejném subnetu host zjistí linkovou adresu cíle a komunikuje lokálně. Brána je potřeba pro cestu do jiné sítě.',
                'kb' => 'routing',
            ],
            [
                'id' => 'port_vs_service',
                'question' => 'Co znamená, když je na serveru „otevřený port 22“?',
                'options' => [
                    'a' => 'Nějaká služba naslouchá na TCP/22 a síťová cesta ji umožňuje; typicky jde o SSH',
                    'b' => 'Server má 22 uživatelů',
                    'c' => 'DNS je automaticky správně',
                    'd' => 'Server je určitě bezpečný',
                ],
                'correct' => 'a',
                'explanation' => 'Port označuje komunikační bod transportní vrstvy. Otevřený port neříká, že je systém bezpečný; jen že je služba dostupná.',
                'kb' => 'ports',
            ],
        ],
        'knowledgebase' => [
            'ip-addressing' => [
                'title' => 'IP adresy, maska a privátní rozsahy',
                'summary' => 'Jak poznat síť, hosta a rozdíl mezi privátní a veřejnou adresou.',
                'body' => [
                    'IPv4 adresa má 32 bitů. Síťová maska nebo CIDR prefix určuje, která část identifikuje síť a která konkrétní zařízení.',
                    'Privátní IPv4 rozsahy jsou 10.0.0.0/8, 172.16.0.0/12 a 192.168.0.0/16. V běžné síti se směrem do internetu často používá NAT.',
                    'Prefix /24 odpovídá masce 255.255.255.0. V typické /24 síti je 256 adres, z nichž síťová a broadcast adresa se běžně nepřidělují hostům.',
                ],
                'example' => '192.168.50.42/24 → síť 192.168.50.0/24, typická brána může být např. 192.168.50.1.',
            ],
            'dns' => [
                'title' => 'DNS bez magie',
                'summary' => 'Doménová jména, resolvery a základní záznamy.',
                'body' => [
                    'DNS převádí jména na data. A záznam mapuje jméno na IPv4 adresu, AAAA na IPv6 a CNAME vytváří alias na jiné jméno.',
                    'Klient se obvykle ptá nakonfigurovaného resolveru. Ten může odpověď znát z cache nebo ji zjistit z autoritativních serverů.',
                    'Když funguje přístup přes IP, ale ne přes jméno, ověř DNS konfiguraci a samotný překlad pomocí nslookup, dig nebo Resolve-DnsName.',
                ],
                'example' => 'nslookup portal.example.cz nebo dig portal.example.cz A',
            ],
            'dhcp' => [
                'title' => 'DHCP a automatická konfigurace',
                'summary' => 'Jak klient získá IP, masku, bránu a DNS.',
                'body' => [
                    'DHCP automatizuje konfiguraci klientů. Typicky předává IP adresu, prefix/masku, výchozí bránu a DNS servery.',
                    'Když klient nedostane očekávanou adresu, kontroluj fyzické připojení, správnou VLAN/síť, dostupnost DHCP serveru a případné vyčerpání poolu.',
                    'Statická adresa a DHCP se mohou kombinovat, ale je potřeba zabránit konfliktům adres.',
                ],
                'example' => 'Windows: ipconfig /all. Linux: ip addr a informace NetworkManager/systemd-networkd.',
            ],
            'ports' => [
                'title' => 'Porty a služby',
                'summary' => 'Proč IP adresa nestačí a co znamená port.',
                'body' => [
                    'IP adresa identifikuje hosta nebo rozhraní, port rozlišuje jednotlivé služby transportní vrstvy.',
                    'Časté TCP porty: SSH 22, HTTP 80, HTTPS 443. DNS používá port 53 přes UDP i TCP podle situace.',
                    'Port může být lokálně otevřený, ale z jiné sítě nedostupný kvůli firewallu, routingu nebo tomu, že služba naslouchá jen na loopbacku.',
                ],
                'example' => 'Linux: ss -tulpn. Windows PowerShell: Get-NetTCPConnection.',
            ],
            'ssh-sftp' => [
                'title' => 'SSH a SFTP',
                'summary' => 'Vzdálený shell, klíče a bezpečný přenos souborů.',
                'body' => [
                    'SSH poskytuje šifrované vzdálené přihlášení a další funkce. Výchozí port je TCP/22.',
                    'SFTP je přenos souborů přes SSH; není to FTP „s přidaným S“. Díky tomu sdílí autentizaci a šifrovaný kanál SSH.',
                    'Bezpečnější autentizace může používat pár veřejného a soukromého klíče. Soukromý klíč se nesdílí.',
                ],
                'example' => 'ssh user@server a sftp user@server',
            ],
            'https' => [
                'title' => 'HTTPS a TLS',
                'summary' => 'Co se děje mezi zadáním URL a načtením stránky.',
                'body' => [
                    'HTTPS je HTTP přenášené přes TLS. Standardně se používá TCP/443.',
                    'TLS chrání důvěrnost a integritu přenosu a pomocí certifikátů pomáhá ověřit identitu serveru.',
                    'Při diagnostice odděluj DNS, TCP spojení, TLS a samotné HTTP – každá vrstva může selhat jiným způsobem.',
                ],
                'example' => 'curl -I https://example.cz ukáže HTTP hlavičky; curl -v přidá diagnostické informace spojení.',
            ],
            'icmp' => [
                'title' => 'Ping, ICMP a traceroute',
                'summary' => 'Co ping dokazuje – a co ne.',
                'body' => [
                    'Ping běžně používá ICMP Echo Request a Echo Reply. Pomáhá ověřit základní dosažitelnost a změřit přibližnou odezvu.',
                    'Neúspěšný ping nemusí znamenat, že je host vypnutý – ICMP může být filtrováno. Úspěšný ping zase nedokazuje, že funguje web nebo SSH.',
                    'Traceroute/tracert pomáhá sledovat cestu přes jednotlivé routery a využívá práci s TTL/Hop Limit.',
                ],
                'example' => 'ping 1.1.1.1 → ověření IP konektivity; ping example.cz navíc vyžaduje překlad jména.',
            ],
            'routing' => [
                'title' => 'Výchozí brána a směrování',
                'summary' => 'Kdy komunikuje host přímo a kdy přes router.',
                'body' => [
                    'Host podle své IP a prefixu pozná, zda je cíl v lokálním subnetu. Lokální cíl řeší přímo na linkové vrstvě.',
                    'Pro cíle mimo lokální síť se obvykle používá výchozí brána. Router pak rozhoduje o další cestě podle routovací tabulky.',
                    'Špatně nastavená brána se často projeví tím, že lokální síť funguje, ale vzdálené sítě ne.',
                ],
                'example' => 'Windows: route print. Linux: ip route.',
            ],
            'troubleshooting' => [
                'title' => 'Systematický troubleshooting sítě',
                'summary' => 'Místo náhodného klikání postupuj po vrstvách.',
                'body' => [
                    '1. Ověř fyzickou/linkovou vrstvu a lokální konfiguraci. 2. Ověř vlastní IP a bránu. 3. Otestuj dosažitelnost brány a známé IP. 4. Ověř DNS. 5. Ověř konkrétní port a službu.',
                    'Měř jeden předpoklad po druhém. Každý výsledek zúží prostor možných příčin.',
                    'Zapisuj si, co už bylo ověřeno. Tím se vyhneš opakování stejných pokusů a rychleji předáš problém dál.',
                ],
                'example' => 'ipconfig/ip addr → ping brána → ping známá IP → nslookup/dig → test konkrétního portu/služby.',
            ],
        ],
    ],

    'class_4a' => [
        'name' => '4.A',
        'subject' => 'Seminář OS a sítě',
        'course_type' => 'networks_advanced',
        'code' => 'S9EG3J',
        'accent' => 'advanced',
        'intro' => 'Pokročilejší diagnostika zaměřená na síťové scénáře, služby, SSH a troubleshooting. Není na známku.',
        'lesson_note' => 'Doporučené pořadí: scénářový test 25–30 min → rozbor výsledků → knowledgebase a 1–2 praktické troubleshooting úlohy.',
        'diagnostic' => [
            'responses' => 2,
            'average' => '9 / 10',
            'focus' => ['DNS A záznam', 'loopback', 'service binding', 'SSH klíče', 'troubleshooting služeb'],
            'warning' => 'Zatím jsou jen 2 vstupní odpovědi, proto je obsah záměrně širší a scénářový.',
        ],
        'questions' => [
            [
                'id' => 'mask24',
                'question' => 'Jaká maska odpovídá prefixu /24?',
                'options' => ['a' => '255.0.0.0', 'b' => '255.255.0.0', 'c' => '255.255.255.0', 'd' => '255.255.255.252'],
                'correct' => 'c',
                'explanation' => '/24 znamená 24 jedničkových bitů masky, tedy 255.255.255.0.',
                'kb' => 'cidr',
            ],
            [
                'id' => 'gateway_scenario',
                'question' => 'Server 10.20.30.15/24 komunikuje s 10.20.40.50/24. Kam typicky odešle paket jako první?',
                'options' => ['a' => 'Přímo cíli bez routeru', 'b' => 'Na výchozí bránu pro síť 10.20.30.0/24', 'c' => 'Na DNS server', 'd' => 'Na loopback'],
                'correct' => 'b',
                'explanation' => 'Cíl leží v jiném /24 subnetu, takže host použije směrování – typicky výchozí bránu.',
                'kb' => 'routing-advanced',
            ],
            [
                'id' => 'dns_a',
                'question' => 'K čemu slouží DNS A záznam?',
                'options' => ['a' => 'Mapuje jméno na IPv4 adresu', 'b' => 'Mapuje jméno pouze na IPv6', 'c' => 'Určuje výchozí bránu', 'd' => 'Ukládá SSH klíč'],
                'correct' => 'a',
                'explanation' => 'A záznam obsahuje IPv4 adresu. Pro IPv6 se používá AAAA.',
                'kb' => 'dns-advanced',
            ],
            [
                'id' => 'loopback',
                'question' => 'Co představuje IPv4 adresa 127.0.0.1?',
                'options' => ['a' => 'Výchozí bránu', 'b' => 'Loopback – tento počítač', 'c' => 'Veřejný DNS server', 'd' => 'Broadcast lokální sítě'],
                'correct' => 'b',
                'explanation' => '127.0.0.1 je loopback. Komunikace zůstává uvnitř lokálního hosta a nejde do fyzické sítě.',
                'kb' => 'binding',
            ],
            [
                'id' => 'bind_localhost',
                'question' => 'Webová aplikace naslouchá pouze na 127.0.0.1:8080. Co to prakticky znamená?',
                'options' => ['a' => 'Je dostupná jen lokálně z daného hosta', 'b' => 'Je automaticky dostupná z celého internetu', 'c' => 'Používá DNS místo TCP', 'd' => 'Port 8080 je zakázaný'],
                'correct' => 'a',
                'explanation' => 'Bind na loopbacku omezuje službu na lokální host. Pro vzdálený přístup musí naslouchat na vhodném síťovém rozhraní a firewall musí provoz povolit.',
                'kb' => 'binding',
            ],
            [
                'id' => 'bind_all',
                'question' => 'Co obvykle znamená, když služba naslouchá na 0.0.0.0:443?',
                'options' => ['a' => 'Naslouchá na všech dostupných IPv4 rozhraních', 'b' => 'Naslouchá jen na loopbacku', 'c' => 'Nemá IP adresu', 'd' => 'Používá UDP bez portu'],
                'correct' => 'a',
                'explanation' => '0.0.0.0 jako bind adresa obvykle znamená všechna lokální IPv4 rozhraní. Dostupnost zvenku ale stále závisí na routingu a firewallu.',
                'kb' => 'binding',
            ],
            [
                'id' => 'tcp_handshake',
                'question' => 'Které pořadí odpovídá klasickému TCP three-way handshake?',
                'options' => ['a' => 'SYN → SYN/ACK → ACK', 'b' => 'ACK → FIN → DNS', 'c' => 'PING → PONG → ACK', 'd' => 'TLS → DHCP → SYN'],
                'correct' => 'a',
                'explanation' => 'TCP spojení se typicky navazuje sekvencí SYN, SYN/ACK a ACK. Teprve potom probíhá aplikační komunikace.',
                'kb' => 'tcp',
            ],
            [
                'id' => 'traceroute',
                'question' => 'Na jakém principu traceroute/tracert typicky zjišťuje jednotlivé hop-y?',
                'options' => ['a' => 'Postupně mění TTL/Hop Limit a sleduje odpovědi routerů', 'b' => 'Čte DNS cache prohlížeče', 'c' => 'Mění MAC adresu serveru', 'd' => 'Používá pouze DHCP'],
                'correct' => 'a',
                'explanation' => 'Traceroute využívá postupně rostoucí TTL/Hop Limit. Router, kde hodnota vyprší, může vrátit ICMP zprávu a tím se odhalí konkrétní hop.',
                'kb' => 'diagnostics',
            ],
            [
                'id' => 'ssh_key',
                'question' => 'Která část SSH klíčového páru se běžně kopíruje na server do authorized_keys?',
                'options' => ['a' => 'Veřejný klíč', 'b' => 'Soukromý klíč', 'c' => 'Oba klíče v jednom souboru', 'd' => 'Heslo uživatele v plaintextu'],
                'correct' => 'a',
                'explanation' => 'Na server se ukládá veřejný klíč. Soukromý klíč musí zůstat pod kontrolou uživatele a nesmí se sdílet.',
                'kb' => 'ssh-keys',
            ],
            [
                'id' => 'chmod600',
                'question' => 'Co znamená chmod 600 private_key?',
                'options' => ['a' => 'Vlastník může číst a zapisovat; ostatní nemají oprávnění', 'b' => 'Všichni mohou soubor spustit', 'c' => 'Soubor je veřejně čitelný', 'd' => 'Soubor se přesune na port 600'],
                'correct' => 'a',
                'explanation' => '6 = read + write pro vlastníka, 0 pro skupinu a 0 pro ostatní. Je to typické omezení pro citlivý soukromý klíč.',
                'kb' => 'permissions',
            ],
            [
                'id' => 'dns_diag',
                'question' => 'Doména se nepřekládá. Který nástroj je vhodný pro přímou kontrolu DNS odpovědi?',
                'options' => ['a' => 'dig / nslookup / Resolve-DnsName', 'b' => 'chmod', 'c' => 'taskkill', 'd' => 'mkdir'],
                'correct' => 'a',
                'explanation' => 'DNS diagnostiku dělej DNS nástrojem. Získáš odpověď, typ záznamu, použitý resolver a často i další užitečné informace.',
                'kb' => 'dns-advanced',
            ],
            [
                'id' => 'listen_diag',
                'question' => 'Služba má běžet na Linuxu na TCP/8443. Jak nejrychleji ověříš, zda proces skutečně naslouchá?',
                'options' => ['a' => 'ss -tulpn (případně obdobný nástroj)', 'b' => 'pwd', 'c' => 'whoami', 'd' => 'clear'],
                'correct' => 'a',
                'explanation' => 'ss ukáže naslouchající sockety, porty a při dostatečných oprávněních i procesy. Tím oddělíš problém služby od problému sítě.',
                'kb' => 'diagnostics',
            ],
            [
                'id' => 'curl_diag',
                'question' => 'Webová služba na localhost:8080 běží. Který příkaz pomůže ověřit HTTP odpověď přímo na serveru?',
                'options' => ['a' => 'curl -I http://127.0.0.1:8080', 'b' => 'chmod 8080 /etc/hosts', 'c' => 'ip addr del 127.0.0.1', 'd' => 'passwd 8080'],
                'correct' => 'a',
                'explanation' => 'curl umožní ověřit aplikační vrstvu lokálně. Pokud lokálně funguje a vzdáleně ne, problém je spíš v bindu, firewallu, routingu nebo NAT.',
                'kb' => 'diagnostics',
            ],
            [
                'id' => 'scenario_service',
                'question' => 'Na serveru curl http://127.0.0.1:8080 funguje, ale z jiného počítače connection refused. ss ukazuje 127.0.0.1:8080. Nejpravděpodobnější příčina?',
                'options' => ['a' => 'Služba je navázaná jen na loopback', 'b' => 'DNS vždy překládá špatně', 'c' => 'Server nemá procesor', 'd' => 'TCP neumí port 8080'],
                'correct' => 'a',
                'explanation' => 'Lokální test funguje a socket je explicitně na 127.0.0.1. Službu je potřeba nakonfigurovat, aby naslouchala na požadovaném síťovém rozhraní.',
                'kb' => 'binding',
            ],
            [
                'id' => 'scenario_dns',
                'question' => 'A záznam app.example.cz ukazuje na starou IPv4 adresu, ale přístup přímo na novou IP funguje. Co opravíš?',
                'options' => ['a' => 'DNS A záznam a následně zohledním TTL/cache', 'b' => 'SSH private key každého klienta', 'c' => 'MAC adresu monitoru', 'd' => 'Loopback tabulku'],
                'correct' => 'a',
                'explanation' => 'Pokud služba na nové IP funguje, ale jméno vrací starou adresu, problém je v DNS datech nebo cache. Po změně může chvíli působit TTL.',
                'kb' => 'dns-advanced',
            ],
        ],
        'knowledgebase' => [
            'cidr' => [
                'title' => 'CIDR a subnetting v praxi',
                'summary' => 'Prefix, síťová adresa, broadcast a použitelné adresy.',
                'body' => [
                    'CIDR prefix udává počet bitů síťové části. /24 odpovídá 255.255.255.0, /26 odpovídá 255.255.255.192.',
                    'Při troubleshooting nejdřív ověř, zda mají komunikující hosté správný prefix. Chybná maska může způsobit, že host považuje vzdálený cíl za lokální nebo naopak.',
                    'V klasickém IPv4 subnetu rozlišuj adresu sítě, adresy hostů a broadcast. Moderní point-to-point scénáře mohou mít specifika.',
                ],
                'example' => '10.0.8.130/26 patří do sítě 10.0.8.128/26.',
            ],
            'routing-advanced' => [
                'title' => 'Routing a rozhodnutí hosta',
                'summary' => 'Jak operační systém vybírá cestu pro paket.',
                'body' => [
                    'Host porovná cíl s routovací tabulkou a vybere nejkonkrétnější odpovídající trasu (longest prefix match).',
                    'Default route 0.0.0.0/0 se použije, když není známá specifičtější cesta.',
                    'Při diagnostice ověř tabulku tras, zdrojovou adresu, bránu a návratovou cestu. Jednosměrná konektivita bývá často routingový problém.',
                ],
                'example' => 'Linux: ip route get 10.20.40.50. Windows: route print / Get-NetRoute.',
            ],
            'dns-advanced' => [
                'title' => 'DNS: A, AAAA, TTL a cache',
                'summary' => 'Diagnostika překladu bez hádání.',
                'body' => [
                    'A záznam mapuje jméno na IPv4, AAAA na IPv6. CNAME ukazuje na jiné jméno, nikoli přímo na IP.',
                    'TTL určuje, jak dlouho může být odpověď cachována. Po změně záznamu mohou různé resolvery dočasně vracet starou hodnotu.',
                    'Při ověřování porovnej odpověď lokálního resolveru s autoritativními servery a sleduj, odkud data pochází.',
                ],
                'example' => 'dig app.example.cz A +trace nebo cílený dotaz na konkrétní DNS server.',
            ],
            'binding' => [
                'title' => 'Loopback a service binding',
                'summary' => 'Proč služba funguje lokálně, ale ne z jiné stanice.',
                'body' => [
                    '127.0.0.1 je IPv4 loopback. Služba navázaná pouze na tuto adresu není dostupná přes fyzická síťová rozhraní.',
                    'Bind na 0.0.0.0 typicky znamená všechna IPv4 rozhraní. Lze ale naslouchat i jen na konkrétní adrese serveru.',
                    'I správný bind nestačí, pokud přístup blokuje host firewall, síťový firewall, ACL nebo chybí routing/NAT.',
                ],
                'example' => 'ss -ltnp | grep :8080 a následně test z localhostu i vzdáleného klienta.',
            ],
            'tcp' => [
                'title' => 'TCP: spojení, stav a chyba',
                'summary' => 'Jak rozlišit timeout, refused a aplikační chybu.',
                'body' => [
                    'TCP navazuje spojení pomocí SYN → SYN/ACK → ACK. Aplikace komunikuje až po vytvoření spojení.',
                    'Connection refused typicky znamená, že cíl aktivně odmítl spojení – často nic neposlouchá na daném portu. Timeout může ukazovat na filtrování nebo nedosažitelnost.',
                    'Úspěšné TCP spojení ještě neznamená, že je v pořádku aplikace nad ním.',
                ],
                'example' => 'curl -v, Test-NetConnection host -Port 443 nebo nc -vz host 443.',
            ],
            'ssh-keys' => [
                'title' => 'SSH klíče a autentizace',
                'summary' => 'Veřejný klíč na server, soukromý klíč zůstává klientovi.',
                'body' => [
                    'Klíčový pár obsahuje veřejnou a soukromou část. Veřejný klíč může být uložen na serveru v authorized_keys.',
                    'Soukromý klíč chraň heslem/passphrase a oprávněními souboru. Nikdy ho neposílej jako běžnou přílohu nebo do repozitáře.',
                    'Při problému s přihlášením ověř uživatele, cestu k authorized_keys, oprávnění a serverovou konfiguraci.',
                ],
                'example' => 'ssh -v user@server vypíše podrobnější průběh autentizace.',
            ],
            'permissions' => [
                'title' => 'Unixová oprávnění v kostce',
                'summary' => 'r=4, w=2, x=1 a tři skupiny oprávnění.',
                'body' => [
                    'Číselný zápis chmod používá součet hodnot read=4, write=2 a execute=1 pro vlastníka, skupinu a ostatní.',
                    '600 znamená rw-------, 644 znamená rw-r--r-- a 755 znamená rwxr-xr-x.',
                    'Citlivé soubory jako soukromé SSH klíče mají mít co nejmenší potřebná oprávnění.',
                ],
                'example' => 'chmod 600 ~/.ssh/id_ed25519',
            ],
            'diagnostics' => [
                'title' => 'Troubleshooting služby po vrstvách',
                'summary' => 'Od procesu přes socket až po firewall a DNS.',
                'body' => [
                    'Nejdřív ověř, že proces běží. Potom zkontroluj, zda naslouchá na očekávané adrese a portu. Následně testuj lokálně a až potom vzdáleně.',
                    'Pokud lokální test funguje a vzdálený ne, zkontroluj bind, host firewall, síťová pravidla, routing a případný NAT.',
                    'DNS řeš až tehdy, když víš, že spojení na správnou IP a port funguje. Jinak mícháš více problémů dohromady.',
                ],
                'example' => 'systemctl status → ss -tulpn → curl localhost → curl IP → firewall/routing → DNS.',
            ],
        ],
    ],

    'class_2a' => [
        'name' => '2.A',
        'subject' => 'Grafika',
        'course_type' => 'graphics',
        'code' => 'RV3F4F',
        'accent' => 'graphics',
        'intro' => 'Základy vizuální komunikace a praktická tvorba plakátu. Test není na známku – slouží jako mapa toho, co už umíš.',
        'lesson_note' => 'Celkem 2×45 minut. Nejprve rychlá diagnostika a mini-průvodce, potom vlastní plakát, kontrola a odevzdání.',
        'diagnostic' => [
            'responses' => 19,
            'average' => null,
            'focus' => ['kompozice', 'hierarchie', 'typografie', 'barvy a kontrast', 'rastrová vs. vektorová grafika', 'export'],
            'warning' => 'Třída pracuje různým tempem; zadání má povinné minimum a rozšiřující část pro rychlejší.',
        ],
        'questions' => [
            [
                'id' => 'hierarchy',
                'question' => 'Co znamená vizuální hierarchie?',
                'options' => ['a' => 'Pořadí, v jakém má divák informace vnímat', 'b' => 'Počet vrstev v Photoshopu', 'c' => 'Seznam použitých fontů', 'd' => 'Velikost souboru'],
                'correct' => 'a',
                'explanation' => 'Hierarchie pomáhá řídit pozornost: co uvidím první, druhé a třetí. Vytváří se velikostí, kontrastem, pozicí, barvou a prostorem.',
                'kb' => 'hierarchy',
            ],
            [
                'id' => 'contrast',
                'question' => 'K čemu v grafice nejvíc slouží kontrast?',
                'options' => ['a' => 'K odlišení prvků a zvýraznění důležitých informací', 'b' => 'K automatickému zmenšení souboru', 'c' => 'K převodu vektoru na text', 'd' => 'K odstranění okrajů stránky'],
                'correct' => 'a',
                'explanation' => 'Kontrast vytváří rozdíl mezi prvky – například světlé/tmavé, velké/malé, výrazné/klidné. Pomáhá čitelnosti a hierarchii.',
                'kb' => 'contrast-color',
            ],
            [
                'id' => 'whitespace',
                'question' => 'Co je „white space“ neboli negativní prostor?',
                'options' => ['a' => 'Prázdný prostor kolem a mezi prvky, který zlepšuje orientaci a čitelnost', 'b' => 'Povinně bílé pozadí', 'c' => 'Vymazaná vrstva', 'd' => 'Chyba při exportu'],
                'correct' => 'a',
                'explanation' => 'Negativní prostor nemusí být bílý. Jde o prostor bez hlavního obsahu, který dává prvkům „vzduch“ a pomáhá organizaci.',
                'kb' => 'composition',
            ],
            [
                'id' => 'alignment',
                'question' => 'Proč je důležité zarovnání prvků?',
                'options' => ['a' => 'Vytváří vizuální řád a vazby mezi prvky', 'b' => 'Zvyšuje rozlišení obrázku', 'c' => 'Mění RGB na CMYK', 'd' => 'Nahrazuje potřebu kontrastu'],
                'correct' => 'a',
                'explanation' => 'Zarovnání dává kompozici strukturu. Náhodně posunuté prvky často působí jako chyba, i když divák neumí přesně říct proč.',
                'kb' => 'composition',
            ],
            [
                'id' => 'typography',
                'question' => 'Která volba nejvíc podporuje čitelnost plakátu?',
                'options' => ['a' => 'Jasná hierarchie nadpisu a textu, rozumný počet fontů a dostatečný kontrast', 'b' => 'Použít co nejvíc fontů', 'c' => 'Všechen text verzálkami v jednom bloku', 'd' => 'Text co nejmenší, aby se vše vešlo'],
                'correct' => 'a',
                'explanation' => 'Typografie musí vytvořit pořadí informací a být čitelná. Obvykle stačí 1–2 rodiny písem a několik řezů/velikostí.',
                'kb' => 'typography',
            ],
            [
                'id' => 'raster_vector',
                'question' => 'Které tvrzení správně popisuje vektorovou grafiku?',
                'options' => ['a' => 'Je tvořena matematicky popsanými tvary a lze ji zvětšovat bez běžné ztráty ostrosti', 'b' => 'Je vždy fotografie', 'c' => 'Je tvořena jen pixely', 'd' => 'Nelze ji použít pro logo'],
                'correct' => 'a',
                'explanation' => 'Vektor je ideální pro loga, ikony a ilustrace, které se musí škálovat. Raster je naopak tvořen pixely a typicky se používá pro fotografie.',
                'kb' => 'raster-vector',
            ],
            [
                'id' => 'logo_format',
                'question' => 'V jakém typu formátu je vhodné uchovávat logo pro další úpravy a libovolné zvětšení?',
                'options' => ['a' => 'SVG nebo jiný vektorový formát', 'b' => 'Nízké JPG 320×200', 'c' => 'Screenshot z chatu', 'd' => 'GIF s 256 barvami jako jediný zdroj'],
                'correct' => 'a',
                'explanation' => 'Logo je vhodné mít jako vektor – například SVG, AI nebo PDF podle workflow. Vektor se dobře škáluje a upravuje.',
                'kb' => 'raster-vector',
            ],
            [
                'id' => 'rgb_cmyk',
                'question' => 'Který barevný model se standardně používá pro obrazovky?',
                'options' => ['a' => 'RGB', 'b' => 'CMYK', 'c' => 'Pantone pouze', 'd' => 'Grayscale vždy'],
                'correct' => 'a',
                'explanation' => 'Displeje pracují se světlem a typicky používají RGB. Tiskový proces často pracuje s CMYK, ale konkrétní výstup je potřeba konzultovat s tiskárnou.',
                'kb' => 'color',
            ],
            [
                'id' => 'color_count',
                'question' => 'Pro začínajícího autora je u plakátu obvykle bezpečnější:',
                'options' => ['a' => 'Pracovat s omezenou paletou a jednou dominantní akcentní barvou', 'b' => 'Použít všechny barvy duhy stejnou intenzitou', 'c' => 'Ignorovat kontrast textu a pozadí', 'd' => 'Měnit barvu každého písmene'],
                'correct' => 'a',
                'explanation' => 'Omezená paleta se snáz drží konzistentní. Akcentní barva může zvýraznit CTA nebo klíčovou informaci.',
                'kb' => 'contrast-color',
            ],
            [
                'id' => 'cta',
                'question' => 'Co je CTA na plakátu nebo sociálním postu?',
                'options' => ['a' => 'Výzva k akci – například „Přihlas se“, „Kup vstupenku“, „Zjisti více“', 'b' => 'Typ souboru', 'c' => 'Barevný profil tiskárny', 'd' => 'Mřížka pro zarovnání'],
                'correct' => 'a',
                'explanation' => 'Call to Action říká divákovi, co má udělat dál. Musí být snadno nalezitelná a významově jasná.',
                'kb' => 'hierarchy',
            ],
            [
                'id' => 'resolution',
                'question' => 'Co se stane, když malý rastrový obrázek výrazně zvětšíš?',
                'options' => ['a' => 'Může se projevit pixelace a ztráta ostrosti', 'b' => 'Automaticky se změní na vektor', 'c' => 'Vždy se zlepší kvalita', 'd' => 'Zmizí barvy'],
                'correct' => 'a',
                'explanation' => 'Raster má konečný počet pixelů. Při velkém zvětšení se informace musí dopočítávat a obraz může působit rozmazaně nebo kostičkovaně.',
                'kb' => 'export',
            ],
            [
                'id' => 'jpg_png',
                'question' => 'Kdy dává PNG často větší smysl než JPG?',
                'options' => ['a' => 'Když potřebuješ průhlednost nebo ostrou jednoduchou grafiku', 'b' => 'Vždy pro každou fotografii bez ohledu na velikost', 'c' => 'Jen pro tisk knih', 'd' => 'PNG neumí barvy'],
                'correct' => 'a',
                'explanation' => 'PNG podporuje průhlednost a bezeztrátovou kompresi, což se hodí pro UI prvky, screenshoty a jednoduchou grafiku. JPG je často efektivnější pro fotografie.',
                'kb' => 'export',
            ],
            [
                'id' => 'grid',
                'question' => 'K čemu slouží mřížka (grid) v layoutu?',
                'options' => ['a' => 'Pomáhá konzistentně zarovnat a rozmístit obsah', 'b' => 'Automaticky vytvoří logo', 'c' => 'Zvýší saturaci barev', 'd' => 'Nahradí text'],
                'correct' => 'a',
                'explanation' => 'Grid vytváří skrytou strukturu. Usnadňuje zarovnání, pravidelné mezery a konzistenci napříč více návrhy.',
                'kb' => 'composition',
            ],
            [
                'id' => 'copyright',
                'question' => 'Najdeš obrázek na internetu. Co je správný postup před použitím ve veřejném projektu?',
                'options' => ['a' => 'Ověřit licenci a podmínky použití, případně použít vlastní nebo řádně licencovaný zdroj', 'b' => 'Cokoliv z Google Obrázků je automaticky volné', 'c' => 'Stačí obrázek oříznout', 'd' => 'Stačí změnit barvu'],
                'correct' => 'a',
                'explanation' => 'Dostupnost obrázku online neznamená, že je bez omezení. Ověř licenci, autora a případnou povinnost uvedení zdroje.',
                'kb' => 'assets',
            ],
            [
                'id' => 'poster_goal',
                'question' => 'Co by měl divák z dobrého plakátu pochopit během několika sekund?',
                'options' => ['a' => 'O čem plakát je a která informace je nejdůležitější', 'b' => 'Kolik vrstev autor použil', 'c' => 'Jaký software autor otevřel', 'd' => 'Všechna data stejnou prioritou'],
                'correct' => 'a',
                'explanation' => 'Plakát musí komunikovat rychle. Hlavní sdělení, datum/místo nebo CTA mají mít jasnou prioritu podle cíle.',
                'kb' => 'hierarchy',
            ],
        ],
        'knowledgebase' => [
            'hierarchy' => [
                'title' => 'Vizuální hierarchie',
                'summary' => 'Jak rozhodnout, co divák uvidí jako první, druhé a třetí.',
                'body' => [
                    'Hierarchie je pořadí důležitosti informací. Tvoří ji velikost, kontrast, pozice, barva, váha písma a množství okolního prostoru.',
                    'U plakátu si před tvorbou napiš tři úrovně: 1) hlavní sdělení, 2) klíčová fakta, 3) doplňující informace. Pokud je všechno stejně výrazné, není výrazné nic.',
                    'CTA – výzva k akci – musí být viditelná, pokud je cílem registrace, nákup nebo návštěva webu.',
                ],
                'example' => 'Nadpis 64 px → datum/místo 28 px → doplňující text 16–18 px. Konkrétní velikosti závisí na formátu.',
            ],
            'composition' => [
                'title' => 'Kompozice, grid a prostor',
                'summary' => 'Jak dostat prvky do řádu bez přeplácání.',
                'body' => [
                    'Začni jednoduchou mřížkou. Zarovnávej prvky na společné osy a drž konzistentní mezery.',
                    'Negativní prostor není promarněné místo. Odděluje skupiny, zlepšuje čitelnost a dovolí důležitému prvku vyniknout.',
                    'Kompozici kontroluj i zmenšenou. Pokud návrh funguje jen při velkém přiblížení, hierarchie může být slabá.',
                ],
                'example' => 'Pro A4 plakát zkus okraje 15–20 mm a 2–4 sloupce jako startovní strukturu.',
            ],
            'contrast-color' => [
                'title' => 'Kontrast a práce s barvou',
                'summary' => 'Barva má pomáhat orientaci, ne soutěžit o pozornost.',
                'body' => [
                    'Kontrast může vzniknout rozdílem jasu, velikosti, barvy, tvaru nebo tloušťky. Použij ho k oddělení priorit.',
                    'Omezená paleta je pro začátek snazší. Jedna neutrální základna + 1–2 akcenty často fungují lépe než mnoho stejně výrazných barev.',
                    'U textu vždy kontroluj čitelnost proti pozadí. Efektní kombinace, kterou nelze přečíst, neplní komunikační cíl.',
                ],
                'example' => 'Tmavé pozadí + světlý text + jedna akcentní barva pro CTA.',
            ],
            'typography' => [
                'title' => 'Typografie pro plakát',
                'summary' => 'Méně fontů, jasnější role, lepší čitelnost.',
                'body' => [
                    'Každý textový styl má mít roli: nadpis, podnadpis, běžný text, poznámka. Tyto role drž konzistentní.',
                    'Na začátku používej 1–2 rodiny písem. Hierarchii vytvářej velikostí, řezem, prokladem a barvou místo náhodného střídání fontů.',
                    'Vyhni se dlouhým blokům verzálek. U delšího textu hlídej délku řádku a řádkování.',
                ],
                'example' => 'Jedna výrazná rodina pro nadpis + neutrální sans-serif pro informace.',
            ],
            'raster-vector' => [
                'title' => 'Raster vs. vektor',
                'summary' => 'Fotografie jsou typicky raster, loga a ikony často vektor.',
                'body' => [
                    'Raster je mřížka pixelů. Má konkrétní rozměry a při velkém zvětšení může ztrácet ostrost.',
                    'Vektor popisuje tvary matematicky. Lze ho škálovat bez běžné pixelace a hodí se pro loga, ikony a ilustrace.',
                    'V praxi se oba typy kombinují: fotografie v rastru, logo ve vektoru a výsledný plakát exportovaný podle cílového média.',
                ],
                'example' => 'SVG = vektor; JPG/PNG = rastrové formáty.',
            ],
            'color' => [
                'title' => 'RGB, CMYK a výstup',
                'summary' => 'Jiný princip pro obrazovku, jiný pro tisk.',
                'body' => [
                    'RGB je aditivní model používaný na obrazovkách. CMYK je subtraktivní model běžný v tisku.',
                    'Barvy na monitoru a na papíře se nemusí shodovat. Pro důležitý tisk se řiď požadavky konkrétní tiskárny a barevným profilem.',
                    'Pro web a sociální sítě obvykle pracuj v RGB a exportuj v rozměrech doporučených cílovou platformou.',
                ],
                'example' => 'Instagram/web → RGB. Produkční tisk → podle specifikace tiskárny, často CMYK workflow.',
            ],
            'export' => [
                'title' => 'Rozlišení a export',
                'summary' => 'Správný formát je součást návrhu.',
                'body' => [
                    'Rastrový obrázek má konkrétní počet pixelů. Při velkém zvětšení může vzniknout pixelace.',
                    'JPG je vhodný hlavně pro fotografie a malé soubory. PNG je vhodný pro průhlednost, screenshoty a ostrou jednoduchou grafiku. SVG je výborný pro vektorovou grafiku na webu.',
                    'Před exportem zkontroluj cílový rozměr, poměr stran, kvalitu, barvy a zda soubor není zbytečně obrovský.',
                ],
                'example' => 'Webový banner exportuj v cílovém pixelovém rozměru; tiskové PDF připrav podle tiskových parametrů.',
            ],
            'assets' => [
                'title' => 'Obrázky, licence a zdroje',
                'summary' => '„Našel jsem to na Google“ není licence.',
                'body' => [
                    'Před použitím cizího obrázku zjisti, zda ho smíš použít, upravit a publikovat. Podmínky se liší podle licence.',
                    'Bezpečná cesta je vlastní tvorba, školou poskytnuté materiály, řádně licencované databáze nebo obsah s jasnými podmínkami použití.',
                    'U některých licencí je nutné uvést autora nebo zachovat stejnou licenci. U komerční práce jsou omezení ještě důležitější.',
                ],
                'example' => 'Do poznámky projektu si napiš zdroj obrázku a licenci – vytvoříš si správný pracovní návyk.',
            ],
        ],
        'guide' => [
            'title' => 'Dvouhodinový projekt: plakát, který komunikuje do 3 sekund',
            'goal' => 'Vytvoř plakát pro skutečnou nebo vymyšlenou akci tak, aby divák do tří sekund pochopil téma a nejdůležitější informaci.',
            'tools' => 'Canva, Figma, Photoshop, Illustrator, Krita/GIMP nebo jiný nástroj, ve kterém dokážeš návrh bezpečně exportovat.',
            'mandatory' => [
                'Formát A4 na výšku nebo digitální 1080 × 1350 px.',
                'Jeden jasný hlavní nadpis.',
                'Datum + místo nebo jiná dvojice klíčových údajů.',
                'Jedna jasná CTA nebo informace „co má divák udělat dál“.',
                'Maximálně 2 rodiny písem a omezená barevná paleta.',
                'Použij zarovnání/grid a vědomě nech negativní prostor.',
                'Použité fotografie/ilustrace musí být vlastní nebo s ověřenou licencí.',
                'Export PNG/JPG pro obrazovku nebo PDF podle zvoleného cíle.',
            ],
            'lesson1' => [
                ['time' => '0–10 min', 'title' => 'Startovní test', 'text' => 'Vyplň test základů grafiky. Nehledej odpovědi v knowledgebase – během testu je studijní část záměrně zamčená.'],
                ['time' => '10–18 min', 'title' => 'Mini-průvodce', 'text' => 'Po testu otevři výsledky a jen ty články knowledgebase, které se týkají tvých chybných odpovědí.'],
                ['time' => '18–25 min', 'title' => 'Brief', 'text' => 'Zvol téma: herní/esport akce, koncert, sportovní událost, školní event, produkt, filmový večer nebo vlastní téma. Napiš si 1 hlavní sdělení, 2 klíčové informace a 1 CTA.'],
                ['time' => '25–40 min', 'title' => 'Wireframe bez efektů', 'text' => 'Nejdřív pouze bloky a text. Vyřeš pořadí informací, zarovnání, grid a mezery. Barvy a obrázky až potom.'],
                ['time' => '40–45 min', 'title' => 'Checkpoint', 'text' => 'Ulož pracovní verzi. Zmenši návrh na 25 % a ověř, zda stále poznáš hlavní sdělení.'],
            ],
            'lesson2' => [
                ['time' => '0–5 min', 'title' => 'Návrat k cíli', 'text' => 'Přečti si znovu svůj brief. Každý prvek, který nepomáhá cíli, může pryč.'],
                ['time' => '5–30 min', 'title' => 'Finální vizuál', 'text' => 'Doplň barvy, obrazový materiál a typografické detaily. Kontroluj kontrast a konzistenci.'],
                ['time' => '30–38 min', 'title' => 'Kontrola v páru nebo samostatně', 'text' => 'Použij checklist níže. Pokud pracuješ ve dvojici, partner má 10 sekund na to, aby řekl, co plakát propaguje a co má udělat.'],
                ['time' => '38–43 min', 'title' => 'Opravy + export', 'text' => 'Oprav největší problém, exportuj finální soubor a zkontroluj ho mimo editor.'],
                ['time' => '43–45 min', 'title' => 'Odevzdání', 'text' => 'Nahraj finální soubor a krátce popiš jedno rozhodnutí, které jsi udělal vědomě kvůli hierarchii, kontrastu nebo kompozici.'],
            ],
            'checklist' => [
                'Do 3 sekund je jasné, o čem plakát je.',
                'Nejdůležitější informace je vizuálně nejsilnější.',
                'Text je čitelný i při zmenšení.',
                'Prvky jsou vědomě zarovnané, ne náhodně posunuté.',
                'Návrh má dostatek negativního prostoru.',
                'Barvy mají dostatečný kontrast a paleta je konzistentní.',
                'Použil/a jsem maximálně 2 rodiny písem.',
                'CTA nebo další krok je snadno dohledatelný.',
                'Obrázky mají dostatečnou kvalitu a znám jejich licenci/zdroj.',
                'Finální export jsem otevřel/a a zkontroloval/a mimo editor.',
            ],
            'extension' => [
                'Vytvoř druhou variantu stejného plakátu pro sociální síť 1080 × 1080 px.',
                'Zachovej stejné sdělení, ale přeuspořádej hierarchii pro nový poměr stran.',
                'Napiš dvě věty: co jsi musel/a změnit a proč.',
            ],
        ],
    ],
];
