<?php

declare(strict_types=1);

return [
    'class_1a' => [
        'id' => 'graphics_type_image',
        'title' => 'Lekce 2 · Typografie + obraz: plakát bez šablony',
        'subtitle' => 'Dalších 2 × 45 minut',
        'goal' => 'Navázat na první plakát a vědomě pracovat s typografií, spacingem, fotografií a CTA. Na konci vznikne druhý Canva plakát, který student umí obhájit.',
        'unlock_note' => 'Odemkne se po dokončení Design Studia z prvního bloku.',
        'knowledge' => ['typography','spacing','image-crop','cta','preflight'],
        'schedule' => [
            ['time'=>'0–10','title'=>'Rekapitulace + typografie','text'=>'Krátké porovnání první práce a Knowledge Tour typografie/spacing.'],
            ['time'=>'10–25','title'=>'Obraz a crop','text'=>'Vyber fotografii, focal point a připrav textovou zónu.'],
            ['time'=>'25–42','title'=>'Typografický skeleton','text'=>'Postav návrh bez dekorací: headline → info → CTA.'],
            ['time'=>'42–45','title'=>'Checkpoint','text'=>'Ověř hierarchii a přejdi do druhé hodiny.'],
            ['time'=>'45–67','title'=>'Canva realizace','text'=>'Doplň fotografii, spacing a styl, ale zachovej informační hierarchii.'],
            ['time'=>'67–80','title'=>'CTA + preflight','text'=>'Otestuj thumbnail, export a přesnost údajů.'],
            ['time'=>'80–90','title'=>'A/B reflexe','text'=>'Porovnej s prvním plakátem a napiš 3 konkrétní zlepšení.'],
        ],
        'steps' => [
            ['id'=>'type_spacing','time'=>'10 min','title'=>'01 · Typografie a spacing','kind'=>'knowledge','xp'=>25,'knowledge'=>['typography','spacing'],'intro'=>'Než otevřeš Canvu, projdi dvě krátké lekce. Zaměř se na role textu a vztah mezer mezi skupinami.','tasks'=>['Dokonči Knowledge Tour „Typografie“.','Dokonči Knowledge Tour „Spacing a vizuální rytmus“.','Napiš si tři role: headline / info / CTA.']],
            ['id'=>'crop','time'=>'15 min','title'=>'02 · Obraz, focal point a crop','kind'=>'quiz','xp'=>20,'knowledge'=>['image-crop'],'intro'=>'Pracuješ s fotografií koncertu. V portrait plakátu chceš text vlevo a hlavní osobu vpravo.','demo'=>['label'=>'Představa layoutu','lines'=>['[ HEADLINE            ]   [ osoba ]','[ datum / místo      ]   [ osoba ]','[ CTA                ]   [ obraz ]']], 'question'=>'Jaký je nejlepší první krok?','options'=>['Zvětšit fotografii tak, aby vyplnila vše bez ohledu na subjekt.','Najít focal point a zvolit crop, který nechá vlevo klidnou textovou zónu.','Přidat další tři efekty.'],'correct'=>1,'explanation'=>'Nejdřív řešíš význam obrazu a prostor pro obsah. Efekty přijdou až potom.','tasks'=>['Otevři Knowledge Tour „Výřez fotografie“.','Vyber jednu vlastní nebo jasně licencovanou fotografii.','Připrav portrait crop a označ textovou zónu.']],
            ['id'=>'skeleton','time'=>'17 min','title'=>'03 · Typografický skeleton','kind'=>'manual','xp'=>20,'knowledge'=>['typography','spacing'],'intro'=>'V Canvě postav návrh pouze z textu a jednoho šedého obdélníku místo fotografie. Žádné efekty.','tasks'=>['Headline musí být první čitelný prvek.','Datum + místo tvoří jednu informační skupinu.','CTA má jasný tvar a konkrétní sloveso.','Použij maximálně dvě rodiny písem.','Použij opakující se spacing místo náhodných mezer.'],'done_label'=>'Skeleton splňuje všech 5 bodů'],
            ['id'=>'hierarchy_check','time'=>'3 min','title'=>'04 · Checkpoint před stylováním','kind'=>'quiz','xp'=>15,'intro'=>'Před přidáním fotografie a stylu zmenši návrh na malou miniaturu.','question'=>'Co musí zůstat čitelné i v thumbnailu?','options'=>['Hlavní zpráva a základní hierarchie.','Všechny drobné dekorace.','Názvy vrstev v editoru.'],'correct'=>0,'explanation'=>'Thumbnail test odhalí, zda design funguje strukturou, ne jen detaily.'],
            ['id'=>'canva_finish','time'=>'22 min','title'=>'05 · Canva: obraz + styl + CTA','kind'=>'manual','xp'=>30,'knowledge'=>['cta'],'intro'=>'Teď skeleton dokonči. Přidej fotografii a vlastní vizuální styl, ale každá změna musí podporovat hlavní sdělení.','tasks'=>['Použij zvolený crop a zachovej focal point.','Zkontroluj kontrast textu proti fotografii.','CTA je viditelné, ale nepřebíjí headline.','Dekorace nepřidávej, pokud nemají funkci.','Proveď grayscale a 3sekundový test.'],'done_label'=>'Finální vizuál prošel 5 kontrolami'],
            ['id'=>'preflight_reflection','time'=>'23 min','title'=>'06 · Preflight + porovnání','kind'=>'quiz','xp'=>30,'knowledge'=>['preflight'],'intro'=>'Exportuj plakát a otevři skutečný soubor mimo Canvu. Potom porovnej s první prací.','demo'=>['label'=>'Preflight','lines'=>['□ správné datum / místo','□ správný rozměr','□ headline čitelný','□ CTA čitelné','□ export otevřen mimo editor']], 'question'=>'Kdy je práce skutečně připravená k odevzdání?','options'=>['Když vypadá dobře v editoru.','Když jsem otevřel/a a zkontroloval/a skutečný export a všechny údaje.','Když má hodně efektů.'],'correct'=>1,'explanation'=>'Preflight kontroluje výsledek, který skutečně dostane divák.','tasks'=>['Ulož export.','Napiš 3 konkrétní rozdíly proti prvnímu plakátu.','Jednu změnu zdůvodni pojmy hierarchie / spacing / crop / CTA.']],
        ],
        'finisher' => ['title'=>'Rychlík · Story adaptace','duration'=>'15–20 min','text'=>'Převeď stejný plakát do 1080 × 1920. Nekopíruj pozice — zachovej role textu, focal point a CTA.','deliverables'=>['story 1080×1920','1 screenshot gridu','2 věty proč se layout změnil']],
    ],
    'class_2a' => [
        'id' => 'graphics_campaign_system',
        'title' => 'Lekce 2 · Z jednoho plakátu udělej malou kampaň',
        'subtitle' => 'Dalších 2 × 45 minut',
        'goal' => 'Převést master plakát do konzistentního systému: master 1080×1350, square 1080×1080 a story 1080×1920. Student se učí adaptaci, photo treatment a obhajobu design systému.',
        'unlock_note' => 'Odemkne se po dokončení Design Studia z prvního bloku.',
        'knowledge' => ['branding-system','photo-treatment','responsive-adaptation','export','portfolio-presentation'],
        'schedule' => [
            ['time'=>'0–12','title'=>'Rozbor systému','text'=>'Definuj konstanty kampaně: typografie, barvy, obraz, grid, CTA.'],
            ['time'=>'12–25','title'=>'Photo treatment','text'=>'Vyřeš focal point, crop a textovou zónu.'],
            ['time'=>'25–45','title'=>'Master refresh','text'=>'Zpevni master plakát jako zdroj pravidel pro adaptace.'],
            ['time'=>'45–60','title'=>'Square adaptace','text'=>'1080×1080 — přeuspořádej, ne jen ořízni.'],
            ['time'=>'60–73','title'=>'Story adaptace','text'=>'1080×1920 — pracuj se safe area a vertikálním rytmem.'],
            ['time'=>'73–83','title'=>'Export matrix','text'=>'Připrav všechny tři výstupy a zkontroluj konzistenci.'],
            ['time'=>'83–90','title'=>'Mini case presentation','text'=>'Stručně obhaj systém a jednu zásadní změnu mezi formáty.'],
        ],
        'steps' => [
            ['id'=>'system','time'=>'12 min','title'=>'01 · Definuj design systém','kind'=>'knowledge','xp'=>25,'knowledge'=>['branding-system'],'intro'=>'Z původního plakátu vytáhni pravidla, která musí přežít všechny formáty.','tasks'=>['Dokonči Knowledge Tour „Mini vizuální systém“.','Zapiš 2 fontové role.','Zapiš 3 barvy max.','Zapiš pravidlo obrazu/cropu.','Zapiš podobu CTA.']],
            ['id'=>'photo','time'=>'13 min','title'=>'02 · Photo treatment','kind'=>'quiz','xp'=>20,'knowledge'=>['photo-treatment'],'intro'=>'Master má výraznou fotografii. Square formát ji ale ořízne jinak.','question'=>'Co máš při adaptaci fotografie zachovat?','options'=>['Přesné souřadnice cropu.','Focal point a funkční prostor pro text.','Stejný počet pixelů vlevo a vpravo.'],'correct'=>1,'explanation'=>'Formát mění crop, ale hlavní subjekt a čitelnost musí zůstat.','tasks'=>['Dokonči Knowledge Tour „Práce s fotografií“.','Připrav crop master + square + story.']],
            ['id'=>'master','time'=>'20 min','title'=>'03 · Master jako zdroj pravidel','kind'=>'manual','xp'=>25,'intro'=>'Oprav původní 1080×1350 návrh tak, aby byl dobrým masterem.','tasks'=>['Jasná hierarchie headline → info → CTA.','Konzistentní grid.','Jedna hlavní akcentní barva.','Definovaný treatment fotografie.','Bez náhodných dekorací, které nepůjdou adaptovat.'],'done_label'=>'Master má 5 jasných pravidel'],
            ['id'=>'adapt','time'=>'28 min','title'=>'04 · Square + Story','kind'=>'knowledge','xp'=>35,'knowledge'=>['responsive-adaptation'],'intro'=>'Vytvoř dvě adaptace. Obsahové priority zůstávají, layout se může zásadně změnit.','tasks'=>['Dokonči Knowledge Tour „Adaptace designu“.','Square 1080×1080: nový crop + vlastní layout.','Story 1080×1920: safe area + vertikální rytmus.','V obou zachovej paletu, typografické role a CTA charakter.']],
            ['id'=>'export_matrix','time'=>'10 min','title'=>'05 · Export matrix','kind'=>'quiz','xp'=>20,'knowledge'=>['export'],'intro'=>'Máš tři formáty stejné kampaně.','question'=>'Jaký je správný exportní postup?','options'=>['Exportovat každý formát samostatně a otevřít jej mimo editor.','Exportovat jen master a ostatní nechat jako screenshot.','Vše uložit do jednoho obřího PNG bez kontroly.'],'correct'=>0,'explanation'=>'Každý formát je samostatný výstup a musí projít vlastním QA.','tasks'=>['Zkontroluj rozměry všech tří souborů.','Pojmenuj soubory konzistentně.','Otevři exporty mimo Canvu.']],
            ['id'=>'presentation','time'=>'7 min','title'=>'06 · Mini obhajoba kampaně','kind'=>'knowledge','xp'=>25,'knowledge'=>['portfolio-presentation'],'intro'=>'Dokonči krátký case slide / poznámku, která vysvětlí systém.','tasks'=>['Dokonči Knowledge Tour „Prezentace procesu“.','Napiš cíl kampaně jednou větou.','Uveď 3 konstanty systému.','Popiš jednu změnu square nebo story a proč byla nutná.']],
        ],
        'finisher' => ['title'=>'Rychlík · Varianta B bez změny obsahu','duration'=>'15–25 min','text'=>'Vytvoř alternativní art direction stejné kampaně, ale zachovej stejné informace a CTA.','deliverables'=>['varianta B master','1 adaptace','krátké A/B zdůvodnění']],
    ],
    'class_3a' => [
        'id' => 'network_small_office',
        'title' => 'Lekce 2 · Navrhni a ověř malou kancelářskou síť',
        'subtitle' => 'Dalších 2 × 45 minut',
        'goal' => 'Navázat na troubleshooting a pochopit, co se děje mezi L2, VLAN, routingem, NATem a konkrétní službou. Na konci student umí vytvořit jednoduchou service matrix a diagnostikovat tok mezi dvěma VLAN.',
        'unlock_note' => 'Odemkne se po dokončení prvního praktického labu.',
        'knowledge' => ['vlan-basics','arp','routing','nat','service-matrix'],
        'schedule' => [
            ['time'=>'0–12','title'=>'Topologie + VLAN','text'=>'Rozděl users a servers do dvou logických sítí.'],
            ['time'=>'12–25','title'=>'ARP a první hop','text'=>'Rozhodni, jakou MAC klient hledá pro lokální a vzdálený cíl.'],
            ['time'=>'25–40','title'=>'Inter-VLAN routing','text'=>'Sleduj paket mezi USERS a SERVERS.'],
            ['time'=>'40–52','title'=>'NAT ven','text'=>'Sleduj privátní klient → veřejná adresa → internet.'],
            ['time'=>'52–72','title'=>'Service matrix + firewall','text'=>'Povol web, zakaž běžným uživatelům SSH, ponech správu admin VLAN.'],
            ['time'=>'72–85','title'=>'Incident','text'=>'Web z USERS nejde, admin SSH funguje — najdi chybu v policy.'],
            ['time'=>'85–90','title'=>'Exit ticket','text'=>'Popiš cestu paketu jednou větou po vrstvách.'],
        ],
        'topology' => [
            'title'=>'OfficeLab',
            'lines'=>[
                'USERS VLAN10 192.168.10.0/24',
                '  PC01 192.168.10.42 → GW 192.168.10.1',
                '                 │ inter-VLAN routing / firewall',
                'SERVERS VLAN20 192.168.20.0/24',
                '  DNS .53   WEB .20:443   SFTP .30:22',
                '                 │ NAT/PAT',
                '              Internet',
            ],
        ],
        'steps' => [
            ['id'=>'vlan','time'=>'12 min','title'=>'01 · Rozděl síť do VLAN','kind'=>'knowledge','xp'=>25,'knowledge'=>['vlan-basics'],'intro'=>'USERS a SERVERS mají být oddělené.','tasks'=>['Dokonči VLAN Knowledge Tour.','USERS: VLAN10 / 192.168.10.0/24.','SERVERS: VLAN20 / 192.168.20.0/24.','Urči gateway .1 v každém subnetu.']],
            ['id'=>'arp','time'=>'13 min','title'=>'02 · ARP a první hop','kind'=>'quiz','xp'=>20,'knowledge'=>['arp'],'intro'=>'PC01 192.168.10.42/24 komunikuje s WEB 192.168.20.20/24.','question'=>'Čí MAC adresu bude PC01 hledat přes ARP jako první?','options'=>['MAC webserveru 192.168.20.20.','MAC své gateway 192.168.10.1.','MAC DNS serveru.'],'correct'=>1,'explanation'=>'Cíl je mimo lokální /24, proto Ethernet rámec směřuje na MAC lokální gateway.'],
            ['id'=>'routing','time'=>'15 min','title'=>'03 · Sleduj inter-VLAN routing','kind'=>'quiz','xp'=>20,'knowledge'=>['routing'],'demo'=>['label'=>'ip route','lines'=>['192.168.10.0/24 dev vlan10','192.168.20.0/24 dev vlan20','default via 203.0.113.1']], 'question'=>'Která route se použije pro 192.168.20.20?','options'=>['192.168.20.0/24 dev vlan20','default route','192.168.10.0/24'],'correct'=>0,'explanation'=>'Přímo připojená /24 route je konkrétnější než default route.','tasks'=>['Nakresli cestu PC01 → GW VLAN10 → router/firewall → VLAN20 → WEB.']],
            ['id'=>'nat','time'=>'12 min','title'=>'04 · Privátní klient ven přes NAT','kind'=>'knowledge','xp'=>25,'knowledge'=>['nat'],'intro'=>'Teď PC01 otevírá veřejný web 1.1.1.1:443.','tasks'=>['Dokonči NAT Knowledge Tour.','Najdi místo, kde se mění zdrojová privátní adresa.','Vysvětli, proč odpověď najde cestu zpět přes překladovou tabulku.']],
            ['id'=>'matrix','time'=>'20 min','title'=>'05 · Service matrix a firewall','kind'=>'knowledge','xp'=>30,'knowledge'=>['service-matrix'],'intro'=>'Navrhni minimální pravidla pro USERS a ADMIN.','demo'=>['label'=>'Požadavky','lines'=>['USERS → WEB :443 = povolit','USERS → DNS :53 = povolit','USERS → SFTP :22 = zakázat','ADMIN → SFTP :22 = povolit']], 'tasks'=>['Dokonči Service Matrix Knowledge Tour.','Sepiš 4 řádky source → destination → service → action.','Zkontroluj, že nemáš any-any allow.']],
            ['id'=>'incident','time'=>'18 min','title'=>'06 · Incident: web nejde, SSH admin funguje','kind'=>'quiz','xp'=>35,'intro'=>'Stav: DNS funguje, PC pingne gateway. Admin VLAN se na SFTP připojí. USERS mají TCP/443 na WEB timeout. Firewall obsahuje: VLAN10 → VLAN20 TCP/22 DENY; VLAN10 → VLAN20 ANY DENY; VLAN99 → VLAN20 TCP/22 ALLOW.','question'=>'Jaká je nejpravděpodobnější oprava?','options'=>['Vypnout firewall.','Přidat před obecný deny přesné VLAN10 → WEB TCP/443 ALLOW a validovat z PC01.','Povolit VLAN10 → VLAN20 ANY.'],'correct'=>1,'explanation'=>'Potřebuješ nejmenší cílené pravidlo pro požadovanou službu. Plošné povolení zbytečně rozšiřuje přístup.','tasks'=>['Po opravě otestuj TCP/443 z USERS.','Ověř, že SSH z USERS zůstává blokované.','Zapiš, co důkazy potvrzují.']],
        ],
        'finisher' => ['title'=>'Rychlík · Guest VLAN','duration'=>'15–20 min','text'=>'Přidej VLAN30 GUEST 192.168.30.0/24. Hosté mají internet + veřejné DNS, ale žádný přístup do SERVERS.','deliverables'=>['subnet + gateway','3 firewall pravidla','2 validační testy']],
    ],
    'class_4a' => [
        'id' => 'production_change_window',
        'title' => 'Lekce 2 · Produkční change window: proxy, TLS, logy a rollback',
        'subtitle' => 'Dalších 2 × 45 minut',
        'goal' => 'Navázat na produkční incident a naučit se řízenou změnu: precheck, reverse proxy upstream, TLS certifikát, korelace logů, validace a rollback.',
        'unlock_note' => 'Odemkne se po dokončení prvního praktického incidentního labu.',
        'knowledge' => ['reverse-proxy','tls-certificates','logs-monitoring','change-management','diagnostics'],
        'schedule' => [
            ['time'=>'0–12','title'=>'Change plan + baseline','text'=>'Definuj success criteria, precheck a rollback dřív než změnu.'],
            ['time'=>'12–27','title'=>'Reverse proxy','text'=>'Ověř Nginx → upstream a čti 502 jako důkaz vrstvy.'],
            ['time'=>'27–42','title'=>'TLS renewal','text'=>'Ověř SNI, SAN, chain a skutečně prezentovaný certifikát.'],
            ['time'=>'42–58','title'=>'Log correlation','text'=>'Propoj monitoring, access/error log a app log podle času.'],
            ['time'=>'58–76','title'=>'Řízený deploy','text'=>'Proveď change a validuj user path + metriky.'],
            ['time'=>'76–86','title'=>'Failure injection','text'=>'Nový upstream port je špatně — rozhodni rollback vs. oprava.'],
            ['time'=>'86–90','title'=>'Post-change note','text'=>'4 věty: změna, důkaz, validace, rollback stav.'],
        ],
        'topology' => [
            'title'=>'Production path',
            'lines'=>[
                'Client → DNS → LB/Nginx :443',
                '                  │ TLS termination',
                '                  └→ app-v2 127.0.0.1:9000',
                '                         │',
                '                       database',
                'Monitoring → /health + /metrics',
            ],
        ],
        'steps' => [
            ['id'=>'change_plan','time'=>'12 min','title'=>'01 · Change plan před změnou','kind'=>'knowledge','xp'=>30,'knowledge'=>['change-management'],'intro'=>'Změna: přesun proxy upstreamu z app-v1:8000 na app-v2:9000 + nový TLS certifikát.','tasks'=>['Dokonči Change Management Knowledge Tour.','Napiš 3 prechecky.','Napiš success criteria.','Napiš jednoznačný rollback krok.']],
            ['id'=>'proxy','time'=>'15 min','title'=>'02 · Reverse proxy a upstream','kind'=>'quiz','xp'=>25,'knowledge'=>['reverse-proxy'],'demo'=>['label'=>'Evidence','lines'=>['curl https://app.example.cz → HTTP/2 502','nginx error.log → connect() failed (111) while connecting to upstream','curl http://127.0.0.1:9000/health → connection refused']], 'question'=>'Kde je teď nejsilnější hypotéza?','options'=>['DNS resolver klienta.','Upstream aplikace / port mezi Nginx a app-v2.','TLS certifikát klienta.'],'correct'=>1,'explanation'=>'Klient dostal HTTP odpověď od Nginx. Proxy ale nedokáže spojit upstream a lokální health test to potvrzuje.'],
            ['id'=>'tls','time'=>'15 min','title'=>'03 · TLS renewal bez falešného pocitu bezpečí','kind'=>'quiz','xp'=>25,'knowledge'=>['tls-certificates'],'demo'=>['label'=>'openssl s_client','lines'=>['subject=CN=app.example.cz','notAfter=Sep 10 12:00:00 2026 GMT','Verify return code: 0 (ok)']], 'question'=>'Datum je 11. září 2026. Jaký je závěr?','options'=>['Certifikát je podle notAfter expirovaný a je potřeba nasadit nový.','Certifikát je určitě platný dalších 30 dní.','Stačí restartovat DNS.'],'correct'=>0,'explanation'=>'notAfter je v minulosti. Po nasazení nového certifikátu je nutné ověřit, co služba skutečně prezentuje.','tasks'=>['Po renew/reload znovu spusť externí TLS test.','Zkontroluj SAN pro app.example.cz.']],
            ['id'=>'logs','time'=>'16 min','title'=>'04 · Korelace monitoringu a logů','kind'=>'knowledge','xp'=>30,'knowledge'=>['logs-monitoring'],'intro'=>'Ve 14:05 po deployi vyskočí 502. Nečti celý log — začni časem a requestem.','tasks'=>['Dokonči Logs & Monitoring Knowledge Tour.','Najdi 14:05 v access logu.','Najdi odpovídající error log.','Porovnej app log ve stejném čase.','Sepiš jednu hypotézu, kterou data vylučují.']],
            ['id'=>'deploy','time'=>'18 min','title'=>'05 · Deploy + validační matice','kind'=>'manual','xp'=>35,'knowledge'=>['diagnostics'],'intro'=>'Upstream už odpovídá. Proveď change jako řízený postup.','tasks'=>['nginx -t / syntax check','reload bez zbytečného restartu','curl externí URL a očekávej 200','ověř TLS certifikát','ověř /health a monitoring','zkontroluj error rate 5–10 minut'],'done_label'=>'Všech 6 validačních bodů je hotových'],
            ['id'=>'failure','time'=>'14 min','title'=>'06 · Failure injection: špatný port po deployi','kind'=>'quiz','xp'=>35,'intro'=>'Po změně se error rate zvedne na 35 %. Nginx config ukazuje proxy_pass http://127.0.0.1:9001, app poslouchá na 9000. Rollback je připravený a trvá 20 sekund.','question'=>'Jaký je nejbezpečnější postup v produkci?','options'=>['Nechat chybu běžet a dlouze zkoumat.','Okamžitě obnovit známý funkční stav rollbackem, stabilizovat službu a teprve potom analyzovat/opravit change.','Vypnout monitoring.'],'correct'=>1,'explanation'=>'Při výrazném dopadu a připraveném rychlém rollbacku je prioritou obnova služby. Analýza může pokračovat po stabilizaci.','tasks'=>['Po rollbacku ověř user path.','Ověř návrat error rate k baseline.','Zapiš chybný parametr do post-change note.']],
        ],
        'finisher' => ['title'=>'Rychlík · Canary 10 %','duration'=>'15–25 min','text'=>'Navrhni, jak bys stejnou změnu nasadil nejdřív pro 10 % provozu a podle jakých metrik bys rozhodl pokračovat/rollback.','deliverables'=>['3 success metrics','2 stop conditions','krátký validační plán']],
    ],
];
