<?php

declare(strict_types=1);

return [
    'class_3a' => [
        'title' => 'Síťová diagnostika krok za krokem',
        'duration' => 90,
        'intro' => 'Dvě vyučovací hodiny postavené jako cesta od rychlé diagnostiky znalostí k praktickému řešení síťových problémů. Nejde o známku; důležité je umět zdůvodnit další diagnostický krok.',
        'schedule' => [
            ['time' => '0–5 min', 'title' => 'Briefing + case study', 'text' => 'Prohlédni roli, časovou osu a síťový diagram „Dne juniorního administrátora“. Pak měř jeden předpoklad po druhém a u každého kroku si řekni, co výsledek dokazuje.'],
            ['time' => '5–25 min', 'title' => 'Startovní test', 'text' => '15 otázek z IP, DHCP, DNS, ICMP, portů, HTTPS a SSH/SFTP. Po každé odpovědi dostaneš krátké vysvětlení.'],
            ['time' => '25–35 min', 'title' => 'Rozbor + knowledgebase', 'text' => 'Otevři témata doporučená podle chyb a projdi jen části, které se týkají tvého výsledku.'],
            ['time' => '35–50 min', 'title' => 'Lab 1 · DHCP → DNS', 'text' => 'Diagnostika klienta, který nejdřív nedostal správnou konfiguraci a po opravě stále neotevře web podle jména.'],
            ['time' => '50–65 min', 'title' => 'Lab 2 · Webová služba', 'text' => 'Rozlišení konektivity hosta, otevřeného portu a skutečně běžící služby.'],
            ['time' => '65–80 min', 'title' => 'Lab 3 · SSH / SFTP', 'text' => 'Volba správného protokolu, portu a testu dostupnosti služby.'],
            ['time' => '80–90 min', 'title' => 'Exit ticket', 'text' => 'Čtyři krátké situace, ve kterých zvolíš správný další krok a vysvětlíš proč.'],
        ],
        'rules' => [
            'Knowledgebase je během startovního testu zamčená, ale v praktické části ji můžeš používat jako dokumentaci.',
            'Každý krok lze zkusit opakovaně. Špatný pokus není penalizovaný.',
            'K dispozici jsou tři úrovně nápovědy. Použij je až ve chvíli, kdy nevíš, co měřit nebo co výsledek znamená.',
            'Kontrola řešení probíhá okamžitě. Po správném kroku dostaneš vysvětlení, co přesně daný výsledek dokazuje.',
        ],
        'case_study' => [
            'title' => 'Den juniorního administrátora',
            'eyebrow' => 'Realistická case study · školní IT podpora',
            'summary' => 'Jedna směna, několik navazujících tiketů a stejná síť. Každý incident simuluje běžný typ problému: DHCP, DNS, dostupnost webové služby a SSH/SFTP. Infrastruktura je fiktivní, ale příkazy, výpisy a diagnostická logika odpovídají reálné administrátorské praxi.',
            'role' => 'Junior IT administrátor / helpdesk L1',
            'mission' => 'Obnovit služby bez náhodných restartů. U každého zásahu nejdřív formuluj hypotézu, potom ji změř a teprve poté navrhni změnu.',
            'sla' => 'Cíl směny: u P3 tiketu do 15 minut určit vrstvu problému a předat reprodukovatelný důkaz.',
            'rules' => [
                'Neřeš symptom náhodnou změnou konfigurace. Každý příkaz musí mít důvod.',
                'Ping je pouze jeden důkaz. Nezaměňuj dostupnost hosta za dostupnost služby.',
                'Před opravou si pojmenuj, co už můžeš vyloučit.',
                'Po opravě proveď validační test stejnou cestou, kterou používá uživatel.',
            ],
            'timeline' => [
                ['time' => '08:05', 'ticket' => 'INC-301', 'priority' => 'P3', 'title' => 'Notebook má kabel, ale „nemá internet“', 'text' => 'Nový klient v učebně nedostal použitelnou konfiguraci. Nejprve zjisti, co mu chybí a zda je problém v DHCP.', 'task_id' => 'dhcp_dns'],
                ['time' => '09:20', 'ticket' => 'INC-302', 'priority' => 'P3', 'title' => 'Server odpovídá, interní web ne', 'text' => 'Uživatel server pingne, ale HTTPS se neotevře. Odděl ICMP, TCP port a stav webové služby.', 'task_id' => 'web_service'],
                ['time' => '10:35', 'ticket' => 'INC-303', 'priority' => 'P3', 'title' => 'SFTP timeout po změně pravidel', 'text' => 'SSH server běží, ale klient se na TCP/22 nedostane. Rozliš službu, síť a firewall.', 'task_id' => 'ssh_sftp'],
                ['time' => '11:20', 'ticket' => 'SHIFT', 'priority' => 'CHECK', 'title' => 'Předání směny', 'text' => 'Zapiš, co jednotlivé testy dokazují a jaký by byl další krok bez hádání.', 'task_id' => 'exit'],
            ],
            'task_meta' => [
                'dhcp_dns' => ['time' => '08:05', 'ticket' => 'INC-301', 'priority' => 'P3', 'focus' => ['laptop','switch','gateway','dns','internet']],
                'web_service' => ['time' => '09:20', 'ticket' => 'INC-302', 'priority' => 'P3', 'focus' => ['laptop','switch','web']],
                'ssh_sftp' => ['time' => '10:35', 'ticket' => 'INC-303', 'priority' => 'P3', 'focus' => ['laptop','switch','sftp']],
                'exit' => ['time' => '11:20', 'ticket' => 'SHIFT', 'priority' => 'CHECK', 'focus' => ['laptop','gateway','dns','web','sftp']],
            ],
            'diagram' => [
                'title' => 'Topologie učebny a interních služeb',
                'caption' => 'Stejná topologie platí pro všechny tikety. Zvýrazněné uzly v praktické části ukazují, kterých částí se incident týká.',
                'width' => 920,
                'height' => 390,
                'nodes' => [
                    ['id' => 'laptop', 'x' => 30, 'y' => 145, 'w' => 150, 'h' => 62, 'label' => 'Notebook', 'sub' => '192.168.50.88'],
                    ['id' => 'switch', 'x' => 225, 'y' => 145, 'w' => 150, 'h' => 62, 'label' => 'Switch / VLAN', 'sub' => 'učebna · /24'],
                    ['id' => 'gateway', 'x' => 420, 'y' => 45, 'w' => 150, 'h' => 62, 'label' => 'Gateway', 'sub' => '192.168.50.1'],
                    ['id' => 'dns', 'x' => 420, 'y' => 145, 'w' => 150, 'h' => 62, 'label' => 'DNS', 'sub' => '192.168.50.53'],
                    ['id' => 'web', 'x' => 650, 'y' => 70, 'w' => 170, 'h' => 62, 'label' => 'Interní web', 'sub' => '192.168.50.20 · 443'],
                    ['id' => 'sftp', 'x' => 650, 'y' => 220, 'w' => 170, 'h' => 62, 'label' => 'SFTP / SSH', 'sub' => '192.168.50.30 · 22'],
                    ['id' => 'internet', 'x' => 420, 'y' => 290, 'w' => 150, 'h' => 62, 'label' => 'Internet', 'sub' => 'např. 1.1.1.1'],
                ],
                'links' => [
                    ['from' => 'laptop', 'to' => 'switch', 'label' => 'Ethernet'],
                    ['from' => 'switch', 'to' => 'gateway', 'label' => 'routing'],
                    ['from' => 'switch', 'to' => 'dns', 'label' => 'UDP/TCP 53'],
                    ['from' => 'switch', 'to' => 'web', 'label' => 'TCP 443'],
                    ['from' => 'switch', 'to' => 'sftp', 'label' => 'TCP 22'],
                    ['from' => 'gateway', 'to' => 'internet', 'label' => 'default route'],
                ],
            ],
            'terminal' => [
                ['task_id' => 'dhcp_dns', 'label' => 'Krok 1 · Zjisti konfiguraci klienta', 'prompt' => 'C:\\>', 'command' => 'ipconfig', 'purpose' => 'Ověřím, zda klient získal IP, masku, bránu a DNS.', 'output' => "IPv4 Address . . . . . : 169.254.44.18\nSubnet Mask  . . . . . : 255.255.0.0\nDefault Gateway . . . :\nDNS Servers . . . . . :", 'meaning' => 'Klient je na link-local/APIPA adrese a nemá bránu ani DNS. Primární hypotéza: DHCP konfigurace nebyla získána.'],
                ['task_id' => 'dhcp_dns', 'label' => 'Krok 2 · Odděl IP konektivitu od DNS', 'prompt' => 'C:\\>', 'command' => 'ping 1.1.1.1', 'purpose' => 'Po získání DHCP parametrů ověřím routing bez použití doménového jména.', 'output' => "Reply from 1.1.1.1: time=12ms\nReply from 1.1.1.1: time=11ms\nPackets: Sent = 4, Received = 4, Lost = 0", 'meaning' => 'IP konektivita přes gateway funguje. Pokud jméno stále nefunguje, další test má mířit na DNS.'],
                ['task_id' => 'dhcp_dns', 'label' => 'Krok 3 · Ověř DNS resolver', 'prompt' => 'C:\\>', 'command' => 'nslookup portal.example.cz', 'purpose' => 'Ověřím konkrétně překlad jména přes nakonfigurovaný resolver.', 'output' => "DNS request timed out.\nServer: 192.168.50.53\nAddress: 192.168.50.53", 'meaning' => 'Síť už funguje, ale DNS dotaz na 192.168.50.53 timeoutuje. Incident se posunul z DHCP/routingu na DNS službu nebo cestu k ní.'],
                ['task_id' => 'web_service', 'label' => 'Krok 1 · Ověř port HTTPS', 'prompt' => 'PS C:\\>', 'command' => 'Test-NetConnection 192.168.50.20 -Port 443', 'purpose' => 'Ping už funguje; teď ověřím konkrétní TCP službu.', 'output' => "ComputerName     : 192.168.50.20\nRemotePort       : 443\nPingSucceeded    : True\nTcpTestSucceeded : False", 'meaning' => 'Host odpovídá, ale TCP/443 ne. To je přesnější důkaz než samotný ping.'],
                ['task_id' => 'web_service', 'label' => 'Krok 2 · Zkontroluj socket na serveru', 'prompt' => '$', 'command' => 'ss -ltnp | grep -E ":80|:443"', 'purpose' => 'Ověřím, zda služba opravdu naslouchá na očekávaném portu.', 'output' => "LISTEN 0 511 0.0.0.0:80 0.0.0.0:* users:((\"nginx\",pid=812,fd=6))", 'meaning' => 'Nginx naslouchá na 80, nikoli na 443. Další krok je kontrola HTTPS konfigurace/certifikátu, ne změna DNS.'],
                ['task_id' => 'ssh_sftp', 'label' => 'Krok 1 · Testuj SFTP', 'prompt' => 'C:\\>', 'command' => 'sftp student@192.168.50.30', 'purpose' => 'Použiji šifrovaný přenos souborů nad SSH.', 'output' => "ssh: connect to host 192.168.50.30 port 22: Connection timed out", 'meaning' => 'Chyba je před autentizací. Je potřeba ověřit TCP/22, naslouchající sshd a firewall.'],
                ['task_id' => 'ssh_sftp', 'label' => 'Krok 2 · Ověř server a firewall', 'prompt' => '$', 'command' => 'ss -ltn | grep :22', 'purpose' => 'Zjistím, zda SSH server vůbec naslouchá.', 'output' => "LISTEN 0 128 0.0.0.0:22 0.0.0.0:*\n# firewall: incoming tcp/22 = DENY", 'meaning' => 'Služba naslouchá. Explicitní blokace je ve firewallu; oprava má být cílené allow pravidlo, ne vypnutí firewallu.'],
            ],
        ],
        'tasks' => [
            [
                'id' => 'dhcp_dns',
                'title' => 'Lab 1 · Notebook se „připojil“, ale nic nefunguje',
                'time' => '15 min',
                'goal' => 'Oddělit problém automatické konfigurace od problému DNS a vybrat správný další diagnostický krok.',
                'scenario' => 'Uživatel se připojí kabelem do školní sítě. Ikona sítě svítí, ale web se neotevře. Dostaneš výpis z klienta a postupně další výsledky měření.',
                'evidence' => [
                    'C:\\> ipconfig',
                    'IPv4 Address . . . . . : 169.254.44.18',
                    'Subnet Mask  . . . . . : 255.255.0.0',
                    'Default Gateway . . . :',
                    'DNS Servers . . . . . :',
                ],
                'steps' => [
                    [
                        'question' => 'Co z prvního výpisu vyplývá jako nejpravděpodobnější problém?',
                        'options' => [
                            'a' => 'Klient pravděpodobně nezískal konfiguraci z DHCP a použil link-local adresu 169.254.x.x.',
                            'b' => 'DNS funguje správně, protože adresa začíná 169.',
                            'c' => 'HTTPS server určitě používá špatný certifikát.',
                            'd' => 'Počítač je ve stejné síti jako všechny servery a stačí restartovat prohlížeč.',
                        ],
                        'correct' => 'a',
                        'explanation' => 'Adresa 169.254.0.0/16 je typická link-local/APIPA konfigurace. Prázdná brána a DNS navíc potvrzují, že klient nedostal běžné DHCP parametry.',
                        'hints' => [
                            'Podívej se nejen na IP, ale také na bránu a DNS.',
                            'Rozsah 169.254.0.0/16 není běžný privátní LAN rozsah přidělený školním DHCP.',
                            'Windows tuto adresu použije, když nedostane použitelnou odpověď DHCP.',
                        ],
                        'kb' => 'dhcp',
                    ],
                    [
                        'evidence' => [
                            'Po kontrole kabelu a správné zásuvky/VLAN:',
                            'C:\\> ipconfig /renew',
                            'IPv4 Address . . . . . : 192.168.50.88',
                            'Subnet Mask  . . . . . : 255.255.255.0',
                            'Default Gateway . . . : 192.168.50.1',
                            'DNS Servers . . . . . : 192.168.50.53',
                        ],
                        'question' => 'Který test teď nejlépe ověří, zda klient zvládne komunikaci mimo lokální síť bez závislosti na DNS?',
                        'options' => [
                            'a' => 'ping 1.1.1.1',
                            'b' => 'nslookup portal.example.cz',
                            'c' => 'sftp portal.example.cz',
                            'd' => 'Změnit název počítače.',
                        ],
                        'correct' => 'a',
                        'explanation' => 'Ping na známou IP oddělí základní IP konektivitu a routing od překladu jmen. Teprve potom má smysl řešit DNS.',
                        'hints' => [
                            'Potřebuješ test, který nepoužívá doménové jméno.',
                            'Chceš ověřit IP konektivitu přes výchozí bránu.',
                            'Použij známou IP adresu jako 1.1.1.1.',
                        ],
                        'kb' => 'routing',
                    ],
                    [
                        'evidence' => [
                            'C:\\> ping 1.1.1.1        → odpovědi chodí',
                            'C:\\> ping 192.168.50.1  → odpovědi chodí',
                            'C:\\> nslookup portal.example.cz',
                            'DNS request timed out.',
                            'Server: 192.168.50.53',
                        ],
                        'question' => 'Na co se máš zaměřit jako na další problém?',
                        'options' => [
                            'a' => 'DNS server / dosažitelnost nebo konfiguraci resolveru.',
                            'b' => 'Výměnu grafické karty.',
                            'c' => 'Port 22 na SSH serveru.',
                            'd' => 'Masku /8 na klientovi.',
                        ],
                        'correct' => 'a',
                        'explanation' => 'Brána i internetová IP fungují, takže základní routing drží. Selhává konkrétně DNS dotaz na nakonfigurovaný resolver 192.168.50.53.',
                        'hints' => [
                            'Co funguje: lokální brána a vzdálená IP. Co nefunguje: překlad jména.',
                            'Podívej se, který server nslookup skutečně oslovuje.',
                            'Dalším krokem je ověřit dostupnost 192.168.50.53 a službu DNS na portu 53.',
                        ],
                        'kb' => 'dns',
                    ],
                ],
            ],
            [
                'id' => 'web_service',
                'title' => 'Lab 2 · Server žije, web ale ne',
                'time' => '15 min',
                'goal' => 'Rozlišit „host je dostupný“ od „konkrétní služba funguje“ a vybrat měření na správné vrstvě.',
                'scenario' => 'Klient 192.168.50.88/24 má otevřít interní web na serveru 192.168.50.20. Ping funguje, prohlížeč hlásí, že stránku nelze načíst.',
                'evidence' => [
                    'C:\\> ping 192.168.50.20  → 4/4 odpovědi',
                    'Požadovaná adresa: https://192.168.50.20/',
                ],
                'steps' => [
                    [
                        'question' => 'Co úspěšný ping opravdu dokazuje?',
                        'options' => [
                            'a' => 'Že existuje základní IP konektivita a cíl odpovídá na ICMP; ne že funguje HTTPS.',
                            'b' => 'Že port 443 je otevřený.',
                            'c' => 'Že certifikát HTTPS je platný.',
                            'd' => 'Že DNS je správně nastavené.',
                        ],
                        'correct' => 'a',
                        'explanation' => 'Ping je test ICMP. Aplikační služba na TCP/443 je jiný předpoklad a musí se ověřit zvlášť.',
                        'hints' => [
                            'Ping a HTTPS nepoužívají stejný protokol.',
                            'ICMP nemá TCP port 443.',
                            'Úspěšný ping znamená „host odpovídá na ICMP“, nic víc.',
                        ],
                        'kb' => 'icmp',
                    ],
                    [
                        'question' => 'Který další test je nejvhodnější z klienta?',
                        'options' => [
                            'a' => 'PowerShell: Test-NetConnection 192.168.50.20 -Port 443',
                            'b' => 'ipconfig /release',
                            'c' => 'nslookup 192.168.50.20',
                            'd' => 'sftp 192.168.50.20',
                        ],
                        'correct' => 'a',
                        'explanation' => 'Potřebuješ cíleně ověřit TCP/443. Test-NetConnection oddělí dostupnost hosta od dostupnosti konkrétního portu.',
                        'hints' => [
                            'Znáš IP i službu, takže DNS teď není hlavní otázka.',
                            'HTTPS standardně používá TCP/443.',
                            'Vyber test konkrétního TCP portu.',
                        ],
                        'kb' => 'ports',
                    ],
                    [
                        'evidence' => [
                            'TcpTestSucceeded : False',
                            'Na serveru:',
                            '$ ss -ltnp',
                            'LISTEN 0 511 0.0.0.0:80  0.0.0.0:* users:(("nginx",pid=721,fd=6))',
                            '(žádný socket na :443)',
                        ],
                        'question' => 'Jaký závěr odpovídá důkazům nejlépe?',
                        'options' => [
                            'a' => 'Webserver naslouchá na HTTP/80, ale HTTPS/443 není nakonfigurované nebo spuštěné.',
                            'b' => 'Klient nemá IP adresu.',
                            'c' => 'Ping zablokoval HTTPS.',
                            'd' => 'Server je určitě vypnutý.',
                        ],
                        'correct' => 'a',
                        'explanation' => 'Proces nginx běží a naslouchá na portu 80. Na 443 nic neposlouchá, takže je potřeba řešit HTTPS konfiguraci/certifikát nebo použít správný protokol podle zadání.',
                        'hints' => [
                            'Porovnej port v URL s porty ve výpisu ss.',
                            'https:// očekává standardně 443.',
                            'Ve výpisu je pouze 0.0.0.0:80.',
                        ],
                        'kb' => 'https',
                    ],
                ],
            ],
            [
                'id' => 'ssh_sftp',
                'title' => 'Lab 3 · Soubor má jít na server bezpečně',
                'time' => '15 min',
                'goal' => 'Správně rozlišit SSH, SFTP a klasické FTP a ověřit dostupnost portu 22.',
                'scenario' => 'Potřebuješ nahrát soubor report.txt na server 192.168.50.30 pod uživatelem student. Správce říká, že na serveru běží SSH na výchozím portu.',
                'evidence' => [
                    'Server: 192.168.50.30',
                    'Uživatel: student',
                    'SSH: výchozí konfigurace',
                    'Požadavek: šifrovaný přenos souboru',
                ],
                'steps' => [
                    [
                        'question' => 'Který příkaz/protokol odpovídá zadání?',
                        'options' => [
                            'a' => 'sftp student@192.168.50.30',
                            'b' => 'ftp student@192.168.50.30:443',
                            'c' => 'ping student@192.168.50.30',
                            'd' => 'nslookup report.txt',
                        ],
                        'correct' => 'a',
                        'explanation' => 'SFTP běží přes SSH, je šifrované a při výchozí konfiguraci používá TCP/22.',
                        'hints' => [
                            'Zadání říká, že má jít o šifrovaný přenos a na serveru běží SSH.',
                            'SFTP není klasické FTP „s portem navíc“.',
                            'Použij klienta sftp a stejné přihlašovací údaje jako pro SSH.',
                        ],
                        'kb' => 'ssh-sftp',
                    ],
                    [
                        'evidence' => [
                            'C:\\> ping 192.168.50.30  → odpovědi chodí',
                            'C:\\> sftp student@192.168.50.30',
                            'ssh: connect to host 192.168.50.30 port 22: Connection timed out',
                        ],
                        'question' => 'Co máš ověřit jako další krok?',
                        'options' => [
                            'a' => 'Dostupnost TCP/22 a zda SSH služba naslouchá / není blokovaná firewallem.',
                            'b' => 'DNS A záznam report.txt.',
                            'c' => 'Změnit masku na /8 bez dalšího měření.',
                            'd' => 'Nastavit HTTPS na port 21.',
                        ],
                        'correct' => 'a',
                        'explanation' => 'IP konektivita existuje, ale TCP/22 timeoutuje. Další důkazy musí oddělit stav služby, firewall a síťovou cestu pro port 22.',
                        'hints' => [
                            'Ping už dokázal základní dosažitelnost hosta.',
                            'Chyba explicitně říká port 22 a timeout.',
                            'Testuj port 22 a na serveru ověř naslouchající SSH socket.',
                        ],
                        'kb' => 'ports',
                    ],
                    [
                        'evidence' => [
                            'Na serveru: $ ss -ltn | grep :22',
                            'LISTEN 0 128 0.0.0.0:22 0.0.0.0:*',
                            'Host firewall: příchozí TCP/22 je DENY',
                        ],
                        'question' => 'Jaká oprava odpovídá zjištěné příčině?',
                        'options' => [
                            'a' => 'Povolit TCP/22 pro požadovanou síť/klienty v host firewallu, ne vypnout firewall celý.',
                            'b' => 'Smazat SSH server, protože naslouchá.',
                            'c' => 'Změnit DNS na 8.8.8.8 bez souvislosti.',
                            'd' => 'Povolit všechny porty z celého internetu.',
                        ],
                        'correct' => 'a',
                        'explanation' => 'Služba naslouchá správně, ale firewall blokuje příchozí provoz. Oprava má být co nejkonkrétnější: povolit jen potřebný provoz ze zamýšleného zdroje.',
                        'hints' => [
                            'Služba podle ss běží a poslouchá na všech IPv4 rozhraních.',
                            'Jediný explicitně špatný údaj je pravidlo firewallu.',
                            'Povol pouze TCP/22 pro potřebný rozsah, ne celý firewall.',
                        ],
                        'kb' => 'troubleshooting',
                    ],
                ],
            ],
            [
                'id' => 'exit',
                'title' => 'Exit ticket · Co uděláš jako první?',
                'time' => '10 min',
                'goal' => 'Ověřit, že umíš zvolit další krok podle dostupných důkazů, ne podle náhodného tipu.',
                'scenario' => 'Čtyři krátké situace. U každé vyber nejrozumnější další krok.',
                'evidence' => [],
                'steps' => [
                    [
                        'question' => '192.168.10.20/24 komunikuje s 192.168.10.80/24. Je pro tuto komunikaci nutná default gateway?',
                        'options' => ['a' => 'Ne, oba hosté jsou ve stejném /24 subnetu.', 'b' => 'Ano, vždy.', 'c' => 'Jen pro ping.', 'd' => 'Jen pokud používají Windows.'],
                        'correct' => 'a',
                        'explanation' => 'Oba hosté jsou ve stejné síti 192.168.10.0/24, takže spolu mohou komunikovat přímo na lokální síti.',
                        'hints' => ['Porovnej síťovou část obou adres.', 'Prefix /24 znamená stejné první tři oktety.', 'Obě adresy patří do 192.168.10.0/24.'],
                        'kb' => 'routing',
                    ],
                    [
                        'question' => 'Web funguje přes 10.0.0.20, ale portal.lab ne. Kterou oblast ověříš jako první?',
                        'options' => ['a' => 'DNS.', 'b' => 'Grafickou kartu.', 'c' => 'SSH klíč.', 'd' => 'DHCP pool na serveru vždy.'],
                        'correct' => 'a',
                        'explanation' => 'Když funguje cílová IP, ale ne jméno, je DNS přirozený další předpoklad k ověření.',
                        'hints' => ['IP spojení už funguje.', 'Rozdíl mezi dvěma pokusy je pouze jméno vs. IP.', 'Ověř překlad jména.'],
                        'kb' => 'dns',
                    ],
                    [
                        'question' => 'Ping na server neodpovídá. Znamená to jistě, že server je vypnutý?',
                        'options' => ['a' => 'Ne. ICMP může být filtrováno; je potřeba ověřit i konkrétní službu/jinou cestu.', 'b' => 'Ano, vždy.', 'c' => 'Ano, pokud jde o HTTPS.', 'd' => 'Ano, protože ping je TCP.'],
                        'correct' => 'a',
                        'explanation' => 'ICMP Echo může být zablokováno. Neúspěšný ping je důkaz o výsledku ICMP testu, ne definitivní důkaz o stavu serveru.',
                        'hints' => ['Ping používá ICMP.', 'Firewally mohou ICMP filtrovat nezávisle na TCP.', 'Ověř konkrétní službu/port.'],
                        'kb' => 'icmp',
                    ],
                    [
                        'question' => 'Který postup je nejvíc systematický při „nejde web“?',
                        'options' => [
                            'a' => 'IP konfigurace → brána/IP konektivita → DNS → konkrétní port → aplikace.',
                            'b' => 'Přeinstalovat OS → restartovat router → zkusit náhodný DNS.',
                            'c' => 'Nejdřív měnit certifikát bez testu portu.',
                            'd' => 'Vždy začít u doménového registrátora.',
                        ],
                        'correct' => 'a',
                        'explanation' => 'Postup od základních vrstev ke konkrétní službě minimalizuje náhodné zásahy a každý výsledek zúží možné příčiny.',
                        'hints' => ['Začni u toho, zda klient vůbec má správnou síťovou konfiguraci.', 'Pak odděl IP konektivitu od DNS.', 'Konkrétní aplikaci řeš až po ověření sítě a portu.'],
                        'kb' => 'troubleshooting',
                    ],
                ],
            ],
        ],
        'extra' => [
            'title' => 'Extra challenge na známku · Dva tikety bez restartu',
            'duration' => '35–45 min',
            'intro' => 'Dobrovolný úkol pro studenty, kteří dokončí celý hlavní blok výrazně dřív. Nejde o závod na čas. Na známku se hodnotí kvalita diagnostiky, práce s důkazy, bezpečnost opravy a ověření výsledku.',
            'brief' => 'Jsi technik/technička podpory. Po přesunu jedné učebny do nové VLAN přišly dva navazující tikety. Nic nerestartuj naslepo a nevypínej firewall. Z dostupných výpisů sestav incident report: co je příčina, jak ji dokážeš, co přesně opravíš a jak ověříš výsledek.',
            'evidence' => [
                'TIKET A · „Internet funguje, ale filesrv.school.lan nejde.“',
                'C:\\> ipconfig /all',
                'IPv4 Address . . . . . : 192.168.70.42',
                'Subnet Mask  . . . . . : 255.255.255.0',
                'Default Gateway . . . : 192.168.70.1',
                'DNS Servers . . . . . : 8.8.8.8',
                'C:\\> ping 192.168.70.1       → 4/4 odpovědi',
                'C:\\> ping 10.10.20.15        → 4/4 odpovědi',
                'C:\\> nslookup filesrv.school.lan',
                'Server: 8.8.8.8  → NXDOMAIN',
                'Dokumentace školy: interní DNS = 10.10.0.53',
                '',
                'TIKET B · Po opravě překladu jmen nejde SFTP na sftp.school.lan.',
                'C:\\> nslookup sftp.school.lan → 10.10.20.30',
                'C:\\> ping 10.10.20.30          → 4/4 odpovědi',
                'C:\\> Test-NetConnection 10.10.20.30 -Port 22 → TcpTestSucceeded: False',
                'Na serveru: $ ss -ltn | grep :22 → LISTEN 0 128 0.0.0.0:22 0.0.0.0:*',
                'Firewall serveru: ALLOW tcp/22 FROM 192.168.60.0/24; ostatní příchozí tcp/22 DENY',
                'Nová učebna je 192.168.70.0/24.',
            ],
            'requirements' => [
                'U každého tiketu určete jednu primární root cause a opřete ji minimálně o dva konkrétní důkazy z výpisů.',
                'Navrhněte diagnostický postup v pořadí. U každého příkazu napište, co jím ověřujete a jaký výsledek očekáváte.',
                'Navrhněte nejmenší bezpečnou opravu. Není dovoleno „vypnout firewall“, „povolit vše“ ani měnit náhodné komponenty.',
                'Sepište ověření po opravě: překlad jména, dostupnost portu a reálný pokus o SFTP.',
                'Knowledgebase je povolena. Automatické nápovědy u tohoto známkovaného challenge nejsou.',
            ],
            'fields' => [
                ['name' => 'diagnosis', 'label' => '1. Diagnóza a důkazy', 'min' => 140, 'placeholder' => 'Pro Tiket A je root cause… Důkaz 1… Důkaz 2… Pro Tiket B…'],
                ['name' => 'diagnostics', 'label' => '2. Diagnostický postup a příkazy', 'min' => 160, 'placeholder' => '1) příkaz… ověřuje… očekávám… 2) příkaz…'],
                ['name' => 'remediation', 'label' => '3. Přesná a bezpečná oprava', 'min' => 120, 'placeholder' => 'Změním… zachovám… firewall pravidlo bude omezené na…'],
                ['name' => 'verification', 'label' => '4. Ověření po opravě', 'min' => 120, 'placeholder' => 'Po opravě ověřím… úspěch poznám podle…'],
                ['name' => 'reflection', 'label' => '5. Proč samotný ping nestačí?', 'min' => 70, 'placeholder' => 'Ping dokazuje…, ale nedokazuje…'],
            ],
            'rubric' => [
                ['area' => 'Diagnóza z důkazů', 'points' => 6, 'text' => 'Obě root cause jsou správné a student přesně odkazuje na relevantní výpisy.'],
                ['area' => 'Diagnostický postup', 'points' => 6, 'text' => 'Příkazy mají logické pořadí a každý testuje konkrétní hypotézu.'],
                ['area' => 'Bezpečná náprava', 'points' => 6, 'text' => 'Oprava je minimální, funkční a respektuje least privilege; firewall se nevypíná.'],
                ['area' => 'Ověření výsledku', 'points' => 4, 'text' => 'Student ověří DNS, TCP/22 i reálné SFTP a umí definovat úspěch.'],
                ['area' => 'Technický incident report', 'points' => 3, 'text' => 'Odpověď je jasná, konkrétní a odlišuje důkaz, hypotézu a změnu.'],
            ],
            'max_points' => 25,
            'grade_scale' => ['23–25 bodů → 1', '20–22 bodů → 2', '16–19 bodů → 3', '12–15 bodů → 4', '0–11 bodů → 5 / doporučeno nejprve vrátit k dopracování'],
            'kb' => ['dhcp', 'dns', 'routing', 'ports', 'ssh-sftp', 'troubleshooting'],
            'teacher_key' => [
                'ticket_a' => 'Primární příčina: klient používá veřejný DNS 8.8.8.8, který nezná interní zónu school.lan. IP konektivita na gateway i fileserver funguje. Oprava: předat/nastavit interní resolver 10.10.0.53, ideálně centrálně přes DHCP pro VLAN 70.',
                'ticket_b' => 'Primární příčina: SSH služba naslouchá, ale host firewall povoluje TCP/22 jen ze staré sítě 192.168.60.0/24. Oprava: přidat/změnit pravidlo pro potřebný zdroj 192.168.70.0/24, nikoli vypnout firewall.',
                'verification' => 'nslookup přes 10.10.0.53 vrátí interní IP; Test-NetConnection na 22 bude True; následný sftp pokus dojde alespoň k autentizaci/přihlášení podle účtu.',
            ],
        ],
    ],

    'class_4a' => [
        'title' => 'Incident response · služby a síť',
        'duration' => 90,
        'intro' => 'Dvě vyučovací hodiny jako sada reálných incidentů. Cílem není uhodnout odpověď, ale číst výpisy, formulovat hypotézu a vybrat nejmenší další měření, které ji potvrdí nebo vyvrátí.',
        'schedule' => [
            ['time' => '0–5 min', 'title' => 'Briefing + produkční incident', 'text' => 'Prohlédni topologii a časovou osu incidentu. Pravidlo dne: před změnou konfigurace musí existovat důkaz, proč ji měníš; postupuj od procesu/socketu přes síť až k DNS/aplikaci.'],
            ['time' => '5–25 min', 'title' => 'Scénářový test', 'text' => '15 otázek z CIDR, routingu, DNS, TCP, bindingu, SSH klíčů a diagnostických příkazů.'],
            ['time' => '25–35 min', 'title' => 'Rozbor výsledků', 'text' => 'Projdi chybné otázky a otevři jen relevantní články knowledgebase.'],
            ['time' => '35–48 min', 'title' => 'Incident 1 · Binding služby', 'text' => 'Služba funguje lokálně, vzdáleně ne. Urči, zda je problém v procesu, bindu nebo síti.'],
            ['time' => '48–60 min', 'title' => 'Incident 2 · DNS po migraci', 'text' => 'Aplikace byla přesunuta, IP funguje, jméno ukazuje jinam. Pracuj s A záznamem, TTL a cache.'],
            ['time' => '60–72 min', 'title' => 'Incident 3 · Routing', 'text' => 'Čti routovací tabulku a zjisti, proč server nedosáhne vzdálené sítě.'],
            ['time' => '72–82 min', 'title' => 'Incident 4 · SSH klíč', 'text' => 'Odliš chybu síťového spojení od chyby autentizace a oprávnění souborů.'],
            ['time' => '82–90 min', 'title' => 'Exit ticket', 'text' => 'Krátký závěrečný incident kombinuje DNS, TCP a aplikační vrstvu.'],
        ],
        'rules' => [
            'Knowledgebase je během startovního testu zamčená. V incidentech je naopak povolená jako běžná dokumentace.',
            'Neprováděj „opravy naslepo“. Nejprve zvol měření, které testuje konkrétní hypotézu.',
            'Každý krok má tři stupně nápovědy a automatickou kontrolu. Chybný pokus se neznámkuje.',
            'Ve vysvětlení po správné odpovědi sleduj hlavně to, co daný výsledek dokazuje a co naopak ještě nedokazuje.',
        ],
        'case_study' => [
            'title' => 'Produkční incident po migraci',
            'eyebrow' => 'Realistická case study · on-call / infrastruktura',
            'summary' => 'Simulace produkčního incidentu, ve kterém se po změně infrastruktury vrství několik nezávislých problémů: service binding, DNS záznam, default route a SSH autentizace. Prostředí je fiktivní, ale syntaxe příkazů, typy výpisů a postup incident response odpovídají běžné praxi.',
            'role' => 'On-call administrátor / infrastruktura',
            'mission' => 'Obnovit službu s minimálním zásahem a průběžně dokazovat, kterou vrstvu už lze vyloučit. Před změnou konfigurace musí existovat měřitelný důvod.',
            'sla' => 'Cíl incidentu: do 10 minut lokalizovat vrstvu, do 30 minut navrhnout bezpečnou nápravu a validační plán.',
            'rules' => [
                'Každá změna musí mít hypotézu, důkaz a rollback.',
                'Rozlišuj proces, socket/binding, routing, DNS, TCP/TLS a aplikační odpověď.',
                'Nespoléhej na jeden test. Hledej nejmenší další měření, které zúží problém.',
                'Restart celé infrastruktury nebo plošné otevření firewallu se nepovažuje za diagnostiku.',
            ],
            'timeline' => [
                ['time' => '13:58', 'ticket' => 'MON-742', 'priority' => 'P2', 'title' => 'Aplikace funguje lokálně, z LAN ne', 'text' => 'Proces je active a lokální curl vrací 200. Z jiného hosta ale TCP/8080 neodpovídá.', 'task_id' => 'binding'],
                ['time' => '14:10', 'ticket' => 'DNS-743', 'priority' => 'P2', 'title' => 'Po migraci jméno stále míří na starý server', 'text' => 'Nová IP vrací 200, DNS ale odpovídá starou adresou. Urči správný záznam a počítej s TTL.', 'task_id' => 'dns_migration'],
                ['time' => '14:22', 'ticket' => 'NET-744', 'priority' => 'P2', 'title' => 'Nový server vidí VLAN, ale ne vzdálené sítě', 'text' => 'Lokální komunikace funguje, default route však vede přes bránu mimo přímo připojený subnet.', 'task_id' => 'routing'],
                ['time' => '14:31', 'ticket' => 'OPS-745', 'priority' => 'P3', 'title' => 'On-call se nemůže přihlásit klíčem', 'text' => 'SSH klient odmítá privátní klíč ještě před autentizací kvůli příliš otevřeným oprávněním.', 'task_id' => 'ssh_permissions'],
                ['time' => '14:42', 'ticket' => 'INC-746', 'priority' => 'CHECK', 'title' => 'End-to-end validace', 'text' => 'Proveď DNS → TCP → TLS/HTTP kontrolu a popiš, co každý výsledek skutečně dokazuje.', 'task_id' => 'exit'],
            ],
            'task_meta' => [
                'binding' => ['time' => '13:58', 'ticket' => 'MON-742', 'priority' => 'P2', 'focus' => ['admin','server_old','app_local']],
                'dns_migration' => ['time' => '14:10', 'ticket' => 'DNS-743', 'priority' => 'P2', 'focus' => ['admin','dns','server_old','server_new']],
                'routing' => ['time' => '14:22', 'ticket' => 'NET-744', 'priority' => 'P2', 'focus' => ['server_old','gateway','remote']],
                'ssh_permissions' => ['time' => '14:31', 'ticket' => 'OPS-745', 'priority' => 'P3', 'focus' => ['admin','server_old']],
                'exit' => ['time' => '14:42', 'ticket' => 'INC-746', 'priority' => 'CHECK', 'focus' => ['admin','dns','server_new','gateway']],
            ],
            'diagram' => [
                'title' => 'Produkční topologie během migrace',
                'caption' => 'Diagram záměrně ukazuje starý i nový aplikační uzel. V jednotlivých incidentech se zvýrazní část cesty, kterou je potřeba ověřit.',
                'width' => 960,
                'height' => 430,
                'nodes' => [
                    ['id' => 'admin', 'x' => 25, 'y' => 160, 'w' => 155, 'h' => 64, 'label' => 'Admin / klient', 'sub' => '10.20.30.80'],
                    ['id' => 'dns', 'x' => 225, 'y' => 40, 'w' => 160, 'h' => 64, 'label' => 'Interní DNS', 'sub' => 'app.lab'],
                    ['id' => 'gateway', 'x' => 225, 'y' => 280, 'w' => 160, 'h' => 64, 'label' => 'Gateway VLAN', 'sub' => '10.20.30.1'],
                    ['id' => 'server_old', 'x' => 455, 'y' => 115, 'w' => 180, 'h' => 70, 'label' => 'Server A', 'sub' => '10.20.30.15 · :8080'],
                    ['id' => 'app_local', 'x' => 455, 'y' => 220, 'w' => 180, 'h' => 70, 'label' => 'myapp socket', 'sub' => '127.0.0.1:8080'],
                    ['id' => 'server_new', 'x' => 710, 'y' => 80, 'w' => 185, 'h' => 70, 'label' => 'Server B · nový', 'sub' => '10.20.30.25'],
                    ['id' => 'remote', 'x' => 710, 'y' => 285, 'w' => 185, 'h' => 70, 'label' => 'Vzdálená síť', 'sub' => 'internet / jiné VLAN'],
                ],
                'links' => [
                    ['from' => 'admin', 'to' => 'dns', 'label' => 'DNS 53'],
                    ['from' => 'admin', 'to' => 'server_old', 'label' => 'HTTP/SSH'],
                    ['from' => 'server_old', 'to' => 'app_local', 'label' => 'loopback bind'],
                    ['from' => 'dns', 'to' => 'server_new', 'label' => 'A záznam'],
                    ['from' => 'server_old', 'to' => 'server_new', 'label' => 'migrace'],
                    ['from' => 'server_old', 'to' => 'gateway', 'label' => 'default route'],
                    ['from' => 'gateway', 'to' => 'remote', 'label' => 'routing'],
                ],
            ],
            'terminal' => [
                ['task_id' => 'binding', 'label' => 'Krok 1 · Proces a lokální HTTP', 'prompt' => '$', 'command' => 'systemctl status myapp && curl -I http://127.0.0.1:8080', 'purpose' => 'Ověřím, zda proces běží a zda aplikace odpovídá lokálně.', 'output' => "myapp.service - active (running)\nHTTP/1.1 200 OK", 'meaning' => 'Proces i aplikace lokálně fungují. Problém není „proces je mrtvý“; další důkaz musí ověřit socket/binding a vzdálenou cestu.'],
                ['task_id' => 'binding', 'label' => 'Krok 2 · Zjisti binding', 'prompt' => '$', 'command' => 'ss -ltnp | grep :8080', 'purpose' => 'Zjistím přesnou adresu a port, na kterých proces naslouchá.', 'output' => "LISTEN 0 128 127.0.0.1:8080 0.0.0.0:* users:((\"myapp\",pid=934,fd=7))", 'meaning' => 'Socket je navázaný pouze na loopback. Firewall nemůže zpřístupnit službu, která na LAN IP vůbec neposlouchá.'],
                ['task_id' => 'dns_migration', 'label' => 'Krok 1 · Porovnej přímou IP a DNS', 'prompt' => '$', 'command' => 'curl -I http://10.20.30.25:8080 && dig app.lab A', 'purpose' => 'Oddělím stav nové aplikace od překladu jména.', 'output' => "HTTP/1.1 200 OK\n\napp.lab. 300 IN A 10.20.30.15", 'meaning' => 'Nový server funguje, ale A záznam stále ukazuje na starou IPv4 adresu. TTL 300 navíc vysvětluje krátkodobou cache po opravě.'],
                ['task_id' => 'routing', 'label' => 'Krok 1 · Čti routovací tabulku', 'prompt' => '$', 'command' => 'ip addr show ens18; ip route', 'purpose' => 'Porovnám subnet rozhraní s adresou default gateway.', 'output' => "inet 10.20.30.15/24\n10.20.30.0/24 dev ens18 proto kernel scope link src 10.20.30.15\ndefault via 10.20.40.1 dev ens18", 'meaning' => 'Server je v 10.20.30.0/24, ale brána 10.20.40.1 není přímo připojená. To je konkrétní routingový nesoulad.'],
                ['task_id' => 'routing', 'label' => 'Krok 2 · Ověř zvolenou cestu', 'prompt' => '$', 'command' => 'ip route get 8.8.8.8', 'purpose' => 'Zjistím, jakou trasu a gateway kernel pro vzdálený cíl skutečně vybere.', 'output' => "8.8.8.8 via 10.20.40.1 dev ens18 src 10.20.30.15", 'meaning' => 'Kernel používá chybnou default route. Před změnou ještě ověř potvrzenou správnou gateway pro VLAN.'],
                ['task_id' => 'ssh_permissions', 'label' => 'Krok 1 · Čti přesnou SSH chybu', 'prompt' => '$', 'command' => 'ssh -i ~/.ssh/id_ed25519 admin@10.20.30.15', 'purpose' => 'Rozliším síťovou chybu od lokální chyby klíče/autentizace.', 'output' => "@ WARNING: UNPROTECTED PRIVATE KEY FILE! @\nPermissions 0644 for 'id_ed25519' are too open.\nThis private key will be ignored.", 'meaning' => 'Klient odmítá klíč lokálně. Primární problém není DNS ani routing, ale oprávnění souboru.'],
                ['task_id' => 'ssh_permissions', 'label' => 'Krok 2 · Oprav least privilege', 'prompt' => '$', 'command' => 'chmod 600 ~/.ssh/id_ed25519 && stat -c "%a %n" ~/.ssh/id_ed25519', 'purpose' => 'Nastavím klíč tak, aby ho mohl číst/zapisovat jen vlastník, a změnu ověřím.', 'output' => "600 /home/admin/.ssh/id_ed25519", 'meaning' => 'Lokální ochrana privátního klíče je v pořádku. Pokud nyní přijde Permission denied (publickey), incident se přesouvá na serverovou autorizaci.'],
                ['task_id' => 'exit', 'label' => 'End-to-end · DNS → TCP → HTTP', 'prompt' => '$', 'command' => 'dig app.lab A +short; nc -vz 10.20.30.25 443; curl -vk https://app.lab/health', 'purpose' => 'Provedu minimální řetězec testů od jména přes transport až po aplikační odpověď.', 'output' => "10.20.30.25\nConnection to 10.20.30.25 443 port [tcp/https] succeeded!\n* TLS handshake complete\n< HTTP/1.1 503 Service Unavailable", 'meaning' => 'DNS, TCP a TLS pro tento pokus proběhly. HTTP 503 posouvá další hypotézu na aplikační/upstream vrstvu.'],
            ],
        ],
        'tasks' => [
            [
                'id' => 'binding',
                'title' => 'Incident 1 · Lokálně 200 OK, vzdáleně nic',
                'time' => '13 min',
                'goal' => 'Najít chybný service binding bez zbytečné změny firewallu nebo DNS.',
                'scenario' => 'Na Ubuntu serveru běží interní aplikace na portu 8080. Správce tvrdí, že služba je aktivní. Z notebooku ve stejné LAN se ale stránka neotevře.',
                'evidence' => [
                    '$ systemctl status myapp  → active (running)',
                    '$ curl -I http://127.0.0.1:8080  → HTTP/1.1 200 OK',
                    '$ ss -ltnp | grep :8080',
                    'LISTEN 0 128 127.0.0.1:8080 0.0.0.0:* users:(("myapp",pid=934,fd=7))',
                ],
                'steps' => [
                    [
                        'question' => 'Která hypotéza nejlépe odpovídá všem důkazům?',
                        'options' => [
                            'a' => 'Aplikace je navázaná jen na loopback 127.0.0.1, takže není dostupná přes LAN rozhraní.',
                            'b' => 'Proces určitě neběží.',
                            'c' => 'DNS je jediná možná příčina.',
                            'd' => 'Port 8080 neexistuje v TCP.',
                        ],
                        'correct' => 'a',
                        'explanation' => 'Proces běží, lokální HTTP odpověď je 200 a socket je explicitně 127.0.0.1:8080. To je přímý důkaz omezeného bindingu.',
                        'hints' => ['Porovnej 127.0.0.1 s adresou fyzického rozhraní.', 'Loopback není dostupný z jiného hosta.', 'Rozhodující řádek je LISTEN 127.0.0.1:8080.'],
                        'kb' => 'binding',
                    ],
                    [
                        'question' => 'Jaká změna je nejpřesnější, pokud má být služba dostupná ze školní LAN?',
                        'options' => [
                            'a' => 'Nastavit bind na konkrétní LAN IP serveru nebo podle záměru na 0.0.0.0 a následně zkontrolovat firewall.',
                            'b' => 'Vypnout celý firewall a nechat bind na 127.0.0.1.',
                            'c' => 'Smazat DNS záznamy.',
                            'd' => 'Změnit port na 53.',
                        ],
                        'correct' => 'a',
                        'explanation' => 'Oprava má změnit příčinu: socket musí naslouchat na rozhraní, přes které přichází klient. 0.0.0.0 znamená všechna IPv4 rozhraní, konkrétní LAN IP je ještě přesnější.',
                        'hints' => ['Firewall neumí zpřístupnit socket, který poslouchá jen na loopbacku.', 'Potřebuješ změnit adresu, na které proces naslouchá.', 'Použij LAN IP nebo 0.0.0.0 podle bezpečnostního záměru.'],
                        'kb' => 'binding',
                    ],
                    [
                        'evidence' => [
                            'Po změně konfigurace:',
                            'LISTEN 0 128 10.20.30.15:8080 0.0.0.0:* users:(("myapp",pid=1012,fd=7))',
                        ],
                        'question' => 'Která dvojice testů nejlépe ověří opravu od serveru až po klienta?',
                        'options' => [
                            'a' => 'curl na 10.20.30.15:8080 lokálně + curl/Test-NetConnection na stejnou IP:8080 z klienta.',
                            'b' => 'Pouze ping localhost.',
                            'c' => 'Pouze nslookup názvu aplikace.',
                            'd' => 'chmod 777 na aplikační adresář.',
                        ],
                        'correct' => 'a',
                        'explanation' => 'Lokální test přes LAN IP ověří nový bind a vzdálený test ověří síťovou cestu/firewall. Teprve pak má smysl přidat DNS jméno.',
                        'hints' => ['Ověř nejdřív socket přes adresu, na kterou je nově navázaný.', 'Pak testuj z jiného hosta.', 'Kombinuj lokální a vzdálený HTTP/TCP test.'],
                        'kb' => 'diagnostics',
                    ],
                ],
            ],
            [
                'id' => 'dns_migration',
                'title' => 'Incident 2 · Aplikace po migraci ukazuje na starý server',
                'time' => '12 min',
                'goal' => 'Odlišit funkční aplikaci od chybného DNS záznamu a správně pracovat s TTL/cache.',
                'scenario' => 'Aplikace app.lab byla přesunuta ze serveru 10.20.30.15 na 10.20.30.25. Přímý přístup na novou IP funguje, jméno ale stále míří na starý stroj.',
                'evidence' => [
                    '$ curl -I http://10.20.30.25:8080  → HTTP/1.1 200 OK',
                    '$ dig app.lab A',
                    'app.lab. 300 IN A 10.20.30.15',
                ],
                'steps' => [
                    [
                        'question' => 'Kde je podle důkazů primární problém?',
                        'options' => ['a' => 'V DNS A záznamu pro app.lab.', 'b' => 'V TCP stacku nového serveru.', 'c' => 'V soukromém SSH klíči.', 'd' => 'V loopback adrese klienta.'],
                        'correct' => 'a',
                        'explanation' => 'Nová IP vrací 200 OK, takže aplikace je dostupná. DNS však explicitně vrací starou IPv4 adresu.',
                        'hints' => ['Přímý HTTP test na nové IP funguje.', 'Rozdíl je mezi názvem a IP.', 'A záznam stále obsahuje 10.20.30.15.'],
                        'kb' => 'dns-advanced',
                    ],
                    [
                        'question' => 'Co je správná oprava?',
                        'options' => ['a' => 'Změnit A záznam app.lab na 10.20.30.25.', 'b' => 'Změnit AAAA záznam, i když se používá IPv4.', 'c' => 'Přepsat default route klientů.', 'd' => 'Povolit port 22.'],
                        'correct' => 'a',
                        'explanation' => 'A záznam mapuje jméno na IPv4. Po migraci musí odpovídat nové adrese aplikace.',
                        'hints' => ['A = IPv4.', 'Nová IPv4 je 10.20.30.25.', 'Uprav konkrétní záznam app.lab A.'],
                        'kb' => 'dns-advanced',
                    ],
                    [
                        'question' => 'Proč může část klientů ještě několik minut vidět starou IP i po opravě?',
                        'options' => ['a' => 'Kvůli DNS cache do vypršení TTL; v příkladu je TTL 300 s.', 'b' => 'Protože TCP vždy cachuje DNS 24 hodin.', 'c' => 'Protože ping mění A záznam.', 'd' => 'Protože chmod 600 blokuje DNS.'],
                        'correct' => 'a',
                        'explanation' => 'TTL 300 dovoluje resolverům držet odpověď až přibližně 5 minut. Diagnostika po změně musí počítat s cache a ověřovat i autoritativní zdroj.',
                        'hints' => ['Číslo 300 ve výpisu není port.', 'DNS odpovědi se mohou cachovat.', '300 sekund = 5 minut TTL.'],
                        'kb' => 'dns-advanced',
                    ],
                ],
            ],
            [
                'id' => 'routing',
                'title' => 'Incident 3 · Špatná default route',
                'time' => '12 min',
                'goal' => 'Číst routovací tabulku a odhalit bránu, která neleží v lokálním subnetu rozhraní.',
                'scenario' => 'Server má adresu 10.20.30.15/24. Lokální hosty ve 10.20.30.0/24 vidí, ale do jiných sítí se nedostane.',
                'evidence' => [
                    '$ ip addr show ens18',
                    'inet 10.20.30.15/24',
                    '$ ip route',
                    '10.20.30.0/24 dev ens18 proto kernel scope link src 10.20.30.15',
                    'default via 10.20.40.1 dev ens18',
                ],
                'steps' => [
                    [
                        'question' => 'Co je na routovací tabulce podezřelé?',
                        'options' => [
                            'a' => 'Default gateway 10.20.40.1 neleží v přímo připojené síti 10.20.30.0/24.',
                            'b' => 'Lokální route 10.20.30.0/24 je vždy špatně.',
                            'c' => 'Server má privátní IP adresu.',
                            'd' => 'Rozhraní se jmenuje ens18.',
                        ],
                        'correct' => 'a',
                        'explanation' => 'Bez jiné specifické on-link route není brána 10.20.40.1 přímo dosažitelná z 10.20.30.15/24. Typická brána musí být na přímo připojené síti.',
                        'hints' => ['Server je v 10.20.30.0/24.', 'Jak by server přímo doručil rámec bráně 10.20.40.1?', 'Porovnej subnet rozhraní a IP default gateway.'],
                        'kb' => 'routing-advanced',
                    ],
                    [
                        'question' => 'Který test nejlépe potvrdí problém ještě před změnou konfigurace?',
                        'options' => ['a' => 'ip route get 8.8.8.8 a ping/ARP kontrola zamýšlené lokální brány.', 'b' => 'dig app.lab AAAA.', 'c' => 'chmod 777 /etc.', 'd' => 'Restartovat všechny servery.'],
                        'correct' => 'a',
                        'explanation' => 'ip route get ukáže vybranou cestu a zdrojovou adresu. Kontrola dosažitelnosti skutečné brány ověří základní předpoklad bez náhodných změn.',
                        'hints' => ['Chceš vidět, jakou trasu kernel skutečně zvolí.', 'Linux má příkaz ip route get <cíl>.', 'Druhá část ověřuje L2/L3 dosažitelnost brány v lokální síti.'],
                        'kb' => 'routing-advanced',
                    ],
                    [
                        'evidence' => [
                            'Správce sítě potvrzuje: gateway pro VLAN je 10.20.30.1.',
                        ],
                        'question' => 'Jak má vypadat opravená default route?',
                        'options' => ['a' => 'default via 10.20.30.1 dev ens18', 'b' => 'default via 127.0.0.1 dev lo', 'c' => 'default via 10.20.40.1 dev ens18', 'd' => '10.20.30.0/24 via 8.8.8.8'],
                        'correct' => 'a',
                        'explanation' => 'Brána 10.20.30.1 je ve stejné přímo připojené síti jako server a podle zadání je správným routerem pro VLAN.',
                        'hints' => ['Použij potvrzenou gateway pro VLAN.', 'Musí být v 10.20.30.0/24.', 'Správný zápis je default via 10.20.30.1 dev ens18.'],
                        'kb' => 'routing-advanced',
                    ],
                ],
            ],
            [
                'id' => 'ssh_permissions',
                'title' => 'Incident 4 · SSH spojení funguje, klíč je odmítnutý',
                'time' => '10 min',
                'goal' => 'Rozlišit síťovou dostupnost SSH od autentizačního problému a opravit oprávnění citlivého klíče.',
                'scenario' => 'TCP/22 je dostupný a server odpovídá. Přihlášení pomocí soukromého klíče ale končí ještě na klientovi varováním o oprávněních souboru.',
                'evidence' => [
                    '$ ssh -i ~/.ssh/id_ed25519 admin@10.20.30.15',
                    '@ WARNING: UNPROTECTED PRIVATE KEY FILE! @',
                    'Permissions 0644 for id_ed25519 are too open.',
                    'This private key will be ignored.',
                ],
                'steps' => [
                    [
                        'question' => 'Je primární problém v síťové cestě na port 22?',
                        'options' => ['a' => 'Ne, klient explicitně odmítá použít příliš otevřený soukromý klíč.', 'b' => 'Ano, protože každá SSH chyba je routing.', 'c' => 'Ano, je potřeba změnit DNS A záznam.', 'd' => 'Ano, port 22 se používá jen pro SFTP.'],
                        'correct' => 'a',
                        'explanation' => 'Chybová zpráva je lokální a konkrétní: soukromý klíč má oprávnění 0644. Síť není primární hypotéza.',
                        'hints' => ['Čti přesnou chybu, ne jen slovo SSH.', 'Klient říká „private key will be ignored“.', 'Problém je v oprávněních lokálního souboru.'],
                        'kb' => 'ssh-keys',
                    ],
                    [
                        'question' => 'Který příkaz odpovídá bezpečné opravě uvedené chyby?',
                        'options' => ['a' => 'chmod 600 ~/.ssh/id_ed25519', 'b' => 'chmod 777 ~/.ssh/id_ed25519', 'c' => 'chmod 644 ~/.ssh/id_ed25519', 'd' => 'sudo ip route flush table main'],
                        'correct' => 'a',
                        'explanation' => '600 = rw-------. Soukromý klíč je čitelný/zapisovatelný pouze vlastníkem a SSH klient ho může použít.',
                        'hints' => ['Soukromý klíč nemá být čitelný ostatními.', 'r=4, w=2, x=1.', 'Pro vlastníka read+write = 6, pro skupinu a ostatní 0.'],
                        'kb' => 'permissions',
                    ],
                    [
                        'question' => 'Pokud po opravě oprávnění server vrátí „Permission denied (publickey)“, co je další relevantní oblast?',
                        'options' => ['a' => 'Zda odpovídající veřejný klíč je u správného uživatele v authorized_keys a má vhodná oprávnění.', 'b' => 'Zda funguje HDMI.', 'c' => 'Zda DNS TTL je 300.', 'd' => 'Zda port 443 naslouchá.'],
                        'correct' => 'a',
                        'explanation' => 'Síť a použití privátního klíče jsou dál. Permission denied(publickey) přesouvá pozornost na serverovou autorizaci: uživatele, authorized_keys, oprávnění a sshd konfiguraci.',
                        'hints' => ['Chyba se změnila, takže jsi postoupil o vrstvu dál.', 'Server už klíčovou autentizaci řeší.', 'Ověř veřejný klíč a authorized_keys správného uživatele.'],
                        'kb' => 'ssh-keys',
                    ],
                ],
            ],
            [
                'id' => 'exit',
                'title' => 'Exit ticket · Jeden incident, čtyři vrstvy',
                'time' => '8 min',
                'goal' => 'Zvolit minimální diagnostický krok na základě aktuálního důkazu.',
                'scenario' => 'Uživatel hlásí „app.lab nejde“. Postupně dostáváš výsledky. Na každém kroku rozhodni, co z nich lze vyvodit.',
                'evidence' => [],
                'steps' => [
                    [
                        'evidence' => ['dig app.lab A → 10.20.30.25'],
                        'question' => 'Co tento výsledek dokazuje?',
                        'options' => ['a' => 'DNS resolver vrací IPv4 10.20.30.25; ještě nevíme, zda je TCP port/aplikace dostupná.', 'b' => 'Aplikace určitě funguje.', 'c' => 'TLS certifikát je platný.', 'd' => 'Firewall je vypnutý.'],
                        'correct' => 'a',
                        'explanation' => 'DNS odpověď potvrzuje překlad jména. Dostupnost portu a aplikace je další nezávislý předpoklad.',
                        'hints' => ['DNS vrací data o jménu.', 'DNS odpověď není TCP handshake.', 'Potřebuješ dál testovat konkrétní službu.'],
                        'kb' => 'dns-advanced',
                    ],
                    [
                        'evidence' => ['nc -vz 10.20.30.25 443 → succeeded'],
                        'question' => 'Co teď víme navíc?',
                        'options' => ['a' => 'TCP/443 je dosažitelný a spojení lze navázat; stále nemusí být v pořádku TLS/HTTP aplikace.', 'b' => 'DNS je autoritativní.', 'c' => 'HTTP vždy vrací 200.', 'd' => 'SSH klíč je platný.'],
                        'correct' => 'a',
                        'explanation' => 'Úspěšné TCP spojení zmenšuje problém na vyšší vrstvy: TLS a aplikaci.',
                        'hints' => ['nc testuje port/spojení.', 'Aplikace běží nad TCP.', 'Další krok může být curl -vk nebo openssl s_client podle cíle.'],
                        'kb' => 'tcp',
                    ],
                    [
                        'evidence' => ['curl -vk https://app.lab → TLS handshake OK, HTTP/1.1 503 Service Unavailable'],
                        'question' => 'Kde je teď nejpravděpodobnější problém?',
                        'options' => ['a' => 'Na aplikační/upstream vrstvě; DNS, TCP a TLS už pro tento pokus proběhly.', 'b' => 'V default route klienta určitě.', 'c' => 'V oprávnění SSH private key.', 'd' => 'V A záznamu, protože HTTP 503 je DNS chyba.'],
                        'correct' => 'a',
                        'explanation' => '503 je HTTP odpověď po úspěšném TLS spojení. Problém je typicky ve službě za proxy, dostupnosti upstreamu nebo aplikačním stavu.',
                        'hints' => ['Dostal jsi skutečný HTTP status.', 'To znamená, že síť a TLS už se dostaly až k webové vrstvě.', '503 = služba dočasně nedostupná / upstream problém.'],
                        'kb' => 'diagnostics',
                    ],
                    [
                        'question' => 'Který princip z dnešní hodiny je nejdůležitější?',
                        'options' => ['a' => 'Každý test má ověřovat konkrétní předpoklad a další krok se volí podle důkazu.', 'b' => 'Při problému je nejrychlejší restartovat vše.', 'c' => 'Ping dokazuje funkčnost celé aplikace.', 'd' => 'DNS je příčinou každého problému s webem.'],
                        'correct' => 'a',
                        'explanation' => 'Systematická diagnostika je řetězec hypotéza → měření → důkaz → další hypotéza. To je přenositelné na sítě, servery i aplikace.',
                        'hints' => ['Co měly společné všechny incidenty?', 'Nejdřív jsme četli důkaz, až potom měnili konfiguraci.', 'Hypotéza → test → závěr.'],
                        'kb' => 'diagnostics',
                    ],
                ],
            ],
        ],
        'extra' => [
            'title' => 'Extra challenge na známku · Produkční incident po deployi',
            'duration' => '35–45 min',
            'intro' => 'Dobrovolný produkční incident pro rychlejší studenty. Hodnotí se schopnost lokalizovat poruchu napříč DNS → TCP/TLS → reverse proxy → aplikace a navrhnout změnu s minimálním dopadem.',
            'brief' => 'Po večerním deployi je app.school.cz dostupná, ale uživatelé dostávají 502. Současně přestal monitoring sbírat metriky. Máte výpisy z DNS, sítě, Nginx a procesů. Vypracujte incident report včetně bezpečné opravy, validačních příkazů a rollbacku. Restart všeho ani otevření portů pro celý internet není akceptované řešení.',
            'evidence' => [
                '$ dig app.school.cz A +short → 10.40.0.25',
                '$ nc -vz 10.40.0.25 443 → Connection succeeded',
                '$ curl -vk https://app.school.cz/health → TLS handshake OK; HTTP/1.1 502 Bad Gateway',
                'Nginx error.log: connect() failed (111: Connection refused) while connecting to upstream, upstream: http://127.0.0.1:9000/health',
                '$ systemctl status school-app → active (running)',
                '$ ss -ltnp | grep -E ":8000|:9000"',
                'LISTEN 0 128 127.0.0.1:8000 0.0.0.0:* users:(("school-app",pid=1412,fd=9))',
                'Nginx site config: proxy_pass http://127.0.0.1:9000;',
                '',
                'Monitoring host = 10.40.5.20. Po deployi navíc:',
                '$ curl http://10.40.0.25:9100/metrics → Connection timed out',
                '$ ss -ltnp | grep :9100 → LISTEN 0 128 127.0.0.1:9100 0.0.0.0:* users:(("school-app",pid=1412,fd=10))',
                'Požadavek bezpečnosti: /metrics smí být dostupné pouze z 10.40.5.20, ne z celé sítě ani internetu.',
            ],
            'requirements' => [
                'Určete odděleně root cause pro 502 a pro nedostupné metriky. U každé uveďte důkaz, který vylučuje alespoň jednu jinou vrstvu.',
                'Navrhněte pořadí diagnostických příkazů. Nestačí vypsat seznam příkazů – vysvětlete, proč jsou v daném pořadí.',
                'Pro 502 navrhněte konkrétní změnu konfigurace a bezpečný způsob aplikace změny bez zbytečného restartu.',
                'Pro metriky navrhněte binding + firewall tak, aby byly dostupné z monitoring hostu, ale ne obecně.',
                'Doplňte validační plán a jednoduchý rollback pro případ, že změna zhorší stav.',
                'Knowledgebase je povolena; automatické nápovědy nejsou součástí známkovaného challenge.',
            ],
            'fields' => [
                ['name' => 'diagnosis', 'label' => '1. Root cause analýza', 'min' => 180, 'placeholder' => '502: … důkazy… Monitoring: … důkazy… Co už můžeme vyloučit…'],
                ['name' => 'diagnostics', 'label' => '2. Diagnostický postup', 'min' => 180, 'placeholder' => 'Krok 1… proč… očekávaný výsledek… Krok 2…'],
                ['name' => 'remediation', 'label' => '3. Náprava a hardening', 'min' => 180, 'placeholder' => 'Nginx změna… test konfigurace… reload… metrics bind… firewall source…'],
                ['name' => 'verification', 'label' => '4. Validace po změně', 'min' => 140, 'placeholder' => 'Ověřím DNS/TCP/TLS/HTTP, stav socketů a dostupnost metrik z povoleného i nepovoleného zdroje…'],
                ['name' => 'rollback', 'label' => '5. Rollback + dopad změny', 'min' => 100, 'placeholder' => 'Před změnou… pokud validace selže… vrátím… ověřím…'],
            ],
            'rubric' => [
                ['area' => 'Root cause a interpretace vrstev', 'points' => 7, 'text' => 'Správně lokalizuje oba problémy a vysvětlí, co dokazují DNS, TCP, TLS, HTTP a sockety.'],
                ['area' => 'Diagnostický postup', 'points' => 5, 'text' => 'Postup je minimální, reprodukovatelný a každé měření má explicitní hypotézu.'],
                ['area' => 'Náprava + bezpečnost', 'points' => 7, 'text' => 'Nginx/upstream je opraven bezpečně; metrics endpoint je zpřístupněn jen potřebnému hostu pomocí vhodného bindu/firewallu.'],
                ['area' => 'Validace a rollback', 'points' => 4, 'text' => 'Student ověří stav z více vrstev a má realistický plán návratu.'],
                ['area' => 'Kvalita incident reportu', 'points' => 2, 'text' => 'Report je technicky přesný, stručný a odlišuje příčinu od symptomu.'],
            ],
            'max_points' => 25,
            'grade_scale' => ['23–25 bodů → 1', '20–22 bodů → 2', '16–19 bodů → 3', '12–15 bodů → 4', '0–11 bodů → 5 / doporučeno nejprve vrátit k dopracování'],
            'kb' => ['diagnostics', 'tcp', 'binding', 'dns-advanced', 'routing-advanced'],
            'teacher_key' => [
                'http_502' => 'DNS je správně, TCP/443 funguje a TLS handshake proběhne. 502 vzniká na reverse proxy, která míří na 127.0.0.1:9000, zatímco aplikace naslouchá na 127.0.0.1:8000. Bezpečná oprava: upravit proxy_pass na 8000, spustit nginx -t a následně reload, ne plošný restart serveru.',
                'metrics' => 'Metriky naslouchají pouze na loopbacku 127.0.0.1:9100, proto vzdálený monitoring nemůže přistoupit. Řešení má zpřístupnit socket na serverové IP nebo vhodném rozhraní a současně firewall povolit TCP/9100 pouze ze zdroje 10.40.5.20. Alternativní bezpečné architektury jsou přijatelné, pokud zachovají omezený přístup.',
                'verification' => 'nginx -t; reload; curl -vk https://app.school.cz/health očekává 200; ss ověří správné sockety; metrics fungují z 10.40.5.20 a jsou blokované z jiného hostu; logy neobsahují nový upstream error.',
            ],
        ],
    ],
];
