<?php

declare(strict_types=1);

return [
 'class_1a'=>[
  'editorial-typography-i'=>['id'=>'gfx-type-i','type'=>'spacingtokens','title'=>'Type Scale Lab','lead'=>'Měň základní rytmus a sleduj, jak se typografické role skládají do čitelného systému.','task'=>'Vytvoř konzistentní škálu a rozestupy pro display, heading, body a metadata.','prediction'=>['q'=>'Je lepší mít mnoho náhodných velikostí?','options'=>['Ne, malá konzistentní škála je čitelnější.','Ano, čím více tím lépe.'],'correct'=>0],'hints'=>['Použij několik opakovaných hodnot.','Zvětši rozdíl mezi display a body.','Sleduj whitespace mezi rolemi.'],'conclusion'=>['q'=>'Co vytváří typografický systém?','options'=>['Jasné role a opakované vztahy.','Náhodné změny velikostí.'],'correct'=>0],'points'=>5],
  'layout-rhythm-i'=>['id'=>'gfx-layout-i','type'=>'spacingtokens','title'=>'Vertical Rhythm Lab','lead'=>'Experimentuj s opakovanými spacing hodnotami a pozoruj, jak se z chaosu stane předvídatelný layout.','task'=>'Použij omezenou spacing škálu a vytvoř jasné skupiny obsahu.','prediction'=>['q'=>'Je každá mezera samostatné rozhodnutí?','options'=>['Ne, rytmus má používat opakovaný systém.','Ano.'],'correct'=>0],'hints'=>['Začni 8px základem.','Menší mezery drž uvnitř skupiny.','Větší mezery oddělují sekce.'],'conclusion'=>['q'=>'K čemu whitespace slouží?','options'=>['Komunikuje vztahy a prioritu.','Jen zabírá místo.'],'correct'=>0],'points'=>5],
  'visual-story-i'=>['id'=>'gfx-story-i','type'=>'cropfocus','title'=>'Visual Story Lab','lead'=>'Měň focal point a crop fotografie a sleduj, jak se mění cesta pohledu mezi obrazem, headline a CTA.','task'=>'Nastav výřez tak, aby obraz podporoval headline a CTA.','prediction'=>['q'=>'Může směr fotografie ovlivnit čtení layoutu?','options'=>['Ano.','Ne.'],'correct'=>0],'hints'=>['Najdi hlavní subjekt.','Nenech ho soutěžit s headline.','Ověř malý náhled.'],'conclusion'=>['q'=>'Co je cílem focal pointu?','options'=>['Zahájit zamýšlenou cestu pozornosti.','Být vždy uprostřed.'],'correct'=>0],'points'=>5],
  'production-preflight-i'=>['id'=>'gfx-preflight-i','type'=>'responsivepreview','title'=>'Preflight Lab','lead'=>'Přepínej cílový formát a kontroluj safe zone, velikost a konzistenci před exportem.','task'=>'Připrav export tak, aby odpovídal cílovému formátu a zachoval důležité prvky.','prediction'=>['q'=>'Stačí exportovat bez kontroly výsledného souboru?','options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Zkontroluj rozměr.','Ověř safe zone.','Otevři exportovaný soubor.'],'conclusion'=>['q'=>'Kdy je práce skutečně hotová?','options'=>['Po kontrole finálního exportu.','Po kliknutí na Export.'],'correct'=>0],'points'=>5],
 ],
 'class_2a'=>[
  'responsive-type-ii'=>['id'=>'gfx-type-ii','type'=>'responsivepreview','title'=>'Responsive Type Lab','lead'=>'Přepínej viewport a sleduj, jak se musí měnit velikost, wrap a spacing typografických rolí.','task'=>'Udrž jasnou hierarchii na desktopu i mobilu.','prediction'=>['q'=>'Má se desktopová typografie jen zmenšit stejným poměrem?','options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Sleduj headline wrap.','Body text nenech příliš malý.','Uprav spacing mezi rolemi.'],'conclusion'=>['q'=>'Co se zachovává?','options'=>['Role a priorita.','Přesný počet řádků.'],'correct'=>0],'points'=>5],
  'design-tokens-ii'=>['id'=>'gfx-tokens-ii','type'=>'components','title'=>'Semantic Token Lab','lead'=>'Měň sémantické tokeny a sleduj dopad do více komponent bez lokálních override.','task'=>'Sestav konzistentní Button/Card systém z pojmenovaných tokenů.','prediction'=>['q'=>'Má komponenta používat náhodné lokální barvy?','options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Odděl primitive a semantic token.','Napoj varianty.','Změň jeden token a sleduj celý systém.'],'conclusion'=>['q'=>'Hlavní výhoda tokenů?','options'=>['Konzistence a snadná globální změna.','Více duplicit.'],'correct'=>0],'points'=>5],
  'interaction-patterns-ii'=>['id'=>'gfx-interactions-ii','type'=>'motioncurve','title'=>'State & Motion Lab','lead'=>'Sestav stavovou sekvenci default → loading → success/error a uprav motion tak, aby podporoval feedback.','task'=>'Navrhni přechod, který je pochopitelný i bez animace.','prediction'=>['q'=>'Má motion nahrazovat informaci?','options'=>['Ne, má ji podporovat.','Ano.'],'correct'=>0],'hints'=>['Začni stavovým modelem.','Motion drž krátký.','Ověř reduced motion.'],'conclusion'=>['q'=>'Dobrá mikrointerakce?','options'=>['Rychle potvrzuje stav a další krok.','Pouze dekoruje.'],'correct'=>0],'points'=>5],
  'design-critique-ii'=>['id'=>'gfx-critique-ii','type'=>'critique','title'=>'Design Critique Lab','lead'=>'Porovnej subjektivní komentář s kritikou postavenou na cíli, evidenci a konkrétním doporučení.','task'=>'Přeformuluj kritiku do profesionálního design argumentu.','prediction'=>['q'=>'Je „nelíbí se mi modrá“ dostatečná kritika?','options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Pojmenuj cíl.','Přidej pozorování.','Navrhni testovatelnou změnu.'],'conclusion'=>['q'=>'Kvalitní kritika stojí na?','options'=>['Cíli a evidenci.','Osobním vkusu.'],'correct'=>0],'points'=>5],
 ],
 'class_3a'=>[
  'subnetting-vlsm'=>['id'=>'net-vlsm','type'=>'subnetlab','title'=>'VLSM Planner Lab','lead'=>'Rozděluj /24 mezi různě velké segmenty a sleduj hranice bloků, překryv a nevyužitou rezervu.','task'=>'Navrhni subnety pro 90, 40, 20 a 10 hostů bez překryvu.','prediction'=>['q'=>'Je bezpečné začít nejmenším segmentem?','options'=>['Ne, nejdřív největší.','Ano.'],'correct'=>0],'hints'=>['90 hostů potřebuje /25.','Pokračuj další hranicí.','Ověř broadcast každého bloku.'],'conclusion'=>['q'=>'Proč řadit od největšího?','options'=>['Snižuje riziko fragmentace a překryvu.','Kvůli DNS.'],'correct'=>0],'points'=>5],
  'network-security-basics'=>['id'=>'net-zones','type'=>'routinglab','title'=>'Security Zones Lab','lead'=>'Měň pravidla mezi USERS, SERVERS a MGMT a sleduj, které služby zůstanou dostupné nebo zablokované.','task'=>'Povol HTTPS uživatelům, SSH jen managementu a ostatní serverový provoz blokuj.','prediction'=>['q'=>'Je ANY→ANY allow dobrý default?','options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Definuj source i destination.','Povol jen konkrétní port.','Ověř negativní scénář.'],'conclusion'=>['q'=>'Least privilege znamená?','options'=>['Jen minimální nutný přístup.','Povolit vše uvnitř sítě.'],'correct'=>0],'points'=>5],
  'dns-dhcp-operations'=>['id'=>'net-dns-dhcp-ii','type'=>'dnscache','title'=>'TTL & Lease Timeline Lab','lead'=>'Měň TTL a sleduj, kdy klient uvidí nový DNS stav; porovnej to s obnovou DHCP lease.','task'=>'Naplánuj změnu tak, aby stará cache nepřekvapila uživatele.','prediction'=>['q'=>'Uvidí všichni nový A record okamžitě?','options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Sniž TTL před změnou.','Sleduj cache expiry.','U DHCP použij renew, když je třeba.'],'conclusion'=>['q'=>'Co řídí životnost DNS cache?','options'=>['TTL.','TCP window.'],'correct'=>0],'points'=>5],
  'service-debug-chain'=>['id'=>'net-debug-chain','type'=>'packetflow','title'=>'Service Chain Lab','lead'=>'Simuluj závadu v DNS, TCP, TLS nebo HTTP a vyber nejkratší testovací cestu k prvnímu chybějícímu důkazu.','task'=>'Najdi vrstvu závady bez zbytečných restartů.','prediction'=>['q'=>'Má smysl začít restartem všeho?','options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Začni DNS.','Pak port.','Potom TLS a HTTP.'],'conclusion'=>['q'=>'Co je cílem diagnostického chainu?','options'=>['Najít první vrstvu, která selhává.','Spustit co nejvíc příkazů.'],'correct'=>0],'points'=>5],
 ],
 'class_4a'=>[
  'infrastructure-as-code'=>['id'=>'ops-iac','type'=>'canary','title'=>'Plan → Apply Lab','lead'=>'Porovnej malý reviewovatelný change set s neřízenou změnou a rozhodni, kdy je bezpečné provést apply.','task'=>'Projdi změnu přes plan, review, apply a validaci.','prediction'=>['q'=>'Je bezpečné provést apply bez kontroly diffu?','options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Nejdřív baseline.','Zkontroluj scope.','Měj rollback/restore cestu.'],'conclusion'=>['q'=>'Co dává IaC největší hodnotu?','options'=>['Opakovatelnost, audit a review změn.','Více ručních kroků.'],'correct'=>0],'points'=>5],
  'config-drift'=>['id'=>'ops-drift','type'=>'monitoring','title'=>'Drift Detection Lab','lead'=>'Sleduj desired a actual konfiguraci, vyvolej drift a rozhodni, zda opravit runtime nebo zdroj pravdy.','task'=>'Detekuj odchylku a vrať prostředí do jednoznačného stavu.','prediction'=>['q'=>'Je každý drift automaticky chyba runtime?','options'=>['Ne, nejdřív musím znát zdroj pravdy.','Ano.'],'correct'=>0],'hints'=>['Porovnej expected vs actual.','Zjisti historii změny.','Sjednoť stav i repozitář.'],'conclusion'=>['q'=>'Kdy je drift vyřešen?','options'=>['Když desired a actual stav znovu souhlasí a změna je zdokumentovaná.','Když alert vypnu.'],'correct'=>0],'points'=>5],
  'performance-engineering'=>['id'=>'ops-performance','type'=>'httpprobe','title'=>'Latency & Saturation Lab','lead'=>'Měň zátěž a sleduj HTTP latency/error rate spolu s využitím zdroje. Hledej okamžik, kdy se systém začne saturovat.','task'=>'Najdi bottleneck podle p95 a provozních signálů.','prediction'=>['q'=>'Stačí sledovat jen průměrnou latency?','options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Sleduj p95.','Porovnej error rate.','Hledej korelaci se saturací.'],'conclusion'=>['q'=>'Co je bottleneck?','options'=>['Zdroj, jehož limit omezuje celý systém.','Nejnovější server.'],'correct'=>0],'points'=>5],
  'capacity-planning'=>['id'=>'ops-capacity','type'=>'loadbalance','title'=>'Capacity & Headroom Lab','lead'=>'Zvyšuj load, simuluj výpadek backendu a hledej kapacitu, která splní SLO i s rezervou.','task'=>'Navrhni kapacitu pro cílový provoz plus headroom.','prediction'=>['q'=>'Je bezpečné provozovat systém trvale na 100 % laboratorního maxima?','options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Najdi bod degradace.','Přidej rezervu.','Otestuj výpadek části backendů.'],'conclusion'=>['q'=>'Proč potřebujeme headroom?','options'=>['Pro špičky, růst a selhání části systému.','Jen kvůli reportingu.'],'correct'=>0],'points'=>5],
 ],
];
