<?php

declare(strict_types=1);

return [
 'class_1a'=>[
  'color-harmony'=>['id'=>'gfx-palette','type'=>'palette','title'=>'Palette Lab: dej barvám role','lead'=>'Měň hue akcentu, sílu backgroundu a počet akcentů. Sleduj, kdy systém zůstává čitelný a kdy začne soupeřit sám se sebou.','task'=>'Vytvoř paletu s jedním dominantním akcentem a čitelným textem.','prediction'=>['q'=>'Co je pro začátečnickou paletu nejbezpečnější?','options'=>['Jeden hlavní akcent + čitelný základ.','Šest stejně silných barev.','Každý blok jinou barvou.'],'correct'=>0],'hints'=>['Začni backgroundem a textem.','Accent má přitáhnout pozornost, ne pokrýt celý design.','Nastav 1 accent a kontrastní text.'],'conclusion'=>['q'=>'Co drží paletu pohromadě?','options'=>['Jasné role barev.','Počet gradientů.','Náhodnost.'],'correct'=>0],'points'=>5],
  'iconography'=>['id'=>'gfx-icons','type'=>'iconset','title'=>'Icon Lab: jedna rodina','lead'=>'Přepínej stroke/fill styl, tloušťku a velikost. Sleduj, jak rychle systém působí nekonzistentně.','task'=>'Nastav tři ikony na společný styl a optickou velikost.','prediction'=>['q'=>'Co je největší problém směsi outline + emoji + 3D?', 'options'=>['Ztráta vizuální konzistence.','Příliš malý datový soubor.','Nedostatek DNS.'],'correct'=>0],'hints'=>['Sjednoť style.','Sjednoť tloušťku.','Sjednoť velikost.'],'conclusion'=>['q'=>'Co je dobrý icon system?','options'=>['Stejná vizuální logika napříč významy.','Každá ikona jiná.','Jen velké ikony.'],'correct'=>0],'points'=>5],
  'image-composition'=>['id'=>'gfx-crop','type'=>'cropfocus','title'=>'Crop Lab: kam jde oko?','lead'=>'Posouvej focal point a textový blok. Náhled ukazuje kolizi i klidovou zónu.','task'=>'Umísti focal point a text tak, aby se vzájemně nepřekrývaly a kompozice měla směr.','prediction'=>['q'=>'Je vždy nejlepší dát vše doprostřed?', 'options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Vytvoř vztah mezi focal point a textem.','Nech text v klidnější oblasti.','Focal point vpravo, text vlevo je dobrý začátek.'],'conclusion'=>['q'=>'Co je hlavní role cropu?','options'=>['Řídit význam a prostor v obraze.','Jen zmenšit soubor.','Přidat filtr.'],'correct'=>0],'points'=>5],
  'template-critique'=>['id'=>'gfx-critique','type'=>'critique','title'=>'Critique Lab: symptom → příčina → oprava','lead'=>'Zapínej typické chyby šablony a sleduj dopad na čitelnost. Cílem je opravit funkční problém, ne jen změnit styl.','task'=>'Odstraň tři zásadní chyby: plochou hierarchii, nízký kontrast a chaotický spacing.','prediction'=>['q'=>'Která věta je kvalitní kritika?', 'options'=>['Datum soupeří s headline, proto ho zmenším a seskupím.','Je to ošklivé.','Přidáme efekt.'],'correct'=>0],'hints'=>['Najdi první problém s hierarchií.','Potom kontrast.','Nakonec spacing.'],'conclusion'=>['q'=>'Co má redesign dokazovat?','options'=>['Lepší funkci vůči cíli.','Více dekorací.','Více fontů.'],'correct'=>0],'points'=>5],
 ],
 'class_2a'=>[
  'ui-spacing-system'=>['id'=>'ui-spacing','type'=>'spacingtokens','title'=>'Spacing Lab: tokeny místo chaosu','lead'=>'Měň počet tokenů a základní krok. Sleduj konzistenci karet a sekcí.','task'=>'Vytvoř malý spacing systém s 4–6 hodnotami a použitelným rytmem.','prediction'=>['q'=>'Co je lepší?', 'options'=>['Omezená sada spacing hodnot.','Náhodná hodnota pro každý gap.'],'correct'=>0],'hints'=>['Začni 4 nebo 8 px.','Použij násobky.','Drž 4–6 hodnot.'],'conclusion'=>['q'=>'Proč tokeny?', 'options'=>['Konzistence a rychlost rozhodování.','Aby bylo více čísel.'],'correct'=>0],'points'=>5],
  'component-consistency'=>['id'=>'ui-components','type'=>'components','title'=>'Component Lab: stejné role, stejná pravidla','lead'=>'Měň radius, padding a states tří tlačítek. Cílem je sjednotit systém, ne všechny prvky udělat identické.','task'=>'Sjednoť primary, secondary a disabled variantu pod jednu komponentu.','prediction'=>['q'=>'Má disabled button vypadat stejně jako primary?', 'options'=>['Ne, stav musí být rozpoznatelný.','Ano vždy.'],'correct'=>0],'hints'=>['Sjednoť anatomy.','Rozliš variantu přes barvu/kontrast.','Drž stejné paddingy/radius.'],'conclusion'=>['q'=>'Co je komponenta?', 'options'=>['Opakovatelné pravidlo a jeho varianty.','Náhodný blok.'],'correct'=>0],'points'=>5],
  'microinteraction-storyboard'=>['id'=>'ui-motion','type'=>'motioncurve','title'=>'Motion Lab: feedback v čase','lead'=>'Měň délku a easing krátké mikrointerakce. Sleduj, kdy je feedback rychlý a kdy už obtěžuje.','task'=>'Nastav success feedback, který je rychlý, čitelný a funkční.','prediction'=>['q'=>'Je 4s animace běžného kliknutí vhodná?', 'options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Mikrointerakce má být krátká.','Zkus 180–300 ms.','Použij ease-out.'],'conclusion'=>['q'=>'Co má pohyb dělat?', 'options'=>['Vysvětlit změnu stavu.','Jen přitahovat pozornost.'],'correct'=>0],'points'=>5],
  'portfolio-case-study'=>['id'=>'ui-portfolio','type'=>'portfolioflow','title'=>'Case Study Builder','lead'=>'Přepínej bloky case study a sleduj, jestli příběh dává smysl bez dlouhého vysvětlování.','task'=>'Sestav pořadí problém → proces → rozhodnutí → výsledek → reflexe.','prediction'=>['q'=>'Co má být první?', 'options'=>['Problém/cíl.','Finální mockup bez kontextu.'],'correct'=>0],'hints'=>['Začni problémem.','Proces bez rozhodnutí nestačí.','Ukonči výsledkem a reflexí.'],'conclusion'=>['q'=>'Co portfolio dokazuje?', 'options'=>['Schopnost řešit problém.','Pouze znalost exportu.'],'correct'=>0],'points'=>5],
 ],
 'class_3a'=>[
  'ipv6-basics'=>['id'=>'net-ipv6','type'=>'ipv6subnet','title'=>'IPv6 Lab: /64 a zkracování','lead'=>'Měň prefix a kompresi adresy. Vizuál zvýrazní síťovou a interface část.','task'=>'Nastav /64 a správně rozpoznej dvě adresy ve stejné síti.','prediction'=>['q'=>'Znamená /64 přesně 64 hostů?', 'options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Prefix je počet bitů síťové části.','Porovnej první 64 bitů.','Použij /64.'],'conclusion'=>['q'=>'Co sdílí hosté v jednom /64?', 'options'=>['Stejný 64bitový síťový prefix.','Stejný TCP port.'],'correct'=>0],'points'=>5],
  'dns-record-types'=>['id'=>'net-dns-records','type'=>'dnsrecords','title'=>'DNS Records Lab','lead'=>'Vyber A, AAAA nebo CNAME pro různé úlohy a sleduj výslednou resolving chain.','task'=>'Nastav www jako CNAME a cílovému hostu A + AAAA.','prediction'=>['q'=>'Co obsahuje CNAME?', 'options'=>['Jiné DNS jméno.','IPv4 adresu.'],'correct'=>0],'hints'=>['Alias ukazuje na jméno.','A je IPv4.','AAAA je IPv6.'],'conclusion'=>['q'=>'Co může pokazit chybný AAAA?', 'options'=>['IPv6 cestu dual-stack klienta.','SSH permissions.'],'correct'=>0],'points'=>5],
  'monitoring-basics'=>['id'=>'net-monitor','type'=>'monitoring','title'=>'Monitoring Lab: co vlastně měříš?','lead'=>'Přepínej ping, TCP a HTTP check a simuluj různé závady. Sleduj, který check incident skutečně odhalí.','task'=>'Nastav monitoring webu tak, aby odhalil stav HTTP 503 i při živém hostu.','prediction'=>['q'=>'Stačí ping pro web?', 'options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Host může žít a app selhat.','Přidej HTTPS check.','Očekávej HTTP 200.'],'conclusion'=>['q'=>'Jaký check je nejblíž uživateli?', 'options'=>['Aplikační HTTP check.','ARP tabulka.'],'correct'=>0],'points'=>5],
  'dhcp-reservations'=>['id'=>'net-dhcp-reserve','type'=>'dhcpreserve','title'=>'Reservation Lab','lead'=>'Měň MAC, pool a reservation. Simulace ukáže, zda klient dostane stabilní adresu bez konfliktu.','task'=>'Rezervuj tiskárně 192.168.10.50 bez kolize s dynamickým poolem.','prediction'=>['q'=>'Je reservation totéž jako ruční static IP na klientovi?', 'options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Reservation je na DHCP serveru.','Vyber správnou MAC.','Vyber IP podle policy.'],'conclusion'=>['q'=>'Co získáš reservation?', 'options'=>['Stabilní lease a centrální options.','Automatický firewall.'],'correct'=>0],'points'=>5],
 ],
 'class_4a'=>[
  'http-observability'=>['id'=>'ops-http','type'=>'httpprobe','title'=>'HTTP Probe Lab','lead'=>'Měň status, redirect a latency. Sleduj, co lze bezpečně tvrdit z jedné odpovědi.','task'=>'Izoluj stav 503 s funkčním TCP a správně interpretuj Retry-After.','prediction'=>['q'=>'503 znamená, že HTTP vrstva odpověděla?', 'options'=>['Ano.','Ne.'],'correct'=>0],'hints'=>['Status je HTTP důkaz.','Nastav 503.','Přidej Retry-After.'],'conclusion'=>['q'=>'Co je dobrý observability signál?', 'options'=>['Status + headers + latency v čase.','Jen screenshot stránky.'],'correct'=>0],'points'=>5],
  'load-balancing'=>['id'=>'ops-lb','type'=>'loadbalance','title'=>'Load Balancer Lab','lead'=>'Měň váhy backendů a health. Animace rozděluje 20 requestů a ukazuje chyby.','task'=>'Vyřaď unhealthy web02 a doruč všechny requesty zdravému backendu.','prediction'=>['q'=>'Má unhealthy backend dál dostávat běžný traffic?', 'options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Health check řídí pool.','Nastav web02 unhealthy.','Enable remove unhealthy.'],'conclusion'=>['q'=>'Co chrání uživatele?', 'options'=>['Health-aware routing.','Více DNS záznamů bez kontroly.'],'correct'=>0],'points'=>5],
  'canary-release'=>['id'=>'ops-canary','type'=>'canary','title'=>'Canary Lab: promote nebo rollback','lead'=>'Měň podíl v2 a error rate. Graf ukazuje dopad na uživatele a decision gate.','task'=>'Najdi stav, kdy canary musí být rollbackována podle threshold.','prediction'=>['q'=>'Proč začít 10 %?', 'options'=>['Omezíš blast radius.','Je to rychlejší DNS.'],'correct'=>0],'hints'=>['Sleduj error rate.','Nastav threshold.','Pokud v2 překročí limit, rollback.'],'conclusion'=>['q'=>'Canary je hlavně co?', 'options'=>['Řízený experiment s omezeným dopadem.','Permanentní load balancer.'],'correct'=>0],'points'=>5],
  'backup-restore'=>['id'=>'ops-restore','type'=>'backuprestore','title'=>'Restore Drill Lab','lead'=>'Vyber backup, recovery point a validační kroky. Simulace spočítá RPO/RTO dopad.','task'=>'Vyber nejnovější ověřený recovery point a proveď testovací restore s validací.','prediction'=>['q'=>'Je backup bez testu restore dostatečný?', 'options'=>['Ne.','Ano.'],'correct'=>0],'hints'=>['Nejprve ověř integritu.','Restore do test targetu.','Ověř data i app.'],'conclusion'=>['q'=>'Co je RPO?', 'options'=>['Tolerovaná ztráta dat v čase.','Doba CPU testu.'],'correct'=>0],'points'=>5],
 ],
];
