<?php

declare(strict_types=1);
if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

function teacher_ops_due_badge(?string $due): string
{
    if(!$due)return '<span class="ops-due neutral">bez termínu</span>';$today=new DateTimeImmutable('today');$d=DateTimeImmutable::createFromFormat('!Y-m-d',$due);if(!$d)return '<span class="ops-due neutral">'.e($due).'</span>';$days=(int)$today->diff($d)->format('%r%a');$class=$days<0?'bad':($days<=1?'warn':'good');$label=$days<0?'po termínu '.abs($days).' d':($days===0?'dnes':($days===1?'zítra':'za '.$days.' d'));return '<span class="ops-due '.$class.'">'.e($label).'</span>';
}
function teacher_render_ops_plus_attention(?string $classId=null): void
{
    $classes=$classId!==null?[teacher_ops_valid_class($classId)]:teacher_ops_class_ids();$watch=teacher_ops_watchlist_visible($classId);$follow=teacher_ops_followups_visible($classId,false);$undos=teacher_ops_undo_available($classId,5);
    ?><section class="teacher-panel ops-health-panel" data-ops-health><div class="teacher-panel-head"><div><span>Class Health</span><h2>Zdraví tříd bez černé skříňky</h2><p>Skóre je rozpadnuté na výsledky, termíny, mastery a aktivitu.</p></div></div><div class="ops-health-grid"><?php foreach($classes as $cid): $h=teacher_ops_class_health($cid); ?><article class="<?=e($h['status'])?>"><header><div><span><?=e(teacher_class_label($cid))?></span><strong><?=number_format((float)$h['score'],0)?>/100</strong></div><b><?=e(teacher_ops_health_label((string)$h['status']))?></b></header><div class="ops-health-components"><?php foreach(['results'=>'Výsledky','deadlines'=>'Termíny','mastery'=>'Mastery','activity'=>'Aktivita'] as $key=>$label): ?><div><span><?=e($label)?></span><progress max="100" value="<?=e((string)$h['components'][$key])?>"></progress><b><?=number_format((float)$h['components'][$key],0)?>%</b></div><?php endforeach; ?></div><footer><a href="?tab=analytics&class=<?=e($cid)?>">Analytika →</a><a href="?tab=class_results&class=<?=e($cid)?>">Studenti →</a></footer></article><?php endforeach; ?></div></section>
    <div class="ops-plus-grid"><section class="teacher-panel" data-ops-followups><div class="teacher-panel-head"><div><span>Follow-up queue</span><h2>Co se nesmí ztratit</h2></div><strong><?=count($follow)?></strong></div><div class="ops-followup-list"><?php foreach(array_slice($follow,0,12) as $row): $students=project_students_for_class((string)$row['class_id']); ?><article><div><span><?=e(teacher_class_label((string)$row['class_id']))?> · <?=e((string)($row['scope']==='team'?'Týmový':'Osobní'))?></span><strong><?=e((string)$row['title'])?></strong><small><?=!empty($row['student_key'])?e((string)($students[(string)$row['student_key']]['label']??$row['student_key'])):'Celá třída'?> · <?=teacher_ops_due_badge($row['due_at']??null)?></small></div><?php if(!empty($row['is_owner'])): ?><form method="post" class="ops-inline-actions"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="teacher_followup_update"><input type="hidden" name="followup_id" value="<?=e((string)$row['id'])?>"><input type="hidden" name="class_id" value="<?=e((string)$row['class_id'])?>"><input type="hidden" name="return_tab" value="attention"><button name="followup_mode" value="done">Hotovo</button><button name="followup_mode" value="tomorrow">Zítra</button><button name="followup_mode" value="week">+7 dní</button></form><?php else: ?><span class="ops-readonly">sdílí <?=e((string)$row['owner_label'])?></span><?php endif; ?></article><?php endforeach; ?><?php if(!$follow): ?><div class="teacher-empty">Follow-up fronta je prázdná.</div><?php endif; ?></div></section>
    <section class="teacher-panel" data-ops-watchlist><div class="teacher-panel-head"><div><span>Watchlist</span><h2>Sledovaní studenti</h2></div><strong><?=count($watch)?></strong></div><div class="ops-watchlist-list"><?php foreach(array_slice($watch,0,12) as $row): $students=project_students_for_class((string)$row['class_id']); ?><article><a href="<?=e(teacher_ops_student_url((string)$row['class_id'],(string)$row['student_key']))?>"><span class="teacher-avatar"><?=e(strtoupper(u_substr((string)($students[(string)$row['student_key']]['label']??'?'),0,1)))?></span><div><strong><?=e((string)($students[(string)$row['student_key']]['label']??$row['student_key']))?></strong><small><?=e(teacher_class_label((string)$row['class_id']))?> · <?=e((string)($row['reason']??'bez poznámky'))?></small></div></a><span class="ops-priority <?=e((string)$row['priority'])?>"><?=e(teacher_task_priority_label((string)$row['priority']))?></span></article><?php endforeach; ?><?php if(!$watch): ?><div class="teacher-empty">Watchlist je prázdný.</div><?php endif; ?></div></section></div>
    <?php if($undos): ?><section class="teacher-panel ops-undo-panel" data-ops-undo><div class="teacher-panel-head"><div><span>Safe Undo</span><h2>Poslední vratné hromadné akce</h2><p>Undo funguje jen dokud se dotčené záznamy mezitím nezměnily.</p></div></div><div class="ops-undo-list"><?php foreach($undos as $u): ?><article><div><strong><?=e((string)$u['summary'])?></strong><small><?=e(date('H:i:s',strtotime((string)$u['created_at'])))?> · platí do <?=e(date('H:i:s',strtotime((string)$u['expires_at'])))?></small></div><form method="post" onsubmit="return confirm('Vrátit tuto hromadnou akci?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="teacher_bulk_undo"><input type="hidden" name="undo_id" value="<?=e((string)$u['id'])?>"><input type="hidden" name="class_id" value="<?=e((string)$u['class_id'])?>"><input type="hidden" name="return_tab" value="attention"><button class="btn secondary small">Vrátit</button></form></article><?php endforeach; ?></div></section><?php endif;
}

function teacher_render_ops_plus_student360(string $classId,string $studentKey): void
{
    $watch=teacher_ops_watchlist_for_student($classId,$studentKey);$follow=array_values(array_filter(teacher_ops_followups_visible($classId,true),static fn($r)=>(string)($r['student_key']??'')===$studentKey));
    ?><div class="ops-plus-grid student360-plus"><section class="teacher-panel"><div class="teacher-panel-head"><div><span>Watchlist</span><h2>Sledování studenta</h2></div><strong><?=count($watch)?></strong></div><div class="ops-watchlist-detail"><?php foreach($watch as $row): ?><article><div><b><?=e($row['scope']==='team'?'Týmový':'Osobní')?> · <?=e(teacher_task_priority_label((string)$row['priority']))?></b><p><?=e((string)($row['reason']??''))?></p><small><?=e((string)$row['owner_label'])?></small></div><?php if(!empty($row['is_owner'])): ?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="teacher_watchlist_delete"><input type="hidden" name="watchlist_id" value="<?=e((string)$row['id'])?>"><input type="hidden" name="class_id" value="<?=e($classId)?>"><input type="hidden" name="student_key" value="<?=e($studentKey)?>"><button class="link-button danger">Odebrat</button></form><?php endif; ?></article><?php endforeach; ?></div><?php if(teacher_permission('watchlist.manage')): ?><form method="post" class="ops-mini-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="teacher_watchlist_save"><input type="hidden" name="class_id" value="<?=e($classId)?>"><input type="hidden" name="student_key" value="<?=e($studentKey)?>"><label>Viditelnost<select name="watchlist_scope"><option value="personal">Osobní</option><option value="team">Týmový</option></select></label><label>Priorita<select name="watchlist_priority"><option value="high">Vysoká</option><option value="normal" selected>Běžná</option><option value="low">Nízká</option></select></label><label class="wide">Důvod<input name="watchlist_reason" maxlength="600" placeholder="Na co si dát pozor při další hodině"></label><button class="btn secondary">Přidat / aktualizovat</button></form><?php endif; ?></section>
    <section class="teacher-panel"><div class="teacher-panel-head"><div><span>Follow-up</span><h2>Další kontakt / kontrola</h2></div><strong><?=count(array_filter($follow,static fn($r)=>(string)($r['status']??'open')!=='done'))?></strong></div><div class="ops-followup-mini"><?php foreach(array_slice($follow,0,8) as $row): ?><article class="<?=e((string)$row['status'])?>"><div><strong><?=e((string)$row['title'])?></strong><small><?=teacher_ops_due_badge($row['due_at']??null)?> · <?=e((string)$row['owner_label'])?></small></div><span><?=e((string)$row['status'])?></span></article><?php endforeach; ?></div><?php if(teacher_permission('followups.manage')): ?><form method="post" class="ops-mini-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="teacher_followup_create"><input type="hidden" name="class_id" value="<?=e($classId)?>"><input type="hidden" name="student_key" value="<?=e($studentKey)?>"><label>Název<input required name="followup_title" maxlength="180" placeholder="Ověřit opravený checkpoint"></label><label>Termín<input type="date" name="followup_due_at"></label><label>Viditelnost<select name="followup_scope"><option value="personal">Osobní</option><option value="team">Týmový</option></select></label><label>Priorita<select name="followup_priority"><option value="high">Vysoká</option><option value="normal" selected>Běžná</option><option value="low">Nízká</option></select></label><label class="wide">Poznámka<input name="followup_detail" maxlength="1000"></label><button class="btn primary">Přidat follow-up</button></form><?php endif; ?></section></div><?php
}

function teacher_render_ops_plus_interventions(string $classId): void
{
    $templates=teacher_ops_templates_visible();?><section class="teacher-panel ops-template-panel"><div class="teacher-panel-head"><div><span>Intervention Playbooks</span><h2>Šablony zásahů</h2><p>Vestavěné playbooky + osobní/týmové šablony. Šablona nic sama nespouští; pouze předvyplní plán.</p></div><strong><?=count($templates)?></strong></div><div class="ops-template-list"><?php foreach($templates as $tpl): ?><article><div><span><?=!empty($tpl['builtin'])?'Vestavěná':e(($tpl['scope']??'personal')==='team'?'Týmová':'Osobní')?></span><strong><?=e((string)$tpl['name'])?></strong><small>kontrola +<?= (int)($tpl['review_days']??7) ?> dní · <?=!empty($tpl['create_task'])?'vytvoří první úkol':'bez auto úkolu'?></small></div><p><?=e((string)($tpl['success_metric']??''))?></p><?php if(empty($tpl['builtin'])&&!empty($tpl['is_owner'])): ?><form method="post" onsubmit="return confirm('Smazat vlastní šablonu?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="teacher_template_delete"><input type="hidden" name="template_id" value="<?=e((string)$tpl['id'])?>"><input type="hidden" name="class_id" value="<?=e($classId)?>"><button class="link-button danger">Smazat</button></form><?php endif; ?></article><?php endforeach; ?></div><?php if(teacher_permission('templates.manage')): ?><details class="ops-template-create"><summary>+ Vytvořit vlastní šablonu</summary><form method="post" class="ops-smart-filter-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="teacher_template_save"><input type="hidden" name="class_id" value="<?=e($classId)?>"><label>Název<input required name="template_name" maxlength="100"></label><label>Viditelnost<select name="template_scope"><option value="personal">Osobní</option><option value="team">Týmová</option></select></label><label>Dní do kontroly<input type="number" name="template_review_days" min="1" max="60" value="7"></label><label>Priorita úkolu<select name="template_task_priority"><option value="high">Vysoká</option><option value="normal" selected>Běžná</option><option value="low">Nízká</option></select></label><label class="wide">Problém<textarea name="template_problem" rows="2"></textarea></label><label class="wide">Definice úspěchu<textarea name="template_success" rows="2"></textarea></label><label>Materiál<textarea name="template_material" rows="2"></textarea></label><label>Mikroúkol<textarea name="template_micro_task" rows="2"></textarea></label><label>Checkpoint<textarea name="template_checkpoint" rows="2"></textarea></label><label>Retry<textarea name="template_retry" rows="2"></textarea></label><label class="ops-check"><input type="checkbox" name="template_create_task" value="1"> Vytvořit první úkol</label><button class="btn primary">Uložit šablonu</button></form></details><?php endif; ?></section><?php
}

function teacher_render_ops_audit(): void
{
    $class=(string)($_GET['class']??'');if($class!==''&&(!isset(project_catalog()[$class])||(function_exists('teacher59_can_class')&&!teacher59_can_class($class))))$class=''; /* v59: jen třída v rozsahu */$action=trim((string)($_GET['audit_action']??''));$rows=teacher_ops_audit_visible(['class_id'=>$class,'action'=>$action]);
    ?><section class="teacher-page-head"><div><div class="eyebrow">Operations Audit</div><h1>Audit učitelských zásahů</h1><p>Neměnná pracovní stopa v46/v46.1 akcí: kdo, kdy a co změnil. Učitel/Asistent vidí vlastní akce; Lead/Admin týmovou stopu.</p></div></section><section class="teacher-panel" data-ops-audit><form method="get" class="ops-audit-filters"><input type="hidden" name="tab" value="ops_audit"><label>Třída<select name="class"><option value="">Všechny</option><?php foreach(teacher_ops_class_ids() as $cid): ?><option value="<?=e($cid)?>" <?=$cid===$class?'selected':''?>><?=e(teacher_class_label($cid))?></option><?php endforeach; ?></select></label><label>Akce<input name="audit_action" value="<?=e($action)?>" placeholder="bulk., intervention., followup…"></label><button class="btn secondary">Filtrovat</button></form><div class="ops-audit-list"><?php foreach($rows as $row): ?><article><div class="ops-audit-time"><strong><?=e(date('d.m.Y',strtotime((string)$row['created_at'])))?></strong><span><?=e(date('H:i:s',strtotime((string)$row['created_at'])))?></span></div><div><span><?=e((string)$row['action'])?> · <?=e((string)$row['owner_label'])?> · <?=e((string)$row['role'])?></span><strong><?=e((string)$row['summary'])?></strong><small><?=!empty($row['class_id'])?e(teacher_class_label((string)$row['class_id'])):'globální'?> · <?=e((string)$row['entity_type'])?> <?=e((string)$row['entity_id'])?></small></div></article><?php endforeach; ?><?php if(!$rows): ?><div class="teacher-empty">Zatím žádné auditní události pro zvolený filtr.</div><?php endif; ?></div></section><?php
}
