<?php

declare(strict_types=1);
if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

function teacher_render_skills(string $classId): void
{
    $matrix=skill_class_matrix($classId);$branches=skill_relevant_branches($classId);$branchDefs=skill_branches();$pending=skill_pending_validations($classId);$selectedKey=(string)($_GET['student']??'');$selectedSkill=(string)($_GET['skill']??'');$students=project_students_for_class($classId);$assignments=array_values(array_filter(skill_assignment_rows(),static fn($r):bool=>is_array($r)&&(string)($r['class_id']??'')===$classId));usort($assignments,static fn($a,$b)=>strcmp((string)($b['created_at']??''),(string)($a['created_at']??'')));
    $branchAvg=[];foreach($branches as $b){$vals=[];foreach($matrix as $r)$vals[]=(float)($r['branches'][$b]['mastery_percent']??0);$branchAvg[$b]=$vals?round(array_sum($vals)/count($vals),1):0;}
    ?>
    <section class="teacher-page-head"><div><div class="eyebrow">Skills · kompetenční diagnostika</div><h1>Skill Trees a Mastery</h1><p>Heatmapa ukazuje ověřené schopnosti, ne známky. Praktické evidence čekající na učitele jsou ve validační frontě níže.</p></div><div class="teacher-project-score"><strong><?=count($pending)?></strong><span>čeká na validaci</span></div></section>
    <div class="teacher-kpi-grid skill-teacher-kpis"><?php foreach($branchAvg as $branch=>$avg):?><article><span><?=e((string)($branchDefs[$branch]['name']??$branch))?></span><strong><?=number_format($avg,0)?> %</strong><small><?=e(skill_mastery_level_label(skill_mastery_level($avg)))?></small></article><?php endforeach;?></div>

    <section class="teacher-panel teacher-skill-assignments"><div class="teacher-panel-head"><div><span>Assignment control</span><h2>Doporučit nebo zadat skill</h2><p>Zadání nemění známku. Pouze zvýrazní další krok ve studentském Skill Tree.</p></div><b><?=count($assignments)?></b></div>
      <form method="post" class="teacher-skill-assign-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="skill_assign"><input type="hidden" name="class_id" value="<?=e($classId)?>">
        <label>Skill<select name="skill" required><?php foreach(skill_relevant_skills($classId) as $s):?><option value="<?=e((string)$s['slug'])?>"><?=e((string)($branchDefs[(string)$s['branch']]['name']??$s['branch']))?> · <?=e((string)$s['name'])?></option><?php endforeach;?></select></label>
        <label>Cíl<select name="target_type"><option value="class">Celá třída</option><option value="student">Jeden student</option></select></label>
        <label>Student<select name="target_key"><option value="">— použije se jen pro individuální zadání —</option><?php foreach($students as $st):$sk=skill_student_key_for_label($classId,(string)$st['label']);?><option value="<?=e($sk)?>"><?=e((string)$st['label'])?></option><?php endforeach;?></select></label>
        <label>Priorita<select name="assignment_type"><option value="recommended">Doporučené</option><option value="required">Povinné</option></select></label>
        <label>Termín<input type="date" name="due_at"></label><button class="btn primary" type="submit">Přiřadit skill</button>
      </form>
      <?php if($assignments):?><div class="teacher-assignment-list"><?php foreach(array_slice($assignments,0,8) as $a):$as=skill_find((string)$a['skill']);$who=(string)$a['target_type']==='student'?skill_student_label_from_key($classId,(string)$a['target_key']):teacher_class_label($classId);$active=(string)($a['status']??'active')==='active';?><article class="<?=$active?'active':'cancelled'?>"><div><strong><?=e((string)($as['name']??$a['skill']))?></strong><span><?=e($who)?> · <?=($a['assignment_type']==='required'?'povinné':'doporučené')?> · <?=$active?'aktivní':'zrušeno'?></span></div><small><?=!empty($a['due_at'])?'do '.e(date('d.m.Y',strtotime((string)$a['due_at']))):'bez termínu'?></small><?php if($active):?><form method="post" onsubmit="return confirm('Zrušit toto zadání?');"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="skill_unassign"><input type="hidden" name="class_id" value="<?=e($classId)?>"><input type="hidden" name="assignment_id" value="<?=e((string)$a['id'])?>"><button class="link-button danger" type="submit">Zrušit</button></form><?php endif;?></article><?php endforeach;?></div><?php endif;?>
    </section>

    <section class="teacher-panel teacher-skill-heatmap"><div class="teacher-panel-head"><div><span>Class heatmap</span><h2><?=e(teacher_class_label($classId))?></h2></div><small>Klikni na studenta pro detail evidence.</small></div>
      <div class="teacher-skill-table-wrap"><table class="teacher-skill-table"><thead><tr><th>Student</th><th>Overall</th><?php foreach($branches as $b):?><th><?=e((string)($branchDefs[$b]['name']??$b))?></th><?php endforeach;?></tr></thead><tbody><?php foreach($matrix as $row):?><tr><td><a href="?tab=skills&class=<?=e($classId)?>&student=<?=e((string)$row['student_key'])?>"><?=e((string)$row['label'])?></a></td><td><b><?=number_format((float)$row['overall'],0)?> %</b></td><?php foreach($branches as $b):$v=(float)($row['branches'][$b]['mastery_percent']??0);?><td><span class="mastery-cell level-<?=e(skill_mastery_level($v))?>"><?=number_format($v,0)?>%</span></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div>
    </section>

    <section class="teacher-panel teacher-validation-queue"><div class="teacher-panel-head"><div><span>Mastery Validation</span><h2>Praktické evidence čekající na kontrolu</h2></div><b><?=count($pending)?></b></div><?php if(!$pending):?><div class="teacher-empty">Fronta je prázdná.</div><?php endif;?><div class="teacher-validation-list"><?php foreach($pending as $row):$skill=skill_find((string)$row['skill']);?><article><div><strong><?=e((string)($row['student_label']??'Student'))?> · <?=e((string)($skill['name']??$row['skill']))?></strong><span><?=e((string)($row['meta']['note']??'Bez poznámky'))?></span><small><?=e(date('d.m.Y H:i',strtotime((string)$row['created_at'])))?> · max <?=number_format((float)$row['points'],0)?> MP</small></div><div class="teacher-validation-actions"><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="skill_validation"><input type="hidden" name="evidence_id" value="<?=e((string)$row['id'])?>"><input type="hidden" name="state" value="approved"><input type="hidden" name="class_id" value="<?=e($classId)?>"><button class="btn primary small">Schválit</button></form><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="skill_validation"><input type="hidden" name="evidence_id" value="<?=e((string)$row['id'])?>"><input type="hidden" name="state" value="rejected"><input type="hidden" name="class_id" value="<?=e($classId)?>"><input name="reason" maxlength="600" placeholder="Důvod / co doplnit"><button class="btn secondary small">Vrátit</button></form></div></article><?php endforeach;?></div></section>

    <?php if($selectedKey!==''):$studentLabel=skill_student_label_from_key($classId,$selectedKey);$progress=skill_progress_snapshot_map($classId,$selectedKey);$branchProgress=skill_branch_snapshot_map($classId,$selectedKey);$spec=skill_specialization_from_branches($branchProgress);$overallSnapshot=skill_overall_mastery_from_branches($branchProgress);?>
    <section class="teacher-panel teacher-student-skills"><div class="teacher-panel-head"><div><span>Student detail</span><h2><?=e($studentLabel!==''?$studentLabel:'Student')?></h2><p><?=e((string)($spec['name']??'Bez specializace'))?> · <?=number_format($overallSnapshot,0)?> % overall</p></div><a class="text-link" href="?tab=skills&class=<?=e($classId)?>">Zavřít detail</a></div>
      <div class="teacher-student-branch-grid"><?php foreach($branches as $b):?><article><span><?=e((string)($branchDefs[$b]['name']??$b))?></span><strong><?=number_format((float)($branchProgress[$b]['mastery_percent']??0),0)?> %</strong><small><?= (int)($branchProgress[$b]['skills_mastered']??0) ?> / <?= (int)($branchProgress[$b]['skills_total']??0) ?> mastered</small></article><?php endforeach;?></div>
      <div class="teacher-skill-detail-grid"><?php foreach(skill_relevant_skills($classId) as $s):$sp=$progress[(string)$s['slug']]??[];?><a class="teacher-skill-row" href="?tab=skills&class=<?=e($classId)?>&student=<?=e($selectedKey)?>&skill=<?=e((string)$s['slug'])?>"><span><?=e((string)($branchDefs[(string)$s['branch']]['icon']??'◇'))?></span><div><strong><?=e((string)$s['name'])?></strong><small><?=e(skill_state_label((string)($sp['unlock_state']??'locked')))?></small></div><b><?=number_format((float)($sp['mastery_percent']??0),0)?>%</b></a><?php endforeach;?></div>
    </section>
    <?php if($selectedSkill!=='' && ($skill=skill_find($selectedSkill))):$evidence=skill_student_evidence($classId,$selectedKey,$selectedSkill);$sp=$progress[$selectedSkill]??[];?>
    <section class="teacher-panel teacher-evidence-detail"><div class="teacher-panel-head"><div><span>Evidence detail</span><h2><?=e((string)$skill['name'])?> · <?=number_format((float)($sp['mastery_percent']??0),0)?> %</h2></div></div><div class="teacher-evidence-list"><?php if(!$evidence):?><div class="teacher-empty">Žádná evidence.</div><?php endif;?><?php foreach(array_reverse($evidence) as $ev):?><article><i><?=in_array((string)$ev['state'],['approved','automatic'],true)?'✓':'…'?></i><div><strong><?=e(ucfirst((string)$ev['type']))?> · +<?=number_format((float)$ev['points'],0)?> MP</strong><span><?=e((string)$ev['source_id'])?> · <?=e((string)$ev['state'])?></span></div><?php if(in_array((string)$ev['state'],['automatic','approved'],true)):?><form method="post" onsubmit="return confirm('Revokovat tuto evidence?');"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="skill_validation"><input type="hidden" name="evidence_id" value="<?=e((string)$ev['id'])?>"><input type="hidden" name="state" value="revoked"><input type="hidden" name="class_id" value="<?=e($classId)?>"><button class="link-button danger">Revokovat</button></form><?php endif;?></article><?php endforeach;?></div>
      <form method="post" class="teacher-skill-evidence-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="skill_teacher_evidence"><input type="hidden" name="class_id" value="<?=e($classId)?>"><input type="hidden" name="student_key" value="<?=e($selectedKey)?>"><input type="hidden" name="skill" value="<?=e($selectedSkill)?>"><label>Typ<select name="evidence_type"><option value="lab">Practical lab</option><option value="project">Project evidence</option><option value="challenge">Mastery validation</option></select></label><label>Výsledek %<input type="number" name="score" min="0" max="100" value="100"></label><label class="wide">Poznámka<input name="note" maxlength="800" placeholder="Co student prakticky prokázal?"></label><button class="btn primary" type="submit">Přidat validovanou evidence</button></form>
    </section><?php endif;endif;?>
    <?php
}
