<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, síťová linie: bezpečnost vlastního systému (kategorie „security“).
 * Otázky se týkají ochrany vlastního zařízení a účtů, ne útoků na cizí systémy.
 * Načítá ji souhrnný soubor teamgames_v58_bank_net.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'net.security.001', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Heslo „12345678“ je bezpečné, protože má osm znaků.', 'options' => [], 'answer' => false, 'tolerance' => null, 'accept' => [], 'explain' => 'Délka nestačí, pokud je heslo snadno uhodnutelné nebo mezi nejčastěji používanými.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.002', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je dvoufaktorové ověření (2FA)?', 'options' => ['přihlášení heslem doplněné o druhý ověřovací krok, například kód z aplikace', 'heslo napsané dvakrát za sebou', 'dva různé účty se stejným heslem', 'záloha hesla na papíře'], 'answer' => 'přihlášení heslem doplněné o druhý ověřovací krok, například kód z aplikace', 'tolerance' => null, 'accept' => [], 'explain' => '2FA přidá k heslu druhý nezávislý prvek, čímž útok jen na heslo ztíží.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.003', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Používání stejného hesla na více různých účtech je bezpečné, pokud je heslo dost dlouhé.', 'options' => [], 'answer' => false, 'tolerance' => null, 'accept' => [], 'explain' => 'Únik jednoho účtu by pak ohrozil i všechny ostatní se stejným heslem.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.004', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Proč je dobré pravidelně instalovat aktualizace operačního systému a programů?', 'options' => ['opravují známé bezpečnostní chyby, které by šlo zneužít', 'jen mění vzhled aplikací', 'schválně zpomalují počítač', 'jsou nutné jen jednou za život počítače'], 'answer' => 'opravují známé bezpečnostní chyby, které by šlo zneužít', 'tolerance' => null, 'accept' => [], 'explain' => 'Neaktualizovaný software může obsahovat už veřejně známé chyby.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.005', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'K čemu slouží zamykání obrazovky, když od zařízení odejdeš?', 'options' => ['zabrání to někomu jinému použít zařízení pod tvým přihlášením', 'zrychlí to nabíjení baterie', 'ušetří to data v mobilním tarifu', 'vypne to internetové připojení'], 'answer' => 'zabrání to někomu jinému použít zařízení pod tvým přihlášením', 'tolerance' => null, 'accept' => [], 'explain' => 'Zamčená obrazovka chrání přístup, i když zařízení jen na chvíli odložíš.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.006', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená ikona zámku (HTTPS) vedle adresy webu v prohlížeči?', 'options' => ['spojení mezi prohlížečem a serverem je šifrované', 'stránka je oficiálně schválená státem', 'stránka nemůže obsahovat chyby', 'stránka je automaticky pravdivá'], 'answer' => 'spojení mezi prohlížečem a serverem je šifrované', 'tolerance' => null, 'accept' => [], 'explain' => 'HTTPS šifruje přenos dat mezi prohlížečem a serverem.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.007', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Šifrované spojení (HTTPS) samo o sobě zaručuje, že obsah stránky je důvěryhodný a pravdivý.', 'options' => [], 'answer' => false, 'tolerance' => null, 'accept' => [], 'explain' => 'HTTPS chrání jen přenos dat, ne to, kdo stránku provozuje nebo co je na ní napsáno.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.008', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co bys měl/a udělat, když ti přijde nečekaná příloha od neznámého odesílatele?', 'options' => ['přílohu neotvírat a ověřit si odesílatele jiným způsobem', 'přílohu rovnou otevřít, ať víš, co obsahuje', 'přeposlat ji všem spolužákům', 'odpovědět s vlastním heslem pro kontrolu'], 'answer' => 'přílohu neotvírat a ověřit si odesílatele jiným způsobem', 'tolerance' => null, 'accept' => [], 'explain' => 'Neznámé přílohy mohou obsahovat škodlivý kód.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.009', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je záloha (backup) dat?', 'options' => ['samostatná kopie důležitých dat uložená odděleně pro případ ztráty originálu', 'jiný název pro heslo', 'komprese souboru kvůli úspoře místa', 'odstranění nepotřebných souborů'], 'answer' => 'samostatná kopie důležitých dat uložená odděleně pro případ ztráty originálu', 'tolerance' => null, 'accept' => [], 'explain' => 'Záloha umožní obnovit data, i když originál zmizí nebo se poškodí.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.010', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Záloha dat uložená jen na stejném disku jako originál moc nepomůže, pokud se tento disk fyzicky poškodí.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Zálohu je vhodné mít na jiném fyzickém místě nebo zařízení.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.011', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co je typickým znakem phishingového e-mailu?', 'options' => ['naléhavá výzva, abys přes odkaz v e-mailu rychle „ověřil“ heslo nebo údaje', 'obyčejná odpověď na tvůj vlastní dotaz', 'e-mail od spolužáka se školním zadáním', 'potvrzení objednávky, kterou sis sám vytvořil'], 'answer' => 'naléhavá výzva, abys přes odkaz v e-mailu rychle „ověřil“ heslo nebo údaje', 'tolerance' => null, 'accept' => [], 'explain' => 'Phishing často vyvolává spěch a strach, aby oběť nestihla situaci ověřit.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.012', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je nebezpečné klikat na odkazy v podezřelých zprávách bez ověření jejich skutečné adresy?', 'options' => ['odkaz může vést na podvodnou stránku vypadající jako přihlášení do známé služby', 'odkazy vždy automaticky nainstalují antivirus', 'odkaz nikdy neotevře žádnou stránku', 'prohlížeč odkazy stejně ignoruje'], 'answer' => 'odkaz může vést na podvodnou stránku vypadající jako přihlášení do známé služby', 'tolerance' => null, 'accept' => [], 'explain' => 'Podvodné stránky napodobují vzhled skutečných služeb, aby vylákaly heslo.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.013', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co je správce hesel (password manager)?', 'options' => ['program, který bezpečně uloží a vygeneruje silná unikátní hesla pro různé účty', 'sešit s hesly napsanými rukou', 'sdílený dokument s hesly celé třídy', 'funkce, která hesla úplně zruší'], 'answer' => 'program, který bezpečně uloží a vygeneruje silná unikátní hesla pro různé účty', 'tolerance' => null, 'accept' => [], 'explain' => 'Správce hesel odstraní potřebu pamatovat si desítky různých hesel nazpaměť.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.014', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Veřejná nezabezpečená Wi-Fi síť, například v kavárně, je z hlediska bezpečnosti stejně důvěryhodná jako domácí síť chráněná heslem.', 'options' => [], 'answer' => false, 'tolerance' => null, 'accept' => [], 'explain' => 'Provoz na otevřené veřejné síti může snáze sledovat někdo jiný ve stejné síti.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.015', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč se nedoporučuje na veřejné Wi-Fi síti přihlašovat bez dalšího zabezpečení do citlivých účtů?', 'options' => ['provoz na nezabezpečené síti může snáz odposlechnout někdo jiný v ní', 'veřejná Wi-Fi je vždy rychlejší', 'veřejná Wi-Fi automaticky šifruje všechna data', 'přihlášení na veřejné síti je zakázané zákonem'], 'answer' => 'provoz na nezabezpečené síti může snáz odposlechnout někdo jiný v ní', 'tolerance' => null, 'accept' => [], 'explain' => 'Bez šifrování může být provoz čitelný pro další zařízení ve stejné síti.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.016', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dva z uvedených jsou dobré návyky pro bezpečné heslo?', 'options' => ['dostatečná délka a náhodnost', 'jedinečné heslo pro každý účet', 'jméno domácího mazlíčka', 'stejné heslo úplně všude'], 'answer' => ['dostatečná délka a náhodnost', 'jedinečné heslo pro každý účet'], 'tolerance' => null, 'accept' => [], 'explain' => 'Dlouhé náhodné a jedinečné heslo omezí škodu, i kdyby jeden účet unikl.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.017', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Zálohy je dobré mít na jiném místě než originální data, aby je nezničila stejná nehoda, například požár nebo krádež zařízení.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Oddělené uložení zálohy sníží riziko, že o data přijdeš úplně.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.018', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co bys měl/a zkontrolovat, než zadáš přihlašovací údaje na webu, kam ses dostal/a přes odkaz z e-mailu?', 'options' => ['zda adresa v prohlížeči skutečně odpovídá oficiální doméně dané služby', 'zda má stránka hezký design', 'zda e-mail obsahuje logo firmy', 'zda je e-mail napsaný česky'], 'answer' => 'zda adresa v prohlížeči skutečně odpovídá oficiální doméně dané služby', 'tolerance' => null, 'accept' => [], 'explain' => 'Vzhled a jazyk lze snadno napodobit, skutečnou doménu o něco hůř.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.019', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je riskantní stahovat a spouštět programy z neověřených zdrojů?', 'options' => ['program může obsahovat škodlivý kód, který poškodí data nebo odcizí údaje', 'neověřené zdroje jsou vždy pomalejší', 'licence takových programů jsou dražší', 'takové programy nejde nikdy nainstalovat'], 'answer' => 'program může obsahovat škodlivý kód, který poškodí data nebo odcizí údaje', 'tolerance' => null, 'accept' => [], 'explain' => 'Neověřený zdroj nezaručuje, že program dělá jen to, co tvrdí.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.020', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 2, 'type' => 'order', 'prompt' => 'Seřaď doporučený postup od prvního kroku, když dostaneš e-mail vyzývající k „ověření“ hesla přes odkaz.', 'options' => [], 'answer' => ['nezadávej heslo do žádného odkazovaného formuláře', 'otevři oficiální web služby ručně, ne přes odkaz z e-mailu', 'přihlas se tam a zkontroluj, zda je opravdu něco potřeba potvrdit', 'pokud e-mail vypadá podvodně, nahlas ho nebo smaž'], 'tolerance' => null, 'accept' => [], 'explain' => 'Ověření se dělá vždy přes samostatně otevřenou oficiální stránku, ne přes odkaz z e-mailu.', 'time_s' => 40, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.021', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Co je sociální inženýrství v kontextu počítačové bezpečnosti?', 'options' => ['snaha přimět člověka prozradit citlivé informace, spíš než prolomit techniku', 'oficiální název pro tým IT podpory', 'způsob programování sociálních sítí', 'typ šifrovacího algoritmu'], 'answer' => 'snaha přimět člověka prozradit citlivé informace, spíš než prolomit techniku', 'tolerance' => null, 'accept' => [], 'explain' => 'Útočník cílí na lidskou důvěru nebo spěch místo technické zranitelnosti.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.022', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'I opatrný člověk se může stát obětí útoku, pokud mu volající, který se vydává za IT podporu, řekne po telefonu nadiktovat heslo nebo kód.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Skutečná IT podpora by o heslo nebo jednorázový kód po telefonu žádat neměla.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.023', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč se doporučuje mít systém i aplikace nastavené na automatické bezpečnostní aktualizace?', 'options' => ['zkracuje to dobu, kdy je zařízení zranitelné vůči už známé chybě', 'aktualizace vždy přidávají jen nové barvy ikon', 'automatické aktualizace zvyšují riziko útoku', 'aktualizace nikdy neopravují bezpečnostní chyby'], 'answer' => 'zkracuje to dobu, kdy je zařízení zranitelné vůči už známé chybě', 'tolerance' => null, 'accept' => [], 'explain' => 'Rychlá záplata omezí čas, kdy může být chyba zneužita.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.security.024', 'line' => 'networks', 'classes' => null, 'category' => 'security', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč je vhodné mít u zálohovaných dat i pravidelně vyzkoušenou obnovu, ne jen samotné zálohování?', 'options' => ['zálohu, kterou se nepodaří obnovit, ve skutečnosti k ničemu nemáš', 'testování obnovy zálohu zbytečně poškodí', 'zálohy se testují jen jednou za život zařízení', 'obnova dat funguje vždy automaticky bez ověření'], 'answer' => 'zálohu, kterou se nepodaří obnovit, ve skutečnosti k ničemu nemáš', 'tolerance' => null, 'accept' => [], 'explain' => 'Nefunkční záloha se odhalí často až ve chvíli, kdy je už pozdě.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
];
