<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, síťová linie: procesy a služby / systemd (kategorie „procs“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_net.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'net.procs.001', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který příkaz vypíše seznam aktuálně běžících procesů?', 'options' => ['ps', 'ls', 'cd', 'pwd'], 'answer' => 'ps', 'tolerance' => null, 'accept' => [], 'explain' => 'ps vypíše přehled procesů podle zadaných přepínačů.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.002', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který příkaz zobrazí živě aktualizovaný přehled procesů a využití zdrojů?', 'options' => ['top', 'cat', 'man', 'history'], 'answer' => 'top', 'tolerance' => null, 'accept' => [], 'explain' => 'top se v terminálu průběžně obnovuje a ukazuje zátěž procesoru a paměti.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.003', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je PID?', 'options' => ['jedinečné číslo identifikující běžící proces', 'heslo ke spuštění programu', 'jméno uživatele, který proces spustil', 'typ souboru'], 'answer' => 'jedinečné číslo identifikující běžící proces', 'tolerance' => null, 'accept' => [], 'explain' => 'PID (process ID) jednoznačně označuje konkrétní běžící proces.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.004', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který příkaz ukončí proces podle jeho PID?', 'options' => ['kill', 'stop', 'end', 'ps'], 'answer' => 'kill', 'tolerance' => null, 'accept' => [], 'explain' => 'kill pošle procesu signál, standardně signál k ukončení.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.005', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Každý běžící proces má v systému své vlastní jedinečné PID.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'PID se procesu přidělí při spuštění a po jeho skončení může být použito znovu pro jiný proces.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.006', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jak se nazývá program běžící na pozadí bez přímé interakce s uživatelem, který obsluhuje nějakou službu?', 'options' => ['démon (daemon)', 'ovladač', 'kernel', 'shell'], 'answer' => 'démon (daemon)', 'tolerance' => null, 'accept' => [], 'explain' => 'Démoni běží na pozadí a obsluhují služby, například webový server.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.007', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Kterým příkazem spravuješ služby (spuštění, zastavení, stav) v systémech se systemd?', 'options' => ['systemctl', 'service', 'ps', 'top'], 'answer' => 'systemctl', 'tolerance' => null, 'accept' => [], 'explain' => 'systemctl je hlavní nástroj pro ovládání služeb pod systemd.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.008', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jaký příkaz spustí systemd službu s názvem priklad.service?', 'options' => ['systemctl start priklad.service', 'systemctl on priklad.service', 'systemctl run priklad.service', 'systemctl boot priklad.service'], 'answer' => 'systemctl start priklad.service', 'tolerance' => null, 'accept' => [], 'explain' => 'Podpříkaz start okamžitě spustí zadanou službu.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.009', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jaký příkaz zastaví systemd službu s názvem priklad.service?', 'options' => ['systemctl stop priklad.service', 'systemctl kill priklad.service', 'systemctl end priklad.service', 'systemctl off priklad.service'], 'answer' => 'systemctl stop priklad.service', 'tolerance' => null, 'accept' => [], 'explain' => 'Podpříkaz stop běžící službu řízeně zastaví.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.010', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Příkaz systemctl status ukáže, jestli služba běží, a poslední řádky jejího výstupu.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'status je základní diagnostický pohled na stav služby.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.011', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Jaký je rozdíl mezi systemctl start a systemctl enable u služby?', 'options' => ['start spustí službu hned, enable zajistí spuštění i po dalším startu systému', 'jsou to dva různé názvy pro úplně totéž', 'enable službu jen dočasně pozastaví', 'start funguje jen jednou za den'], 'answer' => 'start spustí službu hned, enable zajistí spuštění i po dalším startu systému', 'tolerance' => null, 'accept' => [], 'explain' => 'enable nastavuje automatické spuštění při startu, samo o sobě službu hned nespouští.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.012', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Jak přesuneš právě běžící příkaz v terminálu na pozadí, aby ses mohl vrátit k příkazové řádce?', 'options' => ['stiskneš Ctrl+Z a pak zadáš bg', 'vypneš terminál', 'stiskneš Ctrl+C', 'zadáš příkaz sleep'], 'answer' => 'stiskneš Ctrl+Z a pak zadáš bg', 'tolerance' => null, 'accept' => [], 'explain' => 'Ctrl+Z proces pozastaví, bg ho pak nechá pokračovat na pozadí.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.013', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co obvykle udělá klávesová zkratka Ctrl+C v terminálu?', 'options' => ['pošle běžícímu procesu signál k ukončení', 'zkopíruje vybraný text', 'otevře nový terminál', 'uloží aktuální soubor'], 'answer' => 'pošle běžícímu procesu signál k ukončení', 'tolerance' => null, 'accept' => [], 'explain' => 'V terminálu Ctrl+C většinou přeruší běžící příkaz, nekopíruje text.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.014', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Který příkaz vypíše seznam úloh běžících na pozadí v aktuálním terminálu?', 'options' => ['jobs', 'ps aux', 'top', 'history'], 'answer' => 'jobs', 'tolerance' => null, 'accept' => [], 'explain' => 'jobs ukáže úlohy spuštěné z aktuálního terminálu, pozastavené i běžící na pozadí.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.015', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Proces může mít rodičovský proces, který ho spustil, a sám může mít další podřízené procesy.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Procesy v Linuxu tvoří stromovou hierarchii rodič–potomek.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.016', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Který příkaz prohlédne systémové logy spravované pomocí systemd?', 'options' => ['journalctl', 'cat /var/log', 'tail', 'less'], 'answer' => 'journalctl', 'tolerance' => null, 'accept' => [], 'explain' => 'journalctl čte centrální log systemd (journal).', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.017', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dva z uvedených jsou platné podpříkazy systemctl pro práci se službou?', 'options' => ['restart', 'status', 'delete', 'format'], 'answer' => ['restart', 'status'], 'tolerance' => null, 'accept' => [], 'explain' => 'restart a status jsou běžné podpříkazy systemctl, delete a format nejsou.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.018', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená, když je proces ve stavu „spí“ (sleeping)?', 'options' => ['čeká na nějakou událost nebo zdroj a momentálně nevyužívá procesor', 'je nenávratně poškozený', 'skončil s chybou', 'byl smazán ze systému'], 'answer' => 'čeká na nějakou událost nebo zdroj a momentálně nevyužívá procesor', 'tolerance' => null, 'accept' => [], 'explain' => 'Spící proces jen čeká, například na vstup nebo data ze sítě.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.019', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Pokud proces neodpovídá na běžný signál k ukončení, existuje silnější signál, který ho ukončí okamžitě (kill -9).', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Signál SIGKILL proces ukončí okamžitě, bez možnosti si nejdřív uklidit.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.020', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je vhodné před vynuceným ukončením procesu zkusit nejdřív běžné ukončení?', 'options' => ['běžné ukončení dá procesu šanci si bezpečně uklidit rozdělanou práci', 'vynucené ukončení je vždy rychlejší', 'kill -9 nefunguje na běžících procesech', 'není v tom žádný rozdíl'], 'answer' => 'běžné ukončení dá procesu šanci si bezpečně uklidit rozdělanou práci', 'tolerance' => null, 'accept' => [], 'explain' => 'Běžný signál lze zachytit a doprovodit uložením rozdělané práce, vynucený ne.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.021', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 3, 'type' => 'order', 'prompt' => 'Seřaď od prvního k poslednímu kroku, jak zkontrolovat a restartovat nefunkční službu přes systemd.', 'options' => [], 'answer' => ['zjisti stav služby (systemctl status)', 'prohlédni poslední záznamy v logu (journalctl)', 'restartuj službu (systemctl restart)', 'znovu ověř stav služby (systemctl status)'], 'tolerance' => null, 'accept' => [], 'explain' => 'Nejdřív diagnóza, pak zásah a nakonec ověření, že zásah pomohl.', 'time_s' => 42, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.022', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proces se stane takzvaným zombie procesem, když:', 'options' => ['už skončil, ale rodičovský proces si ještě nevyzvedl jeho návratový stav', 'spotřebuje příliš mnoho paměti', 'běží déle než 24 hodin', 'je spuštěný pod účtem root'], 'answer' => 'už skončil, ale rodičovský proces si ještě nevyzvedl jeho návratový stav', 'tolerance' => null, 'accept' => [], 'explain' => 'Zombie proces jen čeká, až si rodič vyzvedne jeho výsledek a uvolní záznam.', 'time_s' => 40, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.023', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'Příkaz systemctl enable sám o sobě službu ihned nespustí, jen zajistí její spuštění při příštím startu systému.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Pro okamžité spuštění je potřeba k enable přidat ještě start.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.procs.024', 'line' => 'networks', 'classes' => null, 'category' => 'procs', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč je užitečné nastavit službě v systemd automatický restart při pádu?', 'options' => ['služba se sama obnoví bez zásahu člověka a zkrátí se výpadek', 'zrychlí to spuštění celého systému', 'sníží to nároky na paměť', 'zabrání to jakékoli budoucí chybě ve službě'], 'answer' => 'služba se sama obnoví bez zásahu člověka a zkrátí se výpadek', 'tolerance' => null, 'accept' => [], 'explain' => 'Automatický restart zmenší dopad krátkodobého pádu služby.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
];
