<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, síťová linie: soubory a práva (kategorie „files“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_net.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'net.files.001', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená první znak „d“ na začátku řádku ve výpisu ls -l?', 'options' => ['jde o složku (adresář)', 'jde o skrytý soubor', 'soubor je spustitelný', 'soubor je symbolický odkaz'], 'answer' => 'jde o složku (adresář)', 'tolerance' => null, 'accept' => [], 'explain' => 'Písmeno d na první pozici označuje adresář, pomlčka běžný soubor, l symbolický odkaz.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.002', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená pomlčka „-“ na první pozici ve výpisu ls -l?', 'options' => ['jde o obyčejný soubor', 'jde o složku', 'soubor je poškozený', 'soubor nemá žádná práva'], 'answer' => 'jde o obyčejný soubor', 'tolerance' => null, 'accept' => [], 'explain' => 'Pomlčka na první pozici znamená běžný soubor, ne složku ani odkaz.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.003', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Práva k souborům a složkám v Linuxu se dělí na tři skupiny. Které to jsou?', 'options' => ['vlastník, skupina, ostatní', 'čtení, zápis, spuštění', 'uživatel, root, host', 'soubor, složka, odkaz'], 'answer' => 'vlastník, skupina, ostatní', 'tolerance' => null, 'accept' => [], 'explain' => 'Práva se nastavují zvlášť pro vlastníka, jeho skupinu a všechny ostatní.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.004', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Které tři základní úrovně oprávnění existují pro každou ze skupin vlastník/skupina/ostatní?', 'options' => ['čtení, zápis, spuštění', 'vytvoření, přesun, smazání', 'sdílení, uzamčení, export', 'přihlášení, odhlášení, restart'], 'answer' => 'čtení, zápis, spuštění', 'tolerance' => null, 'accept' => [], 'explain' => 'Pro každou skupinu se zvlášť povoluje čtení, zápis a spuštění.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.005', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který příkaz změní práva k souboru?', 'options' => ['chmod', 'chown', 'chgrp', 'stat'], 'answer' => 'chmod', 'tolerance' => null, 'accept' => [], 'explain' => 'chmod (change mode) mění práva; chown vlastníka, chgrp skupinu.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.006', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který příkaz změní vlastníka souboru?', 'options' => ['chown', 'chmod', 'chgrp', 'ls'], 'answer' => 'chown', 'tolerance' => null, 'accept' => [], 'explain' => 'chown (change owner) přiřadí soubor jinému uživateli.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.007', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Cesta /home/zak/dokumenty je příklad absolutní cesty, protože začíná lomítkem od kořene souborového systému.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Absolutní cesta vždy začíná od kořene /, relativní cesta vychází z aktuální složky.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.008', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Dvě tečky (..) v souborovém systému Linuxu odkazují na rodičovskou (nadřazenou) složku.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Jedna tečka (.) znamená aktuální složku, dvě tečky (..) složku o úroveň výš.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.009', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jak se značí kořenová (nejvyšší) složka celého souborového systému v Linuxu?', 'options' => ['/', 'home', 'root', 'boot'], 'answer' => '/', 'tolerance' => null, 'accept' => [], 'explain' => 'Kořenová složka se v Linuxu značí jediným lomítkem.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.010', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Symbolický odkaz (symlink) v Linuxu funguje podobně jako:', 'options' => ['zástupce (zkratka) na jiný soubor nebo složku', 'komprimovaný archiv', 'záložní kopie souboru', 'skrytý soubor'], 'answer' => 'zástupce (zkratka) na jiný soubor nebo složku', 'tolerance' => null, 'accept' => [], 'explain' => 'Symlink neobsahuje data, jen ukazuje na cestu k jinému souboru.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.011', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 2, 'type' => 'numeric', 'prompt' => 'Práva rw- odpovídají součtu čtení (4) a zápisu (2), bez spuštění (1). Jaké číslo to v zápisu chmod je?', 'options' => [], 'answer' => 6, 'tolerance' => 0, 'accept' => [], 'explain' => '4 + 2 = 6, tedy čtení a zápis bez spuštění.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.012', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 2, 'type' => 'numeric', 'prompt' => 'Práva rwx odpovídají součtu čtení (4), zápisu (2) a spuštění (1). Jaké číslo to v zápisu chmod je?', 'options' => [], 'answer' => 7, 'tolerance' => 0, 'accept' => [], 'explain' => '4 + 2 + 1 = 7, tedy plná práva čtení, zápisu i spuštění.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.013', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 2, 'type' => 'numeric', 'prompt' => 'Práva r-x odpovídají součtu čtení (4) a spuštění (1), bez zápisu (2). Jaké číslo to v zápisu chmod je?', 'options' => [], 'answer' => 5, 'tolerance' => 0, 'accept' => [], 'explain' => '4 + 1 = 5, tedy čtení a spuštění bez zápisu.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.014', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co vyjadřuje zápis práv chmod 755 pro spustitelný skript?', 'options' => ['vlastník má vše, skupina i ostatní jen čtení a spuštění', 'všichni mají jen právo číst', 'nikdo nemá žádná práva', 'jen vlastník smí soubor vidět'], 'answer' => 'vlastník má vše, skupina i ostatní jen čtení a spuštění', 'tolerance' => null, 'accept' => [], 'explain' => '7 = rwx pro vlastníka, 5 = r-x pro skupinu i ostatní.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.015', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je někdy potřeba přidat spustitelné právo (chmod +x) k nově staženému skriptu?', 'options' => ['bez práva na spuštění systém odmítne skript spustit jako program', 'jinak skript nejde otevřít v editoru', 'jinak skript nejde smazat', 'jinak skript zabírá víc místa na disku'], 'answer' => 'bez práva na spuštění systém odmítne skript spustit jako program', 'tolerance' => null, 'accept' => [], 'explain' => 'Ke spuštění souboru jako programu je potřeba právo x, nestačí ho jen umět přečíst.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.016', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Práva 644 dovolují komukoli soubor spustit jako program.', 'options' => [], 'answer' => false, 'tolerance' => null, 'accept' => [], 'explain' => '644 = čtení a zápis vlastníkovi, jen čtení ostatním – chybí právo na spuštění.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.017', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dva příkazy vypíšou podrobné informace o souboru včetně jeho práv?', 'options' => ['ls -l', 'stat', 'cat', 'pwd'], 'answer' => ['ls -l', 'stat'], 'tolerance' => null, 'accept' => [], 'explain' => 'ls -l vypíše práva u každého řádku výpisu, stat zobrazí ještě podrobnější údaje o jednom souboru.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.018', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Právo číst soubor uvnitř složky nikdy neovlivní právo vstoupit do dané složky – jsou na sobě úplně nezávislá.', 'options' => [], 'answer' => false, 'tolerance' => null, 'accept' => [], 'explain' => 'Bez práva vstupu (spuštění) do složky se k souboru uvnitř nedostaneš, i kdyby měl čtení povolené.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.019', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co se stane, když k souboru jiného vlastníka nemáš žádná práva?', 'options' => ['zůstane pro tebe nečitelný a nezapisovatelný, dokud ti vlastník práva nepřidá', 'soubor automaticky zmizí', 'soubor se ti zkopíruje do domovské složky', 'systém tě automaticky nastaví jako vlastníka'], 'answer' => 'zůstane pro tebe nečitelný a nezapisovatelný, dokud ti vlastník práva nepřidá', 'tolerance' => null, 'accept' => [], 'explain' => 'Bez patřičného oprávnění systém přístup k souboru odmítne.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.020', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Který příkaz změní skupinu, ke které soubor patří?', 'options' => ['chgrp', 'chmod', 'chown', 'groups'], 'answer' => 'chgrp', 'tolerance' => null, 'accept' => [], 'explain' => 'chgrp (change group) přiřadí soubor jiné skupině.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.021', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 3, 'type' => 'numeric', 'prompt' => 'Kolik různých kombinací čtení/zápisu/spuštění lze zapsat jedním osmičkovým číslem 0 až 7 pro jednu skupinu práv?', 'options' => [], 'answer' => 8, 'tolerance' => 0, 'accept' => [], 'explain' => 'Tři nezávislé bity dávají 2 na třetí, tedy 8 kombinací od 0 do 7.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.022', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Skript má práva rwxr--r-- (chmod 744). Může ho spustit uživatel, který je jen ve skupině vlastníka souboru?', 'options' => ['ne, skupina má jen právo čtení, ne spuštění', 'ano, spuštění mají všichni', 'ano, ale jen jednou denně', 'ne, protože skript nejde spustit vůbec'], 'answer' => 'ne, skupina má jen právo čtení, ne spuštění', 'tolerance' => null, 'accept' => [], 'explain' => '744 dává skupině i ostatním jen čtení (4), spuštění má pouze vlastník.', 'time_s' => 40, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.023', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'Symbolický odkaz (symlink) přestane fungovat, pokud se smaže původní soubor, zatímco pevný odkaz (hard link) dál ukazuje na stejná data na disku.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Hard link sdílí přímo data na disku, symlink je jen odkaz na cestu k původnímu souboru.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.files.024', 'line' => 'networks', 'classes' => null, 'category' => 'files', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč se doporučuje neprovádět běžnou práci pod účtem root, i když by to bylo pohodlnější?', 'options' => ['omyl nebo škodlivý program by mohl bez omezení změnit či smazat cokoli v systému', 'účet root je pomalejší než běžný účet', 'root nemůže instalovat programy', 'root nemá přístup k internetu'], 'answer' => 'omyl nebo škodlivý program by mohl bez omezení změnit či smazat cokoli v systému', 'tolerance' => null, 'accept' => [], 'explain' => 'Běžný účet s omezenými právy sníží škodu při chybě nebo útoku.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
];
