<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, grafická linie: rastr, vektor a formáty (kategorie „formats“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_gfx.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'gfx.formats.001', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jaký typ grafiky je složený z pixelů uspořádaných do mřížky, například fotografie?', 'options' => ['rastrová (bitmapová) grafika', 'vektorová grafika', 'textová grafika', 'zvuková stopa'], 'answer' => 'rastrová (bitmapová) grafika', 'tolerance' => null, 'accept' => [], 'explain' => 'Rastr ukládá obraz jako mřížku barevných bodů (pixelů).', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.002', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jaký typ grafiky je popsaný matematickými křivkami a tvary místo pixelů?', 'options' => ['vektorová grafika', 'rastrová grafika', 'zvukový soubor', 'textový dokument'], 'answer' => 'vektorová grafika', 'tolerance' => null, 'accept' => [], 'explain' => 'Vektor popisuje tvary matematicky, ne jako pevnou mřížku bodů.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.003', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Vektorová grafika, například SVG, se při zvětšení nerozmazává.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Vektor se dá škálovat na libovolnou velikost beze ztráty ostrosti.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.004', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Rastrová fotografie se při velkém zvětšení může rozpixelovat a ztratit ostrost.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Rastr má pevný počet pixelů, které se zvětšením zvětší také.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.005', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který formát je nejvhodnější pro fotografii s plynulými přechody barev?', 'options' => ['JPEG', 'SVG', 'ICO', 'GIF (256 barev)'], 'answer' => 'JPEG', 'tolerance' => null, 'accept' => [], 'explain' => 'JPEG zvládá ztrátovou kompresi fotografií s bohatou škálou barev.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.006', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který formát je vektorový a často se používá pro loga a ikony?', 'options' => ['SVG', 'JPEG', 'PNG', 'GIF'], 'answer' => 'SVG', 'tolerance' => null, 'accept' => [], 'explain' => 'SVG je vektorový formát vhodný pro ostré tvary jako loga.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.007', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který z uvedených formátů podporuje průhlednost (alfa kanál) a hodí se pro grafiku s ostrými hranami?', 'options' => ['PNG', 'JPEG', 'MP3', 'DOCX'], 'answer' => 'PNG', 'tolerance' => null, 'accept' => [], 'explain' => 'PNG podporuje plynulou průhlednost díky alfa kanálu.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.008', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Formát JPEG podporuje průhledné pozadí stejně dobře jako PNG.', 'options' => [], 'answer' => false, 'tolerance' => null, 'accept' => [], 'explain' => 'JPEG průhlednost nepodporuje vůbec, na rozdíl od PNG.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.009', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 1, 'type' => 'numeric', 'prompt' => 'Kolik barev nejvýše najednou dokáže zobrazit klasický formát GIF?', 'options' => [], 'answer' => 256, 'tolerance' => 0, 'accept' => [], 'explain' => 'Klasický GIF používá paletu nejvýše 256 barev (8 bitů).', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.010', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co umí navíc formát GIF oproti JPEG a klasickému PNG?', 'options' => ['jednoduchou animaci, tedy několik snímků za sebou', 'ukládat vektorové tvary', '3D model', 'zvukovou stopu'], 'answer' => 'jednoduchou animaci, tedy několik snímků za sebou', 'tolerance' => null, 'accept' => [], 'explain' => 'GIF umí uložit sekvenci snímků a přehrávat je jako krátkou animaci.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.011', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená ztrátová komprese, kterou používá JPEG?', 'options' => ['část obrazových dat se nenávratně zjednoduší kvůli menší velikosti souboru', 'soubor se zvětší, aby vypadal lépe', 'obrázek se automaticky převede na vektor', 'komprese, která nikdy nesníží kvalitu'], 'answer' => 'část obrazových dat se nenávratně zjednoduší kvůli menší velikosti souboru', 'tolerance' => null, 'accept' => [], 'explain' => 'Ztrátová komprese obětuje část detailů výměnou za menší soubor.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.012', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená bezztrátová komprese, kterou používá například PNG?', 'options' => ['soubor se zmenší, ale po rozbalení jsou data identická s originálem', 'obrázek se vždy zvětší', 'část detailů se nenávratně ztratí', 'komprese funguje jen na text'], 'answer' => 'soubor se zmenší, ale po rozbalení jsou data identická s originálem', 'tolerance' => null, 'accept' => [], 'explain' => 'Bezztrátová komprese umožní přesnou rekonstrukci původních dat.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.013', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co je formát WebP?', 'options' => ['modernější formát, který umí ztrátovou i bezztrátovou kompresi a průhlednost', 'starší název pro JPEG', 'typ webové kamery', 'formát jen pro zvuk'], 'answer' => 'modernější formát, který umí ztrátovou i bezztrátovou kompresi a průhlednost', 'tolerance' => null, 'accept' => [], 'explain' => 'WebP kombinuje výhody více starších formátů v jednom.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.014', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Vektorový soubor, například SVG, obvykle nejde použít jako fotografii s realistickými přechody barev tak dobře jako rastrový formát.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Vektor je určený spíš pro tvary a plochy, ne miliony jemných barevných odstínů.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.015', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč se ikony a loga na webu často připravují jako SVG, spíš než jako velký PNG?', 'options' => ['SVG zůstane ostré na jakékoli velikosti a bývá menší', 'SVG se nedá zobrazit v prohlížeči', 'PNG je vždy menší než SVG', 'SVG nepodporuje barvy'], 'answer' => 'SVG zůstane ostré na jakékoli velikosti a bývá menší', 'tolerance' => null, 'accept' => [], 'explain' => 'Vektor škáluje beze ztráty a jeho popis bývá úsporný.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.016', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená rozlišení obrázku, například zápis 1920×1080?', 'options' => ['počet pixelů na šířku a výšku obrázku', 'počet barev v obrázku', 'velikost souboru v megabajtech', 'rychlost načítání stránky'], 'answer' => 'počet pixelů na šířku a výšku obrázku', 'tolerance' => null, 'accept' => [], 'explain' => 'Rozlišení udává rozměr rastrového obrázku v pixelech.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.017', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dva z uvedených formátů jsou rastrové (bitmapové)?', 'options' => ['JPEG', 'PNG', 'SVG', 'DOCX'], 'answer' => ['JPEG', 'PNG'], 'tolerance' => null, 'accept' => [], 'explain' => 'JPEG a PNG ukládají obraz jako mřížku pixelů, SVG je vektorový a DOCX je textový dokument.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.018', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč se fotografie z fotoaparátu obvykle neukládají jako SVG?', 'options' => ['SVG je určený pro tvary a křivky, ne pro miliony jemných barevných přechodů', 'SVG soubory jsou vždy největší ze všech', 'fotoaparáty neumí ukládat žádné soubory', 'SVG nejde otevřít v žádném prohlížeči'], 'answer' => 'SVG je určený pro tvary a křivky, ne pro miliony jemných barevných přechodů', 'tolerance' => null, 'accept' => [], 'explain' => 'Popis fotografie křivkami by byl nepraktický a neefektivní.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.019', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Vyšší míra ztrátové komprese u JPEG obvykle zmenší soubor, ale může přinést viditelné artefakty, například bloky v obraze.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Silná komprese ukládá míň detailů, což se může projevit jako viditelné vady.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.020', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je DPI (počet bodů na palec) důležité hlavně při přípravě obrázku pro tisk?', 'options' => ['nízké DPI může vytištěný obrázek udělat rozmazaný nebo kostičkovaný', 'DPI ovlivňuje jen barvy obrázku', 'DPI se týká výhradně webových stránek', 'DPI mění formát souboru na vektorový'], 'answer' => 'nízké DPI může vytištěný obrázek udělat rozmazaný nebo kostičkovaný', 'tolerance' => null, 'accept' => [], 'explain' => 'Nízká hustota bodů na tiskové ploše se projeví jako horší kvalita tisku.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.021', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč může mít zvětšený výřez fotografie viditelně nižší kvalitu, i když originál vypadal ostře?', 'options' => ['zvětšením se zvětší i jednotlivé pixely, kterých je jen pevný, omezený počet', 'formát fotografie se tím automaticky změní na vektor', 'zvětšení vždy zlepší ostrost obrazu', 'to se stává jen u formátu SVG'], 'answer' => 'zvětšením se zvětší i jednotlivé pixely, kterých je jen pevný, omezený počet', 'tolerance' => null, 'accept' => [], 'explain' => 'Výřez má stejný počet pixelů jako v originálu, jen zvětšený na větší plochu.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.022', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'Formát PNG se dnes běžně používá i pro snímky obrazovky a grafiku s ostrým textem, protože bezztrátová komprese zachová ostré hrany písmen.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Bezztrátová komprese neničí ostré hrany, což se u textu a UI hodí.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.023', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč může být pro web výhodnější použít modernější formát, například WebP, místo staršího JPEG u stejné fotografie?', 'options' => ['při podobné viditelné kvalitě může mít výrazně menší velikost souboru', 'WebP je jediný formát, který prohlížeče vůbec podporují', 'WebP vždy vypadá hůř než JPEG', 'JPEG neumí zobrazit barevné fotografie'], 'answer' => 'při podobné viditelné kvalitě může mít výrazně menší velikost souboru', 'tolerance' => null, 'accept' => [], 'explain' => 'Menší soubor znamená rychlejší načtení stránky při srovnatelné kvalitě.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.formats.024', 'line' => 'graphics', 'classes' => null, 'category' => 'formats', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Ikona se má zobrazovat od velikosti 16×16 pixelů až po velký billboard. Který přístup dává největší smysl?', 'options' => ['připravit ji jako vektor (SVG), který škáluje beze ztráty ostrosti', 'připravit jen jeden velký JPEG a zmenšovat ho podle potřeby', 'použít GIF kvůli animaci', 'ikona v tak rozdílných velikostech stejně nejde použít'], 'answer' => 'připravit ji jako vektor (SVG), který škáluje beze ztráty ostrosti', 'tolerance' => null, 'accept' => [], 'explain' => 'Vektor se přizpůsobí libovolné velikosti bez ztráty kvality.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
];
