<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, grafická linie: CSS (kategorie „css“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_gfx.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'gfx.css.001', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'V CSS box modelu, co obklopuje obsah (content) prvku jako první vrstva směrem ven?', 'options' => ['padding (vnitřní odsazení)', 'margin (vnější odsazení)', 'border (okraj)', 'pozadí obrázku'], 'answer' => 'padding (vnitřní odsazení)', 'tolerance' => null, 'accept' => [], 'explain' => 'Padding je mezera mezi obsahem a okrajem prvku.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.002', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Která vrstva CSS box modelu je nejvíc vně, za okrajem (border)?', 'options' => ['margin (vnější odsazení)', 'padding (vnitřní odsazení)', 'content (obsah)', 'žádná, border je poslední'], 'answer' => 'margin (vnější odsazení)', 'tolerance' => null, 'accept' => [], 'explain' => 'Margin odděluje prvek od jeho sousedů.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.003', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 1, 'type' => 'order', 'prompt' => 'Seřaď vrstvy CSS box modelu od obsahu (uvnitř) směrem ven.', 'options' => [], 'answer' => ['content (obsah)', 'padding (vnitřní odsazení)', 'border (okraj)', 'margin (vnější odsazení)'], 'tolerance' => null, 'accept' => [], 'explain' => 'Pořadí vrstev box modelu je vždy obsah, padding, border, margin.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.004', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Margin vytváří mezeru mezi prvkem a jeho sousedy, zatímco padding je mezera uvnitř prvku kolem jeho obsahu.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Margin působí vně prvku, padding uvnitř kolem obsahu.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.005', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jak zapíšeš v CSS selektor pro všechny prvky s třídou „karta“?', 'options' => ['.karta', '#karta', 'karta', '*karta'], 'answer' => '.karta', 'tolerance' => null, 'accept' => [], 'explain' => 'Tečka před jménem označuje selektor podle třídy (class).', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.006', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jak zapíšeš v CSS selektor pro prvek s jedinečným id „hlavicka“?', 'options' => ['#hlavicka', '.hlavicka', 'hlavicka', '@hlavicka'], 'answer' => '#hlavicka', 'tolerance' => null, 'accept' => [], 'explain' => 'Mřížka před jménem označuje selektor podle id.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.007', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Kterou vlastností CSS rozmístíš prvky v řádku vedle sebe pružně pomocí flexboxu?', 'options' => ['display: flex', 'display: none', 'position: fixed', 'color: red'], 'answer' => 'display: flex', 'tolerance' => null, 'accept' => [], 'explain' => 'display: flex zapíná flexbox layout pro přímé potomky prvku.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.008', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Vlastnost display: none prvek úplně skryje a nezabírá po něm ani místo v layoutu.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'display: none prvek zcela odstraní z vykresleného layoutu.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.009', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Která jednotka CSS je pevná a nemění se podle velikosti nadřazeného písma?', 'options' => ['px (pixel)', 'em', 'rem', '%'], 'answer' => 'px (pixel)', 'tolerance' => null, 'accept' => [], 'explain' => 'px je absolutní jednotka, na rozdíl od relativních em, rem a %.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.010', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který CSS selektor vybere prvek podle stavu, například při najetí myší?', 'options' => [':hover', ':first-child', '.trida', '#id'], 'answer' => ':hover', 'tolerance' => null, 'accept' => [], 'explain' => ':hover je pseudotřída reagující na najetí kurzoru myši.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.011', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co dělá vlastnost justify-content ve flexboxu?', 'options' => ['rozmisťuje prvky podél hlavní osy kontejneru, například na střed nebo od sebe', 'mění barvu textu', 'nastavuje výšku řádku', 'vytváří mřížku sloupců a řádků'], 'answer' => 'rozmisťuje prvky podél hlavní osy kontejneru, například na střed nebo od sebe', 'tolerance' => null, 'accept' => [], 'explain' => 'justify-content řídí rozložení podél hlavní osy flex kontejneru.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.012', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co dělá vlastnost align-items ve flexboxu?', 'options' => ['zarovnává prvky napříč vedlejší osou kontejneru, například nahoru nebo na střed', 'mění velikost písma', 'řadí prvky abecedně', 'nastavuje barvu pozadí'], 'answer' => 'zarovnává prvky napříč vedlejší osou kontejneru, například nahoru nebo na střed', 'tolerance' => null, 'accept' => [], 'explain' => 'align-items řeší zarovnání kolmo na hlavní osu flexboxu.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.013', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co ovlivňuje vlastnost flex-direction?', 'options' => ['zda jsou prvky flex kontejneru řazené v řádku, nebo ve sloupci', 'barvu prvků', 'velikost fontu', 'počet sloupců mřížky'], 'answer' => 'zda jsou prvky flex kontejneru řazené v řádku, nebo ve sloupci', 'tolerance' => null, 'accept' => [], 'explain' => 'flex-direction určuje hlavní osu, podél které se prvky řadí.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.014', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'K čemu slouží CSS grid, tedy vlastnost display: grid?', 'options' => ['k rozložení prvků do dvourozměrné mřížky řádků a sloupců', 'k animaci textu', 'ke změně barvy odkazů', 'k načtení externího souboru'], 'answer' => 'k rozložení prvků do dvourozměrné mřížky řádků a sloupců', 'tolerance' => null, 'accept' => [], 'explain' => 'Grid layout pracuje zároveň s řádky i sloupci.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.015', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Flexbox je vhodný hlavně pro rozložení v jednom směru, zatímco grid umí řešit rozložení v obou směrech najednou.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Grid pracuje s řádky i sloupci současně, flexbox typicky jen s jednou osou.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.016', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená jednotka rem v CSS?', 'options' => ['velikost relativní k velikosti písma kořenového elementu (html)', 'pevná velikost v milimetrech', 'procento šířky rodičovského prvku', 'vždy stejná hodnota jako px'], 'answer' => 'velikost relativní k velikosti písma kořenového elementu (html)', 'tolerance' => null, 'accept' => [], 'explain' => 'rem = root em, počítá se vždy od kořenového elementu, ne od rodiče.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.017', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Jaký CSS selektor vybere odkazy <a> jen uvnitř prvku s třídou „menu“?', 'options' => ['.menu a', 'a.menu', '.menu > .a', 'a:menu'], 'answer' => '.menu a', 'tolerance' => null, 'accept' => [], 'explain' => 'Mezera mezi selektory znamená potomka kdekoli uvnitř.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.018', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dvě z uvedených jsou platné hodnoty vlastnosti display v CSS?', 'options' => ['flex', 'grid', 'left', 'underline'], 'answer' => ['flex', 'grid'], 'tolerance' => null, 'accept' => [], 'explain' => 'flex a grid jsou hodnoty display, left a underline patří jinam.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.019', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč se často nastavuje box-sizing: border-box na prvky stránky?', 'options' => ['šířka a výška prvku pak zahrnují i padding a border, což usnadní výpočty', 'zrychlí to načítání stránky', 'změní to barvu pozadí', 'zruší to potřebu marginu'], 'answer' => 'šířka a výška prvku pak zahrnují i padding a border, což usnadní výpočty', 'tolerance' => null, 'accept' => [], 'explain' => 'border-box zjednoduší plánování rozměrů prvků v layoutu.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.020', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co zjednodušeně znamená specificita CSS selektorů?', 'options' => ['pravidlo, které určuje, který styl „vyhraje“, když se na prvek vztahuje víc pravidel', 'rychlost, jakou se CSS soubor stáhne', 'počet barev použitých ve stylu', 'jak dlouho je selektor napsaný'], 'answer' => 'pravidlo, které určuje, který styl „vyhraje“, když se na prvek vztahuje víc pravidel', 'tolerance' => null, 'accept' => [], 'explain' => 'Specificita rozhoduje mezi konfliktními pravidly stejné důležitosti.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.021', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Selektor id má obvykle vyšší specificitu než selektor třídy. Co to v praxi znamená při konfliktu dvou pravidel?', 'options' => ['pravidlo s id selektorem obvykle přebije pravidlo zapsané jen přes třídu', 'třída vždy přebije id', 'specificita nemá na výsledný styl žádný vliv', 'prohlížeč náhodně vybere jedno z pravidel'], 'answer' => 'pravidlo s id selektorem obvykle přebije pravidlo zapsané jen přes třídu', 'tolerance' => null, 'accept' => [], 'explain' => 'Vyšší specificita selektoru rozhoduje při stejné důležitosti pravidel.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.022', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'Prvek s display: flex uspořádá své přímé potomky do flexboxu, ale sám o sobě nemění chování jejich vlastních vnořených potomků.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Flex layout se týká jen vztahu kontejneru a jeho přímých dětí.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.023', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Tři karty ve flex kontejneru mají mít stejnou mezeru mezi sebou i po stranách bez ručního počítání marginů. Která vlastnost to řeší nejpřímočařeji?', 'options' => ['gap (mezera mezi flex nebo grid prvky)', 'color', 'font-weight', 'text-align'], 'answer' => 'gap (mezera mezi flex nebo grid prvky)', 'tolerance' => null, 'accept' => [], 'explain' => 'Vlastnost gap přidá jednotnou mezeru mezi položkami bez řešení marginů.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.css.024', 'line' => 'graphics', 'classes' => null, 'category' => 'css', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč responzivní návrh často kombinuje relativní jednotky (%, rem) s pevnými jen tam, kde to dává smysl, například u tenkého 1px okraje?', 'options' => ['relativní jednotky se lépe přizpůsobí různým velikostem obrazovky a nastavení uživatele', 'pevné jednotky prohlížeče vůbec nepodporují', 'relativní jednotky jsou vždy rychlejší na výpočet', 'CSS bez pevných jednotek nejde vůbec napsat'], 'answer' => 'relativní jednotky se lépe přizpůsobí různým velikostem obrazovky a nastavení uživatele', 'tolerance' => null, 'accept' => [], 'explain' => 'Kombinace jednotek dá layoutu flexibilitu i tam, kde je potřeba přesnost.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
];
