<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, grafická linie: HTML sémantika (kategorie „html“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_gfx.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'gfx.html.001', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který element HTML se používá pro hlavní obsah stránky, obvykle jen jednou na stránku?', 'options' => ['<main>', '<div>', '<span>', '<footer>'], 'answer' => '<main>', 'tolerance' => null, 'accept' => [], 'explain' => '<main> označuje hlavní jedinečný obsah stránky.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.002', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který element HTML typicky obsahuje navigační odkazy webu?', 'options' => ['<nav>', '<main>', '<aside>', '<table>'], 'answer' => '<nav>', 'tolerance' => null, 'accept' => [], 'explain' => '<nav> je určený pro hlavní navigační odkazy.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.003', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který element HTML se používá pro patičku stránky?', 'options' => ['<footer>', '<header>', '<nav>', '<section>'], 'answer' => '<footer>', 'tolerance' => null, 'accept' => [], 'explain' => '<footer> obsahuje typicky kontakty, odkazy a informace na konci stránky.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.004', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který element HTML se používá pro hlavičku stránky nebo sekce, často s logem a nadpisem?', 'options' => ['<header>', '<footer>', '<aside>', '<article>'], 'answer' => '<header>', 'tolerance' => null, 'accept' => [], 'explain' => '<header> uvozuje stránku nebo sekci úvodním obsahem.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.005', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 1, 'type' => 'numeric', 'prompt' => 'Kolik úrovní nadpisů, od h1 po h6, HTML nabízí?', 'options' => [], 'answer' => 6, 'tolerance' => 0, 'accept' => [], 'explain' => 'HTML má šest úrovní nadpisů, od h1 po h6.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.006', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Na jedné stránce by měl být obvykle jen jeden nadpis h1, shrnující hlavní téma stránky.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'h1 by měl reprezentovat hlavní téma celé stránky.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.007', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který element vytvoří v HTML klikací odkaz na jinou stránku?', 'options' => ['<a>', '<link>', '<button>', '<nav>'], 'answer' => '<a>', 'tolerance' => null, 'accept' => [], 'explain' => '<a href="..."> vytváří hypertextový odkaz; <link> se používá třeba pro připojení stylů.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.008', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který pár značek vytvoří neseřazený, odrážkový seznam?', 'options' => ['<ul></ul>', '<ol></ol>', '<table></table>', '<nav></nav>'], 'answer' => '<ul></ul>', 'tolerance' => null, 'accept' => [], 'explain' => 'ul = unordered list, neseřazený seznam s odrážkami.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.009', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který pár značek vytvoří číslovaný seznam?', 'options' => ['<ol></ol>', '<ul></ul>', '<dl></dl>', '<li></li>'], 'answer' => '<ol></ol>', 'tolerance' => null, 'accept' => [], 'explain' => 'ol = ordered list, seznam s automatickým číslováním.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.010', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Každá položka seznamu <li> musí být uvnitř <ul> nebo <ol> (případně <menu>).', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => '<li> dává smysl jen jako položka nějakého seznamu.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.011', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená sémantické HTML?', 'options' => ['používání elementů podle jejich významu, ne jen podle vzhledu', 'psaní HTML jen velkými písmeny', 'HTML úplně bez CSS', 'HTML určené jen pro mobily'], 'answer' => 'používání elementů podle jejich významu, ne jen podle vzhledu', 'tolerance' => null, 'accept' => [], 'explain' => 'Sémantické značky nesou informaci o obsahu, ne jen o vzhledu.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.012', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je lepší použít <button> pro tlačítko než obyčejný <div> se stylem tlačítka?', 'options' => ['<button> je automaticky ovladatelný klávesnicí a čtečkou obrazovky', '<div> se nedá nijak stylovat', '<button> nejde použít společně s CSS', '<div> je vždy rychlejší'], 'answer' => '<button> je automaticky ovladatelný klávesnicí a čtečkou obrazovky', 'tolerance' => null, 'accept' => [], 'explain' => 'Sémantický <button> má vestavěné chování tlačítka bez dalšího kódu.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.013', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co dělá element <article> v sémantickém HTML?', 'options' => ['označuje samostatný, smysluplný celek obsahu, například jeden článek blogu', 'jen mění barvu textu', 'vytváří tabulku', 'nahrazuje element <body>'], 'answer' => 'označuje samostatný, smysluplný celek obsahu, například jeden článek blogu', 'tolerance' => null, 'accept' => [], 'explain' => '<article> by měl dávat smysl i vytržený ze zbytku stránky.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.014', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'K čemu slouží element <aside>?', 'options' => ['pro obsah vedlejší k hlavnímu obsahu, například postranní panel', 'pro hlavní obsah stránky', 'pro navigaci webu', 'pro patičku stránky'], 'answer' => 'pro obsah vedlejší k hlavnímu obsahu, například postranní panel', 'tolerance' => null, 'accept' => [], 'explain' => '<aside> nese obsah doplňkový, ne hlavní.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.015', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Přeskočení úrovně nadpisů, například z h1 rovnou na h4 kvůli menší vizuální velikosti, se nedoporučuje.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Přeskakování úrovní ztěžuje orientaci pomocí struktury nadpisů.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.016', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč formulářové pole potřebuje svázaný element <label>?', 'options' => ['popisuje pole srozumitelně i pro čtečku obrazovky a zvětší klikací plochu', 'label mění barvu pozadí pole', 'label je jen ozdobný text bez funkce', 'label nahrazuje textové pole úplně'], 'answer' => 'popisuje pole srozumitelně i pro čtečku obrazovky a zvětší klikací plochu', 'tolerance' => null, 'accept' => [], 'explain' => 'Kliknutí na label u propojeného pole ho i aktivuje.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.017', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dva z uvedených jsou sémantické strukturální elementy HTML5?', 'options' => ['<section>', '<article>', '<div>', '<span>'], 'answer' => ['<section>', '<article>'], 'tolerance' => null, 'accept' => [], 'explain' => '<div> a <span> jsou obecné, bez vlastního významu.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.018', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co určuje první řádek HTML dokumentu, zápis <!DOCTYPE html>?', 'options' => ['prohlížeči, že jde o dokument v aktuálním standardu HTML5', 'název webové stránky', 'hlavní barvu stránky', 'jazyk stránky'], 'answer' => 'prohlížeči, že jde o dokument v aktuálním standardu HTML5', 'tolerance' => null, 'accept' => [], 'explain' => 'Doctype říká prohlížeči, podle jakých pravidel má stránku vykreslit.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.019', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Jaký je hlavní rozdíl mezi elementem <div> a <span> ve výchozím zobrazení?', 'options' => ['<div> je blokový element, <span> je řádkový (inline)', '<span> je vždy širší než <div>', '<div> nejde stylovat pomocí CSS', 'mezi nimi není žádný rozdíl'], 'answer' => '<div> je blokový element, <span> je řádkový (inline)', 'tolerance' => null, 'accept' => [], 'explain' => 'Blokový element zabere celou šířku řádku, řádkový jen potřebný prostor.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.020', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč se atribut alt u obrázku považuje za součást sémantiky, ne jen vzhledu?', 'options' => ['nese informaci o obsahu obrázku, kterou využije třeba čtečka obrazovky', 'mění velikost obrázku', 'nastavuje barvu pozadí za obrázkem', 'zrychluje načítání internetu'], 'answer' => 'nese informaci o obsahu obrázku, kterou využije třeba čtečka obrazovky', 'tolerance' => null, 'accept' => [], 'explain' => 'alt popisuje obsah, nezávisle na tom, jak obrázek vypadá vizuálně.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.021', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč je nevhodné volit úroveň nadpisu jen podle toho, jak velký nebo tučný má vizuálně být?', 'options' => ['naruší to logickou strukturu stránky, na kterou spoléhají čtečky obrazovky i vyhledávače', 'nadpisy jinak nejdou vůbec zobrazit', 'to je jediný způsob, jak text zvětšit', 'nadpisy nemají na strukturu žádný vliv'], 'answer' => 'naruší to logickou strukturu stránky, na kterou spoléhají čtečky obrazovky i vyhledávače', 'tolerance' => null, 'accept' => [], 'explain' => 'Vzhled by měl řešit CSS, úroveň nadpisu by měla odpovídat struktuře.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.022', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'Stránka poskládaná jen z <div> elementů se stejným vizuálním výsledkem jako sémantické HTML může být pro čtečku obrazovky hůř srozumitelná.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Bez sémantiky čtečka nepozná, co je navigace, hlavní obsah nebo patička.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.023', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Formulářové pole nemá svázaný <label>, jen placeholder text uvnitř pole. V čem to je problém?', 'options' => ['placeholder zmizí, jakmile uživatel začne psát, a nemusí ho přečíst každá čtečka obrazovky', 'placeholder je úplně totéž co label', 'formulář bez labelu se vůbec neodešle', 'placeholder text zpomaluje načítání stránky'], 'answer' => 'placeholder zmizí, jakmile uživatel začne psát, a nemusí ho přečíst každá čtečka obrazovky', 'tolerance' => null, 'accept' => [], 'explain' => 'Placeholder nenahrazuje trvalý, přístupný popisek pole.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.html.024', 'line' => 'graphics', 'classes' => null, 'category' => 'html', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč je vhodné vnořovat sémantické elementy logicky, například <article> uvnitř <section>, podle skutečného vztahu obsahu?', 'options' => ['pomáhá to jak lidem, tak nástrojům pochopit vztahy mezi částmi obsahu', 'jinak by se stránka vůbec nenačetla', 'vnořování elementů je jen estetická záležitost', 'prohlížeče vnořené elementy ignorují'], 'answer' => 'pomáhá to jak lidem, tak nástrojům pochopit vztahy mezi částmi obsahu', 'tolerance' => null, 'accept' => [], 'explain' => 'Logická struktura usnadňuje orientaci i strojové zpracování obsahu.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
];
