<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, grafická linie: barvy a kontrast (kategorie „color“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_gfx.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'gfx.color.001', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který barevný model se používá pro obrazovky a skládá barvy ze světla (červená, zelená, modrá)?', 'options' => ['RGB', 'CMYK', 'škála šedi', 'monochrom'], 'answer' => 'RGB', 'tolerance' => null, 'accept' => [], 'explain' => 'RGB skládá barvy sčítáním světla tří kanálů: červené, zelené a modré.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.002', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který barevný model se typicky používá pro tisk a skládá barvy ze čtyř inkoustů?', 'options' => ['CMYK', 'RGB', 'HSL', 'binární'], 'answer' => 'CMYK', 'tolerance' => null, 'accept' => [], 'explain' => 'CMYK míchá azurovou, purpurovou, žlutou a černou barvu inkoustu.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.003', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Kolik znaků má běžný zápis barvy v hexadecimálním tvaru bez mřížky, například ff9900?', 'options' => ['6', '3', '8', '4'], 'answer' => '6', 'tolerance' => null, 'accept' => [], 'explain' => 'Každý ze tří kanálů RGB se zapisuje dvěma hexadecimálními znaky, dohromady šest.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.004', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Barva #000000 v zápisu RGB hex představuje černou.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Nulová hodnota všech tří kanálů dává černou barvu.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.005', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Barva #ffffff v zápisu RGB hex představuje bílou.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Maximální hodnota všech tří kanálů dává bílou barvu.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.006', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená kontrast barev v souvislosti s čitelností textu?', 'options' => ['rozdíl jasu mezi barvou textu a pozadí', 'počet použitých barev na stránce', 'sytost jedné barvy', 'teplota barvy, studená nebo teplá'], 'answer' => 'rozdíl jasu mezi barvou textu a pozadí', 'tolerance' => null, 'accept' => [], 'explain' => 'Vyšší rozdíl jasu mezi textem a pozadím zlepšuje čitelnost.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.007', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jaký je podle WCAG 2.2 minimální poměr kontrastu pro běžný text na úrovni AA?', 'options' => ['4,5:1', '1:1', '2:1', '10:1'], 'answer' => '4,5:1', 'tolerance' => null, 'accept' => [], 'explain' => 'WCAG 2.2 AA vyžaduje pro běžný text poměr kontrastu aspoň 4,5:1.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.008', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jaký je podle WCAG 2.2 minimální poměr kontrastu pro velký text na úrovni AA?', 'options' => ['3:1', '4,5:1', '1:1', '7:1'], 'answer' => '3:1', 'tolerance' => null, 'accept' => [], 'explain' => 'Velký nebo tučný text má mírnější požadavek, 3:1.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.009', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Světle šedý text na bílém pozadí má vždy dostatečný kontrast.', 'options' => [], 'answer' => false, 'tolerance' => null, 'accept' => [], 'explain' => 'Světle šedá na bílé bývá pod hranicí 4,5:1, je potřeba to změřit.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.010', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co jsou doplňkové (komplementární) barvy na barevném kole?', 'options' => ['barvy ležící naproti sobě, které vytvářejí silný kontrast', 'barvy vedle sebe se stejným odstínem', 'jen odstíny šedé', 'barvy používané výhradně v tisku'], 'answer' => 'barvy ležící naproti sobě, které vytvářejí silný kontrast', 'tolerance' => null, 'accept' => [], 'explain' => 'Komplementární barvy leží na opačných stranách barevného kola.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.011', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co vyjadřuje ve zkratce HSL písmeno L?', 'options' => ['světlost (lightness)', 'odstín (hue)', 'sytost (saturation)', 'vrstvu (layer)'], 'answer' => 'světlost (lightness)', 'tolerance' => null, 'accept' => [], 'explain' => 'HSL = hue, saturation, lightness – odstín, sytost, světlost.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.012', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co vyjadřuje ve zkratce HSL písmeno H?', 'options' => ['odstín (hue)', 'světlost (lightness)', 'sytost (saturation)', 'výšku (height)'], 'answer' => 'odstín (hue)', 'tolerance' => null, 'accept' => [], 'explain' => 'H (hue) určuje samotný barevný tón na barevném kruhu.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.013', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je na velký text a klíčové prvky rozhraní podle WCAG 2.2 mírnější nárok na kontrast (3:1) než na běžný text (4,5:1)?', 'options' => ['větší nebo tučnější písmo zůstává čitelné i při nižším kontrastu', 'je to jen historická náhoda bez důvodu', 'velký text se čte vzácněji', 'pravidlo platí jen pro tištěné materiály'], 'answer' => 'větší nebo tučnější písmo zůstává čitelné i při nižším kontrastu', 'tolerance' => null, 'accept' => [], 'explain' => 'Velikost a tloušťka písma sama o sobě zlepšuje rozpoznatelnost tvarů.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.014', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Barvoslepost postihuje jen zanedbatelné procento lidí, a proto se s ní při návrhu barev nemusí počítat.', 'options' => [], 'answer' => false, 'tolerance' => null, 'accept' => [], 'explain' => 'Poruchu barvocitu má výrazná část populace, hlavně mužů, proto se s ní počítá.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.015', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč se nedoporučuje předávat důležitou informaci, například chybu ve formuláři, jen barvou?', 'options' => ['lidé s poruchou barvocitu by ji nemuseli rozeznat', 'barvy jsou vždy pomalejší na vykreslení', 'barva se na obrazovce nedá zobrazit', 'to je zakázané autorským zákonem'], 'answer' => 'lidé s poruchou barvocitu by ji nemuseli rozeznat', 'tolerance' => null, 'accept' => [], 'explain' => 'Vedle barvy je vhodné přidat ikonu, text nebo jiný vizuální signál.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.016', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 2, 'type' => 'numeric', 'prompt' => 'Kolik základních barevných kanálů (červený, zelený, modrý) má model RGB?', 'options' => [], 'answer' => 3, 'tolerance' => 0, 'accept' => [], 'explain' => 'RGB má tři kanály: červený, zelený a modrý.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.017', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co se stane s barvou při postupném snižování její světlosti (lightness) směrem k nule?', 'options' => ['ztmavne až k černé', 'zesvětlá až k bílé', 'změní se jen její odstín', 'zůstane úplně stejná'], 'answer' => 'ztmavne až k černé', 'tolerance' => null, 'accept' => [], 'explain' => 'Nulová světlost odpovídá černé bez ohledu na odstín.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.018', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená vysoká sytost (saturation) barvy?', 'options' => ['barva je plná a výrazná, málo smíchaná s šedou', 'barva je téměř černobílá', 'barva je vždy velmi světlá', 'jde o synonymum pro odstín'], 'answer' => 'barva je plná a výrazná, málo smíchaná s šedou', 'tolerance' => null, 'accept' => [], 'explain' => 'Nízká sytost naopak posouvá barvu blíž k šedé.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.019', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dvě z uvedených barev se na klasickém barevném kole považují za teplé?', 'options' => ['červená', 'oranžová', 'modrá', 'zelená'], 'answer' => ['červená', 'oranžová'], 'tolerance' => null, 'accept' => [], 'explain' => 'Červená a oranžová patří mezi teplé barvy, modrá a zelená mezi studené.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.020', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je vhodné kontrast textu na barevném tlačítku ověřit vždy znovu, ne jen u černého textu na bílé?', 'options' => ['kontrast se počítá vždy pro konkrétní dvojici barev popředí a pozadí', 'kontrast je u všech barev pozadí stejný', 'tlačítka nepotřebují žádný kontrast', 'stačí zkontrolovat kontrast jednou pro celý web'], 'answer' => 'kontrast se počítá vždy pro konkrétní dvojici barev popředí a pozadí', 'tolerance' => null, 'accept' => [], 'explain' => 'Každá kombinace barev popředí a pozadí má svůj vlastní poměr kontrastu.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.021', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'Dvě barvy se stejným jasem, například červená a zelená, mohou mít nízký kontrast jasu, i když se lidem s běžným barvocitem zdají velmi odlišné.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Kontrast podle WCAG se počítá z jasu barev, ne z jejich subjektivní odlišnosti.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.022', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč nástroje pro kontrolu kontrastu počítají poměr jasu, místo aby jen porovnávaly, jak „jiné“ barvy vypadají?', 'options' => ['jas lze změřit objektivně a použít jako jednotné pravidlo pro čitelnost', 'subjektivní dojem je přesnější než měření', 'barvy nejde nijak měřit', 'poměr jasu nemá se čitelností nic společného'], 'answer' => 'jas lze změřit objektivně a použít jako jednotné pravidlo pro čitelnost', 'tolerance' => null, 'accept' => [], 'explain' => 'Objektivní měření umožňuje stanovit jasné, ověřitelné pravidlo.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.023', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Web má tmavě modrý text na středně modrém pozadí s podobným jasem. Co se pravděpodobně stane s čitelností?', 'options' => ['kontrast bude nízký a text se bude číst hůř', 'kontrast bude vždy vysoký, protože jde o stejný odstín', 'čitelnost ovlivňuje jen velikost písma', 'barva pozadí čitelnost nijak neovlivňuje'], 'answer' => 'kontrast bude nízký a text se bude číst hůř', 'tolerance' => null, 'accept' => [], 'explain' => 'Podobný jas textu a pozadí znamená nízký kontrast bez ohledu na odstín.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.color.024', 'line' => 'graphics', 'classes' => null, 'category' => 'color', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'I když text splňuje minimální kontrast 4,5:1, ještě vyšší kontrast může čtení dál usnadnit, hlavně lidem se sníženou zrakovou ostrostí.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Minimum podle WCAG je práh, ne doporučený cíl pro co nejlepší čitelnost.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
];
