<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, grafická linie: přístupnost webu (kategorie „a11y“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_gfx.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'gfx.a11y.001', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'K čemu slouží atribut alt u obrázku?', 'options' => ['popisuje obsah obrázku pro lidi, kteří ho nevidí, nebo když se nenačte', 'mění velikost obrázku', 'nastavuje pozici obrázku na stránce', 'zrychluje načítání obrázku'], 'answer' => 'popisuje obsah obrázku pro lidi, kteří ho nevidí, nebo když se nenačte', 'tolerance' => null, 'accept' => [], 'explain' => 'alt text čte čtečka obrazovky a zobrazí se i při nenačtení obrázku.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.002', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Čistě dekorativní obrázek, který nenese žádnou informaci, může mít alt="" (prázdný).', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Prázdný alt řekne čtečce, ať obrázek přeskočí jako nepodstatný.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.003', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Proč je důležité, aby šla stránka ovládat i jen klávesnicí?', 'options' => ['ne každý používá myš, někteří se pohybují po stránce jen klávesou Tab', 'klávesnice je vždy rychlejší než myš pro všechny uživatele', 'myš na počítačích už dnes nikdo nepoužívá', 'to platí jen pro herní weby'], 'answer' => 'ne každý používá myš, někteří se pohybují po stránce jen klávesou Tab', 'tolerance' => null, 'accept' => [], 'explain' => 'Ovládání jen klávesnicí je nutné například pro lidi s motorickým postižením.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.004', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená viditelný fokus u interaktivních prvků, například tlačítek nebo odkazů?', 'options' => ['viditelné zvýraznění prvku, na kterém právě stojí kurzor klávesnice (Tab)', 'barva pozadí celé stránky', 'velikost písma nadpisu', 'počet kliknutí potřebných k akci'], 'answer' => 'viditelné zvýraznění prvku, na kterém právě stojí kurzor klávesnice (Tab)', 'tolerance' => null, 'accept' => [], 'explain' => 'Fokus ukazuje, kde se uživatel ovládající klávesnicí právě nachází.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.005', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Odstranění viditelného zvýraznění fokusu jen kvůli vzhledu ztěžuje ovládání stránky klávesnicí.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Bez fokusu uživatel ovládající klávesnici neví, kde na stránce je.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.006', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Proč je popisný text odkazu, například „stáhnout ceník“, lepší než obecné „klikni sem“?', 'options' => ['čtečka obrazovky umí vypsat seznam odkazů a potřebuje, aby dávaly smysl samy o sobě', 'odkazy s textem klikni sem se nedají otevřít', 'popisné odkazy jsou vždy kratší', 'prohlížeč jinak odkaz nezobrazí'], 'answer' => 'čtečka obrazovky umí vypsat seznam odkazů a potřebuje, aby dávaly smysl samy o sobě', 'tolerance' => null, 'accept' => [], 'explain' => 'Mimo kontext věty musí text odkazu sám naznačit, kam vede.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.007', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'K čemu slouží titulky (captions) u videa?', 'options' => ['zpřístupní mluvené slovo lidem, kteří neslyší zvuk nebo mají zvuk vypnutý', 'zrychlí přehrávání videa', 'zmenší velikost souboru videa', 'automaticky přeloží video do jiného jazyka'], 'answer' => 'zpřístupní mluvené slovo lidem, kteří neslyší zvuk nebo mají zvuk vypnutý', 'tolerance' => null, 'accept' => [], 'explain' => 'Titulky pomáhají neslyšícím i lidem sledujícím video bez zvuku.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.008', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je odkaz „přeskočit na obsah“ na začátku stránky?', 'options' => ['odkaz umožňující přeskočit opakovanou navigaci a jít rovnou na hlavní obsah', 'odkaz na jinou webovou stránku', 'tlačítko pro smazání historie prohlížeče', 'odkaz jen pro administrátory webu'], 'answer' => 'odkaz umožňující přeskočit opakovanou navigaci a jít rovnou na hlavní obsah', 'tolerance' => null, 'accept' => [], 'explain' => 'Skip link ušetří uživatelům klávesnice opakované procházení menu.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.009', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 1, 'type' => 'numeric', 'prompt' => 'Jaká je často doporučovaná minimální velikost strany dotykového cíle (např. tlačítka) v pixelech pro snadné ovládání prstem?', 'options' => [], 'answer' => 44, 'tolerance' => 0, 'accept' => [], 'explain' => 'Běžné doporučení, které používá i EDUCANET, je minimálně 44×44 pixelů.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.010', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Proč by formulářové chybové hlášení mělo být napsané jasně a svázané s konkrétním polem?', 'options' => ['uživatel hned ví, co přesně a kde má opravit', 'chybové hlášení je jen ozdoba stránky', 'formulář se bez chybového hlášení vůbec neodešle', 'chybové hlášení musí být vždy červené'], 'answer' => 'uživatel hned ví, co přesně a kde má opravit', 'tolerance' => null, 'accept' => [], 'explain' => 'Konkrétní hlášení u pole zrychlí opravu chyby ve formuláři.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.011', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená nastavení „prefers-reduced-motion“, které respektuje přístupný web?', 'options' => ['uživatel preferuje omezené nebo žádné animace, web by měl efekty ztlumit', 'uživatel chce rychlejší internet', 'uživatel chce menší písmo', 'uživatel chce jiný jazyk stránky'], 'answer' => 'uživatel preferuje omezené nebo žádné animace, web by měl efekty ztlumit', 'tolerance' => null, 'accept' => [], 'explain' => 'Silné animace mohou některým lidem způsobovat nevolnost nebo je rušit.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.012', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je důležité, aby šel web zvětšit v prohlížeči bez rozbití layoutu?', 'options' => ['lidé se slabším zrakem si tak mohou text zvětšit a dál stránku pohodlně číst', 'zvětšení stránky slouží jen k tisku', 'prohlížeče zvětšení stránek nepodporují', 'zvětšení je potřeba jen na mobilu'], 'answer' => 'lidé se slabším zrakem si tak mohou text zvětšit a dál stránku pohodlně číst', 'tolerance' => null, 'accept' => [], 'explain' => 'Pevně nastavené rozměry mohou při zvětšení text nebo prvky oříznout.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.013', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Pořadí, ve kterém se dá procházet stránka klávesou Tab, by mělo logicky odpovídat vizuálnímu a obsahovému pořadí prvků.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Neintuitivní pořadí fokusu mate uživatele ovládající stránku klávesnicí.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.014', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Jaké je základní pravidlo pro použití ARIA atributů, známé jako „první pravidlo ARIA“?', 'options' => ['existuje-li vhodný nativní prvek, například <button>, použij ho místo ARIA na <div>', 'ARIA se má používat na úplně každý prvek stránky', 'ARIA nahrazuje potřebu psát HTML', 'ARIA se týká jen barev na stránce'], 'answer' => 'existuje-li vhodný nativní prvek, například <button>, použij ho místo ARIA na <div>', 'tolerance' => null, 'accept' => [], 'explain' => 'Nativní prvky mají přístupné chování zabudované, ARIA ho jen doplňuje tam, kde chybí.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.015', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč může být automaticky přehrávané video se zvukem bez snadného vypnutí problém pro přístupnost?', 'options' => ['může rušit uživatele čtečky obrazovky nebo být pro někoho nepříjemné a obtížné zastavit', 'video se zvukem nikdo nesleduje', 'zvuk zrychlí načítání stránky', 'to je problém jen na pomalém internetu'], 'answer' => 'může rušit uživatele čtečky obrazovky nebo být pro někoho nepříjemné a obtížné zastavit', 'tolerance' => null, 'accept' => [], 'explain' => 'Neočekávaný zvuk může přehlušit řeč čtečky obrazovky.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.016', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je vhodné otestovat formulář i jen pomocí klávesnice, bez použití myši?', 'options' => ['odhalí to, jestli se dá každé pole a tlačítko skutečně ovládat i bez myši', 'testování klávesnicí je jen formalita bez praktického významu', 'myš je při vyplňování formulářů vždy povinná', 'klávesnicí nejde formulář nikdy ovládat'], 'answer' => 'odhalí to, jestli se dá každé pole a tlačítko skutečně ovládat i bez myši', 'tolerance' => null, 'accept' => [], 'explain' => 'Test klávesnicí rychle odhalí pasti pro uživatele bez myši.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.017', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dvě z uvedených jsou zásady přístupného návrhu webu?', 'options' => ['viditelný fokus u interaktivních prvků', 'popisný alt text u informačních obrázků', 'co nejvíc blikajících prvků najednou', 'skrytí chybových hlášení formuláře'], 'answer' => ['viditelný fokus u interaktivních prvků', 'popisný alt text u informačních obrázků'], 'tolerance' => null, 'accept' => [], 'explain' => 'Blikající prvky a skryté chyby naopak přístupnost zhoršují.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.018', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč se doporučuje nechávat mezi interaktivními prvky, například tlačítky v menu, dostatečnou mezeru?', 'options' => ['sníží to riziko omylem trefit sousední tlačítko, hlavně na dotyku', 'mezery zpomalí načítání stránky', 'mezery jsou jen estetická záležitost bez funkce', 'menší mezery jsou vždy lépe přístupné'], 'answer' => 'sníží to riziko omylem trefit sousední tlačítko, hlavně na dotyku', 'tolerance' => null, 'accept' => [], 'explain' => 'Dostatečný odstup omezí nechtěné dotykové omyly.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.019', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Živá oblast (aria-live) na stránce umožní čtečce obrazovky oznámit dynamickou změnu obsahu, aniž by uživatel musel stránku znovu procházet.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'aria-live upozorní na změnu obsahu, například nový výsledek nebo chybu, automaticky.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.020', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je důležité mít u audio přehrávače na webu i textový přepis?', 'options' => ['zpřístupní obsah neslyšícím i tam, kde poslech není vhodný, například v tichu', 'transkript nahrazuje potřebu mít vůbec zvuk', 'transkript zrychlí přehrávání zvuku', 'transkript je jen záložní kopie pro autora'], 'answer' => 'zpřístupní obsah neslyšícím i tam, kde poslech není vhodný, například v tichu', 'tolerance' => null, 'accept' => [], 'explain' => 'Textový přepis zpřístupní obsah i bez poslechu zvuku.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.021', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Formulářové pole má jen placeholder a žádný svázaný label. Proč je lepší přidat label a placeholder ponechat jen jako doplněk?', 'options' => ['label zůstává viditelný i po vyplnění pole, placeholder zmizí, jakmile se začne psát', 'placeholder je vždy lepší než label', 'label a placeholder dělají přesně totéž', 'pole s placeholderem nejde vůbec odeslat'], 'answer' => 'label zůstává viditelný i po vyplnění pole, placeholder zmizí, jakmile se začne psát', 'tolerance' => null, 'accept' => [], 'explain' => 'Bez trvalého labelu uživatel po vyplnění ztratí, k čemu pole patřilo.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.022', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'I stránka, která vizuálně vypadá bezvadně, může být pro uživatele čtečky obrazovky nepoužitelná, pokud chybí správná struktura nadpisů a popisky prvků.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Čtečka obrazovky se opírá o strukturu a popisky, ne o vzhled.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.023', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč se doporučuje otestovat důležitou stránku i s vypnutými styly nebo obrázky?', 'options' => ['odhalí to, jestli obsah dává smysl podle skutečné HTML struktury, ne jen podle vzhledu', 'bez CSS se stránka vůbec nenačte', 'vypnutí CSS je jediný způsob, jak stránku zrychlit', 'test bez obrázků se týká jen tiskáren'], 'answer' => 'odhalí to, jestli obsah dává smysl podle skutečné HTML struktury, ne jen podle vzhledu', 'tolerance' => null, 'accept' => [], 'explain' => 'Test bez stylů ukáže skutečný sémantický základ stránky.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.a11y.024', 'line' => 'graphics', 'classes' => null, 'category' => 'a11y', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Tým opravuje přístupnost webu, ale má čas jen na pár nejdůležitějších změn. Která úprava typicky pomůže nejvíc lidem najednou?', 'options' => ['doplnit chybějící alt texty a zajistit viditelný fokus u ovládacích prvků', 'změnit jen barvu loga', 'přidat další animace', 'zvětšit jen patičku stránky'], 'answer' => 'doplnit chybějící alt texty a zajistit viditelný fokus u ovládacích prvků', 'tolerance' => null, 'accept' => [], 'explain' => 'Alt texty a viditelný fokus patří mezi základní a nejúčinnější opravy.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
];
