<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, grafická linie: kompozice a UX (kategorie „ux“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_gfx.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'gfx.ux.001', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jak se nazývá pravidlo kompozice, které dělí obraz na třetiny a umísťuje důležité prvky na jejich průsečíky?', 'options' => ['pravidlo třetin', 'zlatý řez naruby', 'pravidlo poloviny', 'diagonální test'], 'answer' => 'pravidlo třetin', 'tolerance' => null, 'accept' => [], 'explain' => 'Pravidlo třetin umísťuje důležité prvky na průsečíky mřížky 3×3.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.002', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je prázdný prostor (whitespace) v grafickém návrhu?', 'options' => ['záměrně nevyplněný prostor kolem prvků, který zlepšuje přehlednost', 'chyba v návrhu, které je třeba se vyhnout', 'místo určené jen pro reklamu', 'prostor, který se musí vždy vyplnit barvou'], 'answer' => 'záměrně nevyplněný prostor kolem prvků, který zlepšuje přehlednost', 'tolerance' => null, 'accept' => [], 'explain' => 'Prázdný prostor dává prvkům „dýchat“ a usnadňuje orientaci.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.003', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Přeplněná stránka bez dostatku prázdného prostoru bývá hůř čitelná a orientace v ní je obtížnější.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Nedostatek prostoru ztěžuje očím rozlišit jednotlivé prvky.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.004', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je vizuální hierarchie v návrhu?', 'options' => ['uspořádání prvků tak, aby oko vidělo nejdůležitější věci jako první', 'abecední řazení textu', 'použití jen jedné barvy v návrhu', 'skrytí méně důležitých prvků úplně'], 'answer' => 'uspořádání prvků tak, aby oko vidělo nejdůležitější věci jako první', 'tolerance' => null, 'accept' => [], 'explain' => 'Hierarchie vede pozornost k tomu nejdůležitějšímu jako první.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.005', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Proč je konzistence, tedy jednotný vzhled tlačítek, odkazů a nadpisů, v návrhu důležitá?', 'options' => ['uživatel se rychleji naučí, jak se stránka ovládá, a předvídá chování prvků', 'konzistence nemá na použitelnost žádný vliv', 'konzistentní návrh se vždy načítá pomaleji', 'konzistence je důležitá jen pro tiskoviny'], 'answer' => 'uživatel se rychleji naučí, jak se stránka ovládá, a předvídá chování prvků', 'tolerance' => null, 'accept' => [], 'explain' => 'Stejně vypadající prvky se chovají předvídatelně napříč stránkou.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.006', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je výzva k akci (call to action), například tlačítko „Odeslat“ nebo „Přihlásit se“?', 'options' => ['výrazný prvek navádějící uživatele k další žádoucí akci', 'jakýkoli nadpis stránky', 'okrajová poznámka v patičce', 'barva pozadí stránky'], 'answer' => 'výrazný prvek navádějící uživatele k další žádoucí akci', 'tolerance' => null, 'accept' => [], 'explain' => 'Call to action jasně ukazuje, co má uživatel udělat dál.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.007', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Responzivní web se přizpůsobuje různým velikostem obrazovky, například mobilu i počítači.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Responzivní návrh mění rozložení podle dostupné šířky obrazovky.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.008', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená přístup „mobile first“ při návrhu webu?', 'options' => ['návrh se nejdřív řeší pro malou obrazovku mobilu a pak se rozšiřuje pro větší', 'web se navrhuje jen pro mobily a na počítači nefunguje', 'mobile first znamená, že web nemá žádné styly', 'jde o návrh jen pro jednu značku telefonu'], 'answer' => 'návrh se nejdřív řeší pro malou obrazovku mobilu a pak se rozšiřuje pro větší', 'tolerance' => null, 'accept' => [], 'explain' => 'Začátek od nejmenší obrazovky nutí soustředit se na to nejdůležitější.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.009', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je afordance u ovládacího prvku, například tlačítka s vystouplým okrajem?', 'options' => ['vizuální náznak, jak se má prvek použít, například že jde stisknout', 'skrytá funkce, o které uživatel neví', 'jiný název pro barvu tlačítka', 'technický název pro chybové hlášení'], 'answer' => 'vizuální náznak, jak se má prvek použít, například že jde stisknout', 'tolerance' => null, 'accept' => [], 'explain' => 'Afordance napovídá funkci prvku už jen tím, jak vypadá.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.010', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Zpětná vazba po akci uživatele, například potvrzení „Zpráva odeslána“, pomáhá uživateli vědět, že se akce povedla.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Bez zpětné vazby uživatel neví, jestli akce proběhla správně.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.011', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co popisuje F-vzorec (F-pattern) při čtení webové stránky?', 'options' => ['typický způsob, jakým oči často sledují obsah stránky ve tvaru písmene F', 'typ rozložení textu do sloupce ve tvaru F', 'font speciálně navržený pro nadpisy', 'vzorec pro výpočet kontrastu barev'], 'answer' => 'typický způsob, jakým oči často sledují obsah stránky ve tvaru písmene F', 'tolerance' => null, 'accept' => [], 'explain' => 'Výzkumy očních pohybů ukazují častý vzorec čtení podobný písmenu F.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.012', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co je seskupování podle blízkosti (proximity) v návrhu?', 'options' => ['prvky, které spolu logicky souvisí, se umísťují blízko sebe', 'prvky se řadí podle abecedy', 'všechny prvky mají stejnou velikost', 'prvky se náhodně rozmisťují po stránce'], 'answer' => 'prvky, které spolu logicky souvisí, se umísťují blízko sebe', 'tolerance' => null, 'accept' => [], 'explain' => 'Blízkost signalizuje divákovi, že prvky patří k sobě.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.013', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je důležité navigaci webu udržet jednoduchou a předvídatelnou?', 'options' => ['uživatel se snáz zorientuje a najde to, co hledá, bez zbytečného tápání', 'složitá navigace vždy vypadá profesionálněji', 'navigace nemá na použitelnost webu žádný vliv', 'jednoduchá navigace znamená míň stránek na webu'], 'answer' => 'uživatel se snáz zorientuje a najde to, co hledá, bez zbytečného tápání', 'tolerance' => null, 'accept' => [], 'explain' => 'Přehledná navigace šetří uživateli čas a snižuje frustraci.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.014', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Testování s reálnými uživateli může odhalit problémy použitelnosti, které si tvůrci návrhu sami nevšimli.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Tvůrci znají návrh moc dobře, a proto snadno přehlédnou matoucí místa.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.015', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co je mřížkový systém (grid system) v grafickém designu?', 'options' => ['neviditelná mřížka sloupců a řádků, podle které se zarovnávají prvky návrhu', 'viditelná dekorativní mřížka na pozadí stránky', 'tabulka s daty', 'systém pro ukládání barevných palet'], 'answer' => 'neviditelná mřížka sloupců a řádků, podle které se zarovnávají prvky návrhu', 'tolerance' => null, 'accept' => [], 'explain' => 'Mřížka pomáhá zarovnávat prvky konzistentně napříč stránkou.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.016', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená rovnováha (balance) v kompozici, například symetrická nebo asymetrická?', 'options' => ['rozložení vizuální váhy prvků tak, aby výsledek působil stabilně a promyšleně', 'stejná barva použitá na celé ploše', 'přesně stejný počet textu a obrázků', 'úplná absence jakéhokoli stylu'], 'answer' => 'rozložení vizuální váhy prvků tak, aby výsledek působil stabilně a promyšleně', 'tolerance' => null, 'accept' => [], 'explain' => 'Rovnováha nemusí být symetrická, jde hlavně o pocit stability.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.017', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dvě z uvedených patří mezi zásady přehledné kompozice?', 'options' => ['dostatek prázdného prostoru kolem klíčových prvků', 'jasná vizuální hierarchie důležitosti', 'co nejvíc různých fontů najednou', 'náhodné rozmístění tlačítek'], 'answer' => ['dostatek prázdného prostoru kolem klíčových prvků', 'jasná vizuální hierarchie důležitosti'], 'tolerance' => null, 'accept' => [], 'explain' => 'Náhodné rozmístění a přemíra fontů naopak přehlednost narušují.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.018', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč se doporučuje mít na stránce jednu hlavní výzvu k akci, ne pět stejně výrazných tlačítek najednou?', 'options' => ['příliš mnoho stejně důležitých voleb ztěžuje rozhodnutí, co udělat jako první', 'tlačítka navíc web vždy zpomalí', 'jedno tlačítko je vždy hezčí než pět', 'více tlačítek prohlížeč technicky nepodporuje'], 'answer' => 'příliš mnoho stejně důležitých voleb ztěžuje rozhodnutí, co udělat jako první', 'tolerance' => null, 'accept' => [], 'explain' => 'Jasná priorita akcí usnadňuje uživateli rozhodování.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.019', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co je drobečková navigace (breadcrumbs)?', 'options' => ['řádek odkazů ukazující cestu od domovské stránky k aktuální stránce', 'seznam receptů na webu', 'ozdobný prvek bez funkce', 'jiný název pro hlavní menu'], 'answer' => 'řádek odkazů ukazující cestu od domovské stránky k aktuální stránce', 'tolerance' => null, 'accept' => [], 'explain' => 'Drobečková navigace pomáhá pochopit, kde se uživatel v hierarchii webu nachází.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.020', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 2, 'type' => 'order', 'prompt' => 'Seřaď typické kroky procesu návrhu webu od prvního k poslednímu.', 'options' => [], 'answer' => ['zjištění potřeb uživatelů (výzkum)', 'návrh drátěného modelu (wireframe)', 'vizuální design a prototyp', 'testování s uživateli a úpravy'], 'tolerance' => null, 'accept' => [], 'explain' => 'Výzkum předchází návrhu, prototyp se testuje až nakonec.', 'time_s' => 40, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.021', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč se prototyp návrhu často testuje na malé skupině uživatelů ještě před finálním spuštěním webu?', 'options' => ['umožní to odhalit a opravit problémy použitelnosti, dokud je to levné a snadné', 'testování před spuštěním je zákonná povinnost', 'prototypy se testují jen z estetických důvodů', 'testování po spuštění je vždy rychlejší'], 'answer' => 'umožní to odhalit a opravit problémy použitelnosti, dokud je to levné a snadné', 'tolerance' => null, 'accept' => [], 'explain' => 'Chyby objevené v prototypu se opravují levněji než po ostrém spuštění.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.022', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'I vizuálně atraktivní návrh může mít slabou použitelnost, pokud uživatelé nesnadno najdou to, co potřebují.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Krásný vzhled sám o sobě nezaručuje snadné použití.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.023', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Formulář na objednávku má deset stejně výrazných tlačítek na jedné obrazovce. Jaký to má typický dopad na uživatele?', 'options' => ['uživatel může zaváhat nebo udělat chybu, protože neví, které tlačítko je hlavní', 'uživatelé vždy ocení víc možností najednou', 'více tlačítek stránku zrychlí', 'to nemá na chování uživatele žádný vliv'], 'answer' => 'uživatel může zaváhat nebo udělat chybu, protože neví, které tlačítko je hlavní', 'tolerance' => null, 'accept' => [], 'explain' => 'Přemíra rovnocenných voleb zvyšuje riziko zmatku i chyby.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.ux.024', 'line' => 'graphics', 'classes' => null, 'category' => 'ux', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč se v UX designu často opakuje zásada „nedělej uživatele přemýšlet víc, než je nutné“?', 'options' => ['čím míň úsilí musí uživatel vynaložit na pochopení rozhraní, tím snáz splní svůj cíl', 'uživatelé mají rádi složité rozhraní jako výzvu', 'přemýšlení uživatele webu vůbec neovlivňuje', 'tato zásada platí jen pro hry'], 'answer' => 'čím míň úsilí musí uživatel vynaložit na pochopení rozhraní, tím snáz splní svůj cíl', 'tolerance' => null, 'accept' => [], 'explain' => 'Intuitivní rozhraní šetří pozornost a snižuje chybovost.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
];
