<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, síťová linie: IP a maska (kategorie „ip“).
 * Adresy jen z RFC 5737 (192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24) nebo privátních rozsahů.
 * Načítá ji souhrnný soubor teamgames_v58_bank_net.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'net.ip.001', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Kolik bitů má IPv4 adresa?', 'options' => ['32', '64', '128', '16'], 'answer' => '32', 'tolerance' => null, 'accept' => [], 'explain' => 'IPv4 adresa = čtyři osmibitové oktety, tedy 4 × 8 = 32 bitů.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.002', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Na kolik částí (oktetů) oddělených tečkami se běžně zapisuje IPv4 adresa?', 'options' => ['4', '2', '8', '16'], 'answer' => '4', 'tolerance' => null, 'accept' => [], 'explain' => 'Adresa se zapisuje jako čtyři čísla oddělená tečkami, například 192.168.1.10.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.003', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jaký je platný rozsah hodnot jednoho oktetu IPv4 adresy?', 'options' => ['0 až 255', '0 až 999', '1 až 256', '0 až 128'], 'answer' => '0 až 255', 'tolerance' => null, 'accept' => [], 'explain' => 'Jeden oktet má 8 bitů, což dává rozsah hodnot 0 až 255.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.004', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Adresa 127.0.0.1 se nazývá loopback a odkazuje vždy na vlastní počítač.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Loopback adresa slouží zařízení k odeslání dat samo sobě, například při testování.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.005', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'K čemu slouží síťová maska (subnet mask)?', 'options' => ['odděluje síťovou část adresy od části pro zařízení', 'šifruje síťovou komunikaci', 'přiděluje MAC adresy', 'překládá doménová jména'], 'answer' => 'odděluje síťovou část adresy od části pro zařízení', 'tolerance' => null, 'accept' => [], 'explain' => 'Maska určuje, kolik bitů adresy patří síti a kolik zbývá pro jednotlivá zařízení.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.006', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená zápis 192.168.1.0/24?', 'options' => ['prvních 24 bitů adresy tvoří síťovou část', 'adresa má 24 zařízení', 'jde o číslo portu 24', '24 je verze protokolu'], 'answer' => 'prvních 24 bitů adresy tvoří síťovou část', 'tolerance' => null, 'accept' => [], 'explain' => 'Číslo za lomítkem (CIDR) udává počet bitů vyhrazených pro síťovou část adresy.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.007', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Která z adres patří do soukromého (privátního) rozsahu určeného pro vnitřní sítě?', 'options' => ['192.168.1.10', '203.0.113.10', '198.51.100.10', '192.0.2.10'], 'answer' => '192.168.1.10', 'tolerance' => null, 'accept' => [], 'explain' => 'Rozsah 192.168.0.0/16 je vyhrazený pro vnitřní (privátní) sítě.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.008', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Adresy v rozsahu 10.0.0.0/8 patří mezi privátní adresy určené pro vnitřní sítě.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Celý rozsah 10.0.0.0/8 je vyhrazený pro privátní sítě.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.009', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Kolik adres teoreticky pojme celý rozsah IPv4 bez ohledu na vyhrazené adresy?', 'options' => ['přibližně 4,3 miliardy', 'přibližně 4,3 milionu', 'přesně 65 536', 'přesně 256'], 'answer' => 'přibližně 4,3 miliardy', 'tolerance' => null, 'accept' => [], 'explain' => '2 na 32. je přibližně 4,3 miliardy možných adres.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.010', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je MAC adresa ve srovnání s IP adresou?', 'options' => ['jedinečná adresa síťového rozhraní přiřazená výrobcem, nemění se podle sítě', 'dočasná adresa přidělovaná při každém připojení k internetu', 'jiný název pro IP adresu', 'adresa e-mailové schránky'], 'answer' => 'jedinečná adresa síťového rozhraní přiřazená výrobcem, nemění se podle sítě', 'tolerance' => null, 'accept' => [], 'explain' => 'MAC adresa je fyzická adresa síťové karty, IP adresa se naopak mění podle sítě.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.011', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 2, 'type' => 'numeric', 'prompt' => 'Kolik použitelných adres pro zařízení má síť s maskou /24, bez síťové a broadcastové adresy?', 'options' => [], 'answer' => 254, 'tolerance' => 0, 'accept' => [], 'explain' => '256 adres mínus síťová a broadcastová adresa je 254.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.012', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 2, 'type' => 'numeric', 'prompt' => 'Kolik adres celkem, včetně síťové a broadcastové, obsahuje síť s maskou /24?', 'options' => [], 'answer' => 256, 'tolerance' => 0, 'accept' => [], 'explain' => 'Poslední oktet má 8 volných bitů, 2 na 8. je 256.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.013', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 2, 'type' => 'numeric', 'prompt' => 'Kolik použitelných adres pro zařízení má menší síť s maskou /28?', 'options' => [], 'answer' => 14, 'tolerance' => 0, 'accept' => [], 'explain' => '/28 dává 16 adres celkem, minus síťová a broadcastová vychází 14.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.014', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 2, 'type' => 'text', 'prompt' => 'Jaká je broadcastová adresa sítě 192.168.1.0/24? Napiš celou adresu ve tvaru x.x.x.x.', 'options' => [], 'answer' => '192.168.1.255', 'tolerance' => null, 'accept' => [], 'explain' => 'Broadcastová adresa má všechny bity hostitelské části nastavené na jedničku, tedy poslední oktet 255.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.015', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 2, 'type' => 'text', 'prompt' => 'Jaká je síťová adresa pro zařízení s IP 192.168.1.130 a maskou /24? Napiš celou adresu.', 'options' => [], 'answer' => '192.168.1.0', 'tolerance' => null, 'accept' => [], 'explain' => 'Maska /24 ponechává poslední oktet pro zařízení, síťová adresa má tuto část vynulovanou.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.016', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Jaká maska odpovídá zápisu /16?', 'options' => ['255.255.0.0', '255.0.0.0', '255.128.0.0', '0.0.0.0'], 'answer' => '255.255.0.0', 'tolerance' => null, 'accept' => [], 'explain' => 'Prvních 16 bitů nastavených na jedničku dává masku 255.255.0.0.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.017', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Jaká maska odpovídá zápisu /8?', 'options' => ['255.0.0.0', '255.255.0.0', '255.192.0.0', '0.0.0.0'], 'answer' => '255.0.0.0', 'tolerance' => null, 'accept' => [], 'explain' => 'Prvních 8 bitů nastavených na jedničku dává masku 255.0.0.0.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.018', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Čím menší je číslo za lomítkem u masky, například /8 oproti /24, tím víc adres pro zařízení síť obsahuje.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Menší číslo znamená méně bitů pro síť, a tedy víc bitů zbývá pro zařízení.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.019', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Adresy 192.0.2.0/24, 198.51.100.0/24 a 203.0.113.0/24 se v dokumentaci a výuce používají proto, že:', 'options' => ['jsou vyhrazené jen pro příklady a nepatří žádné reálné síti', 'jsou nejrychlejší ze všech adres', 'patří výhradně školám', 'jsou to jediné platné veřejné adresy'], 'answer' => 'jsou vyhrazené jen pro příklady a nepatří žádné reálné síti', 'tolerance' => null, 'accept' => [], 'explain' => 'RFC 5737 vyhrazuje tyto rozsahy speciálně pro dokumentaci a výuku.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.020', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co se stane, když dvě zařízení ve stejné síti /24 mají nastavenou stejnou IP adresu?', 'options' => ['dojde ke kolizi adres a komunikace jednoho nebo obou zařízení přestane fungovat správně', 'nic, obě zařízení fungují bez problémů', 'systém jim automaticky přidělí novou masku', 'jde o standardní a doporučený stav'], 'answer' => 'dojde ke kolizi adres a komunikace jednoho nebo obou zařízení přestane fungovat správně', 'tolerance' => null, 'accept' => [], 'explain' => 'Adresa musí být v rámci sítě jedinečná, jinak dochází ke konfliktům.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.021', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 3, 'type' => 'numeric', 'prompt' => 'Kolik použitelných adres pro zařízení má síť s maskou /30, která se typicky používá pro propojení dvou zařízení?', 'options' => [], 'answer' => 2, 'tolerance' => 0, 'accept' => [], 'explain' => '/30 dává 4 adresy celkem, minus síťová a broadcastová vychází 2.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.022', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 3, 'type' => 'text', 'prompt' => 'Do jaké sítě (síťová adresa/24) patří zařízení s IP 203.0.113.77 a maskou /24? Napiš síťovou adresu.', 'options' => [], 'answer' => '203.0.113.0', 'tolerance' => null, 'accept' => [], 'explain' => 'Maska /24 ponechává poslední oktet, síťová adresa má tuto část vynulovanou.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.023', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'IPv6 adresa je výrazně delší než IPv4 (128 bitů oproti 32 bitům) a byla zavedena mimo jiné proto, že adres IPv4 začalo být málo.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'IPv6 nabízí obrovský adresní prostor a řeší nedostatek volných IPv4 adres.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ip.024', 'line' => 'networks', 'classes' => null, 'category' => 'ip', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Zařízení má IP 172.20.5.9. Podle jakého rozsahu poznáš, že jde o privátní adresu?', 'options' => ['172.16.0.0 až 172.31.255.255 je vyhrazený privátní rozsah', '172.x.x.x je vždy veřejná adresa', 'privátní jsou jen adresy začínající na 10', 'podle IP adresy to poznat nejde'], 'answer' => '172.16.0.0 až 172.31.255.255 je vyhrazený privátní rozsah', 'tolerance' => null, 'accept' => [], 'explain' => 'Kromě 10.0.0.0/8 a 192.168.0.0/16 je privátní i rozsah 172.16.0.0/12.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
];
