<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, síťová linie: služby a porty (kategorie „ports“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_net.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'net.ports.001', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Na kterém portu obvykle běží nešifrovaný web (HTTP)?', 'options' => ['80', '443', '22', '25'], 'answer' => '80', 'tolerance' => null, 'accept' => [], 'explain' => 'HTTP standardně používá port 80, šifrovaný HTTPS port 443.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.002', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Na kterém portu obvykle běží šifrovaný web (HTTPS)?', 'options' => ['443', '80', '21', '53'], 'answer' => '443', 'tolerance' => null, 'accept' => [], 'explain' => 'HTTPS standardně používá port 443.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.003', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Na kterém portu obvykle běží služba SSH pro vzdálené bezpečné přihlášení?', 'options' => ['22', '21', '23', '25'], 'answer' => '22', 'tolerance' => null, 'accept' => [], 'explain' => 'SSH standardně naslouchá na portu 22.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.004', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Na kterém portu obvykle běží služba DNS?', 'options' => ['53', '80', '443', '21'], 'answer' => '53', 'tolerance' => null, 'accept' => [], 'explain' => 'DNS standardně používá port 53.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.005', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Na kterém portu obvykle běží odesílání e-mailu protokolem SMTP?', 'options' => ['25', '110', '143', '53'], 'answer' => '25', 'tolerance' => null, 'accept' => [], 'explain' => 'SMTP pro odesílání pošty standardně používá port 25.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.006', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Číslo portu spolu s IP adresou určuje, které konkrétní službě na daném zařízení je komunikace určena.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'IP adresa najde zařízení, číslo portu na něm vybere konkrétní službu.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.007', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jaký je platný rozsah čísel portů?', 'options' => ['0 až 65535', '0 až 255', '1 až 1000', '0 až 9999'], 'answer' => '0 až 65535', 'tolerance' => null, 'accept' => [], 'explain' => 'Číslo portu se ukládá do 16 bitů, což dává rozsah 0 až 65535.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.008', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jak se nazývají porty v rozsahu 0 až 1023, na kterých běží nejznámější služby?', 'options' => ['dobře známé (well-known) porty', 'dynamické porty', 'privátní porty', 'záložní porty'], 'answer' => 'dobře známé (well-known) porty', 'tolerance' => null, 'accept' => [], 'explain' => 'Well-known porty jsou vyhrazené pro běžné služby jako HTTP nebo SSH.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.009', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Telnet, starší nešifrovaný způsob vzdáleného přístupu, posílá data včetně hesel čitelně, proto se dnes nahrazuje šifrovaným SSH.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Nešifrovaný přenos hesel je bezpečnostní riziko, SSH ho řeší šifrováním.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.010', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená, když je na zařízení port „otevřený“?', 'options' => ['naslouchá na něm služba připravená přijímat spojení', 'port je fyzicky poškozený', 'jde o port, který nikdy nejde použít', 'znamená to, že počítač je vypnutý'], 'answer' => 'naslouchá na něm služba připravená přijímat spojení', 'tolerance' => null, 'accept' => [], 'explain' => 'Otevřený port má na druhé straně program čekající na příchozí spojení.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.011', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Na kterém portu obvykle běží příjem pošty protokolem POP3?', 'options' => ['110', '25', '143', '443'], 'answer' => '110', 'tolerance' => null, 'accept' => [], 'explain' => 'POP3 standardně používá port 110.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.012', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Na kterém portu obvykle běží příjem pošty protokolem IMAP?', 'options' => ['143', '110', '25', '21'], 'answer' => '143', 'tolerance' => null, 'accept' => [], 'explain' => 'IMAP standardně používá port 143.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.013', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Na kterém portu obvykle běží řídicí kanál přenosu souborů protokolem FTP?', 'options' => ['21', '20', '22', '25'], 'answer' => '21', 'tolerance' => null, 'accept' => [], 'explain' => 'FTP používá port 21 pro řízení a port 20 pro přenos dat.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.014', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dva protokoly patří mezi hlavní přenosové protokoly transportní vrstvy pracující s čísly portů?', 'options' => ['TCP', 'UDP', 'HTML', 'CSS'], 'answer' => ['TCP', 'UDP'], 'tolerance' => null, 'accept' => [], 'explain' => 'TCP a UDP jsou transportní protokoly, HTML a CSS s porty nesouvisí.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.015', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Čím se hlavně liší protokol TCP od UDP?', 'options' => ['TCP navazuje spojení a hlídá doručení dat, UDP posílá data bez potvrzení', 'TCP je jen pro e-mail, UDP jen pro web', 'UDP je vždy bezpečnější než TCP', 'mezi nimi není žádný rozdíl'], 'answer' => 'TCP navazuje spojení a hlídá doručení dat, UDP posílá data bez potvrzení', 'tolerance' => null, 'accept' => [], 'explain' => 'UDP je rychlejší, ale nekontroluje, zda data dorazila.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.016', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Který příkaz v Linuxu pomůže zjistit, které porty na zařízení aktuálně naslouchají?', 'options' => ['ss (nebo starší netstat)', 'ls', 'cat', 'grep'], 'answer' => 'ss (nebo starší netstat)', 'tolerance' => null, 'accept' => [], 'explain' => 'Příkaz ss vypíše aktivní síťová spojení a naslouchající porty.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.017', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co dělá firewall s porty na zařízení?', 'options' => ['podle pravidel povoluje nebo blokuje komunikaci na jednotlivých portech', 'zvyšuje rychlost internetu', 'automaticky otevře všechny porty', 'mění IP adresu zařízení'], 'answer' => 'podle pravidel povoluje nebo blokuje komunikaci na jednotlivých portech', 'tolerance' => null, 'accept' => [], 'explain' => 'Firewall filtruje síťový provoz podle nastavených pravidel.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.018', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Dvě různé služby mohou na stejném zařízení běžet současně na úplně stejném čísle portu a protokolu bez omezení.', 'options' => [], 'answer' => false, 'tolerance' => null, 'accept' => [], 'explain' => 'Na daném portu a protokolu smí najednou naslouchat jen jedna služba.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.019', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'K čemu slouží dočasné (dynamické) porty na straně klienta při připojování k serveru?', 'options' => ['klient si přes ně otevře vlastní konec spojení, obvykle z vysokého čísla portu', 'server je používá k ukládání hesel', 'slouží výhradně pro DNS dotazy', 'jde o synonymum pro port 80'], 'answer' => 'klient si přes ně otevře vlastní konec spojení, obvykle z vysokého čísla portu', 'tolerance' => null, 'accept' => [], 'explain' => 'Klient obvykle používá náhodný vysoký port, server naslouchá na známém portu.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.020', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je rozumné mít na zařízení otevřené jen porty služeb, které opravdu potřebuješ?', 'options' => ['omezí to možnosti, jak se k zařízení někdo nepovolaný připojí', 'zrychlí to internetové připojení', 'sníží to spotřebu elektřiny', 'zvětší to volné místo na disku'], 'answer' => 'omezí to možnosti, jak se k zařízení někdo nepovolaný připojí', 'tolerance' => null, 'accept' => [], 'explain' => 'Každý zbytečně otevřený port je potenciální cesta dovnitř.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.021', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 3, 'type' => 'numeric', 'prompt' => 'Kolik různých čísel portů je celkem k dispozici v rozsahu 0 až 65535 včetně obou krajních hodnot?', 'options' => [], 'answer' => 65536, 'tolerance' => 0, 'accept' => [], 'explain' => 'Číslo portu má 16 bitů, 2 na 16. dává 65536 možných hodnot.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.022', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Server naslouchá na portu 443 pro HTTPS. Co se stane, když firewall tento port zablokuje pro příchozí spojení?', 'options' => ['nová šifrovaná spojení zvenčí se k webu nedostanou, i když server běží', 'web poběží, ale bez obrázků', 'HTTPS se automaticky přepne na port 80', 'nic, port 443 se nedá blokovat'], 'answer' => 'nová šifrovaná spojení zvenčí se k webu nedostanou, i když server běží', 'tolerance' => null, 'accept' => [], 'explain' => 'Blokovaný port zabrání navázání nových spojení na danou službu.', 'time_s' => 40, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.023', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'Skenování portů, tedy zjišťování, které porty na cizím zařízení jsou otevřené, bez svolení může na síti školy nebo firmy porušovat pravidla.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Neschválené skenování cizích zařízení bývá zakázané provozním řádem sítě.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.ports.024', 'line' => 'networks', 'classes' => null, 'category' => 'ports', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč databázová služba, například na portu 3306, obvykle nemá být přístupná přímo z internetu?', 'options' => ['snížilo by to ochranu dat, útočník by se mohl pokusit připojit přímo k databázi', 'databáze by bez toho vůbec nefungovala', 'port 3306 je vyhrazený jen pro tisk', 'zpomalilo by to jen zálohování'], 'answer' => 'snížilo by to ochranu dat, útočník by se mohl pokusit připojit přímo k databázi', 'tolerance' => null, 'accept' => [], 'explain' => 'Databáze by měla být dostupná jen z aplikace, ne přímo z veřejné sítě.', 'time_s' => 40, 'source' => 'builtin', 'status' => 'published'],
];
