<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, síťová linie: DNS (kategorie „dns“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_net.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'net.dns.001', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co dělá DNS?', 'options' => ['překládá doménová jména na IP adresy', 'šifruje webovou komunikaci', 'přiděluje MAC adresy', 'ukládá hesla uživatelů'], 'answer' => 'překládá doménová jména na IP adresy', 'tolerance' => null, 'accept' => [], 'explain' => 'DNS funguje jako telefonní seznam internetu – jménu přiřadí odpovídající adresu.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.002', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jak se zkratka DNS rozepisuje?', 'options' => ['Domain Name System', 'Data Network Service', 'Digital Name Server', 'Direct Network System'], 'answer' => 'Domain Name System', 'tolerance' => null, 'accept' => [], 'explain' => 'DNS = Domain Name System, systém doménových jmen.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.003', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Bez DNS bychom si museli pamatovat IP adresy webů místo jejich jmen.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'DNS zbavuje lidi nutnosti pamatovat si čísla IP adres.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.004', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jaký typ záznamu DNS převádí doménové jméno na adresu IPv4?', 'options' => ['A', 'MX', 'NS', 'TXT'], 'answer' => 'A', 'tolerance' => null, 'accept' => [], 'explain' => 'Záznam typu A (address) ukazuje na IPv4 adresu.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.005', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jaký typ záznamu DNS převádí doménové jméno na adresu IPv6?', 'options' => ['AAAA', 'A', 'CNAME', 'PTR'], 'answer' => 'AAAA', 'tolerance' => null, 'accept' => [], 'explain' => 'Záznam AAAA slouží pro delší adresy IPv6.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.006', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jaký typ záznamu DNS určuje, kam se má doručovat e-mail pro danou doménu?', 'options' => ['MX', 'A', 'NS', 'SOA'], 'answer' => 'MX', 'tolerance' => null, 'accept' => [], 'explain' => 'Záznam MX (mail exchange) míří na poštovní server domény.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.007', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co dělá záznam typu CNAME?', 'options' => ['vytváří alias, přezdívku odkazující na jiné doménové jméno', 'ukládá textové poznámky k doméně', 'určuje poštovní server', 'ukládá heslo k doméně'], 'answer' => 'vytváří alias, přezdívku odkazující na jiné doménové jméno', 'tolerance' => null, 'accept' => [], 'explain' => 'CNAME přesměruje jedno jméno na jiné doménové jméno.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.008', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Jedna doména může mít nastaveno více DNS záznamů najednou, například A i MX zároveň.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Různé typy záznamů slouží různým účelům a mohou existovat současně.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.009', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jak se nazývá poslední část doménového jména, například „cz“ nebo „com“?', 'options' => ['doména nejvyššího řádu (TLD)', 'subdoména', 'hostitel', 'proxy'], 'answer' => 'doména nejvyššího řádu (TLD)', 'tolerance' => null, 'accept' => [], 'explain' => 'TLD (top-level domain) je poslední část jména za tečkou.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.010', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je subdoména, například blog v blog.skola.cz?', 'options' => ['část domény o úroveň níž, oddělená tečkou před hlavním jménem', 'jiný název pro celou doménu', 'typ DNS záznamu', 'zkratka pro IP adresu'], 'answer' => 'část domény o úroveň níž, oddělená tečkou před hlavním jménem', 'tolerance' => null, 'accept' => [], 'explain' => 'Subdoména rozšiřuje hlavní doménu o další úroveň, například pro jinou sekci webu.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.011', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená TTL u DNS záznamu?', 'options' => ['jak dlouho si má překlad zůstat uložený v mezipaměti, než se má znovu ověřit', 'typ šifrování záznamu', 'počet záznamů dané domény', 'verzi protokolu DNS'], 'answer' => 'jak dlouho si má překlad zůstat uložený v mezipaměti, než se má znovu ověřit', 'tolerance' => null, 'accept' => [], 'explain' => 'TTL (time to live) určuje životnost záznamu v cache.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.012', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'K čemu slouží místní soubor hosts v operačním systému?', 'options' => ['ručně přiřadí doménovému jménu IP adresu bez dotazu na DNS server', 'ukládá hesla k webům', 'nastavuje firewall', 'ukládá historii prohlížeče'], 'answer' => 'ručně přiřadí doménovému jménu IP adresu bez dotazu na DNS server', 'tolerance' => null, 'accept' => [], 'explain' => 'Soubor hosts má přednost před dotazem na DNS server.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.013', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Jaký typ záznamu DNS uvádí, které servery jsou pro danou doménu autoritativní (odpovědné za její záznamy)?', 'options' => ['NS', 'A', 'MX', 'TXT'], 'answer' => 'NS', 'tolerance' => null, 'accept' => [], 'explain' => 'Záznam NS (name server) říká, který server spravuje záznamy domény.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.014', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Když se zařízení poprvé zeptá na doménu a dostane odpověď, může si ji dočasně zapamatovat a příště se ptát rychleji.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Toto dočasné uložení se nazývá mezipaměť (cache) a zrychluje opakované dotazy.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.015', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'K čemu se často používá záznam typu TXT u domény?', 'options' => ['k ověření vlastnictví domény nebo doplňujícím textovým informacím', 'k překladu na adresu IPv6', 'k nastavení poštovního serveru', 'k nastavení hesla ke stránce'], 'answer' => 'k ověření vlastnictví domény nebo doplňujícím textovým informacím', 'tolerance' => null, 'accept' => [], 'explain' => 'TXT záznamy nesou libovolný text, často pro ověřování služeb.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.016', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co se stane, pokud DNS server pro danou doménu dočasně neodpovídá a záznam není v žádné mezipaměti?', 'options' => ['jméno se nepodaří přeložit na IP adresu a spojení selže', 'prohlížeč adresu automaticky uhodne', 'spojení se přesměruje na výchozí server', 'nic, DNS se pro připojení nepoužívá'], 'answer' => 'jméno se nepodaří přeložit na IP adresu a spojení selže', 'tolerance' => null, 'accept' => [], 'explain' => 'Bez fungujícího DNS překladu se prohlížeč nemá kam připojit.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.017', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dvě z uvedených jsou platné typy DNS záznamů?', 'options' => ['A', 'MX', 'ZIP', 'RGB'], 'answer' => ['A', 'MX'], 'tolerance' => null, 'accept' => [], 'explain' => 'A a MX jsou skutečné typy DNS záznamů, ZIP a RGB s DNS nesouvisí.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.018', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Jak se obecně nazývá proces zjištění IP adresy podle doménového jména?', 'options' => ['překlad (resolving) doménového jména', 'směrování paketů', 'šifrování přenosu', 'autentizace uživatele'], 'answer' => 'překlad (resolving) doménového jména', 'tolerance' => null, 'accept' => [], 'explain' => 'Tomuto procesu se říká resolving neboli překlad jména na adresu.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.019', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Kořenové (root) DNS servery jsou na vrcholu hierarchie a znají adresy serverů odpovědných za jednotlivé domény nejvyššího řádu.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Root servery odkazují na servery TLD, ty dál na servery konkrétních domén.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.020', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč mívají domény nastavené i záložní (sekundární) DNS servery?', 'options' => ['aby překlad jména fungoval, i když jeden server vypadne', 'aby web běžel dvakrát rychleji', 'aby doména stála méně peněz', 'aby šlo měnit jméno domény za provozu'], 'answer' => 'aby překlad jména fungoval, i když jeden server vypadne', 'tolerance' => null, 'accept' => [], 'explain' => 'Více serverů zvyšuje spolehlivost překladu domény.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.021', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 3, 'type' => 'order', 'prompt' => 'Seřaď zjednodušený postup překladu domény www.priklad.cz na IP adresu od prvního kroku k poslednímu.', 'options' => [], 'answer' => ['zařízení se zeptá DNS serveru na jméno www.priklad.cz', 'DNS server najde nebo dohledá odpovídající IP adresu', 'zařízení dostane IP adresu jako odpověď', 'zařízení se pomocí IP adresy připojí k cílovému serveru'], 'tolerance' => null, 'accept' => [], 'explain' => 'Dotaz na jméno vždy předchází samotnému připojení na cílovou IP adresu.', 'time_s' => 42, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.022', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Co hrozí, pokud útočník přesvědčí zařízení, aby použilo podvržený DNS záznam ukazující na jinou IP adresu?', 'options' => ['zařízení se může připojit na jiný server, než uživatel čekal, i po napsání správné adresy', 'nic, prohlížeč to vždy pozná sám', 'DNS podvržení není technicky možné', 'ovlivní to jen rychlost připojení, ne cílový server'], 'answer' => 'zařízení se může připojit na jiný server, než uživatel čekal, i po napsání správné adresy', 'tolerance' => null, 'accept' => [], 'explain' => 'Proto se pro citlivá spojení navíc ověřuje certifikát cílového serveru.', 'time_s' => 40, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.023', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'Jedna IP adresa může patřit více doménovým jménům zároveň, například pokud na jednom serveru běží víc webů.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Sdílení jedné adresy více doménami je běžné u webhostingu.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.dns.024', 'line' => 'networks', 'classes' => null, 'category' => 'dns', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč je krátký TTL, například 60 sekund, užitečný při plánované změně serveru, na který doména ukazuje?', 'options' => ['stará adresa vyprší z mezipaměti rychle a zařízení se dřív zeptají znovu', 'zpomalí to útočníky', 'sníží to velikost webu', 'zabrání to výpadkům úplně'], 'answer' => 'stará adresa vyprší z mezipaměti rychle a zařízení se dřív zeptají znovu', 'tolerance' => null, 'accept' => [], 'explain' => 'Kratší TTL znamená kratší dobu, po kterou zařízení věří starému záznamu.', 'time_s' => 40, 'source' => 'builtin', 'status' => 'published'],
];
