<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, síťová linie: hardware a OS (kategorie „hw“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_net.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'net.hw.001', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Která součást počítače provádí výpočty a bývá označovaná jako „mozek“ počítače?', 'options' => ['procesor (CPU)', 'pevný disk', 'grafická karta', 'klávesnice'], 'answer' => 'procesor (CPU)', 'tolerance' => null, 'accept' => [], 'explain' => 'Procesor (CPU) provádí instrukce programů a řídí výpočty.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.002', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'K čemu slouží operační paměť RAM?', 'options' => ['dočasně uchovává data a programy, se kterými počítač právě pracuje', 'trvale uchovává soubory i po vypnutí', 'zobrazuje obraz na monitoru', 'připojuje počítač k internetu'], 'answer' => 'dočasně uchovává data a programy, se kterými počítač právě pracuje', 'tolerance' => null, 'accept' => [], 'explain' => 'RAM je rychlá, ale dočasná paměť pro právě běžící programy.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.003', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Obsah operační paměti RAM se při vypnutí počítače ztratí.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'RAM je takzvaně nestálá (volatilní) paměť, na rozdíl od disku.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.004', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Kde se natrvalo ukládají soubory i po vypnutí počítače?', 'options' => ['na úložišti, například na SSD nebo HDD disku', 'v operační paměti RAM', 'v procesoru', 'v grafické kartě'], 'answer' => 'na úložišti, například na SSD nebo HDD disku', 'tolerance' => null, 'accept' => [], 'explain' => 'Úložiště (SSD, HDD) uchovává data trvale, i bez napájení.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.005', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Čím se SSD disk obvykle liší od staršího HDD disku?', 'options' => ['nemá pohyblivé mechanické části a bývá rychlejší', 'je vždy levnější než HDD', 'ukládá data jen dočasně', 'funguje pouze bez elektrického napájení'], 'answer' => 'nemá pohyblivé mechanické části a bývá rychlejší', 'tolerance' => null, 'accept' => [], 'explain' => 'SSD ukládá data do paměťových čipů bez pohyblivých částí.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.006', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je operační systém?', 'options' => ['software, který řídí hardware počítače a spouští ostatní programy', 'fyzická součástka uvnitř počítače', 'jiný název pro internetový prohlížeč', 'typ počítačové myši'], 'answer' => 'software, který řídí hardware počítače a spouští ostatní programy', 'tolerance' => null, 'accept' => [], 'explain' => 'Operační systém je základní software zprostředkující práci s hardwarem.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.007', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Linux je jeden z několika běžně používaných operačních systémů pro počítače.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Vedle Linuxu existují i další rozšířené operační systémy pro počítače a mobilní zařízení.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.008', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co dělá jádro (kernel) operačního systému?', 'options' => ['řídí přístup programů k hardwaru, jako je procesor nebo paměť', 'kreslí okna aplikací', 'ukládá hesla do prohlížeče', 'překládá web do češtiny'], 'answer' => 'řídí přístup programů k hardwaru, jako je procesor nebo paměť', 'tolerance' => null, 'accept' => [], 'explain' => 'Kernel je jádro OS zprostředkovávající přístup k hardwaru.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.009', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je ovladač (driver)?', 'options' => ['software, díky kterému operační systém umí komunikovat s konkrétním zařízením', 'fyzický kabel k monitoru', 'typ počítačového viru', 'jiný název pro operační systém'], 'answer' => 'software, díky kterému operační systém umí komunikovat s konkrétním zařízením', 'tolerance' => null, 'accept' => [], 'explain' => 'Ovladač překládá obecné požadavky OS na povely konkrétnímu hardwaru.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.010', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je základní deska (motherboard)?', 'options' => ['deska, na kterou se připojují ostatní hlavní součásti počítače', 'druh počítačové myši', 'software pro správu souborů', 'typ internetového připojení'], 'answer' => 'deska, na kterou se připojují ostatní hlavní součásti počítače', 'tolerance' => null, 'accept' => [], 'explain' => 'Základní deska propojuje procesor, paměť, úložiště a další součásti.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.011', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Vícejádrový (multi-core) procesor umí zpracovávat víc úloh současně efektivněji než jednojádrový.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Každé jádro může nezávisle zpracovávat samostatnou úlohu.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.012', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená, že operační systém je 64bitový oproti 32bitovému?', 'options' => ['mimo jiné umí pracovat s podstatně větším množstvím operační paměti', 'znamená to jen jinou barvu ikon', '32bitové systémy jsou vždy novější', '64bitové systémy nepotřebují procesor'], 'answer' => 'mimo jiné umí pracovat s podstatně větším množstvím operační paměti', 'tolerance' => null, 'accept' => [], 'explain' => '64bitová architektura zvládá adresovat mnohem víc paměti než 32bitová.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.013', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 2, 'type' => 'order', 'prompt' => 'Seřaď zjednodušený postup startu počítače od prvního kroku k poslednímu.', 'options' => [], 'answer' => ['BIOS/UEFI zkontroluje základní hardware', 'zavaděč najde a spustí operační systém', 'jádro operačního systému se načte do paměti', 'uživatel se přihlásí a může spustit své programy'], 'tolerance' => null, 'accept' => [], 'explain' => 'Kontrola hardwaru předchází načtení systému, přihlášení je až posledním krokem.', 'time_s' => 40, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.014', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co je zavaděč (bootloader)?', 'options' => ['malý program, který po startu počítače načte a spustí operační systém', 'ovladač tiskárny', 'typ webového prohlížeče', 'součást grafické karty'], 'answer' => 'malý program, který po startu počítače načte a spustí operační systém', 'tolerance' => null, 'accept' => [], 'explain' => 'Zavaděč běží mezi BIOSem/UEFI a spuštěním jádra operačního systému.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.015', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Pomocí virtualizace lze na jednom počítači spustit více operačních systémů zároveň, každý v izolovaném virtuálním stroji.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Virtuální stroj se hardwaru navenek tváří jako samostatný počítač.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.016', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co umožňuje dvojí zavádění systému (dual boot)?', 'options' => ['vybrat si při startu počítače mezi dvěma nainstalovanými operačními systémy', 'spustit dva programy úplně současně', 'zdvojnásobit výkon procesoru', 'zálohovat data automaticky'], 'answer' => 'vybrat si při startu počítače mezi dvěma nainstalovanými operačními systémy', 'tolerance' => null, 'accept' => [], 'explain' => 'Dual boot nabídne při startu výběr, který nainstalovaný systém spustit.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.017', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč nedostatek volné operační paměti obvykle počítač zpomalí?', 'options' => ['systém začne část dat přesouvat na pomalejší úložiště (odkládací prostor)', 'procesor se automaticky vypne', 'monitor sníží rozlišení', 'internetové připojení se přeruší'], 'answer' => 'systém začne část dat přesouvat na pomalejší úložiště (odkládací prostor)', 'tolerance' => null, 'accept' => [], 'explain' => 'Odkládací prostor (swap) je mnohem pomalejší než operační paměť.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.018', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dvě z uvedených jsou funkce operačního systému?', 'options' => ['řízení přístupu programů k hardwaru', 'plánování běhu jednotlivých procesů', 'úprava fotografií', 'tisk faktur zákazníkům'], 'answer' => ['řízení přístupu programů k hardwaru', 'plánování běhu jednotlivých procesů'], 'tolerance' => null, 'accept' => [], 'explain' => 'Úprava fotografií i tisk faktur jsou úkoly konkrétních aplikací, ne operačního systému.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.019', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'K čemu slouží grafická karta (GPU)?', 'options' => ['zpracovává a vykresluje obraz, mimo jiné pro monitor nebo hry', 'ukládá dokumenty natrvalo', 'připojuje počítač k tiskárně', 'řídí síťové porty routeru'], 'answer' => 'zpracovává a vykresluje obraz, mimo jiné pro monitor nebo hry', 'tolerance' => null, 'accept' => [], 'explain' => 'GPU je specializovaná na rychlé výpočty spojené s grafikou.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.020', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co je periferní zařízení?', 'options' => ['zařízení připojené k počítači zvenčí, například tiskárna nebo klávesnice', 'jiný název pro operační systém', 'druh počítačového viru', 'součást uvnitř procesoru'], 'answer' => 'zařízení připojené k počítači zvenčí, například tiskárna nebo klávesnice', 'tolerance' => null, 'accept' => [], 'explain' => 'Periferie rozšiřují počítač o vstup, výstup nebo další funkce.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.021', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'Vyšší počet jader procesoru samo o sobě vždy zrychlí i program, který neumí svou práci rozdělit mezi víc jader.', 'options' => [], 'answer' => false, 'tolerance' => null, 'accept' => [], 'explain' => 'Program musí být navržený pro paralelní zpracování, jinak využije jen jedno jádro.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.022', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč se u náročných úloh chlazení procesoru řeší stejně pečlivě jako jeho výkon?', 'options' => ['přehřátý procesor si sníží výkon nebo se ochranně vypne, aby se nepoškodil', 'chlazení nemá na výkon vůbec žádný vliv', 'chlazení zvyšuje kapacitu úložiště', 'chlazení nahrazuje potřebu operační paměti'], 'answer' => 'přehřátý procesor si sníží výkon nebo se ochranně vypne, aby se nepoškodil', 'tolerance' => null, 'accept' => [], 'explain' => 'Tomuto ochrannému snížení výkonu se říká tepelné omezení (throttling).', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.023', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč je dobré mít ovladače klíčového hardwaru, například grafické karty, aktuální?', 'options' => ['zlepšují stabilitu, výkon a někdy opravují i bezpečnostní chyby', 'ovladače se aktualizují jen kvůli vzhledu', 'staré ovladače jsou vždy rychlejší', 'aktualizace ovladačů nic nemění'], 'answer' => 'zlepšují stabilitu, výkon a někdy opravují i bezpečnostní chyby', 'tolerance' => null, 'accept' => [], 'explain' => 'Nové verze ovladačů často řeší chyby i zabezpečení.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.hw.024', 'line' => 'networks', 'classes' => null, 'category' => 'hw', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Co se stane, když operační systém nemá ovladač pro nově připojené zařízení?', 'options' => ['zařízení nemusí fungovat správně nebo vůbec, dokud se ovladač nedoinstaluje', 'zařízení se automaticky vrátí do obchodu', 'operační systém se natrvalo poškodí', 'počítač se automaticky přeinstaluje'], 'answer' => 'zařízení nemusí fungovat správně nebo vůbec, dokud se ovladač nedoinstaluje', 'tolerance' => null, 'accept' => [], 'explain' => 'Bez odpovídajícího ovladače systém neví, jak se zařízením komunikovat.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
];
