<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, grafická linie: licence Creative Commons (kategorie „license“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_gfx.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'gfx.license.001', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 1, 'type' => 'text', 'prompt' => 'Jak se zkracuje název licencí „Creative Commons“? Napiš zkratku dvěma velkými písmeny.', 'options' => [], 'answer' => 'CC', 'tolerance' => null, 'accept' => [], 'explain' => 'Creative Commons se běžně zkracuje jako CC.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.002', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená prvek licence BY v Creative Commons?', 'options' => ['musíš uvést autora díla', 'dílo nesmíš nijak upravovat', 'dílo nesmíš použít komerčně', 'dílo musíš sdílet za stejných podmínek'], 'answer' => 'musíš uvést autora díla', 'tolerance' => null, 'accept' => [], 'explain' => 'BY (Attribution) vyžaduje uvedení autorství.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.003', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená prvek licence NC v Creative Commons?', 'options' => ['dílo nesmíš použít komerčně, tedy pro výdělek', 'musíš uvést autora', 'dílo nesmíš upravovat', 'licence platí jen jeden rok'], 'answer' => 'dílo nesmíš použít komerčně, tedy pro výdělek', 'tolerance' => null, 'accept' => [], 'explain' => 'NC (NonCommercial) zakazuje komerční využití díla.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.004', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená prvek licence ND v Creative Commons?', 'options' => ['dílo nesmíš upravovat ani z něj vytvářet odvozená díla', 'musíš uvést autora', 'dílo nesmíš sdílet dál', 'dílo je zdarma jen pro školy'], 'answer' => 'dílo nesmíš upravovat ani z něj vytvářet odvozená díla', 'tolerance' => null, 'accept' => [], 'explain' => 'ND (NoDerivatives) zakazuje úpravy a odvozená díla.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.005', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená prvek licence SA, ShareAlike, v Creative Commons?', 'options' => ['upravené dílo musíš dál šířit za stejné nebo slučitelné podmínky', 'musíš uvést autora', 'dílo nesmíš sdílet mimo školu', 'dílo smí použít jen jednou'], 'answer' => 'upravené dílo musíš dál šířit za stejné nebo slučitelné podmínky', 'tolerance' => null, 'accept' => [], 'explain' => 'ShareAlike přenáší stejné podmínky i na odvozené dílo.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.006', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Licence CC BY dovoluje i komerční použití díla, pokud uvedeš autora.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Samotné BY bez NC komerční použití neomezuje.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.007', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená označení CC0, neboli „public domain“, u díla?', 'options' => ['dílo je bez omezení volně použitelné, autor se vzdal majetkových práv', 'dílo smí použít jen jeho autor', 'dílo je zakázáno kdykoli použít', 'CC0 znamená totéž co all rights reserved'], 'answer' => 'dílo je bez omezení volně použitelné, autor se vzdal majetkových práv', 'tolerance' => null, 'accept' => [], 'explain' => 'CC0 uvolní dílo bez jakýchkoli podmínek použití.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.008', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Obrázek nalezený na internetu bez uvedené licence smíš automaticky volně použít, protože je veřejně dostupný.', 'options' => [], 'answer' => false, 'tolerance' => null, 'accept' => [], 'explain' => 'Bez uvedené licence platí výchozí ochrana autorským právem, pokud autor neřekl jinak.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.009', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená „všechna práva vyhrazena“, pokud autor nepřipojí žádnou volnější licenci?', 'options' => ['dílo smí bez svolení autora použít jen v rámci zákonných výjimek', 'dílo smí kdokoli volně použít', 'dílo je automaticky veřejně dostupné ke stažení', 'licence platí jen na papírové kopie'], 'answer' => 'dílo smí bez svolení autora použít jen v rámci zákonných výjimek', 'tolerance' => null, 'accept' => [], 'explain' => 'Výchozí stav autorského práva je plná ochrana bez dalšího svolení.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.010', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Proč je dobré při použití cizí fotografie v projektu uvést zdroj a licenci?', 'options' => ['respektuje to práva autora a splňuje podmínky licence', 'zdroj se uvádí jen kvůli délce práce', 'uvedení zdroje obrázek automaticky zlepší', 'to je nutné jen u textu, ne u obrázků'], 'answer' => 'respektuje to práva autora a splňuje podmínky licence', 'tolerance' => null, 'accept' => [], 'explain' => 'Uvedení zdroje je často přímo podmínkou licence (BY).', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.011', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená licence CC BY-SA?', 'options' => ['smíš dílo použít i upravit, pokud uvedeš autora a šíříš úpravu za stejné podmínky', 'smíš dílo jen sdílet, ne upravovat', 'dílo nesmíš vůbec šířit dál', 'licence platí jen jeden měsíc'], 'answer' => 'smíš dílo použít i upravit, pokud uvedeš autora a šíříš úpravu za stejné podmínky', 'tolerance' => null, 'accept' => [], 'explain' => 'BY-SA kombinuje povinnost uvést autora a šířit úpravu za stejnou licencí.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.012', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená licence CC BY-NC?', 'options' => ['smíš dílo použít a uvést autora, ale ne pro komerční účely', 'smíš dílo prodávat bez omezení', 'musíš dílo vždy upravit', 'dílo nesmíš vůbec stáhnout'], 'answer' => 'smíš dílo použít a uvést autora, ale ne pro komerční účely', 'tolerance' => null, 'accept' => [], 'explain' => 'BY-NC spojuje povinnost uvést autora se zákazem komerčního využití.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.013', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená licence CC BY-ND?', 'options' => ['smíš dílo šířit dál s uvedením autora, ale beze změn', 'smíš dílo libovolně upravovat', 'dílo nesmíš vůbec sdílet', 'licence je jen pro tisk'], 'answer' => 'smíš dílo šířit dál s uvedením autora, ale beze změn', 'tolerance' => null, 'accept' => [], 'explain' => 'BY-ND dovolí šíření originálu, ale zakáže úpravy.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.014', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Licence CC BY-NC-ND patří mezi nejpřísnější varianty Creative Commons – dovoluje sdílet dál beze změn a nekomerčně, s uvedením autora.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Kombinace NC a ND spolu s BY dává nejméně volnosti ze všech CC licencí.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.015', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Školní projekt použije fotografii s licencí CC BY-NC. Co to znamená pro použití ve školní prezentaci?', 'options' => ['je to v pořádku pro nekomerční školní účel, pokud se uvede autor', 'fotografii nelze použít vůbec', 'fotografii lze použít jen s placenou licencí navíc', 'licence NC znamená zákaz úprav'], 'answer' => 'je to v pořádku pro nekomerční školní účel, pokud se uvede autor', 'tolerance' => null, 'accept' => [], 'explain' => 'Školní nekomerční prezentace odpovídá podmínkám NC i BY.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.016', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč prodej trička s potiskem licencovaným jako CC BY-NC-SA porušuje licenci?', 'options' => ['prodej je komerční využití, což NC část licence zakazuje', 'trička nejsou vůbec povolený formát pro licence', 'CC licence se na fyzické předměty nevztahují', 'BY-NC-SA zakazuje jakékoli veřejné použití'], 'answer' => 'prodej je komerční využití, což NC část licence zakazuje', 'tolerance' => null, 'accept' => [], 'explain' => 'NC podmínka platí bez ohledu na to, na jaký předmět se potisk umístí.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.017', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dvě z uvedených zkratek patří mezi standardní prvky licencí Creative Commons?', 'options' => ['BY', 'SA', 'XL', 'PDF'], 'answer' => ['BY', 'SA'], 'tolerance' => null, 'accept' => [], 'explain' => 'BY a SA jsou licenční prvky, XL a PDF s licencemi CC nesouvisí.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.018', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč nejde vzít dílo s licencí CC BY-SA, upravit ho a nové dílo vydat jako „všechna práva vyhrazena“?', 'options' => ['podmínka ShareAlike vyžaduje šíření úpravy za stejnou nebo slučitelnou licenci', 'BY-SA úpravy úplně zakazuje', 'licence SA se po úpravě automaticky ruší', 'to je vždy povolené bez omezení'], 'answer' => 'podmínka ShareAlike vyžaduje šíření úpravy za stejnou nebo slučitelnou licenci', 'tolerance' => null, 'accept' => [], 'explain' => 'ShareAlike se přenáší i na odvozená díla dál.', 'time_s' => 34, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.019', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Uvedení jména autora u licence CC BY se obvykle očekává i tehdy, když dílo jen mírně upravíš, ne pouze při použití beze změny.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Povinnost uvést autora platí i pro upravené verze díla.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.020', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč je licence CC0 vhodná pro materiály, které chce autor dát k volnému použití bez jakýchkoli podmínek?', 'options' => ['odstraňuje i požadavek na uvedení autora, na rozdíl od ostatních CC licencí', 'CC0 je vlastně totéž co all rights reserved', 'CC0 platí jen jeden rok', 'CC0 zakazuje komerční použití'], 'answer' => 'odstraňuje i požadavek na uvedení autora, na rozdíl od ostatních CC licencí', 'tolerance' => null, 'accept' => [], 'explain' => 'CC0 jde dál než ostatní CC licence a nevyžaduje žádnou podmínku.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.021', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Žák chce do školního videa vložit hudbu s licencí CC BY-NC-ND, zkrátit ji a upravit hlasitost. Je to v souladu s licencí?', 'options' => ['ne, ND (žádné úpravy) zakazuje i takovou úpravu díla', 'ano, úpravy jsou vždy povolené', 'ano, pokud je úprava jen technická', 'ne, protože NC zakazuje úpravy'], 'answer' => 'ne, ND (žádné úpravy) zakazuje i takovou úpravu díla', 'tolerance' => null, 'accept' => [], 'explain' => 'ND zakazuje úpravy obecně, včetně střihu a změny hlasitosti.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.022', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'Kombinace materiálů s licencemi CC BY-SA a CC BY-NC-SA do jednoho výsledného díla může být problematická, protože podmínky ShareAlike obou licencí nejdou vždy jednoduše sloučit.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Různé varianty ShareAlike nejsou vždy vzájemně kompatibilní.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.023', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč se podmínka ShareAlike (SA) někdy neformálně popisuje jako „přenosná“ na další díla?', 'options' => ['požaduje, aby i odvozené dílo neslo stejnou nebo slučitelnou licenci dál', 'protože se licence sama maže po roce', 'protože platí jen jeden den', 'protože zakazuje jakékoli sdílení'], 'answer' => 'požaduje, aby i odvozené dílo neslo stejnou nebo slučitelnou licenci dál', 'tolerance' => null, 'accept' => [], 'explain' => 'Podmínka se přenáší z původního díla i na jeho úpravy.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.license.024', 'line' => 'graphics', 'classes' => null, 'category' => 'license', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč je důležité si před použitím cizího díla ověřit přesné znění licence, a ne se spoléhat jen na zkratku „CC“?', 'options' => ['jednotlivé varianty CC licencí se výrazně liší v tom, co dovolují a zakazují', 'všechny CC licence jsou naprosto stejné', 'zkratka CC vždy znamená volné použití bez omezení', 'licenci stačí zkontrolovat jen u placených děl'], 'answer' => 'jednotlivé varianty CC licencí se výrazně liší v tom, co dovolují a zakazují', 'tolerance' => null, 'accept' => [], 'explain' => 'Rozdíl mezi například BY a BY-NC-ND je v praxi zásadní.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
];
