<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, síťová linie: příkazy Linuxu (kategorie „linux“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_net.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'net.linux.001', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který příkaz vypíše obsah aktuální složky?', 'options' => ['ls', 'cd', 'pwd', 'rm'], 'answer' => 'ls', 'tolerance' => null, 'accept' => [], 'explain' => 'ls vypíše soubory a složky v aktuální složce; cd mění složku, pwd vypíše cestu.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.002', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který příkaz změní aktuální pracovní složku?', 'options' => ['cd', 'ls', 'pwd', 'mkdir'], 'answer' => 'cd', 'tolerance' => null, 'accept' => [], 'explain' => 'cd (change directory) přepne shell do jiné složky.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.003', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který příkaz vypíše cestu ke složce, ve které se právě nacházíš?', 'options' => ['pwd', 'ls', 'cd', 'whoami'], 'answer' => 'pwd', 'tolerance' => null, 'accept' => [], 'explain' => 'pwd znamená print working directory – vypíše aktuální cestu.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.004', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který příkaz vytvoří novou složku?', 'options' => ['mkdir', 'rmdir', 'touch', 'cat'], 'answer' => 'mkdir', 'tolerance' => null, 'accept' => [], 'explain' => 'mkdir (make directory) vytvoří složku; rmdir naopak prázdnou složku smaže.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.005', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Kterým příkazem vytvoříš nový prázdný soubor?', 'options' => ['touch', 'mkdir', 'nano', 'less'], 'answer' => 'touch', 'tolerance' => null, 'accept' => [], 'explain' => 'touch vytvoří prázdný soubor nebo aktualizuje čas jeho poslední úpravy.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.006', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Příkaz rm -r smaže i neprázdnou složku i s jejím obsahem.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Přepínač -r (rekurzivně) nechá rm sestoupit do podsložek a smazat vše uvnitř.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.007', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který příkaz vypíše celý obsah textového souboru najednou na obrazovku?', 'options' => ['cat', 'ls', 'mkdir', 'cd'], 'answer' => 'cat', 'tolerance' => null, 'accept' => [], 'explain' => 'cat (concatenate) vypíše obsah souboru na standardní výstup.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.008', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který příkaz zkopíruje soubor na nové místo?', 'options' => ['cp', 'mv', 'rm', 'ln'], 'answer' => 'cp', 'tolerance' => null, 'accept' => [], 'explain' => 'cp (copy) vytvoří kopii souboru; původní soubor zůstane zachován.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.009', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Který příkaz přesune soubor do jiné složky nebo ho přejmenuje?', 'options' => ['mv', 'cp', 'rm', 'cat'], 'answer' => 'mv', 'tolerance' => null, 'accept' => [], 'explain' => 'mv (move) přesune nebo přejmenuje soubor, na rozdíl od cp originál nezachová.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.010', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Skryté soubory a složky v Linuxu mají název začínající tečkou.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Například .bashrc je skrytý soubor – ls ho ukáže až s přepínačem -a.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.011', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Který příkaz otevře podrobný návod k použití jiného příkazu?', 'options' => ['man', 'help', 'info', 'doc'], 'answer' => 'man', 'tolerance' => null, 'accept' => [], 'explain' => 'man vypíše podrobný manuál, například „man ls“.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.012', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Který příkaz prohledá obsah souborů podle zadaného textového vzoru?', 'options' => ['grep', 'find', 'ls', 'cat'], 'answer' => 'grep', 'tolerance' => null, 'accept' => [], 'explain' => 'grep hledá řádky odpovídající vzoru uvnitř souborů.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.013', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Který příkaz najde soubory podle názvu v celém adresářovém stromu?', 'options' => ['find', 'grep', 'which', 'stat'], 'answer' => 'find', 'tolerance' => null, 'accept' => [], 'explain' => 'find prochází zadaný strom složek a hledá podle jména, typu nebo dalších vlastností.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.014', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Který příkaz vypíše jen posledních několik řádků souboru, například konec logu?', 'options' => ['tail', 'head', 'cat', 'more'], 'answer' => 'tail', 'tolerance' => null, 'accept' => [], 'explain' => 'tail ukazuje konec souboru, což se hodí třeba pro sledování logů.', 'time_s' => 25, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.015', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Který příkaz vypíše jen prvních několik řádků souboru?', 'options' => ['head', 'tail', 'wc', 'cut'], 'answer' => 'head', 'tolerance' => null, 'accept' => [], 'explain' => 'head vypíše začátek souboru, ve výchozím nastavení prvních deset řádků.', 'time_s' => 25, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.016', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dva znaky se v shellu běžně používají jako zástupné (wildcard) při zápisu jmen souborů?', 'options' => ['*', '?', '#', '%'], 'answer' => ['*', '?'], 'tolerance' => null, 'accept' => [], 'explain' => 'Hvězdička zastupuje libovolný počet znaků, otazník právě jeden znak.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.017', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co udělá v shellu symbol > za příkazem, například echo ahoj > zprava.txt?', 'options' => ['přesměruje výstup příkazu do souboru a přepíše ho', 'spustí příkaz na pozadí', 'porovná dva soubory', 'zřetězí dva příkazy za sebe'], 'answer' => 'přesměruje výstup příkazu do souboru a přepíše ho', 'tolerance' => null, 'accept' => [], 'explain' => 'Znak > přesměruje standardní výstup do souboru; existující obsah se ztratí.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.018', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Symbol >> na rozdíl od > přidá výstup na konec souboru a existující obsah nesmaže.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => '>> připojuje na konec (append), zatímco > soubor nejdřív vyprázdní.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.019', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Který příkaz vypíše historii naposledy spuštěných příkazů v terminálu?', 'options' => ['history', 'log', 'past', 'recent'], 'answer' => 'history', 'tolerance' => null, 'accept' => [], 'explain' => 'history vypíše seznam dříve zadaných příkazů s pořadovými čísly.', 'time_s' => 25, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.020', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 2, 'type' => 'command', 'prompt' => 'Napiš příkaz, kterým v terminálu otevřeš soubor poznamky.txt v textovém editoru nano.', 'options' => [], 'answer' => 'nano poznamky.txt', 'tolerance' => null, 'accept' => [], 'explain' => 'Editor se spouští jako příkaz nano následovaný jménem souboru.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.021', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Čím se liší příkaz cp -r od obyčejného cp?', 'options' => ['cp -r zkopíruje i celé složky se vším uvnitř, cp jen jednotlivé soubory', 'cp -r je rychlejší, ale méně bezpečný', 'cp -r funguje jen na vzdálených serverech', 'mezi nimi není žádný rozdíl'], 'answer' => 'cp -r zkopíruje i celé složky se vším uvnitř, cp jen jednotlivé soubory', 'tolerance' => null, 'accept' => [], 'explain' => 'Přepínač -r (rekurzivně) je nutný pro kopírování celých adresářů.', 'time_s' => 35, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.022', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 3, 'type' => 'command', 'prompt' => 'Napiš příkaz, který vypíše obsah aktuální složky včetně skrytých souborů v dlouhém formátu s právy a velikostmi.', 'options' => [], 'answer' => 'ls -la', 'tolerance' => null, 'accept' => ['ls -al', 'ls -l -a', 'ls -a -l'], 'explain' => 'Přepínač -l zapne dlouhý výpis, -a přidá skryté soubory; pořadí přepínačů nevadí.', 'time_s' => 40, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.023', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 3, 'type' => 'order', 'prompt' => 'Seřaď kroky od prvního k poslednímu: zjisti, kde v systému souborů jsi; vytvoř novou složku projekt; přejdi do složky projekt.', 'options' => [], 'answer' => ['pwd', 'mkdir projekt', 'cd projekt'], 'tolerance' => null, 'accept' => [], 'explain' => 'Nejdřív ověříš polohu, pak vytvoříš složku a nakonec do ní přejdeš.', 'time_s' => 40, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'net.linux.024', 'line' => 'networks', 'classes' => null, 'category' => 'linux', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč je vhodné být opatrný s příkazem rm -rf ve vlastní domovské složce?', 'options' => ['smaže soubory nenávratně a bez zpětného dotazu', 'jen je přesune do koše', 'zpomalí počítač na několik hodin', 'vyžaduje restart systému'], 'answer' => 'smaže soubory nenávratně a bez zpětného dotazu', 'tolerance' => null, 'accept' => [], 'explain' => '-r maže rekurzivně a bez koše, -f navíc potlačí dotazy na potvrzení.', 'time_s' => 35, 'source' => 'builtin', 'status' => 'published'],
];
