<?php

declare(strict_types=1);

if (basename((string)($_SERVER['SCRIPT_FILENAME'] ?? '')) === basename(__FILE__)) { http_response_code(403); exit; }

/**
 * EDUCANET v58 · TG-BANK – kvízová banka, grafická linie: typografie (kategorie „type“).
 * Načítá ji souhrnný soubor teamgames_v58_bank_gfx.php pro TG-CORE (teamgames_v58_quiz.php).
 * Soubor smí být v jednom requestu includován i vícekrát – proto obsahuje jen `return [...]`,
 * žádné funkce, třídy ani konstanty.
 */

return [
    ['id' => 'gfx.type.001', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jak se nazývá písmo, které má na koncích tahů písmen malé ozdobné patky?', 'options' => ['patkové (serif)', 'bezpatkové (sans-serif)', 'monospace', 'kurzíva'], 'answer' => 'patkové (serif)', 'tolerance' => null, 'accept' => [], 'explain' => 'Serif = patkové písmo, sans-serif = bezpatkové.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.002', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jak se nazývá písmo, jehož tahy na koncích nemají žádné ozdobné patky?', 'options' => ['bezpatkové (sans-serif)', 'patkové (serif)', 'monospace', 'tučné'], 'answer' => 'bezpatkové (sans-serif)', 'tolerance' => null, 'accept' => [], 'explain' => 'Sans-serif znamená doslova „bez patek“.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.003', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Jak se nazývá písmo, kde má každý znak stejnou šířku, používané třeba v kódu?', 'options' => ['monospace (jednotná šířka znaků)', 'serif', 'kurzíva', 'tučné'], 'answer' => 'monospace (jednotná šířka znaků)', 'tolerance' => null, 'accept' => [], 'explain' => 'Monospace usnadňuje zarovnání znaků pod sebe, hodí se pro kód.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.004', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 1, 'type' => 'text', 'prompt' => 'Jak se česky nazývá skloněné písmo používané například pro zdůraznění nebo citace? Napiš jedním slovem.', 'options' => [], 'answer' => 'kurzíva', 'tolerance' => null, 'accept' => ['italika'], 'explain' => 'Skloněný řez písma se česky nazývá kurzíva, anglicky italic.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.005', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená řádkování (line-height) v typografii?', 'options' => ['svislá vzdálenost mezi řádky textu', 'vzdálenost mezi jednotlivými písmeny', 'tloušťka písma', 'barva textu'], 'answer' => 'svislá vzdálenost mezi řádky textu', 'tolerance' => null, 'accept' => [], 'explain' => 'Řádkování ovlivňuje, jak blízko u sebe jsou jednotlivé řádky textu.', 'time_s' => 24, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.006', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co je hierarchie textu, například u nadpisu, podnadpisu a odstavce?', 'options' => ['odlišení důležitosti textu velikostí, tloušťkou nebo barvou písma', 'abecední řazení slov', 'počet použitých písem na stránce', 'zarovnání textu doprava'], 'answer' => 'odlišení důležitosti textu velikostí, tloušťkou nebo barvou písma', 'tolerance' => null, 'accept' => [], 'explain' => 'Vizuální hierarchie pomáhá čtenáři rychle najít to důležité.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.007', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 1, 'type' => 'bool', 'prompt' => 'Příliš mnoho různých druhů písma na jedné stránce obvykle působí nepřehledně.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Doporučuje se držet se malého počtu vzájemně sedících písem.', 'time_s' => 20, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.008', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená tučný řez písma (bold)?', 'options' => ['zesílenou tloušťku tahů písma pro zvýraznění', 'skloněný tvar písma', 'jinou velikost písma', 'jiný jazyk textu'], 'answer' => 'zesílenou tloušťku tahů písma pro zvýraznění', 'tolerance' => null, 'accept' => [], 'explain' => 'Tučný řez zvýrazní text zesílenými tahy písma.', 'time_s' => 22, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.009', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Proč se pro dlouhé odstavce textu na webu obvykle nepoužívá čistě tučné písmo?', 'options' => ['tučný text na velké ploše se čte hůř a působí křiklavě', 'tučné písmo se na webu nedá zobrazit', 'tučné písmo je vždy menší', 'tučné písmo nejde zarovnat na střed'], 'answer' => 'tučný text na velké ploše se čte hůř a působí křiklavě', 'tolerance' => null, 'accept' => [], 'explain' => 'Tučný řez se hodí spíš na krátké zvýraznění, ne na celé odstavce.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.010', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 1, 'type' => 'single', 'prompt' => 'Co znamená zarovnání textu do bloku (justify)?', 'options' => ['text je zarovnaný rovně k oběma okrajům úpravou mezer mezi slovy', 'text je zarovnaný jen doleva', 'text je vždy na střed', 'text nemá žádné zarovnání'], 'answer' => 'text je zarovnaný rovně k oběma okrajům úpravou mezer mezi slovy', 'tolerance' => null, 'accept' => [], 'explain' => 'Zarovnání do bloku roztáhne mezery, aby oba okraje byly rovné.', 'time_s' => 26, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.011', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co je to prokládání znaků (tracking, letter-spacing)?', 'options' => ['rovnoměrná úprava mezer mezi všemi znaky textu', 'úprava mezery jen mezi dvěma konkrétními znaky', 'tloušťka písma', 'výška řádku'], 'answer' => 'rovnoměrná úprava mezer mezi všemi znaky textu', 'tolerance' => null, 'accept' => [], 'explain' => 'Tracking mění mezery mezi znaky rovnoměrně v celém textu.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.012', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co je kerning?', 'options' => ['jemné doladění mezery mezi konkrétní dvojicí znaků', 'celkové zvětšení velikosti písma', 'barva pozadí za textem', 'počet sloupců textu'], 'answer' => 'jemné doladění mezery mezi konkrétní dvojicí znaků', 'tolerance' => null, 'accept' => [], 'explain' => 'Kerning řeší mezeru jen mezi vybranými páry znaků, na rozdíl od trackingu.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.013', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč se pro dlouhé odstavce textu doporučuje spíš kratší až střední délka řádku než velmi dlouhá?', 'options' => ['kratší řádek se snáz sleduje očima a snižuje riziko ztráty místa ve větě', 'dlouhé řádky se na webu nedají zobrazit', 'délka řádku nemá na čtení žádný vliv', 'krátké řádky vždy vypadají neprofesionálně'], 'answer' => 'kratší řádek se snáz sleduje očima a snižuje riziko ztráty místa ve větě', 'tolerance' => null, 'accept' => [], 'explain' => 'Velmi dlouhé řádky ztěžují oku návrat na správný začátek dalšího řádku.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.014', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Přiměřeně větší řádkování u delšího textu obvykle zlepšuje čitelnost oproti řádkům namačkaným těsně na sebe.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Větší řádkování usnadňuje očím sledovat jednotlivé řádky odděleně.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.015', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co znamená párování písem (font pairing)?', 'options' => ['promyšlená kombinace dvou či více písem, která si dobře sedí', 'používání jen jednoho písma na celém webu', 'automatický výběr náhodného písma', 'převod textu na obrázek'], 'answer' => 'promyšlená kombinace dvou či více písem, která si dobře sedí', 'tolerance' => null, 'accept' => [], 'explain' => 'Časté je párování jednoho výraznějšího písma pro nadpisy a klidnějšího pro text.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.016', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč se ve webovém designu často řeší záložní (fallback) písma?', 'options' => ['pokud se hlavní písmo nenačte, prohlížeč použije jiné podobné písmo', 'záložní písma jsou vždy hezčí než hlavní', 'fallback písma se používají jen v tiskovinách', 'prohlížeče žádná záložní písma nepodporují'], 'answer' => 'pokud se hlavní písmo nenačte, prohlížeč použije jiné podobné písmo', 'tolerance' => null, 'accept' => [], 'explain' => 'Záložní písmo zabrání zobrazení textu bez jakéhokoli formátování.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.017', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 2, 'type' => 'multi', 'prompt' => 'Které dvě z uvedených jsou typické vlastnosti bezpatkových (sans-serif) písem?', 'options' => ['čisté tvary bez ozdobných zakončení tahů', 'jednodušší, geometričtější tvary písmen', 'ozdobné patky na koncích tahů', 'vždy jen ručně psané písmo'], 'answer' => ['čisté tvary bez ozdobných zakončení tahů', 'jednodušší, geometričtější tvary písmen'], 'tolerance' => null, 'accept' => [], 'explain' => 'Bezpatková písma nemají patky a bývají opticky jednodušší a geometričtější.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.018', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Proč se velikost písma na webu často udává v relativních jednotkách, například rem, místo pevných pixelů?', 'options' => ['lépe se přizpůsobí nastavení velikosti písma v prohlížeči uživatele', 'relativní jednotky fungují jen v tiskovinách', 'pevné jednotky prohlížeč vůbec nepodporuje', 'relativní jednotky vždy zvětší text dvakrát'], 'answer' => 'lépe se přizpůsobí nastavení velikosti písma v prohlížeči uživatele', 'tolerance' => null, 'accept' => [], 'explain' => 'Relativní jednotky respektují uživatelovo zvětšení textu v prohlížeči.', 'time_s' => 32, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.019', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 2, 'type' => 'bool', 'prompt' => 'Velká písmena (verzálky) použitá na celý dlouhý odstavec textu se obecně čtou hůř než běžná kombinace velkých a malých písmen.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Tvary malých písmen usnadňují rozpoznávání celých slov najednou.', 'time_s' => 28, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.020', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 2, 'type' => 'single', 'prompt' => 'Co je typografická účaří (baseline) v textu?', 'options' => ['pomyslná čára, na které „sedí“ spodní okraj většiny písmen', 'okraj stránky', 'barva pozadí textu', 'mezera mezi odstavci'], 'answer' => 'pomyslná čára, na které „sedí“ spodní okraj většiny písmen', 'tolerance' => null, 'accept' => [], 'explain' => 'Účaří je referenční čára, podle které se zarovnávají znaky písma.', 'time_s' => 30, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.021', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč se u velkých nadpisů někdy mírně zmenšuje řádkování oproti běžnému odstavci?', 'options' => ['velká písmena mají opticky větší vnímanou mezeru, menší řádkování ji vyváží', 'menší řádkování u nadpisů je jen náhodná móda bez důvodu', 'nadpisy nesmí mít žádné řádkování', 'řádkování u nadpisů se nikdy neliší od textu'], 'answer' => 'velká písmena mají opticky větší vnímanou mezeru, menší řádkování ji vyváží', 'tolerance' => null, 'accept' => [], 'explain' => 'Větší písmo opticky zvětšuje i mezery, proto se řádkování často doladí.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.022', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 3, 'type' => 'bool', 'prompt' => 'Kombinace příliš mnoha řezů stejného písma, například tenký, běžný, tučný a extra tučný, na jedné stránce může vizuální hierarchii spíš zmást, pokud není použitá promyšleně.', 'options' => [], 'answer' => true, 'tolerance' => null, 'accept' => [], 'explain' => 'Bez jasného systému může velký počet řezů působit chaoticky.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.023', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč se pro delší text na obrazovce často preferuje bezpatkové písmo, zatímco patkové bývá tradičně oblíbené v tisku?', 'options' => ['na nižším rozlišení obrazovky se jemné patky mohou hůř vykreslovat', 'patkové písmo na obrazovce vůbec nejde zobrazit', 'bezpatkové písmo je vždy menší', 'tiskárny neumí tisknout bezpatková písma'], 'answer' => 'na nižším rozlišení obrazovky se jemné patky mohou hůř vykreslovat', 'tolerance' => null, 'accept' => [], 'explain' => 'Jemné detaily patek potřebují dost vysoké rozlišení, aby vynikly čistě.', 'time_s' => 38, 'source' => 'builtin', 'status' => 'published'],
    ['id' => 'gfx.type.024', 'line' => 'graphics', 'classes' => null, 'category' => 'type', 'difficulty' => 3, 'type' => 'single', 'prompt' => 'Proč je důležité zachovat dostatečný rozdíl velikosti mezi úrovněmi nadpisů (h1, h2, h3) a běžným textem?', 'options' => ['čtenář i čtečka obrazovky pak snáz rozpozná strukturu a důležitost částí', 'jinak by prohlížeč nadpisy vůbec nezobrazil', 'velikost nadpisů nemá na strukturu žádný vliv', 'nadpisy musí být vždy stejně velké jako text'], 'answer' => 'čtenář i čtečka obrazovky pak snáz rozpozná strukturu a důležitost částí', 'tolerance' => null, 'accept' => [], 'explain' => 'Jasná vizuální hierarchie pomáhá orientaci v obsahu stránky.', 'time_s' => 36, 'source' => 'builtin', 'status' => 'published'],
];
