<?php

declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(400);exit("CLI only\n");}
require dirname(__DIR__).'/bootstrap.php';
require dirname(__DIR__).'/runtime_content.php';
$runtime=runtime_content_load_classes(['class_1a','class_2a','class_3a','class_4a']);$nextLessons=$runtime['nextLessons'];$extendedLessons=$runtime['extendedLessons'];
$base=dirname(__DIR__).'/materials/learning_studios';if(!is_dir($base)&&!mkdir($base,0775,true)&&!is_dir($base))throw new RuntimeException('Nelze vytvořit '.$base);
$csv=[['class','lesson','title','family','topic','representations','model_steps','teachback_markers']];$total=0;
foreach(['class_1a','class_2a','class_3a','class_4a'] as $classId){$dir=$base.'/'.$classId;if(!is_dir($dir))mkdir($dir,0775,true);foreach(v42_lessons_for_class($classId) as $lesson){$s=v44_studio_spec($classId,$lesson,$modules[$classId]);$total++;$n=(int)$lesson['number'];$lines=[];$lines[]='# Learning Studio · '.$s['lesson_title'];$lines[]='';$lines[]='**Třída:** '.$classId.'  ';$lines[]='**Lekce:** '.$n.'  ';$lines[]='**Rodina:** '.$s['family'].'  ';$lines[]='**Primary topic:** '.$s['topic'];$lines[]='';$lines[]='## Big idea';$lines[]=$s['big_idea'];$lines[]='';$lines[]='## Reprezentace';foreach($s['representations'] as $r)$lines[]='- **'.$r['label'].'** — '.$r['title'].': '.$r['text'];$lines[]='';$lines[]='## Difference Lens';$lines[]='- Typická varianta: `'.implode(' → ',$s['difference']['before']).'`';$lines[]='- Funkční model: `'.implode(' → ',$s['difference']['after']).'`';$lines[]='- Prompt: '.$s['difference']['prompt'];$lines[]='';$lines[]='## Analogy bridge';$lines[]='**Přirovnání:** '.$s['analogy'];$lines[]='';$lines[]='**Limit přirovnání:** '.$s['analogy_limit'];$lines[]='';$lines[]='## Teach-back';$lines[]=$s['teachback_question'];$lines[]='';$lines[]='Očekávané pojmy/signály: `'.implode('`, `',$s['teachback_markers']).'`';$lines[]='';$lines[]='## Model před / po';$lines[]='Student uloží vlastní pořadí před korekcí a po ní. Rozdíl slouží jako evidence změny mentálního modelu, ne jako známka.';$lines[]='';$lines[]='## 90s Replay';foreach($s['replay'] as $r)$lines[]='- **'.$r['label'].'** — '.$r['text'];$lines[]='';$lines[]='## Memory Snapshot seed';$lines[]='- Jedna věta: '.$s['memory_seed']['sentence'];$lines[]='- Past: '.$s['memory_seed']['trap'];$lines[]='- Retrieval cue: '.$s['memory_seed']['cue'];$lines[]='';file_put_contents($dir.'/lesson_'.str_pad((string)$n,2,'0',STR_PAD_LEFT).'.md',implode("\n",$lines)."\n");$csv[]=[$classId,$n,$s['lesson_title'],$s['family'],$s['topic'],count($s['representations']),count($s['model_expected']),count($s['teachback_markers'])];}}
$f=fopen($base.'/STUDIO_CATALOG.csv','wb');foreach($csv as $row)fputcsv($f,$row,';','"','\\');fclose($f);echo "Generated $total learning studios in $base\n";
