<?php

declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(400);exit("CLI only\n");}
require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__).'/runtime_content.php';
$runtime=runtime_content_load_classes(['class_1a','class_2a','class_3a','class_4a']);$nextLessons=$runtime['nextLessons'];$extendedLessons=$runtime['extendedLessons'];
$root=dirname(__DIR__).'/materials/visual_simulations';if(!is_dir($root))mkdir($root,0775,true);
$catalog=[['class','lesson','title','family','renderer','parameters','what_if']];$count=0;
foreach(['class_1a','class_2a','class_3a','class_4a'] as $classId){$dir=$root.'/'.$classId;if(!is_dir($dir))mkdir($dir,0775,true);foreach(v42_lessons_for_class($classId) as $lesson){$s=v45_simulation_spec($classId,$lesson,$modules[$classId]);$num=(int)$lesson['number'];$lines=[];$lines[]='# '.($lesson['title']??('Lekce '.$num));$lines[]='';$lines[]='**Třída:** '.$classId.'  ';$lines[]='**Lekce:** '.$num.' / 28  ';$lines[]='**Rodina:** '.$s['family'].'  ';$lines[]='**Renderer:** '.$s['renderer'];$lines[]='';$lines[]='## Konkrétní situace';$lines[]='';$lines[]=$s['problem'];$lines[]='';$lines[]='## Princip';$lines[]='';$lines[]=$s['princip'];$lines[]='';$lines[]='## Manipulovatelné parametry';$lines[]='';foreach($s['params'] as $p)$lines[]='- **'.$p['label'].'** (`'.$p['id'].'`): '.($p['min']).'–'.($p['max']).($p['unit']??'').'; start '.($p['value']).', target '.($p['target']).'. '.$p['hint'];$lines[]='';$lines[]='## What-if scénáře';$lines[]='';$lines[]='Každý scénář lze použít najednou nebo krokovat po jedné změně. Při krokování má student před každým krokem vyslovit predikci směru dopadu.';$lines[]='';foreach($s['what_if'] as $w){$lines[]='### '.$w['title'];$lines[]='';$lines[]=$w['text'];$lines[]='';}$lines[]='## A/B experiment';$lines[]='';$lines[]='1. Ulož výchozí stav jako A.';$lines[]='2. Změň pouze jednu proměnnou a ulož jako B.';$lines[]='3. Porovnej funkčnost, čitelnost/evidence, odolnost a riziko.';$lines[]='4. V detailním diffu projdi hodnoty A, B a deltu každého parametru.';$lines[]='5. Vysvětli, který parametr způsobil rozdíl a co z výsledku **nelze** tvrdit.';$lines[]='6. U obhájené varianty zapiš krátkou evidence note ve formátu změna → pozorování → závěr.';$lines[]='';$lines[]='## Teacher projection';$lines[]='';$lines[]='- **Otázka:** '.$s['projection']['ask'];$lines[]='- **Reveal:** '.$s['projection']['reveal'];$lines[]='- **Compare:** '.$s['projection']['compare'];$lines[]='- **Fáze:** Predikce → Diskuse → Reveal.';$lines[]='- **Spotlight:** zvýrazni jeden parametr a nech třídu předpovědět směr změny.';$lines[]='- **Klávesy:** P / D / R / F / ← / → / 1–3.';$lines[]='';$lines[]='## Transfer';$lines[]='';$lines[]=$s['transfer'];$lines[]='';file_put_contents($dir.'/lesson_'.str_pad((string)$num,2,'0',STR_PAD_LEFT).'.md',implode("\n",$lines));$catalog[]=[$classId,$num,(string)$lesson['title'],(string)$s['family'],(string)$s['renderer'],count($s['params']),count($s['what_if'])];$count++;}}
$f=fopen($root.'/SIMULATION_CATALOG.csv','wb');foreach($catalog as $r)fputcsv($f,$r,',','"','\\');fclose($f);echo "Generated $count visual simulation specs.\n";
